commercialhaskell/stack

src/Stack/PackageIndex.hs

Add output to show the name of the mirror that we are pulling from. https://github.com/commercialhaskell/stack/issues/227

Improve output for package index update

---

src/Stack/Types/Config.hs

This is a quick fix for #241. More could be done -- perhaps show a URL to a definitive list of possible values?

make the resolver error show a hopefully more clear description for nightlies

---

src/Stack/Types/Config.hs

As suggested by @greggwebs. The syntax proposed yesterday has the
advantage of concision, but using YAML syntax for the different
components adds marginal verbosity. As it is, the previous syntax made
extensibility problematic, whereas that's exactly where YAML
shines (what if we need an extra field to identify a particular git
commit?). Further, using YAML means people are free to include their own
metadata about package locations, without disturbing Stack.
Here's an example:
```
- location:
git: https://github.com/kolmodin/binary
commit: 8debedd3fcb6525ac0d7de2dd49217dce2abc0d9
```
Note that this patch *removes* the old syntax. The reasoning being -
custom user tooling would need to conservatively support both syntaxes
if there was a brief and a long syntax, because it can't assume that …

Use YAML syntax for remote git location identification.

---

src/Stack/Build/Execute.hs
src/Stack/Types/Internal.hs
src/Stack/Types/StackT.hs

Handle runhaskell output with logInfo
@snoyberg I think b1b88f5 is slightly subtle of a change so I'd like you to
take a look. The summary is:
1. All output goes into the printBuildOutput function now, unless a log
file is specified.
2. printBuildOutput can probably do other filtering in the future. But
its purpose is now two-fold; the filtering, and ensuring no stray stdout
makes it into the world without going through monad-logger first.
Now sticky output can work properly even with build output dumped live. Pinging @DanBurton as this serves as a decent example of display progress output with the new `logSticky` and `logStickyDone`.

Build progress

---

src/Data/Aeson/Extended.hs
src/Network/HTTP/Download.hs
src/Stack/Build/Types.hs
src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/Docker.hs
src/Stack/PackageIndex.hs
src/Stack/Setup.hs
src/Stack/Types/Config.hs
src/Stack/Types/Docker.hs
src/Stack/Types/FlagName.hs
src/Stack/Types/GhcPkgId.hs
src/Stack/Types/PackageIdentifier.hs
src/Stack/Types/PackageName.hs
src/Stack/Types/Version.hs
stack.cabal

This overrides the aeson combinators to have better error messages
Just import Data.Aeson.Extended instead of Data.Aeson

Better aeson error messages. addresses #269

---

.ghci
src/Stack/Exec.hs
src/Stack/Package.hs
src/Stack/Repl.hs
src/main/Main.hs
stack.cabal

This is for #130.
Here is demonstration output: http://lpaste.net/raw/277892153647038464
This configures with 
* All source directories, cabal macros and autogen directories.
* Extensions.
From every target in the cabal project, and every package in your stack.yaml.
You can call 
$ stack ghci  
or 
$ stack ghci projectname
Like in `stack build`.
There're a number of other options in [`BuildInfo`](http://hackage.haskell.org/package/Cabal-1.22.3.0/docs/Distribution-PackageDescription.html#t:BuildInfo):  `ldOptions`, `ccOptions`, `includes` etc.  I'm not sure which of them are actually necessary. Needs to be figured out.
Meanwhile, I'd like to float this by the interested parties: @feuerbach @hesselink @acfoltzer @ndmitchell @snoyberg 
Other points:
* I think some might want a `--load-all` …

Implement clever stack ghci (aka cabal repl)

---

src/Options/Applicative/Builder/Extra.hs
src/Stack/Build.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Installed.hs
src/Stack/Build/Types.hs
src/Stack/Package.hs
src/Stack/PackageDump.hs
src/Stack/Types/Config.hs
src/main/Main.hs
src/test/Stack/PackageDumpSpec.hs

This doesn't yet generate the index or do relative links, and it requires rebuilding the package in order to generate haddocks, but does work well in my testing and think it's worth merging with the current feature set (especially as this touches enough code that conflicts are frequent).  
As for building haddocks without rebuilding the packages: this should be doable by adding some extra logic to singleBuild that lets it skip `runhaskell Setup.hs build` when building only haddocks (along with some adjustments to ConfigCache and maybe getInstalled), but interested in opinion about whether that's the right approach or if this would be better done at the Plan level (i.e. split the plan into _build_, _haddock_, and _install_ steps).  Note that haddocks need to be built before installing the …

Build haddocks for dependencies (#143)

---

src/Stack/Build/Execute.hs

`printBuildOutput` (https://github.com/commercialhaskell/stack/blob/706736a6a46810533281eb7cc38714f31a6a5412/src/Stack/Build/Execute.hs) re-prints the output from `ghc`.  However, in my environment (GHC 7.10.1, Windows 8.1), it suffers from indigestion due to `decodeUtf8`:
```
stack: Cannot decode byte '\x81': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
```
This patch fixes this so that stack correctly prints compile errors.

Bypass decodeUtf8 in printBuildOutput

---

src/Path/IO.hs
src/Stack/Package.hs

DRY up file resolver functions that only differ whether it's a file or directory by introducing internal helper functions.

Reduce duplication in file resolver functions

---

src/Stack/BuildPlan.hs

The old behaviour is described in #434
The new behaviour looks as follows:
Downloading lts-42.0 build plan ...SnapshotNotFound "lts-42.0"
Non existing resolver: "lts-42.0".
For a complete list of available snapshots see https://www.stackage.org/snapshots
Resolves #434

Handle attempt to use non-existing resolver

---

src/Stack/Config.hs
src/Stack/Init.hs

Currently `stack init` takes into account *all* .cabal files in the cwd as well as non-ignored sub directories.  If I run it on the `stack` project it will for example also pick up the `new-template.cabal`
and refuse all of the available build plans due to unresolved packages like `acme-dont` that are used in some of the integration tests.
With the new flag `stack init --ignore-subdirs` it will only consider `stack.cabal` and not recurse into sub directories. 
To allow this I added a boolean flag to `findCabalFiles` which I don't like that much but I avoided to define a data type for the argument (e.g  `data FindCabalRecurse = DoRecurse | Don'tRecurse`) for simplicity.

Add --ignore-subdirs flag to init command

---

src/Path/Find.hs
test/integration/tests/skip-unreachable-dirs/Main.hs
test/integration/tests/skip-unreachable-dirs/files/foo.cabal

Catch permission denied exception in findFiles function and ignore such
directories.
In my project I have directory with content of linux container. After running `stack init` command I got an error "Permission denied" on this directory.
Fixed such behavior and added test for this usecase.

Skip unreachable directories during init

---

stack.yaml

Seems 16e906e13f45af9308f42dd8d86f4179b4119fd6 missed that one.

extra-deps: hfsevents

---

src/Stack/PackageDump.hs

Warning and solution printed during compilation:
```
Deprecated: "It is an internal function and should never have been
exported. Use 'break (== x)' instead. (There are rewrite rules that
handle this special case of 'break'.)"
```

Remove usage of `ByteString.breakByte`

---

src/Stack/Build.hs
src/Stack/Dot.hs
src/main/Main.hs
src/test/Stack/DotSpec.hs
stack.cabal

When given `--external`, `stack dot` will include external dependencies.
By default it keeps the old behavior and only includes local packages and their interdependencies.
If `--external` is activated local packages will have the "dashed" line attribute so that one can distinguish local packages from external dependencies.
As an example, given a tree like this with two projects `one` and `two`:
```
├── [4.0K]  one
│   ├── [ 686]  one.cabal
│   └── [  46]  Setup.hs
├── [  78]  stack.yaml
└── [4.0K]  two
├── [  46]  Setup.hs
└── [ 710]  two.cabal
```
`stack dot` will produce:
while `stack dot --external` will produce:
This would also fix #431.

Add --external flag to `stack dot`

---

ChangeLog.md
src/Stack/Dot.hs
src/test/Stack/DotSpec.hs
stack.cabal

TL;DR: Add `--prune p1,p2,p3` to `stack dot` to remove nodes from the dependency graph
Playing around with some haskell projects and their `stack dot` graphs, it becomes apparent that it it a little hard to look at them because they get quite huge.  As an example, take the graph for `wreq` generated by `stack dot --external --no-include-base`:
okay that is a LOT.  Looking a bit more we see that `wreq-examples` is also there which depends on a bunch of the dependencies.
The new feature is that `--prune` takes a comma separated list of package names that will be pruned.
So here is `wreq` without dependencies of `wreq-examples` and `lens`:
Still a lot but more manageable.
Of course we can have a dependency graph that is a little more focused by pruning more (randomly chosen) dependencies …

Add --prune to `stack dot`

---

src/Stack/Config.hs
src/Stack/Package.hs
src/Stack/Setup.hs
src/Stack/Types/BuildPlan.hs

I have very little confidence I did this right, but here's my good faith effort. :)
See #399

For windowsintegersimple resolve flags as if Windows OS

---

src/Stack/Setup.hs

This is my naive attempt to make the `dist` path available for cases like running `doctest`. See https://groups.google.com/forum/#!topic/haskell-stack/OoP88_VckhY.
I tried to imitate how the other env variables are set without fully understanding what the consequences may be. Testing it manually works as I would expect.

Report `dist` path as `HASKELL_DIST_DIR` env variable

---

.gitignore
src/Stack/Build/Execute.hs
src/Stack/Build/Types.hs
src/main/Main.hs

New version of the PR addressing #430. Piggybacks on the `toRun` concept introduced in the last week now. No large scale splitting out of existing code.

Add --no-tests parameter to stack test

---

src/Stack/Build/Execute.hs
src/Stack/Build/Source.hs
src/Stack/Build/Types.hs
src/main/Main.hs

Implements #496.
I renamed the `boptsTestArgs` to `boptsAdditionalArgs` and use that field for both testing and benchmarking.  I also chose to use `--benchmark-arguments` instead of `--benchmark-options` because for tests it is `--test-arguments`.
With this `stack bench --benchmark-arguments='-o $benchmark.html --csv $benchmark.csv'` works as expected.

Implement `stack bench --benchmark-arguments`

---

src/main/Main.hs

Just noticed that the arguments parser order matters for the `--help` flag.  Due to #512 currently the specific flags are at the front, e.g.
```
stack bench -h
Usage: stack bench [--benchmark-arguments BENCH_ARGS] [TARGET]
([--library-profiling] | [--no-library-profiling])
([--executable-profiling] | [--no-executable-profiling])
([--optimizations] | [--no-optimizations]) ([--haddock] |
[--no-haddock]) [--dry-run] [--pedantic]
[--ghc-options OPTION] [--flag PACKAGE:[-]FLAG] [--prefetc
h]
[--only-snapshot] [--file-watch] ([--keep-going] |
[--no-keep-going])
Build and benchmark the project(s) in this directory/configuration
```
notice the `[--benchmark-arguments BENCH_ARGS]` before `[TARGET]`, I think it looks better like this (which is why this pr flips the order):
```
stack bench -h
Usage: …
```

Flip order of build and test/bench opts parser

---

src/main/Main.hs

Instead of using the pattern:
```haskell
fmap (fromMaybe "default value")
(optional (_parser (_meta)))
```
we can use `optparse-applicative`'s [value](http://hackage.haskell.org/package/optparse-applicative-0.11.0.2/docs/Options-Applicative-Builder.html#v:value) function to specify a default value:
```haskell
_parser (_meta <> value "default value")
```
This is the benefit of being able to show defaults automatically by enabling it with [showDefault](http://hackage.haskell.org/package/optparse-applicative-0.11.0.2/docs/Options-Applicative-Builder.html#v:showDefault) in the help text, e.g. for `stack ghci --help` we now get (note the help for `--with-ghc`):
```
Usage: stack ghci [TARGET] [--ghc-options OPTION] [--with-ghc GHC] [--no-load]
[--package ARG]
Run ghci in the context of …
```

Use `value` instead of fromMaybe for arguments

---

src/Stack/Fetch.hs

Fixes #504.
When you get a "Didn't see pkg-<ver> in your package indices" message,
also see list of candidates with same major version. Might be that you
forgot some minor thing like ".0" in the end of a version string.

Propose fuzzy-matched versions

---

src/Stack/Config.hs
src/Stack/Docker.hs
src/Stack/Dot.hs
src/Stack/Init.hs
src/Stack/Options.hs
src/Stack/Types/Config.hs
src/main/Main.hs
stack.cabal

All Options Parsers have been moved out from Main.hs
and other Modules and in to one single location at Stack.Options.
Other types that existed solely for configuration, have been
moved to Stack.Types.Config.

Refactoring Options Parsers

---

src/Stack/Init.hs
src/Stack/New.hs
src/main/Main.hs

Resolves #575.
`new` was already using the `initOptsParser` which has the `forceOverwrite` option, so I just forwarded that to `Stack.New.newProject` and check for that options value before refusing the overwrite.

Allow "--force" with `stack new` (#575)

---

src/Stack/Fetch.hs

I noticed that you merged [my previous PR](https://github.com/commercialhaskell/stack/pull/557) (thanks!), this PR is an improvement from what was asked there.
Copy of my comment from there:
@snoyberg I updated function to be better in terms of alg complexity. It now uses Map.splitLookup to do a logN-split, filtering smaller elements. It then filters bigger elements by doing takeWhile (takes only satisfying head).
Thus, I think I don't understand your comment in full. Since we're only running this algorithm for one package (I tested, if two packages didn't match we still fail and error only for the first one), the map-reconstruction for better version-matching wouldn't make a lot of sense. Might be that it would make sense in future, when we show errors for many packages at once.

Better fuzzy-matching algorithm (n -> logn)

---

src/Stack/Types/StackT.hs

Usurpation of #446.
Assumption: Only `LevelError` and `LevelWarn` are logged to stderr, the rest (`LevelInfo`, `LevelOther "sticky[-done]"` and **`LevelDebug`**) go to stdout. Or should `LevelDebug` go to stderr as well?

Log LevelError and LevelWarn to stderr

---

src/Stack/Dot.hs
src/Stack/Types/StackT.hs
src/main/Main.hs

E.g.
$ (export STACK_YAML=stack.yaml && stack path --local-install-root)
Getting project config file from STACK_YAML environment
/home/conathan/Desktop/mirrored/stack-fix/stack.git/.stack-work/install/x86_64-linux/lts-2.17/7.8.4
$ (export STACK_YAML=stack.yaml && stack --verbosity silent path --local-install-root)
/home/conathan/Desktop/mirrored/stack-fix/stack.git/.stack-work/install/x86_64-linux/lts-2.17/7.8.4
but I still think it's a good idea to also send log messages to stderr.

Make `stack path` output independent of logging. (Issue #604)

---

src/main/Main.hs

It was not clear to me what `VERSION` meant -- it had no documentation
-- so I changed it to `GHC_MAJOR_VERSION` and added documentation.
Before:
$ stack setup --help
Usage: stack setup [VERSION] ([--reinstall] | [--no-reinstall])
Get the appropriate ghc for your project
--reinstall              Enable Reinstall GHC, even if available (implies
no-system-ghc)
--no-reinstall           Disable Reinstall GHC, even if available (implies
no-system-ghc)
After:
$ stack setup --help
Usage: stack setup [GHC_MAJOR_VERSION] ([--reinstall] | [--no-reinstall])
Get the appropriate GHC for your project
GHC_MAJOR_VERSION        Major version of GHC to install, e.g. 7.10. The
default is to install the version implied by the
resolver.
--reinstall              Enable …

Improve `stack setup --help` output.

---

src/Path/IO.hs
src/Stack/Build.hs
src/Stack/Build/Execute.hs
src/Stack/Package.hs
src/Stack/SDist.hs
src/Stack/Upload.hs
src/main/Main.hs
stack.cabal

Instead of using the `cabal` binary to create sdists, this uses `runhaskell Setup.hs sdist --list-sources` to get a list of paths to include in the tarball.  It then uploads this tarball without writing it to a file.

Use Setup.hs to get sdist list + add tar.gz code #313

---

stack.cabal

project-template version is not precise so dependency
solver could chose older version that stack is incompatible
with.

Set lower dependency restrictions on project-template.

---

src/Stack/Ide.hs

_NB._ See [this pull request](https://github.com/commercialhaskell/stack-ide/pull/35), which would first need to be applied to `stack-ide`.
This PR would be a step into having `stack` provide the appropriate version of `ide-backend-server` to each project where `stack-ide` is used.
What the patch does is simply make `stack-ide` look for `ide-backend-server` and `ide-backend-exe-cabal` in the `bin` directory of the local and snapshot databases, respectively. If, for every project, one can then persuade `stack` to build `ide-backend-server` and `ide-backend` in addition to the project packages, then one gets the right ghc-version of `ide-backend-server` for free. At the moment, I achieve this rather crudely by adding the following package entry in the `stack.yaml` file of every project I …

Make stack-ide receive a path where the correct ide-backend-server is installed

---

src/Stack/Fetch.hs
stack.cabal

The `tar` package, in name of portability, doesn't preserve file
permissions when creating and unpacking archives. A sample package which
relies on permissions to be kept as they were packed with is
`ghc-parser` which executes a bash script as part of its build process.
Before this patch we'd get
```
/run/user/1000/stack26234/ghc-parser-0.1.7.0/Setup.hs:2:1: Warning:
Module ‘System.Cmd’ is deprecated: Use "System.Process" instead
/bin/sh: ./build-parser.sh: Permission denied
Configuring ghc-parser-0.1.7.0...
Warning: 'hs-source-dirs: src-7.8.3' directory does not exist.
```
but now the package builds fine.
cc @mboes

Preserve file permissions when unpacking sources

---

ChangeLog.md
src/Stack/Config.hs
src/Stack/Types/Config.hs
src/Stack/Upgrade.hs
src/main/Main.hs
src/test/Stack/BuildPlanSpec.hs
src/test/Stack/ConfigSpec.hs

I'm not sure this is a good idea, which is why I'm putting it on a
separate branch for discussion. Pinging @manny-fp and @chrisdone.
My reasoning for this change: we currently have weird behavior where
some commands (e.g. stack install) will work outside of a project, but
others (e.g., stack build) will not. This makes a lot of sense for some
commands (like stack test), since it's almost certainly user error to
run `stack test` outside a project. However:
* This logic is difficult to explain to people
* My guesses about usage were wrong, e.g. people really do want
`stack build somelibrary` to work outside a project for things like
`stack runghc` to work nicely
* Consistent behavior > smart behavior
So this new approach is: we always fall back to the implicit global
project, but notify the …

Never throw an exception when stack.yaml is missing

---

src/Options/Applicative/Builder/Extra.hs

Before this PR:
```
% stack --no-system-ghc --system-ghc path
Invalid option `--system-ghc'
Usage: stack [--version] [--help] [--docker*] ([--verbosity VERBOSITY] |
[-v|--verbose]) ([--system-ghc] | [--no-system-ghc])
...
```
After:
```
% .../bin/stack --help                           
stack - The Haskell Tool Stack
Usage: stack [--version] [--help] [--docker*] ([--verbosity VERBOSITY] |
[-v|--verbose]) ([--system-ghc] | [--no-system-ghc])
...
```
```
% .../bin/stack --no-system-ghc --system-ghc path
global-stack-root: /Users/phadej/.stack
project-root: /Users/phadej/Coding/stack
...
```
This is useful in scripting, where one have alias with some default flags, but later want to override them

Accept multiple instance of same cli option flag

---

src/Stack/Dot.hs
src/main/Main.hs
src/test/Stack/DotSpec.hs

Implements #638 .
Adds a new command `stack list-dependencies` that will list all transitive dependencies for the local packages.
It's not able to show dependencies for the test and benchmark packages, because I could not figure out how to do it, nevertheless I though I should probably pr this as is for the added functionality.
The problem I had with test/benchmark in a nutshell: 
> It seems like `loadSourceMap` and `loadLocals` by default assume that they are not enabled (package config sets it to false). Once I changed that it seems like it somehow does not pickup the dependencies for test packages like QuickCheck when using `withLoadPackage`'s function to load packages...
If you see what I am doing wrong I'd be happy to change this :)
The nice part is that it reuses the structure …

New command `list-dependencies`

---

src/Stack/Build/Source.hs
src/Stack/Build/Types.hs

Adds a little helpful information if the flags are invalid.  Implemented by using `Package` instead of only `PackageName` in the `UnusedFlags` constructor `UFFlagsNotDefined`.
Output before:
```
$ stack build --flag stack:foo --flag stack:bar --flag foo:bar
Invalid flag specification:
- Package 'foo' not found (specified on command line)
- Package 'stack' does not define the following flags (specified on command line): bar, foo
```
Output after:
```
$ stack build --flag stack:foo --flag stack:bar --flag foo:bar
Invalid flag specification:
- Package 'foo' not found (specified on command line)
- Package 'stack' does not define the following flags (specified on command line):
bar
foo
- Flags defined by package 'stack':
stack:integration-tests
```

Show available flags if flag not found

---

src/Stack/Build.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Types.hs
src/Stack/Upgrade.hs
src/main/Main.hs
stack.cabal

This is the third and final (for now) refinement of the locking mechanism.
"Filelock2" (#700) refines the locking to be per-snapshot, rather than global/per-user.  This patch goes further and allows the snapshot lock to be released early by any build command whose actions are *all local*.
The next reasonable step would be to allow mixed snapshot/local builds to release early once the snapshot portion of the build is done.  (This could be accomplished simply by making the unlock itself an `Action`, and scheduled as part of the dependence graph of actions.)
That last refinement would be nice to have, but "filelock3" already handles the most important common case -- a server running CI jobs again and again builds the snapshot bits only on the first execution (and occasionally thereafter). …

Filelock3 -- release snapshot lock early for local-only builds

---

src/main/Main.hs

New options: `--snapshot-doc-root` and `--local-doc-root`
Motivation:
* Troubleshooting info; and
* Quick access to the documentation (e.g. `elinks $(stack path --snapshot-doc-root)/index.html`).
Coding style note: I was unsure about whether you'd rather have me adding reader monad actions to `Stack.Types.Config`, just like to those for the other paths. In the end, I went for the least invasive option, simply concatenating the paths *in situ*, imitating `Stack.Build.Haddock.snapDocDir`.

`stack path` shows documentation roots.

---

ChangeLog.md
src/Options/Applicative/Args.hs
src/Stack/Build.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Source.hs
src/Stack/Build/Target.hs
src/Stack/Config.hs
src/Stack/Dot.hs
src/Stack/Options.hs
src/Stack/SDist.hs
src/Stack/Types/Build.hs
src/Stack/Types/Config.hs
src/Stack/Types/Package.hs
src/main/Main.hs
src/test/Stack/Build/ExecuteSpec.hs
src/test/Stack/Build/TargetSpec.hs
stack.cabal
test/integration/tests/617-extra-dep-flag/Main.hs

Not quite ready for merge to master. I want to review the diff and do some cleanup, and then it's up to @borsboom on timing. I originally said this should be merged after the upcoming release, but this is already looking pretty stable, so I'm not necessarily opposed to including it now.
Pinging @chrisdone for review
Merging this to master resolves #651

651 target parse overhaul

---

src/Options/Applicative/Builder/Extra.hs
src/Stack/Options.hs
src/main/Main.hs

A common pattern found repeatedly is:
`fmap T.pack (strArgument _)` or `fmap T.pack (strOption _)`
This pr adds two functions in `Options/Applicative/Builder/Extra`, `textOption` and `textArgument` which are like  `strArgument` and `strOption` just for Text instead of String.  
It might be possible to instead use an upper bound on `optparse-applicative` depending on the outcome of pcapriotti/optparse-applicative#147, though it might be easier to just maintain local copies for now inside `stack`.  In order to prevent conflicts in the near future the local versions are called `text-` instead of `txt-` as in the  `optparse-applicative` pr.

Add text versions of strArgument and strOption

---

ChangeLog.md
src/Stack/Build/Source.hs
src/Stack/Build/Target.hs
stack.cabal
test/integration/tests/443-specify-path/Main.hs

This resolves #763. This is high priority for release, sorry for the late-landing bug. Pinging @gregwebs

763 disabled executable

---

ChangeLog.md
src/Stack/Build/Source.hs
src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/Fetch.hs
src/Stack/Init.hs
src/Stack/Setup.hs
src/Stack/Solver.hs
src/Stack/Types.hs
src/Stack/Types/Build.hs
src/Stack/Types/Compiler.hs
src/Stack/Types/Config.hs
src/Stack/Types/Version.hs
src/main/Main.hs
stack.cabal

To test before https://github.com/fpco/stackage-content/pull/8 is merged, replace [this line](https://github.com/commercialhaskell/stack/blob/736-exact-ghc-versions/src/Stack/Setup.hs#L497) with
```
req = "https://raw.githubusercontent.com/fpco/stackage-content/c9165a5845370cf83b2dd373a66cb9a80f9bf74d/stack/stack-setup-2.yaml"
```
Description from the commit:
* Requires the exact GHC version specified by the snapshot.
* Deprecates major-version (ghc-7.10, ghc-7.8) resolvers, but still
supports them.  They resolve to the newest installed / available ghc
matching that number.
* Changes the format of stack-setup.yaml, and so changes which URL is
used to find it (in order to not break old stack versions).
* Refactors ensureTool code, as it already had a lot of special cases,
which I found …

Use exact GHC versions rather than major-version #736

---

src/Stack/Docker.hs

Works in case we have versions like 1.2.3-somegarbage instead of purely
numerical ones.
Fixes #786

Further trim docker --version output

---

src/Stack/Upgrade.hs
src/main/Main.hs

Default is the same as always and the flag does nothing worthwhile if
--git is not specified too.
Closes #787

Add --git-repo to stack upgrade

---

ChangeLog.md
src/Stack/Build.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Source.hs
src/Stack/SDist.hs
src/Stack/Types/Package.hs

See #805. Motivation: when you switch between `cabal configure` and `cabal configure --enable-tests`, the cabal_macros.h file is changed, leading to the library to be recompiled needlessly. Based on an idea from @gregwebs, this change makes it so that, whenever the test suite and benchmark dependencies are present, `--enable-tests` and `--enable-benchmarks` are passed in, respectively. We use components as a parameter to `cabal build` to control which components are built (unfortunately, there's no way to simply say "don't rebuild the library"...).
Pinging @chrisdone and @borsboom. @Fuuzetsu could you test out this branch and let me know if it helps out your `stack build && stack test` use case?

Enable tests whenever possible

---

src/Stack/FileWatch.hs
src/Stack/Options.hs
src/main/Main.hs
stack.cabal
stack.yaml

( A first attempt of Part 1 for #703 )
This is a very basic implementation and I've moved out most of the logic to a separate package ( http://hackage.haskell.org/package/ignore ) as I would like to reuse it for other projects. Don't know if this is the desired approach, looking for feedback :-)

--file-watch should respect VCS boring/ignore files

---

.travis.yml
stack.cabal
stack.yaml

Quickfix to #831 - will build the `ignore` library w/o pcre for now.

build the ignore library w/o pcre support

---

README.md
src/Stack/Setup.hs

To address the concern that some users have had about stack installing GHC and potentially messing up their existing installations, this PR updates the README slightly to be more explicit about that, and also adds some output to the "setup" command so that they hopefully won't panic and try to interrupt the installation.
I thought of doing this while reading the intro to Snoyman's new Stack guide, where it says:
> Finally, stack is isolated: it will not make changes outside of specific stack directories (described below). Do not be worried if you see comments like "Installing GHC": stack will not tamper with your system packages at all. Additionally, stack packages will not interfere with packages installed by other build tools like cabal.
I also wanted to refer to a reddit thread I …

add some wording to soothe users about installing GHC

---

src/Stack/Ghci.hs

Still start up stack-ide and stack ghci even if there are project compilation errors.

---

scripts/release/release.hs

This has several advantages:
* The executable bit is set by default, so no need to `chmod +x` after
decompressing.
* No need to rename binary to `stack` after decompressing.
* Can use tarball as the source argument for Docker `ADD` commands,
for conveniently installing a stack binary into a docker image when
the package manager not appropriate / not available.
The tarball still only contains just the `stack` binary.

Create tarballs rather than gzipping naked binaries during release.

---

ChangeLog.md
src/Stack/Build/Cache.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Haddock.hs
src/Stack/Build/Installed.hs
src/Stack/Dot.hs
src/Stack/GhcPkg.hs
src/Stack/PackageDump.hs
src/Stack/SDist.hs
src/Stack/Types/Build.hs
src/Stack/Types/GhcPkgId.hs
src/test/Stack/PackageDumpSpec.hs

Adapt to upcoming Cabal installed package identifier format change

---

ChangeLog.md
src/Stack/Setup.hs
src/main/Main.hs

Instead of using PortableGit, this moves stack over to using the full msys2. The advantage: it comes with pacman. This change also makes it so that the relevant --extra-lib-dirs and --extra-include-dirs are automatically set, meaning the following actually works:
stack exec -- pacman -S mingw64/mingw-w64-x86_64-icu
stack build text-icu. It's working on the msys2 branch
Props to @ygale for the thread at http://sourceforge.net/p/icu/mailman/message/34125921/.
I'd like to get some Windows user tests of this besides myself before this is merged.

Full msys2 support

---

ChangeLog.md
src/Stack/Options.hs
src/Stack/Types/Config.hs
src/main/Main.hs

Fixes #806
Downside: usage information now looks like:
Usage: stack exec [CMD -- ARGS (e.g. stack ghc -- X.hs -o x)]
Notice how "CMD" is inside the square brackets. Still seems like a
worthwhile tradeoff to me.

Hacky workaround for optparse-applicative issue with stack exec --help

---

GUIDE.md
README.md

Addresses #874 just by mentioning the default in the README for stack setup, and by stating how stack is isolated in the guide.

Reference stack directories explicitly in guide

---

src/Stack/Docker.hs

src/Stack/Docker.hs:573:31:
warning: \u used with no following hex digits; treating as '\' followed by identifier [-Wunicode]
,maybe [] (\u -> ["--username=" ++ u]) (dockerRegistryUsername docker)

Fix warning about unicode specifier

---

src/Stack/Upgrade.hs
stack.cabal

Ref #811
I've tested on my local fork, it works. But I am not sure if I am doing it in a robust way. Perhaps I could have made a customised `readProcess` just like what you have as [`callProcess`](https://github.com/commercialhaskell/stack/blob/master/src/System/Process/Run.hs#L63).

Don't rebuild stack if it is up-to-date

---

GUIDE.md

I decided to read the GUIDE.md by editing it.
I thoroughly cleaned up the file, removing extraneous words,
fixing line lengths, making grammar fixes, clarifying unclear bits,
improving formatting, and generally improving anywhere I noticed room for improvement.
I know not every change may be precisely the preference of others, but I really didn't change any content, just made it more readable, cleaner, etc. I think the vast majority of this is just clear improvements. Unfortunately, the diff is a bit hard to follow because line changes in places make git unable to pick out what were mostly only small changes, just lots of them. The reflowing in cases makes the diff a bit less skimmable though.
One content change though: I removed the bit about the needed extra flag for bug prior to 0.1.4 …

complete copy-edit, clean up of GUIDE.md

---

src/Stack/Build/Execute.hs

When I upgraded to stack 0.1.4.1, switched to LTS-3.4 and back to LTS 3.0, this happened:
```
> stack build
...
alex-3.1.4: copying precompiled package
happy-1.19.5: copying precompiled package
...
Pr/Users/johndoe/.stack/snapshots/x86_64-osx/lts-3.0/7.10.2/bin/: copyFile: inappropriate type (is a directory)
/Users/johndoe/.stack/snapshots/x86_64-osx/lts-3.0/7.10.2/bin/: copyFile: inappropriate type (is a directory)
```
This commit fixed it for me.

copyFile can't handle directories

---

src/Stack/Types/Config.hs

When stack cannot parse the `resolver` field in `stack.yaml`, it currently prints the following error message:
> Could not parse '/Users/romac/Code/stack-resolver-bug/stack.yaml':
AesonException "failed to parse field 'resolver': Invalid resolver value: **ghcjs-0.1.0-ghc-7.10.2**. Possible valid values include lts-2.12, nightly-YYYY-MM-DD, ghc-7.10.2, and **ghcjs-0.1.0-ghc-7.10.2**. See https://www.stackage.org/snapshots for a complete list."
See https://github.com/commercialhaskell/stack/wiki/stack.yaml.
The message incorrectly mentions that `ghcjs-0.1.0-ghc-7.10.2` is a valid resolver name, when the correct one is `ghcjs-0.1.0_ghc-7.10.2`, as [advertised on the wiki](https://github.com/commercialhaskell/stack/wiki/stack.yaml).

Fix GHCJS resolver name in "Invalid resolver value" error message

---

src/Stack/GhcPkg.hs
src/Stack/Setup.hs
src/main/Main.hs

It can be handy to know which global db stack is using.  In order to add some hacks for xmonad recompilation, I needed to hardcode a global db path and compute my own GHC_PACKAGE_PATH (https://github.com/mgsloan/compconfig/blob/master/xmonad.hs#L505).  This patch also adds `stack path --ghc-package-path`.
One downside of this is that it adds an additional invocation of `ghc-pkg`.  Benchmarked with `time`, this seems to have a very negligible affect on speed of the `stack path` command.

Add stack path --global-pkg-db / --ghc-package-path

---

ChangeLog.md
src/Data/Binary/VersionTagged.hs
src/Stack/Build/Cache.hs
src/Stack/PackageDump.hs
src/Stack/PackageIndex.hs
src/Stack/Types/Build.hs
src/Stack/Types/BuildPlan.hs
src/Stack/Types/Compiler.hs
src/Stack/Types/FlagName.hs
src/Stack/Types/GhcPkgId.hs
src/Stack/Types/Package.hs
src/Stack/Types/PackageIdentifier.hs
src/Stack/Types/PackageName.hs
src/Stack/Types/Version.hs
stack-7.8.yaml
stack.cabal
stack.yaml

I tried to use the old stack and one with this patch one after each other, both pruned other's caches.
Fixes #889

Use binary-tagged, remove WithTag

---

src/Stack/Ghci.hs
src/Stack/Package.hs
src/Stack/Types/Package.hs

This works with the `hoogle` codebase now.
Pinging @ndmitchell for merge.
@snoyberg want to give it a quick sanity check?

Pass .o file paths to GHCi from c-sources (#756)

---

ChangeLog.md
src/Stack/FileWatch.hs
src/Stack/Options.hs
src/Stack/Types/Build.hs
src/main/Main.hs

When developing in a Docker container with code injected using a volume, `stack test --file-watch` run from inside the container won't register changes to the code made in the host environment because fsnotify events don't propagate down into the Docker container. This patch gives the option to poll the filesystem instead of relying on events, which is the less performant but more portable option. It's a pretty concise change to make since polling is already built into fsnotify - literally just flipping a bool.
I've sanity checked it against the example above (tests running in Docker container, code being edited outside the container) and it works like a charm. Let me know what you think!

Add filesystem polling via --file-watch-poll flag

---

src/Stack/Build/Execute.hs

This patch extends `extraBuildOptions` in `Execute.hs` to accept
an extra argument of type `BuildOpts`, as well as checking if coverage
is enabled. In case it is, `-hpcdir` is passed as `--ghc-option`.
This is needed to avoid certain in-memory REPL (like
[hint](https://hackage.haskell.org/package/hint)) to choke
on that command line option.
This was the result of a compilation with latest `stack`:
And this is compiling with my patched stack:
```
☁  chronos [issue-489] ⚡ /Users/adinapoli/programming/haskell/stack/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/Stack/stack clean
☁  chronos [issue-489] ⚡ /Users/adinapoli/programming/haskell/stack/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/Stack/stack install --flag chronos:development
```
A couple of things I have noticed (which I …

Fix #997 (pass --ghc-options -hpcdir) only on --coverage

---

LICENSE

This fixes #1020 by changing the name from stackage-common to stack.

Update LICENCE to correct the project name

---

ChangeLog.md
src/Stack/Build/Cache.hs
src/Stack/Build/Execute.hs
src/Stack/Setup.hs
src/Stack/Types/Build.hs
src/Stack/Types/Compiler.hs
src/Stack/Types/Config.hs
src/System/Process/Read.hs
src/main/Main.hs

See https://github.com/commercialhaskell/stack/issues/749#issuecomment-142477335 for more info - this isn't expected to work out of the box, since ghcjs source tarballs need to be available and listed in stack-setup-2.yaml

Support for stack setup installing + booting GHCJS

---

src/Stack/Build/Execute.hs

Executable only packages don't get an entry in the pkgdb. Instead stack marks them via a dummy file in installed-packages. If a package is copied from another snapshot it gets registered if it has library, but when it has not the binaries are copied but the snapshot, which they are copied to doesn't get to know this. That means every time you do stack build they get copied again. That alone isn't a big problem, but they can trigger rebuilds of other packages, which can get out of hand. A solution would be to mark them as installed. Writing this in copyPreCompiled does the trick:
```
case (mlib, exes) of
(Nothing, _:_) -> markExeInstalled (taskLocation task) taskProvides
_ -> return ()
```
But I wasn't sure about the full implications of this. So I opted for simply not caching them …

mark executable-only packages as installed when copied from cache

---

src/Stack/Constants.hs

I've had problems using Stack with our project on Windows. The issue was that when installing dependencies (in particular, aeson-pretty-0.7.2), Stack failed to compile Paths_aeson_pretty module because full path to intermediate files exceeded Windows 260 characters limit.
This pull request makes build artifacts path shorter by replacing "platform/cabal" part of it with first 8 characters of Base16-encoded SHA1 of it. In my case, this helped to get aeson-pretty succesfully installed.

Use partial SHA1 instead of full platform name and Cabal version on Windows

---

src/Path/IO.hs
src/Stack/Build/Execute.hs
src/Stack/SDist.hs
src/Stack/Setup.hs
src/Stack/Solver.hs
src/Stack/Upgrade.hs
src/System/Process/PagerEditor.hs
src/test/Network/HTTP/Download/VerifiedSpec.hs
src/test/Stack/BuildPlanSpec.hs
src/test/Stack/ConfigSpec.hs

When the $TMPDIR environment variable is set, the directory paths
provided by `withSystemTempDirectory` and `withTempDirectory` from
System.IO.Temp provided by the temporary library are not
canonicalised. This commit wraps these functions into canonicalized
versions.
See an earlier PR for discussion commercialhaskell/stack#1019
Fixes commercialhaskell/stack#1017

Canonicalizes temporary directory paths

---

src/Stack/FileWatch.hs

Just something which could be kind of nice.

Set default FileWatch command to force a rebuild

---

ChangeLog.md
doc/GUIDE.md
doc/architecture.md
doc/yaml_configuration.md
src/Stack/Build/Target.hs
src/Stack/Config.hs
src/Stack/Constants.hs
src/Stack/Docker.hs
src/Stack/Init.hs
src/Stack/New.hs
src/Stack/Setup.hs
src/Stack/Types/Config.hs
src/main/Main.hs

* Rename `~/.stack/stack.yaml` to `~/.stack/config.yaml`
* Rename `~/.stack/global` to `~/.stack/global-project`
* Rename `/etc/stack/config` to `/etc/stack/config.yaml`
* Support old locations of the renamed paths, with deprecation warnings
* Clarify wording of some messages
* Write comment to top of new `~/.stack/config.yaml` describing its purpose
* Write comment to top of new `~/.stack/global-project/stack.yaml` describing its purpose
* Write `~/.stack/global-project/README` describing the purpose of the directory

Rename config files and clarify their purposes (#969)

---

src/main/Main.hs

Fixes #1063.
Now it displays: 
```
> stack --version
Version 0.1.5.0, Git revision 06a4b270de2d2dcbd3ee8abe98078151c4a8f075 (dirty) (2204 commits) i386
```

Display the architecture properly

---

ChangeLog.md
src/Stack/Options.hs
src/Stack/Types/Config.hs
src/main/Main.hs

+ Generalize `execOptsParser` to accept a second optional argument for metavar.
+ Add a new command `eval`, where `stack eval CODE [ARGS]` evaluates to `stack ghc -- -e CODE [ARGS]`.

Fix #959: Inline haskell on the command-line

---

src/Stack/Build.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Installed.hs
src/Stack/Build/Source.hs
src/Stack/Config.hs
src/Stack/Init.hs
src/Stack/PackageDump.hs
src/Stack/Types/Build.hs
src/Stack/Types/Config.hs
src/Stack/Types/Package.hs
src/test/Stack/PackageDumpSpec.hs

This pull-request adds support for creating and using reusable _extra package database_ with stack.
[This test repository](https://github.com/vigoo/stack-sandbox-chain-test) demonstrates how it would work:
- `stack build` in `lib1` builds the library into the local package database and nothing else
- `stack build` in `lib2` builds its dependencies (`ansi-wl-pprint` and everything it needs) **and** `lib2` itself to its local package database.
- `stack build` in `app` builds the executable using both `lib1` and `lib2` from the previously built package databases.
The change adds two new options to the stack yaml:
- `extra-package-dbs` is a list of relative or absolute paths to extra package databases, which will be added on top of the _global_ package database, before snapshot and local
- …

Extra package database support

---

src/Stack/Types/Config.hs

Current `Monoid` instance does not allow to override behaviour as specified in [`stack-info` documentation](https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#setup-info).

Fix Monoid SetupInfo instance

---

src/main/Main.hs

@snoyberg vouched for stack path definitely not needing locking.  (Which makes intuitive sense, but I was conservative initially, and only opted out commands where after someone vouched for them or I read the relevant code.)
Note that as of the current release this only affects runs with `STACK_LOCK=true`.

Allow stack path to release the lock immediately.  Fixes #872

---

src/Stack/New.hs
src/Stack/Options.hs

Following #965, I added a new option "--bare" to stack new that causes the new project to be created in the current directory rather than in a subdirectory.

Add flag "--bare" to stack new #965

---

doc/yaml_configuration.md

Now that valid-wanted has been deprecated, it should be removed from the documentation.

Recommend extra-dep in yaml_configuration.yml

---

ChangeLog.md
src/Stack/Build/Installed.hs
src/Stack/Ghci.hs
src/Stack/Package.hs
src/Stack/Types/Build.hs
src/Stack/Types/Package.hs

Pass -package-id to ghci (closes #867)

---

doc/GUIDE.md

Added a brief comment about debugging and additional resources containing profiling reference and tutorials. In response to #877

Debugging guide

---

README.md

The previous link was giving back no results.
It seems like the label was changed.

Fix `awaiting pr` label link

---

src/Stack/Init.hs
src/Stack/Solver.hs

Pass the user-specified package flags to Cabal's "--constraint" argument.

Consider user-specified package flags in stack solver #1071

---

src/Stack/Ide.hs

This patch ensures we use the correct platform-specific search path separators in the `stack ide` command.
With this we're very close to a fully working stack-ide on Windows - just [#92](https://github.com/commercialhaskell/stack-ide/issues/92) remains.

Use platform-specific search path separators

---

doc/yaml_configuration.md

There's no `stack container image` command.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/commercialhaskell/stack/1168)

fix wrong image command in docs

---

src/Stack/FileWatch.hs
src/main/Main.hs
stack.cabal
stack.yaml

Pinging @agrafix. I believe that this is no longer necessary in Stack
since the file-watch code only monitors files which are actually used by
the build process. Can you confirm that this doesn't break your
workflow?

Remove ignore package dependency

---

appveyor.yml

Appveyor guarantees `curl` and `7z` on the PATH, so use the default tools, makes it easier to understand for non-Appveyor experts. I stole the appveyor code for HLint from Stack, then modified it in HLint, so this is me returning my changes.
cc @snoyberg who seems to be your Appveyor guy.

Simplify the Appveyor before_test setup

---

doc/GUIDE.md

I looked if there was a way to just link to the latest version, but I didn't find anything useful.

Update travis instructions to use stack-0.1.5.0

---

src/Stack/ConfigCmd.hs
src/Stack/Options.hs
src/main/Main.hs
stack.cabal
test/integration/lib/StackTest.hs

config selects the projects stack.yaml, regardless of directory
Parsing of config add command
Integration test helper (will be used to compare stack.yaml files)
Check to see if snapshot exists before writing
TODO:
Adding differnet fields
Additional subcommands for git

Stack config add resolver command

---

src/Stack/Ide.hs

The fix mentioned here https://github.com/lukexi/stack-ide-sublime/issues/17#issuecomment-142949632 still caused crashes since undefined was being evaluated. This makes it work as intended by changing it to `return ()` (and lets stack-ide-sublime work again)

Fix stack ide crash when not using stty

---

doc/yaml_configuration.md

Currently there is no documentation about the template parameters that `stack new` suggests if not set, i.e. `author-email`, `author-name`, `category`, `copyright` and `github-username`.
I've added some information based on my understanding of these parameters. I haven't looked at any code to see if my description is exhaustive of all effects of the parameters. It would be nice if someone who worked on the stack templates could proofread what I wrote.
I am open to suggestions of any kind.

yaml_configuration.md: Add information about template parameters

---

src/Stack/Build/Source.hs

Re: #1195 — let me know if there's a better place to do this!
(I also noticed a couple of .git files in the list returned from `getPackageFilesSimple`, maybe we should filter those too?)

Filter the cabal_macros.h file when checking for dirty files

---

src/Stack/Build/Execute.hs

The issue #1052 was once fixed but got broken again when compiling custom `Setup.hs` has been implemented — see https://github.com/commercialhaskell/stack/issues/1052#issuecomment-149281657. This PR fixes this by excluding local extra bin directories from lookup when searching for GHC to compile `Setup.hs` with.

Ignoring stack-built `ghc` executables when looking for compiler for Setup.hs (#1052).

---

appveyor.yml

The first commit saves me somewhere in the 1-3 minute range under good scenarios, but occasionally appveyor goes nuts and takes over an hour, which no longer happens with the new formulation.
The second makes it possible to actually navigate the appveyor page. Note that the `--arch i386` flag has disappeared. I think that's OK because stack binary i386 will default to i386. If not, perhaps there is a need for it to go in a `stack setup` flag?
Since Appveyor already has MSYS and 7zip installed, we could skip them with a suitable flag to `stack setup` (or by default), which would shave another minute or so off appveyor builds. I'm quite keen for stack to become the de facto appveyor toolkit, because its much easier than any alternative.
CC @snoyberg

More appveyor improvements

---

ChangeLog.md
src/Stack/Ghci.hs
src/Stack/Ide.hs
src/Stack/Options.hs
src/Stack/Types/Build.hs
src/main/Main.hs

(closes #1065, fixes #1180)
Optimistically, launch GHCi anyway even if the build fails.
@chrisdone, can you review?

'stack ghci': build project before launching GHCi

---

src/Stack/Types/StackT.hs

Resolves #1227.
I figure local times make much more sense than keeping UTC and adding on a timezone, similar to how other command line tools behave locally (I'm in AEST/GMT+11).

Show debug timestamps in user's local time

---

src/Stack/Package.hs

I remove the slash after stubdir, and it works.
I also removed them after -i, since it's cleaner, and it doesn't seem to make it worse.

Fixes #1067, failure to start ghci on Windows

---

src/Stack/Fetch.hs
src/Stack/Types/PackageIdentifier.hs
stack.cabal

This implements thing described in #158. I've chosen to stay conservative with threshold 1. Limiting number of matches can be confusing because desired package name can be eliminated from list of suggestions. With current implementation number of matches won't ever be too big to limit it.
Here is example of how it works:
```
[mark@arch ~]$ stack build stackage-metdata-0.3.0.0
Run from outside a project, using implicit global project config
Using resolver: lts-3.9 from implicit global project's config file: /home/mark/.stack/global-project/stack.yaml
Didn't see stackage-metdata-0.3.0.0 in your package indices.
Perhaps you meant "stackage-metadata"?
Updating and trying again.
Updating package index Hackage (mirrored at https://github.com/commercialhaskell …
```

Typo recommendations

---

src/Control/Concurrent/Execute.hs
src/Stack/Build/Cache.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Source.hs
src/Stack/Ghci.hs
src/Stack/SDist.hs
src/Stack/Types/Build.hs
src/Stack/Types/Package.hs

Third swing at this worked out well!
One issue this has is that in the presence of cyclic dependencies, it will rebuild each time.  I'm looking into this, but really it's not so bad since it's pretty rare to do this.
Here's the output of running `stack test` on my [https://github.com/mgsloan/multi-test-suite](multi-test-suite) repo, which originally was for testing test coverage with multiple test suites.  It now also includes an example of a cyclic dependency.  Specifically, `multi-test-suite` depends on `cyclic`, and `cyclic`'s test-suite depends on `multi-test-suite`.
```
cyclic-0.1.0.0: unregistering (dependencies changed)
multi-test-suite-0.1.0.0: unregistering (missing dependencies: cyclic)
cyclic-0.1.0.0: configure
cyclic-0.1.0.0: build
cyclic-0.1.0.0: copy/register …
```

Do all-in-one package builds when there are no cyclic dependencies

---

src/Stack/PackageDump.hs

`fromMaybe x (Map.lookup y z)` is equivalent to `Map.findWithDefault x y z`

Simplify a part of conduitDumpPackage a little bit

---

src/Stack/Types/Build.hs

[Data.Map.findWithDefault](http://hackage.haskell.org/package/containers-0.5.6.3/docs/Data-Map-Strict.html#v:findWithDefault) to the rescue.

Refactor `allGhcOptions` helper

---

src/Stack/Build.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Source.hs
src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/PackageIndex.hs
src/Stack/Types.hs
src/Stack/Types/Config.hs
src/Stack/Types/PackageIndex.hs
src/test/Stack/BuildPlanSpec.hs
stack.cabal

This PR covers issues uncovered by profiling the noopt build case. Results found that `Stack.PackageIndex.getPackageCaches`
was a costly function taking approx `%8-9` of total execution time. In additional
it was called three times by the following functions:
- `Stack.Build.ConstructPlan.constructPlan`
- `Stack.Build.Source.loadSourceMap`
- `Stack.Fetch.withCabalLoader`
taken together this would mean that the total time is around `%25` spent in this function. This PR makes improvements to the efficiency of this operation.
This PR makes two changes:
1. runOnce for withCabalLoader action in build config.
2. Safe invocations of getPackagesCaches should instead get a stored copy of the package caches from the build config. These are:
- `Stack.Build.ConstructPlan.constructPlan`
- …

Improved efficiency for getPackageCaches

---

src/Stack/Build/Haddock.hs

Among other things:
* Fix a comment that breaks haddocks generation for stack
* Rename the `generate*HaddockIndex` functions to `generate*Haddocks` as they generate both the index as well as the actual haddocks

Some refactorings in Stack.Build.Haddock

---

src/Stack/GhcPkg.hs
src/Stack/Setup.hs
src/main/Main.hs

An addition to the `extra-package-dbs` option (https://github.com/commercialhaskell/stack/pull/990), to pass the extra package databases in the `stack ghci` command too.

Support for extra-package-dbs in 'stack ghci'

---

src/Stack/Types/PackageName.hs

Fixes #1336, but now allows package names that cause a different error to happen when you try to build:
```
~/projects/test$ stack new "a-3o"
Downloading template "new-template" to create project "a-3o" in a-3o/ ...
[...]
Wrote project config to: [...]/projects/test/a-3o/stack.yaml
~/projects/test$ cd a-3o/
~/projects/test/a-3o$ stack build
Error parsing targets: Directory not found: a-3o
```
The error on attempting to build is of course not ideal.
It's caused by a "word" starting with a number, which is now allowed in my code. Cabal itself doesn't seem to care, but stack apparently does internally somewhere. It's related to the `PackageIdentifier` stuff of course, but I haven't looked deeper yet.
So, my question: should I just disallow that case, even though Cabal doesn't seem to care? …

disallow package names with "words" consisting solely of numbers

---

doc/yaml_configuration.md

Less confusing. The documentation for the `apply-ghc-options` uses "targets" to mean something else.

Slightly less confusing language in the documentation for `ghc-options`.

---

stack-7.8.yaml
stack.cabal

Generic derivation in <1.4 is
rnf x = seq x ()
which is not what we want.
Previously the deepseq-generics package was used, but not everywhere.  I
unfortunately dropped it. OTOH there were fair amount of wrong instances
defined without using the deepseq-generics. It's less error-prone to
simply bump lower bound.
One way to resolve https://github.com/commercialhaskell/stack/issues/1351

Bump lower bound of deepseq to >=1.4

---

src/Stack/Build.hs
test/integration/lib/StackTest.hs
test/integration/tests/1198-multiple-exes-with-same-name/Main.hs
test/integration/tests/1198-multiple-exes-with-same-name/files/also-has-exe-foo/also-has-exe-foo.cabal
test/integration/tests/1198-multiple-exes-with-same-name/files/also-has-exe-foo/app/Main.hs
test/integration/tests/1198-multiple-exes-with-same-name/files/app/Main.hs
test/integration/tests/1198-multiple-exes-with-same-name/files/has-exe-foo-too/app/Main.hs
test/integration/tests/1198-multiple-exes-with-same-name/files/has-exe-foo-too/has-exe-foo-too.cabal
test/integration/tests/1198-multiple-exes-with-same-name/files/has-exe-foo.cabal

...in a multi-package project because any of them could be the one that
ends up being used by `stack exec` or locally installed.
Fixes https://github.com/commercialhaskell/stack/issues/1198.

Warn if there are several executables with the same name

---

src/Stack/Build/Source.hs
src/Stack/Options.hs
src/Stack/Package.hs
src/Stack/SDist.hs
src/main/Main.hs

See #1183. Here I've added `--check` switch. Previously simple tuple was used to hold options for `upload` and `sdist` commands. Now with the addition of `--check` option, I switched to `(,,)`. Is it OK? Should some data structure be defined instead of tuple? This is very beginning of my work, so I create this PR early to ask questions along the way.

Addition of ‘--check’ option for ‘upload’ and ‘sdist’

---

src/Stack/Build.hs
test/integration/tests/1198-multiple-exes-with-same-name/Main.hs

* Using NonEmpty instead of [] removes one case to check in warnings
* Map.intersectionWith and Map.mapMaybe are more intuitive than
Map.mergeWithKey
* localExes is computed with a single list comprehension instead of two
As a side effect the order of the executables in the warnings has changed.

Improve calculation of build warnings

---

ChangeLog.md
doc/yaml_configuration.md
src/Stack/Config.hs
src/Stack/Types/Config.hs

Hi,
The ability to refer to a dependency on a git commit is useful, and I'd quite like to add support for the same thing for Mercurial repositories.
Firstly, would that be useful?
Secondly, I think all I'd have to do would be to add a new constructor to `Stack.Types.Config.PackageLocation`, implement `ToJSON` and `FromJSON`, and add a new case to `Stack.Config.resolvePackageLocation` that would look very similar to the git one except would run `hg clone` and then `hg update -C` instead of `git clone` and `git reset --hard` respectively. I've not actually tried it so perhaps there's more, but it'd be useful to know I'm on the right lines.
Thirdly, the cases for `PLHttpTarball` and `PLGit` are already rather similar and I'd feel bad adding a third case just like them. Would it be ok to …

Support for dependent packages in Mercurial

---

src/Stack/Upgrade.hs
src/main/Main.hs
stack.cabal

fixes issue #1425
Without the new flag, stack rebuilds a couple of modules when the git index changes:
```
~/projects/stack (flag_use_git_status_in_version)$ stack build
~/projects/stack (flag_use_git_status_in_version)$ touch bogus.txt                                                   
~/projects/stack (flag_use_git_status_in_version %)$ git add bogus.txt                                               
~/projects/stack (flag_use_git_status_in_version +)$ stack build
stack-0.1.9.0: unregistering (local file changes: .git/index)
stack-0.1.9.0: build
Preprocessing library stack-0.1.9.0...
[73 of 76] Compiling Stack.Upgrade    ( src/Stack/Upgrade.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Stack/Upgrade.o ) [/home/mud/projects/stack/.git/index changed]
In-place registering …
```

add flag to allow disabling compile-time git status checks

---

ChangeLog.md
src/Options/Applicative/Complicated.hs
src/Stack/Exec.hs
src/Stack/Ghci.hs
src/main/Main.hs

Uses `System.Directory.findExecutable`. Adds a `mOnInvalidArgs` callback to the
`complicatedOptions` function on `Options.Applicative.Complicated` the rest of
the logic is centralized on `Main`.
I didn't use `System.Process.Read.findExecutable` because I'd then need
`getMinimalEnvOverride`, which would require `GlobalOpts` I think. I'm not sure,
but I don't understand what'd give at the moment.
Will rebase after discussion.
This closes #1433.

Add executable fall-through

---

src/Stack/Build/Execute.hs
src/Stack/Docker.hs
src/Stack/Exec.hs
src/Stack/Ide.hs
src/Stack/Image.hs
src/Stack/New.hs
src/Stack/Setup.hs
src/Stack/Upgrade.hs
src/System/Process/Run.hs

this PR
- rename `runIn` to `runCmd`
- add a new `runCmd'` function taking and extra ```(CreateProcess -> CreateProcess)``` param
- fixes #1410 by using ```runCmd' (\cp -> cp { std_out = UseHandle stderr })``` in `getSetupExe`
- define a new `data CMD = CMD directoryToRunIn commandToRun envOverride commandLineArguments`
- refactor `runIn`, `callProcess`, `callProcess'` to take a CMD arg to ease code exploration, and argument passing

[RFC] Send output of building setup to stderr (fixes #1410)

---

src/Stack/Build/Execute.hs
src/Stack/Config.hs
src/Stack/Constants.hs
src/Stack/Docker.hs
src/Stack/Ghci.hs
src/Stack/Image.hs
src/Stack/Options.hs
src/Stack/Setup.hs
src/Stack/Sig/Sign.hs
src/Stack/Types/Config.hs
src/Stack/Types/StackT.hs
src/main/Main.hs

Here I've started to work on this. Currently I've added `--work-dir` option represented by `globalWorkDir` in `GlobalOpts`. Please correct me if this is a wrong place to put this option.
Now my plan is:
1. Store this option is Stack monadic environment (`Config`?), so functions that need to know stack working directory could query it. I think `HasConfig env, MonadReader env` can be used.
2. Instead of `workDirRel` constant, use that value from config, this will probably add `HasConfig, MonadReader env` or similar constraint to some functions that previously didn't need it.
3. Take care of `ignoreDirs` which specifies which directories shouldn't be searched for `.cabal` files. It currently lists `".stack-work"`. With this change it would need to construct the list more “dynamically”.
My …

Addition of ‘--work-dir’ option to override working directory, #1178

---

ChangeLog.md
src/Stack/Build/Execute.hs
src/Stack/Build/Source.hs
src/Stack/Ghci.hs
src/Stack/Package.hs
src/Stack/Types/Build.hs
src/Stack/Types/Package.hs

[WIP] resolves #1429
**`stack test --coverage`**

Support for detailed-0.9 test type

---

src/Data/Attoparsec/Args.hs
src/Stack/Build.hs
src/Stack/Build/Installed.hs
src/Stack/Build/Source.hs
src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/Config/Nix.hs
src/Stack/Coverage.hs
src/Stack/Docker.hs
src/Stack/Docker/GlobalDB.hs
src/Stack/Ghci.hs
src/Stack/Image.hs

Appy various hlint hints:
- Attoparsec.Args: Replace not . (==) with (/=)
- Stack.Build: redundant brackets
- Stack.Build.Installed: use `forM_`, redundant bracket
- Stack.BuildPlan: fuse mapM and map, use const
- Stack.Build.Source: redundant bracket, eta reduce
- Stack.Config: Redundant brackets
- Stack.Config.Nix: use when
- Stack.Coverage: use (/=)
- Stack.Docker.GlobalDB: use unless
- Stack.Docker: redundant brackets
- Stack.Ghci:  use mapMaybe
- Stack.Image: reduce duplication
-- 24pullrequests
[![](http://24pullrequests.com/assets/logo-8a77737f86fec8def19a1c9a605c9841dbd44e59f243ed3bf64bbdf3214d6fa1.png)](http://24pullrequests.com/)

Apply various hlint hints

---

src/Data/Attoparsec/Args.hs
src/test/Stack/ArgsSpec.hs
stack.cabal

Added functions to generate input strings comprehensively for the
interpreter argument parser. The generator combines the alternatives in
all possible ways.
After running the tests, found a couple of bugs of theoretical interest
and fixed those so that the parser behaves in a consistent manner even
in those cases.

Add unit tests for interpreter argument parser

---

src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/BuildPlan.hs
src/Stack/GhcPkg.hs
src/Stack/Package.hs
src/Stack/PackageDump.hs
src/Stack/PackageIndex.hs
src/Stack/Setup.hs
src/Stack/Setup/Installed.hs
src/Stack/Types/Build.hs
src/Stack/Types/BuildPlan.hs
src/Stack/Types/FlagName.hs
src/Stack/Types/GhcPkgId.hs
src/Stack/Types/PackageIdentifier.hs
src/Stack/Types/PackageName.hs
src/Stack/Types/Sig.hs
src/Stack/Types/Version.hs
src/test/Stack/DotSpec.hs
src/test/Stack/PackageDumpSpec.hs
stack.cabal

This is a WIP attempt to fix #1337.
It's a refactor with very minor changes of my previous attempt (mostly cleaned up history and manually reviewed the changes I'd done to make sure they ... actually made sense).
Comments welcome, and I'm still testing and working on adding integration tests and such.

improve unicode handling

---

src/Stack/Config.hs
src/System/Process/Read.hs

See #1453. It should be as simple as this, but it doesn't work. According to actual message the whole `Left` pattern in `readInNull` is not executed (otherwise error message would be different), so that additional message is not logged. I grepped all places where `ProcessExistedUnsuccessfully` is caught, everywhere it's handled similarly to how it's done in `readInNull`. Are you sure it ever works?
Perhaps `Left (ProcessExitedUnsuccessfully _ ec)` is not correct approach here? Shouldn't we get existentially qualified `SomeException` with actual typeable exception inside it which then can be extracted with help of `fromException`? Maybe that's why pattern matching fails?
Maybe I'm wrong, I'll return to this later.

Show a message when resetting git commit fails

---

src/Data/Attoparsec/Args.hs
src/main/Main.hs

We were prioritising execution of a file over stack commands if a filename in
the current directory was the same as a stack command. With this fix we first
try a stack command, then an external command stack-<command> and if those fail
we look for a file in the current directory to execute in interpreter mode.
If we intend to execute the file we can specify the path like ./filename.
I had to refactor `main` to make this work. I tried to minimise the refactoring
and limit the scope to only this fix. Main looks better and modular now.
closes #1471

Fix #1471 stack commands and file name conflicts

---

src/Stack/Docker.hs
src/Stack/Nix.hs
src/main/Main.hs

Stack interpreter comment annotation allows arbitrary commands to be
written and executed when the file is run. It can lead to confusing
and surprising behavior if mistakes are made in writing a proper
comment.
This change restricts the interpreter mode commands to runghc and
runhaskell. This change moves add-commands to a separate function.
Closes #1504

Restrict commands allowed in interpreter mode

---

doc/GUIDE.md
src/Data/Attoparsec/Args.hs
src/Data/Attoparsec/Interpreter.hs
src/main/Main.hs
src/test/Stack/ArgsSpec.hs
stack.cabal

Add better diagnostics to interpreter options parsing. More details in the commit messages.
Its best to review the commits spearately. The first commit just splits a file, no other change. The second one is most of the changes.
Closes #1516

Interpreter error messages

---

src/Stack/Nix.hs

Nix: Pass $STACK_IN_NIX_EXTRA_ARGS before command args.

---

doc/faq.md

At the moment, the link is not actually rendered as a link at http://docs.haskellstack.org/en/stable/faq.html#i-get-strange-ld-errors-about-recompiling-with-fpic, this should (hopefully, since I couldn't find out how to actually build the documentation) fix that.

faq.md: Don't split a link across a line break

---

src/Stack/Config.hs
src/Stack/New.hs
src/Stack/Options.hs
src/Stack/Types/Config.hs
src/Stack/Types/TemplateName.hs
stack.cabal

- You can now specify an explicit URL to download the template from
- I've improved the logging/output so that it doesn't say it's "Downloading" a local file
- You can specify a default-template in ~/.stack/config.yaml, which is nice if you have a favorite
I considered adding the ability to configure the template repository location, but I'm thinking I might leave that for a separate PR later if it sounds interesting to anyone. I think it'd be a decent feature, but it's a little complicated by the existence of the `stack templates` command, which I haven't really worked out how to deal with.
I'm working on some tests to exercise this functionality and make sure, but it basically seems to work fine to me.

improve 'stack new'

---

src/Stack/Build/Execute.hs

In a previous version of `stack`, running
stack test my-project:test:test-suite-1
would only run `test-suite-1`. The behaviour now seems to be to run all test suites.
Furthermore, running
stack clean
stack test my-project:test:test-suite-1
only seems to _build_ the given test suite but then attempts to run them all, and obviously the rest of them fail with `executable not found`.

All test suites run even when only one is requested

---

src/Stack/New.hs

give better errors for broken templates

---

src/Stack/Build/Installed.hs

Annoying double space in generated (verbose?) text.
For example: 
```
[debug] Ignoring package Cabal due to  wanting version 1.22.5.0 instead of 1.22.4.0
```
Note the double space in "to  wanting".

Remove aberrant double spaces in generated text

---

src/Stack/Options.hs

```
$ stack image --help
Usage: stack image COMMAND [--help]
Subcommands specific to imaging (EXPERIMENTAL)
--help                   Show this help text
Available commands:
container                Build a Docker image for the project
Run 'stack --help' for global options that apply to all subcommands.
```
```
$ stack image --help
Usage: stack image [--nix-shell-file FILEPATH] COMMAND
[--nix-shell-file FILEPATH] [--help]
Subcommands specific to imaging (EXPERIMENTAL)
--nix-shell-file FILEPATH
Nix file to be used to launch a nix-shell (for
regular Nix users)
--nix-shell-file FILEPATH
Nix file to be used to launch a nix-shell (for
regular Nix users)
--help                   Show this help text
Available commands:
container                Build a Docker …
```

Hide `nix-shell-file` from help text

---

doc/README.md

Following steps from "How to contribute" section, I've noticed that `stack --version` doesn't launch newly-built stack executable and probably should be changed to `stack exec stack -- --version`.

[docs] Small fix in 'How to contribute' section.

---

stack.cabal

The build dependency on email-validate from bcf73ec0 seem to be redundant.

stack.cabal: remove the redundant build-dependency on email-validate

---

src/Stack/Options.hs

Now passing --no-nix is not considered evidence of a need for Nix.

Obey --no-nix

---

src/System/Process/Read.hs

This makes reproducing bugs much easier. Now I see:
Running C:\Program Files (x86)\Git\cmd\git.exe fetch --tags --depth=1 in directory C:\Users\ndmit_000\AppData\Roaming\stack\indices\Hackage\git-update\all-cabal-hashes\ exited with ExitFailure 128
Before I just saw a git, but the directory it was in took ages to find.

Include the current working directory in process failure exceptions

---

src/Stack/PackageIndex.hs

This helps with #1418, certainly recovering from an artificial instance of the problem I was able to reproduce (just deleting the `.git` directory).

If git fetch fails wipe the directory and try again from scratch

---

doc/GUIDE.md

The -- can be used to pass parameters to the executable instead of
stack when stack exec is used. We added a short note in the debugging
section as an alternative.

Add note in debugging section on parameter passing

---

doc/travis_ci.md

The installed version did not match with what was added to PATH,
effectively ignoring installed GHC.

Fix version mismatch in Travis-CI doc

---

src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/ConfigCmd.hs
src/Stack/Init.hs
src/Stack/Options.hs
src/Stack/Setup.hs
src/Stack/Setup/Installed.hs
src/Stack/Solver.hs
src/Stack/Types/Build.hs
src/Stack/Types/BuildPlan.hs
src/Stack/Types/Config.hs
src/System/Process/Read.hs
src/main/Main.hs

These commits are part of a series of commits to enhance the `stack init` and `solver` functionality. The goal is to be able to automatically init any project which has a working cabal file. Similarly the `stack solver` command should be able to verify and fix the configuration in an optimal manner. Also, to provide a better user experience by providing informative error messages and next steps at every failure. In other words, init should just work and be smooth and painless and always work unless the package is really broken.
See also #1529 and #1533.
The commit messages have more details about the problems and fixes. I will be adding more commits to the branch very soon. I am pushing these out for an early review. The changes are logically self contained, add incremental functionality …

Stack init and solver overhaul

---

ChangeLog.md
src/Stack/Config.hs
src/Stack/Config/Nix.hs
src/Stack/Nix.hs
src/Stack/Types/Config.hs-boot
src/Stack/Types/Nix.hs
src/main/Main.hs
src/test/Stack/NixSpec.hs

Stack now selects the correct GHC version in the following cases:
* an abstract resolver was given,
* a concrete resolver was given,
* a compiler version was given.
Previously, we could only deal with concrete resolvers correctly. So
e.g.
```
$ stack --resolver lts-2 build
```
should now use GHC-7.8.4 from the nixpkgs repo. I think exactly the same
approach should be workable for Docker too, but how exactly the use case
should work there is less clear to me.
Fixes #1641.

Nix: select the right GHC version in more cases.

---

stack.cabal

Add an optional flag, that is off by default to allow the stack binary to be created as a fully static executable.
This is primarily to enable fully static binaries on Alpine Linux which uses musl libc and is designed for static linking. The resultant binaries can run on almost any linux however, depending on libc used. (don't do this with glibc distributions unless you like weird behavior)
Example:
```
/tmp/stack-1.0.0 # cabal install -fstatic
Resolving dependencies...
In order, the following will be installed:
stack-1.0.0 (latest: 9.9.9) +static (reinstall) (changes: gitrev-1.1.0 added, optparse-simple-0.0.3 added)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Notice: installing into a sandbox located at /tmp/stack-1.0.0/.cabal-sandbox
Configuring …
```

Add static flag to the stack executable

---

src/Stack/Clean.hs
src/Stack/Constants.hs
src/Stack/Options.hs

Now this option do the work requested.
stack new test
cd test
stack build
stack clean --full
This will clean all the targets for complex project.
Also tested with single and multiple targets ie
stack clean target1 target2 --full

Added option for full working dir cleanup in command clean

---

doc/yaml_configuration.md
src/Stack/Config.hs
src/Stack/Types/Config.hs
stack.cabal

Allow to use Github's 'download as zip' in addition to Tarballs and Git clone.

YAML config: support Zip archives

---

src/Stack/New.hs

Hi
With the new year just rolling around, @Toxaris noticed a lot of the templates at [stack-templates](https://github.com/commercialhaskell/stack-templates) [needed updating](https://github.com/commercialhaskell/stack-templates/issues/28). This PR aims to address this and prevent it in the future by providing a mechanism for templates to insert the current calendar year.
If accepted, templates will be able to be written like:
```Copyright {{author-name}} (c) {{year}}```
Thanks

Give mustache templates access to a 'year' tag

---

stack.cabal

This has the benefit that we now have haddocks for all of stack's internal
modules. This even includes "Paths_stack", assuming that others would be
as curious about its contents as me.
Fixes #1733.

Expose "other-modules" #1733

---

doc/install_and_upgrade.md

Small note prompting to run `xcode-select --install` if C compiler is not found while calling `stack setup`

note in install_and_upgrade regarding #1515

---

doc/docker_integration.md

Noticed a small typo, so I reworded the note.

Fix typo in docker reset documentation

---

ChangeLog.md
doc/yaml_configuration.md
src/Path/Find.hs
src/Stack/Build/Execute.hs
src/Stack/Config.hs
src/Stack/Constants.hs
src/Stack/Constants.hs-boot
src/Stack/Docker.hs
src/Stack/Options.hs
src/Stack/Types/Config.hs

Users other than the owner of the ~/.stack directory are now prevented
from using a stack installation in order to avoid problems with file
permissions. To disable this precaution users can pass the
--allow-different-user flag or use the 'allow-different-user'
configuration option in their ~/.stack/config.yaml.
On Windows, the new flag and configuration options have no effect.
When stack is re-spawned in Docker, the ownership check is skipped
(see #1777).
This reverts commits 0a89c9c29d744a4955e62b59774036e98d6b1e8e and
218e7ddb90c346d814474cb6b8c5e9c67c4706f8.

Add 'allow-different-user' flag and configuration option #471, fix #1777

---

src/Path/Extra.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Target.hs
src/Stack/Package.hs

Previously the idiom `forgivingAbsence (relsoveFile …)` alone was used, which relied on `canonicalizePath` throwing `isDoesNotExistError` when path does not exist. As it turns out, this behavior is actually not intentional and unreliable, see
https://github.com/haskell/directory/issues/44
This was “fixed” in version 1.2.3.0 of `directory` package (now it never throws). To make it work with all versions, we need to use the following idiom:
```haskell
forgivingAbsence (resolveFile …) >>= rejectMissingFile
```
This commit fixes all cases where new directory versions might cause problems.

Improve file and directory resolution

---

src/Stack/Build/Source.hs
src/Stack/Build/Target.hs
src/Stack/Config.hs
src/Stack/Ghci.hs
src/Stack/Init.hs
src/Stack/Types/Config.hs

The field has been deprecated since [v0.1.1.0](https://github.com/commercialhaskell/stack/releases/tag/v0.1.1.0).
I've also removed all references to "validWanted" and introduced a type alias `TreatLikeExtraDep` to make it easier to interpret the `Bool` that is being passed around.

Remove deprecated valid-wanted field

---

doc/GUIDE.md

the ghc (non-stack) builds will sometimes need alex or happy.
having gmp-dev is not enough, we need the actual libs as well.

alex, happy, and libgmp where necessary

---

src/Stack/New.hs
src/Stack/Package.hs
src/Stack/Solver.hs

This allows stack templates to define only a `package.yaml` file instead of a
`.cabal` file.
Let me know if this needs a bit more finesse around how it generates the cabal files.  I.e. I could probably unify how it walks the dir path generating as it goes if a package file is found, instead of walking twice.

Adds hpack support for when initing projects.

---

ChangeLog.md
src/Stack/Config.hs

`git` packages using submodules may need to be cloned recursively.
- Allows us to pass arguments to the `clone` command on a case-by-case basis.
- Adds the `--recursive` option to `git clone`.
- `hg clone` will [already clone subrepos](https://www.mercurial-scm.org/wiki/Subrepository#Update).
I have not added a configuration option to control this, because it doesn’t seem particularly useful in the context of repos which are Haskell packages.
Fixes #1764.

Clone recursively

---

src/Stack/Init.hs
src/Stack/Types/Config.hs

Sometimes you already know that dependencies will not be met and want to create
a config anyway which you will fix later. In that case we can skip using
--solver and directly use --omit-packages to create a config with packages
commented out in the config.

Allow --omit-packages even without --solver

---

stack-7.8.yaml
stack.cabal
stack.yaml

- fix an issue with file globs on Windows
- add support for conditionals

Require hpack >= 0.10.0

---

src/Stack/Exec.hs
src/Stack/Ghci.hs

spawn 'stack ghci'

---

doc/faq.md

As mentioned in #1862 (specifically [this comment](https://github.com/commercialhaskell/stack/issues/1862#issuecomment-191173247)).
* Role of the `- '.'` line has been clarified
* A note has been added to the git-only example to reinforce this.

Clarified the role of the `- '.'` line.

---

src/Stack/Ghci.hs

* :add main-file on a separate line in order to load as much as possible in case of error
does not solve the root problem, but improves the end ghci state of #1606
* Current
```
Specify main module to use (press enter to load none): 1
Loading main module from cadidate 1, --main-is /Users/luigy/code/haskell/ghcid/src/Ghcid.hs
Configuring GHCi with the following packages: ghcid
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
[1 of 8] Compiling Language.Haskell.Ghcid.Util ( /Users/luigy/code/haskell/ghcid/src/Language/Haskell/Ghcid/Util.hs, interpreted )
[2 of 8] Compiling Wait             ( /Users/luigy/code/haskell/ghcid/src/Wait.hs, interpreted )
[3 of 8] Compiling Language.Haskell.Ghcid.Terminal ( /Users/luigy/code/haskell/ghcid/src/Language/Haskell/Ghcid/Terminal.hs, …
```

better ghci result after :load collisions with Main module

---

src/Stack/Build/Haddock.hs
stack-7.8.yaml
stack.cabal
stack.yaml

In order to fix https://github.com/commercialhaskell/stack/issues/1832 , as @mrkkrp suggested we switch to `path-io-1.1.0`
Can people test it to be sure no other permission problems appear?

Fix permission error when haddock files are copied within stack --nix

---

doc/install_and_upgrade.md

The current installation instructions state that you need to run the following command:
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 575159689BEFB442`
This is fine if your firewall doesn't block it, but this isn't the case for many people (port 11371 is often blocked). The workaround for this is to use the following url for the key server instead:
`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 575159689BEFB442`
This is the pull request changing this, as suggested here: https://github.com/commercialhaskell/stack/issues/1914
Martin Dehnel-Wild

Change default keyserver URL to port 80 not 11371 (to prevent firewall issues in installation)

---

src/Stack/Docker.hs

This patch is for docker projects and specifically to assist tools (e.g.
Emacs) that read/write files in $HOME for dev work (flycheck & friends)
resolves #1949

mount $HOME in the container

---

src/Stack/Sig/GPG.hs
src/Stack/Sig/Sign.hs
src/Stack/Types/Sig.hs

OpenPGP Key ID is the least reliable way to identify a key. From the
spec:
"Note that it is possible for there to be collisions of Key IDs -- two
different keys with the same Key ID. Note that there is a much smaller,
but still non-zero, probability that two different keys have the same
fingerprint."
resolves #1952

Always use full fingerprints from GPG

---

doc/GUIDE.md

Make needed changes to .cabal for the extra-deps acme-missiles example in GUIDE.md more explicit by adding a snippet.

Add .cabal snippet to acme.missiles example in GUID.md

---

doc/ghcjs.md

Moved "old base" to the bottom
Added 2 newer GHCJS examples at the top

updated ghcjs examples

---

src/Options/Applicative/Complicated.hs
src/main/Main.hs
stack.yaml

```
% stack exec -- stack --version
Version 1.0.5, Git revision c2159137c1cdff5bb4e6c68c58967038e26a0a5b (dirty) (3450 commits) x86_64 hpack-0.12.0
% stack exec -- stack --hpack-numeric-version
0.12.0
```

Issue 1800: Show bundled hpack version in --version

---

src/Stack/Config.hs

Fixes the problem:
```
packages:
- location:
git: http://gerrit.example.com/myrepo
commit: refs/changes/14/1814/2
```
```
$ stack test
Running /usr/bin/git reset --hard refs/changes/14/1814/2 in directory /home/cblp/dev/example/.stack-work/downloaded/cd48acc46c3d9ad4e0b5362b27617c4cb3d379e93b5d73338191b1a3ded81633.tmp/ exited with ExitFailure 128
fatal: ambiguous argument 'refs/changes/14/1814/2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Please ensure that commit refs/changes/14/1814/2 exists within http://gerrit.example.com/myrepo
```

Allow git/hg revisions containing slashes

---

src/Stack/New.hs
src/Stack/Types/TemplateName.hs

Hi! This is my first stab at #1571. There didn't seem to be much of a consensus on how best to implement this feature so I went off of @mgsloan's suggestion:
> An alternative implementation not blocked on #1595 would be to have a single file in the templates repo that associated template names with descriptions / other metadata.
Running stack templates now downloads and can display optional metadata from a .yaml file located in the stack-templates repository.
The file is setup like this:
``` yaml
quickcheck-test-framework:
description: a library for random testing of program properties
servant:
description: a set of packages for declaring web APIs at the type-level
ghcjs:
description: Haskell to JavaScript compiler, based on GHC
```
Currently the data type I implemented supports …

retrieve template metadata from stack-template repo

---

src/Stack/Build/ConstructPlan.hs
src/Stack/PackageIndex.hs

For no-op builds of the `these` package I see speedups of about 17%. For the `stack` project it's only around 8%.

Avoid expensive version calculations during build plan construction

---

src/Stack/Build/ConstructPlan.hs
src/Stack/Fetch.hs
src/Stack/PackageIndex.hs

Avoid loading of package caches during build plan construction

---

doc/nix_integration.md
src/Stack/Types/Nix.hs

In order to solve https://github.com/commercialhaskell/stack/issues/1924, I propose to no longer enable nix by default when a nix: section is present in the configuration.
This allows package developers to propose a nix configuration (list of nix packages) for their packages without _forcing_ the use of nix. I.e. now, if the user has a `nix.enable` flag set to `false` in their `$HOME/.stack/config.yaml`, this setting will not be overriden by the presence of a nix package list.

Removing nix enabled by default when nix: section is present

---

src/Stack/Package.hs
src/Stack/Sig/GPG.hs
src/Stack/Sig/Sign.hs
src/Stack/Solver.hs
src/Stack/Types/Sig.hs
src/test/Stack/SolverSpec.hs
stack-7.8.yaml
stack.cabal

Also `text-1.2.1.1 (latest: 1.2.2.0) -integer-simple (via: parsec-3.1.9) (new package)` was parsed without flags before

Resolve #2084: Rewrite solver output parseLine using regexp

---

ChangeLog.md
src/Stack/Build.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Source.hs
src/Stack/BuildPlan.hs
src/Stack/Coverage.hs
src/Stack/Dot.hs
src/Stack/Fetch.hs
src/Stack/Ghci.hs
src/Stack/Ide.hs
src/Stack/Package.hs
src/Stack/SDist.hs
src/Stack/Setup.hs
src/Stack/Solver.hs
src/Stack/Types/Build.hs
src/Stack/Types/BuildPlan.hs
src/Stack/Types/Config.hs
src/Stack/Types/Package.hs
src/Stack/Upgrade.hs
src/test/Stack/BuildPlanSpec.hs
stack-7.8.yaml
stack.cabal

This patch turned out to be much larger than expected, and mostly for tedious reasons. I recommend reviewing one commit at a time, as two of these are very mechanical (changing constraints and adding fields to some data types).
I added support to stackage-curator recently to include hashes of .cabal files for newly generated snapshots. This patch will ensure that, when using Git as a package index and a snapshot with this hash information, we get the same version of the .cabal file as was used when generating the snapshot, avoiding the possibility of Hackage edits from corrupting the snapshot for end users.
I recommend holding off on merging this for a few days so it can be properly tested with upstream Stackage Nightly snapshots that actually have this .cabal hash information.

Cabal file Git SHA

---

src/Stack/Sig/GPG.hs

Otherwise we are assuming the user has set up their gpg.conf like
everyone else [bad assumption]

always use --with-fingerprint

---

src/Stack/Config/Nix.hs

We only want to filter the version, not the whole name. Otherwise, we end
up with things like "haskellpackagesghc7103" which is of course nonsense.
Also, when the stack.yaml file only specifes a major ghc version (like 7.10), we
need to supply a minor version so that we can look up the correct compiler in
nixpkgs.

nix: fix generation of compiler attribute

---

src/Stack/Coverage.hs

`show (ErrorCall x) = x`, so the error message is as before.

Fix pattern overlap warning with GHC-7.8 and GHC-7.10

---

src/Stack/Build/Haddock.hs
src/Stack/Config/Build.hs
src/Stack/Options.hs
src/Stack/Types/Config/Build.hs

This is my first PR to this repository, I tried to follow the code usages.
Tell me if something is surprising.
This simply add the "--haddock-arguments" options which takes a string of arguments.
So you could for example use your own CSS:
~~~
stack haddock --haddock-arguments "--css $PWD/my.css"
~~~

Ability to provide args to haddock command

---

doc/GUIDE.md

There is no "enable" in the flags for the "stack install" command.

Correct profiling flag names

---

src/Data/Store/VersionTagged.hs
src/Stack/Build/Cache.hs

There was an issues that caused the decoding of the caches to fail (see
fpco/store#25): decodeFileMaybe tried to deserialize to a value of type
a, while the files contained values of type Tagged a.

Fix caches.

---

src/Stack/Setup.hs
src/Stack/Setup/Installed.hs

It's odd to create an empty directory just to list it, from a function that merely lists the installed programs. Better to have that directory created at the same place we may be writing to it.

listInstalled: move side-effects away

---

src/Stack/Build/Cache.hs

Because these paths always point inside the Stack root, better make them relative to the Stack root, making the Stack root more easily relocatable, in the future.
This change is backward-compatible.

Make the paths stored in precompiled-cache Stack-root relative

---

src/Stack/Ghci.hs
src/Stack/Package.hs

`Distribution.Simple` based `Setup.hs` sometimes create
`<package>.buildinfo` files as an artifact of the configure phase.
This is the case in particular when using the autoconf hooks. Since
this is an internal detail private to any given package's `Setup.hs`,
Stack shouldn't (and doesn't) need to care or be aware of this. But
`stack ghci` does, since in that use case we're not using Cabal to
build - we're taking care of the build ourselves. In particular,
ignoring the `<package.buildinfo` file can mean that a successful
build using `stack build` can't be replicated using `stack ghci`.
E.g. in the case of the `network` package, the set of C files to build
is decided at configure time, based on the current platform. So the
`c-files` stanza in the .cabal file is not complete. This in turn …

Support .buildinfo files in stack ghci.

---

src/Stack/Types/Config.hs
src/System/Process/Read.hs
src/main/Main.hs

Blocked on https://github.com/ndmitchell/hoogle/issues/170#issuecomment-227970023
Pinging @snoyberg @mgsloan @borsboom @ndmitchell

Add stack hoogle command (hoogle-5.0)

---

src/Stack/Build/Source.hs

Commit c891a24 created a regression, ghc-options were no longer applied to 
packages in the snapshot. The "mini build plan" for missing snapshot packages
did not check the configuration's "ghc-options" settings at all, so even
configurations with "apply-ghc-options: everything" would not apply those
options.
This commit, combined with a change to config.yaml, fixes these issues:
https://github.com/DanielG/ghc-mod/issues/762
https://github.com/gibiansky/IHaskell/issues/636
To fix those issues, `config.yaml` (usually located in `~/.stack`) should
contain:
```
apply-ghc-options: everything
ghc-options:
"*": -opta-Wa,-mrelax-relocations=no
```
And for snapshots already installed, the following command will force stack
to rebuild them with those options:
```
stack exec -- ghc-pkg unregister …
```

Fix issue #2289, apply ghc-options to snapshot pkg

---

src/Network/HTTP/Download.hs
src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/Fetch.hs
src/Stack/New.hs
src/Stack/PackageIndex.hs
src/Stack/Setup.hs
src/Stack/Sig/Sign.hs
src/Stack/Types/Config.hs
src/Stack/Types/TemplateName.hs
src/Stack/Upload.hs
src/test/Network/HTTP/Download/VerifiedSpec.hs
stack-7.8.yaml
stack-8.0.yaml
stack.cabal
stack.yaml

Because I'm not really familiar with `http-client` I usually opted to replace the deprecated `parseUrl` with the synonymous `parseUrlThrow`.
Closes https://github.com/commercialhaskell/stack/issues/2332.

Use http-client-0.5.0, http-conduit-2.2.0, http-client-tls-0.3.0

---

ChangeLog.md
src/Stack/Nix.hs

GHCi and therefore template haskell need LD_LIBRARY_PATH when in a nix shell.
This makes stack (when using a list of nix packages instead of a shell file) behave more like `haskell.lib.buildStackProject` in nixpkgs.
See for instance https://github.com/tweag/HaskellR/issues/253

Nix: Adding LD_LIBRARY_PATH to shell (Template Haskell issues)

---

ChangeLog.md
src/Stack/Package.hs

This is necessary for packages that use a custom Setup.hs
(`build-type: Custom`).  Previously, stack wouldn't rebuild the package
if the only changes were to the `extra-source-files`.
Stack was already marking the package as dirty if `data-files` changed;
this just hooks `extra-source-files` into the same mechanism.

Let extra-source-files mark a package as dirty (#1891, #2040).

---

ChangeLog.md
doc/yaml_configuration.md
src/Stack/Config.hs
src/Stack/Options.hs
src/Stack/Types/Build.hs
src/Stack/Types/Config.hs

This allows one to specify `with-gcc:` in stack.yaml.
Happy for any feedback - I just picked this up as it's marked with newcomer!

Add a config option to override gcc path

---

src/Stack/Image.hs
src/main/Main.hs

Fixes a bug where the user executes
`stack image container --image image9`
where the stack.yaml has multiple docker image definitions.  The code
was staging all of them but then creating an image by selecting the base
image (correct) along with the contents of folder "0" (incorrect)
Solution is to only stage the image(s) that we want to build (using the
same image name fitering that we have in our function to build the
image(s).
Haskell does not protect you from logic fails :D

PAT-590 incorrect docker image content

---

stack.cabal

Stack uses createProcess_ which has been added in `process-1.2.1`.
Therefore, the prior bound on process ( `>= 1.2.0 && < 1.5` ) was too lax.

cabal: Require process-1.2.1 or greater

---

ChangeLog.md
src/Stack/Types/Build.hs

This fixes issue #2350. See the commit for details.
This PR also includes a minor refactoring commit which improves consistency.

Fix cabal warning about use of a deprecated profiling flag (Fixes #2350)

---

src/Stack/Types/Config.hs

Follow-up to #2374. Unfortunately, the Yaml library's `prettyPrintParseException` doesn't do a great job for the example in #2374:
```
Could not parse '/home/sidharth/sidharthkapur1@gmail.com/workspace/stack-testing/2374/stack.yaml':
YAML parse exception at line 2, column 17,
:
mapping values are not allowed in this context
See http://docs.haskellstack.org/en/stable/yaml_configuration/.
```
The second line of the error contains only a `:` because `yamlContext` is empty in this case (see [code](https://hackage.haskell.org/package/yaml-0.8.18/docs/src/Data-Yaml-Internal.html#prettyPrintParseException)). It would be nice to send them a PR to clean this up. Regardless, I think this is an improvement.

Pretty-print YAML parse errors

---

src/Stack/SDist.hs

Here tar (the tool) [warns on Travis](https://travis-ci.org/commercialhaskell/stack/jobs/145921846#L254) that a time stamp in a tarball generated by stack sdist is very odd:
> tar: stack.cabal: implausibly old time stamp 1970-01-01 00:00:00
The warning *is* harmless, but it might still puzzle users (e.g. http://raspberrypi.stackexchange.com/a/13152/4395 in other scenarios), so here's a 2-line fix.

stack sdist: Fix timestamp in tarball

---

src/main/Main.hs

Stack has support for running Haskell scripts directly, when you pass a
filename as an argument.
Previously this worked by having a fallback: if any argument couldn't be
parsed as a valid option, check if the first argument was a file.
Sadly this broke for cases such as:
stack --nix example.hs
And this means something different:
stack example.hs --nix
Now Stack will split the arguments into two:
1. All arguments until the first existing file
2. The first existing file and all arguments afterwards
So the above example gets parsed as:
1. `["--nix"]`
2. `["example.hs"]`
The first section will be reparsed as options. The second section will
be used like it was previously.
This fixes the specific case of running interpreter scripts when having
the Nix option enabled globally. Stack would …

Allow global Stack arguments with a script

---

ChangeLog.md
doc/nix_integration.md
src/Stack/Config/Nix.hs
src/Stack/Nix.hs
src/Stack/Runners.hs
src/main/Main.hs
src/test/Stack/NixSpec.hs

As explained in https://github.com/commercialhaskell/stack/issues/2259
we will soon no longer be able to give to nix-shell indentifiers like `haskell.packages.lts-5_14.ghc`
since LTS mirroring will be removed from the Nixpkgs.
This PR proposes to retrieve the wanted GHC version before creating the nix shell, which will now
always be called with derivations like `haskell.compiler.ghc7103`.
Until the lts mirroring is removed from Nix, this also provides the advantage that now you don't have to pay attention to which LTS you use into your `stack.yaml`

Nix-shell no longer called with a GHC from an LTS mirror

---

ChangeLog.md
src/Options/Applicative/Builder/Extra.hs
src/Stack/Build/Haddock.hs
src/Stack/Config.hs
src/Stack/Config/Build.hs
src/Stack/Config/Docker.hs
src/Stack/Constants.hs-boot
src/Stack/Docker.hs
src/Stack/Image.hs
src/Stack/Nix.hs
src/Stack/Options.hs
src/Stack/Package.hs
src/Stack/Path.hs
src/Stack/Setup.hs
src/Stack/Setup/Installed.hs
src/Stack/Types/Build.hs
src/Stack/Types/Config.hs
src/Stack/Types/Config/Build.hs
src/Stack/Types/Docker.hs
src/Stack/Types/Image.hs
src/System/Process/Read.hs
stack-7.8.yaml
stack-8.0.yaml
stack.cabal
stack.yaml

For a review it's probably best to look at each commit in sequence.
See #2267 for the original issue.

Use less permissive types in the config monoids (#2267)

---

.travis.yml

…and finish more quickly
I deleted the jobs with ghc-7.10.1 and ghc-7.10.2 under the assumption that these are less important now that ghc-7.10.3 is out and that compatibility with them can be more or less concluded from the ghc-7.10.3 jobs.
Alternatively the cabal ghc-7.10.3 job could instead run with ghc-7.10.1.
The ghc-head/cabal-head jobs are IMO rather useless as they hardly ever succeed.

Run only 5 Travis jobs so they can all run in parallel

---

.travis-setup.sh
.travis.yml

Fix #2390:
- download stack before using it;
- error out if the uses of stack fails;
- pass enough options to stack to make it work without requiring `stack setup` (specifically, pick correct stack file and GHC version).
This still does not ensure a successful build from scratch on GHC-7.8.4, but it still fixes a clear bug.

Travis: download stack for cabal builds

---

doc/GUIDE.md
src/Stack/Options.hs

Related: #2285, #2074, #877.
Closes #1759, #2128.

Document --profile and --trace in the guide

---

src/Stack/Solver.hs
stack-7.8.yaml
stack-8.0.yaml
stack.cabal
stack.yaml
test/integration/lib/StackTest.hs
test/integration/tests/1336-1337-new-package-names/Main.hs

(Untested yet).
Potential quick fix to the most urgent part #1810, based on @harendra-kumar's pure Haskell normalization library. A more proper and systematic fix, replacing `text` with a normalizing version, remains for future work.
Includes one line from normalization-insensitive, pending https://github.com/ppelleti/normalization-insensitive#2—maybe I should add @ppelleti's copyright or is this line too trivial?

Fix #1810: Unicode-normalized pkg name comparison

---

src/Stack/Types/Config.hs

This patch fixes the inconsistency between the ToJSON and FromJSON instances of PackageLocation. The problem affects git and hg locations, that are parsed from an object but encoded as strings (in a very different way).

Inconsistency between ToJSON and FromJSON instances of PackageLocation

---

doc/GUIDE.md
src/Stack/SetupCmd.hs
src/Stack/Types/Config.hs

Fix #2314: Clarify output from stack setup, since it confused both a
user and stack developers for a while in that issue.
Also update references in other code and in the guide.

setup output: "locally installed" -> "sandboxed"

---

.travis.yml
src/Stack/Build/Cache.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Ghci.hs
src/Stack/New.hs
src/Stack/Types/StackT.hs
src/test/Network/HTTP/Download/VerifiedSpec.hs
src/test/Stack/StoreSpec.hs
stack-7.8.yaml
stack.cabal

Fix #2439. As mentioned there:
-  fix warnings from -Wredundant-constraints on GHC 8
-  fix the build script to propagate failures
-  add -Werror also to stack builds

Travis: Propagate failures in Cabal builds

---

src/Stack/Fetch.hs

As reported in #2418, spurious newlines are being emitted. Doing a `git bisect` reduced it to a commit which introduced a `$logWarn` message which seemed responsible. This patch simply wraps the debug statements so that no call is made it the error report is the empty list.
(I leave aside the matter of whether this was a good way to do error reporting; I'm just trying to fix the output bug)
AfC

Only call logWarn if there's anything to report

---

ChangeLog.md
src/Stack/Setup.hs
stack.cabal

This should make most commands slightly faster.
On my machine, `stack path` takes ~20% less time than before, a no-op
`stack build` in a single-package project ~15%.

setupEnv: Run some processes concurrently

---

src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Types/Build.hs
src/Stack/Types/Internal.hs
src/Stack/Types/StackT.hs
src/Text/PrettyPrint/Leijen/Extended.hs
stack-7.8.yaml
stack.cabal

Sometimes when you select the wrong version of a package that a lot of things depend on, you can get gobs and gobs of output.  For example, setting `containers-0.3.0.0` breaks pretty much every package in the build plan and you get hundreds of lines of output: https://gist.github.com/mgsloan/2a93bc5282f38d9b337e9571dbc8611a
I've omitted info about which specific inter-package dependencies have failed.  Instead, it tells you the root problem with color-coded info
The "needed due to" path gives the shortest path from a target to the package.  Hopefully it's clear that this is not necessarily the only path (in this case, just one of many)

Pretty printer + improved plan construction errors

---

CONTRIBUTING.md
ISSUE_TEMPLATE.md
doc/MAINTAINER_GUIDE.md

This template will be shown in the text field when opening a new issue. You can give it a try at https://github.com/sjakobi/stack/issues/new.
The main expected advantage is that we'd receive fewer bug reports for outdated stack versions and that fewer bug reports would require questions for clarification.
I'm slightly worried that the template might come off as unfriendly or might make bug reports overly onerous and thus discourage bug reports. If you have any ideas on how to reduce such an effect, please comment!

Add an issue template

---

src/Data/Store/VersionTagged.hs
src/Stack/Build/Cache.hs
src/Stack/Build/Installed.hs
src/Stack/BuildPlan.hs
src/Stack/PackageDump.hs
src/Stack/PackageIndex.hs
src/Stack/Types/Build.hs
src/Stack/Types/BuildPlan.hs
src/Stack/Types/Compiler.hs
src/Stack/Types/Package.hs
src/Stack/Types/PackageDump.hs
src/Stack/Types/PackageIndex.hs
src/test/Stack/StoreSpec.hs
stack-7.8.yaml
stack-8.0.yaml
stack.cabal
stack.yaml

Not quite ready yet, still pending review and release of the changes to store.
Also, the type hashes change when moving to 7.8 due to a type changing location:
```diff
--- /home/mgsloan/fpco/stack/.stack-work/store-versioned/aHzcZ6_w3rL6NtEJUqEfh6fcjAc=	2016-08-02 02:54:02.680394461 -0700
+++ /home/mgsloan/fpco/stack/.stack-work/store-versioned/QQs6brImltateKQyGnt1TgdkoVM=	2016-08-02 02:59:26.306286816 -0700
@@ -13,6 +13,13 @@
slot 0 :: [(Stack.Types.PackageIdentifier.PackageIdentifier,Stack.Types.PackageIndex.PackageCache)]
}
+data-type Data.Maybe.Maybe Stack.Types.PackageIndex.PackageDownload
+  = Nothing {
+  }
+  | Just {
+    slot 0 :: Stack.Types.PackageIndex.PackageDownload
+  }
+
data-type Data.Text.Internal.Text
= pack {
slot 0 :: [GHC.Types.Char]
@@ -20,13 +27,6 @@
data-type …
```

Use new Data.Store.Version to address #2296

---

ChangeLog.md
doc/yaml_configuration.md
src/Stack/Setup.hs
src/Stack/Types/Config.hs

Implements #2224.
Should I write tests?

Install GHC from file

---

Setup.hs
src/Options/Applicative/Complicated.hs
src/main/Main.hs
stack.cabal

Addresses: https://github.com/commercialhaskell/stack/issues/2222
I have no idea how to differentiate between whether package is build with `stack` or `cabal`, and AFAICS you can screw dependencies with custom `stack.yaml` as well (not so easily though).
The output of `--version` is now quite long, but OTOH, dunno if it used much for anything else then issue reporting?
```
% stack exec stack -- --version
Version 1.1.3, Git revision fb3f1d23d82e633cbc8d07dcbaf1f14c8c358751 (dirty) (3700 commits) x86_64 hpack-0.14.0
Compiled with:
- Cabal-1.22.8.0
- aeson-0.11.2.0
- ansi-terminal-0.6.2.3
- async-2.1.0
- attoparsec-0.13.0.2
- base-4.8.2.0
- base-compat-0.9.1
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- binary-0.7.5.0
- binary-tagged-0.1.4.0
- blaze-builder-0.4.0.2
- …
```

Print dependencies version in --version

---

doc/GUIDE.md

Hello,
I find that I'm often installing stuff and then later on I want to find out exactly which versions I installed (especially switching between projects created at different points in time). To do this, I rely on the command `stack list-dependencies`, but I always forget the command and have to look it up: is it `list-dependencies` or `show-dependencies`? Hyphen or no hyphen? Isn't it something simpler than `list-dependencies` (in the Python world, I'd use `pip freeze` or `conda env export`.)
To answer my question, there's the power-user section at the [bottom of the user guide](https://docs.haskellstack.org/en/stable/GUIDE/#power-user-commands) and it usually takes me a few minutes to find the command because it's buried there.
Anyway, it occurred to me that other people might also …

[DOCUMENTATION] Request to emphasize `stack list-dependencies` in user guide

---

src/Stack/Setup.hs

This PR improves the support for OpenBSD's tar as discussed in #2283. For `.tar.xz` archives that are unsupported there, it will error out and require installing `gtar`. For other archives it will specify `z` and `j` options (on all platforms), hence supporting OpenBSD tar directly (and I assume staying compatible with other ones).
The first commit is already tested by @bonds on OpenBSD, I tested both on OS X, and checked  manpages for GNU tar and FreeBSD tar, so this should work there too.
Relevant UNIX man pages:
[OpenBSD tar](http://man.openbsd.org/tar.1)
[FreeBSD tar](http://www.freebsd.org/cgi/man.cgi?query=tar&apropos=0&sektion=0&manpath=FreeBSD+10.3-RELEASE+and+Ports&arch=default&format=html).

Support OpenBSD's tar where possible, require GNU tar for xz support (#2283)

---

doc/faq.md

@mgsloan It seems `*` is rendered as expected after all, there just needs to be a blank line before the start of the list.

Fix bulleted list presentation in the FAQ.

---

src/main/Main.hs

Motivation: if you call `runghc`, that process continues to live on
separate from the actual `ghc` process that interprets the code. That's
inefficient. But more worryingly: the `runghc` process itself can cause
major problems in Docker images, since it ends up swallowing SIGINTs as
the PID-1 process. This was discussed quite a bit on Twitter:
https://twitter.com/argumatronic/status/763418990982991872

Replace runghc with ghc -e Main.main

---

ChangeLog.md
src/Stack/Config.hs
src/Stack/Options.hs
src/Stack/Types/Config.hs

Remove the `--os` flag.

---

src/Path/Extra.hs
src/test/Stack/Ghci/PortableFakePaths.hs
src/test/Stack/Ghci/ScriptSpec.hs
src/test/Stack/GhciSpec.hs
stack.cabal

Fix the regressions from #2457.

Fix Windows build

---

etc/scripts/get-stack.sh

`test` (or `[`) would return 0 upon success and non-zero upon failure.
As such, explicit return statements are not required.

simplify is_64_bit

---

src/main/Main.hs

Always pass all the explicitly specified packages in the script to ghc command
line. Also allow ghc options to be specified from the interpreter command. This
will give user the flixibility to, for example, use '-hide-all-packages' ghc
option. Like this:
{- stack runghc
--package base
--package exceptions
--package transformers
--package containers
--package getopt-generics
--package filepath
--package path
--package path-io
--package process
--package unix-compat
--
-hide-all-packages
-}
fixes #1208

Interpreter: Provide a way to hide implicit packages

---

src/Stack/PackageIndex.hs

Fixes #2175.
This fix is quite minimal, and it comes with a significant slowdown for the first `stack update`, which is why I used "type: discuss" for this PR.
```
$ ./.stack-work/install/x86_64-osx/lts-6.0/7.10.3/bin/stack update
remote: Counting objects: 797395, done.
remote: Compressing objects: 100% (449683/449683), done.
remote: Total 797395 (delta 337171), reused 797302 (delta 337078), pack-reused 0
Receiving objects: 100% (797395/797395), 193.46 MiB | 4.16 MiB/s, done.
Resolving deltas: 100% (337171/337171), completed with 1 local object.
```
However, local tests confirm that #2175 disappers. Note that to see the results, one needs to remove various caches and the repo:
```
rm -f ~/.stack/build-plan-cache/x86_64-linux/lts-6.0.cache
rm ~/.stack/indices/Hackage/00-index.cache
rm -rf …
```

Stop truncating all-cabal-hashes repo (#2175)

---

src/Stack/GhcPkg.hs
src/main/Main.hs

Current mechanism of using GHC_PACKAGE_PATH for runghc and ghc commands does
not seem to work well when we have multiple versions of the same package. GHC
does not always pick up the packages in the same order as GHC_PACKAGE_PATH.
This fix determines of the package-ids using ghc-pkg and then passes
package-ids on command line of ghc or runghc invocation. This works only when
the user explicitly passes --package to runghc or ghc commands. When --package
is not specified we have no easy way to determine what all packages will be
used by the file being compiled.
This will make sure that scripts which explicitly list all or multi-instance
packages will always run reliably.
fixes #1957 (Requires all packages to be listed explicitly)

Use package-id arg to stack ghc/runghc instead of package name

---

src/Stack/Solver.hs

As shown in #2502, `cabal init --solver` can fail with `Could not parse
cabal-install errors` on Windows.  The problem boils down to the fact that
we test `isSuffixOf "suffix" "stuff suffix\r"`, which is false, so we
should better strip `\r` before calling `isSuffixOf`.
I've verified that `\r` is actually there only indirectly; I inferred it
from the presence of `stripCR` and the parse failure, and I've recently
seen the behavior of lines on strings with Windows line ends.
Testing confirms this PR fixes the bug—the original procedure fails with
the parent commit and works with this one.
Fixes #2502.

solver: parse cabal errors also on Windows

---

src/System/Process/Read.hs
src/System/Process/Run.hs

Branch born in response to #2241 and #2489.
I added docs to chase down a swallowed exception that I thought caused #2241, while the bug was simply fixed in the sources I looked at. Yet, the extra docs are hopefully useful.
Some of the inconsistencies I found should maybe be fixed by changing behaviors rather than docs, but I'm not 100% sure how to proceed. I'd guess we could want a single exception everywhere for simplicity, in particular Stack's `ReadProcessException` (since it can express more failures than the alternative `ProcessExitedUnsuccessfully`). But overall I'm not 100% sure these files have a coherent design, nor is it easy to find one (see also: `Stack/Exec.hs`).

Cleanup Exception docs

---

ChangeLog.md
doc/nix_integration.md
src/Stack/Config/Nix.hs
src/Stack/Nix.hs
src/Stack/Options.hs
src/Stack/Types/Nix.hs

This PR makes it easier to use stack nix with small disk spaces or low bandwidth internet.
Nix provides a command that removes all the packages that aren't registered as nix GC roots: nix-collect-garbage.
This PR gives you an option to tell stack to call nix-shell with the option to register the packages as GC roots. This way, you can run nix-collect-garbage to remove old packages you don't need anymore and nix will preserve your current depedencies, so you don't have to re-download them again.

Added option to add nix dependencies as nix GC roots

---

doc/GUIDE.md

List doesn't render properly with Read the Docs without newline before start of list.

Missing newline

---

src/Stack/Fetch.hs
stack-7.8.yaml
stack-8.0.yaml
stack.cabal
stack.yaml

The `text-metrics` package is ×2.5 faster and it works on strict `Text` values rather than on `String`s, which eliminates the need in unpacking of all package names (which should also speed-up things).

Switch from ‘edit-distance’ to ‘text-metrics’

---

ChangeLog.md
src/Stack/Dot.hs
src/Stack/Options/DockerParser.hs
src/Stack/Options/DotParser.hs
src/Stack/Package.hs
src/Stack/Types/Package.hs
src/main/Main.hs
src/test/Stack/DotSpec.hs
src/test/Stack/GhciSpec.hs
stack.cabal

Stack makes it a breeze to build a project with lots of (transitive) dependencies without worrying too much about them, but when it comes to distributing the final binary, it is useful to know what your dependencies actually are. In particular, I want to know the licenses of my dependencies, to make sure that they are compatible, and to make sure that I am not accidentally violating one.
For Cabal there is the [`cabal-dependency-licenses`](https://github.com/jaspervdj/cabal-dependency-licenses) package, but I haven’t been able to make it work with Stack. However, because Stack can already list all dependencies, I figured it shouldn’t be too hard to make Stack list the licenses too. So that is what this PR does.
* Add a `--license` flag to `stack list-dependencies`. When specified, `stack …

Add --license option to list-dependencies

---

ChangeLog.md
src/Stack/Build/Source.hs

The immediate problem I noticed was that, when running `stack build`
with two local packages, one an extra-dep, the build output was not sent
to the console. This fixes the problem, but I believe there's still an
issue with the test suite being spuriously run. Still investigating
that.

Don't treat local extra-dep packages as targets

---

src/Stack/Runners.hs
src/Stack/Types/StackT.hs
src/Stack/Upload.hs
src/test/Network/HTTP/Download/VerifiedSpec.hs
src/test/Stack/BuildPlanSpec.hs
src/test/Stack/ConfigSpec.hs
src/test/Stack/NixSpec.hs
stack.cabal

Related to snoyberg/http-client#214. The fixes to improve latency in
creating a manager may give the biggest improvement to the global
manager, so switching over to using that makes sense. As it stands,
Stack is not modifying the manager configuration at all, so this
shouldn't be a problem, and if that changes in the future, we can always
modify the global manager directly with setGlobalManager.
A more invasive change is to remove the Manager from the configuration
environments entirely and either (1) use getGlobalManager throughout the
codebase or (2) switch over to the Network.HTTP.Simple module. I'm not
opposed to doing that necessarily, but wanted to kick off with the
simpler change.
EDIT by @Blaisorblade: fixes #2359.

Switch to getGlobalManager #2359

---

ChangeLog.md
src/Stack/Config.hs
src/Stack/Init.hs
src/Stack/Types/Config.hs

Motivation: the vast majority of the time, an external package should be
treated as an external dependency, in that we don't want to run test
suites. I regularly see user confusion on this topic. It was probably a
mistake on my part to make the default be extra-dep: false for external
packages.
Changing the default would be a breaking change, so instead, this change
will give the user a warning when they use an external package - such as
from a Git repo - without an explicit extra-dep setting. If the user
really wants the current default behavior, they can add `extra-dep:
false` to silence the warning. I expect in most cases users will end up
adding `extra-dep: true` and avoid a stumbling block.

Warn on missing extra-dep for external packages.

---

src/Stack/Exec.hs
stack-7.8.yaml
stack-8.0.yaml
stack.cabal
stack.yaml

This improves behavior of stack exec in the Docker use case, ensuring
signals are properly handled and orphan processes are reaped.

Add PID-1 support for stack exec

---

src/Network/HTTP/Download/Verified.hs

@snoyberg @borsboom Please review, I believe this has been a bad longstanding bug in the download code.  When retry occurs, it continues appending to the same file.  The fix is simple - have `withBinaryFile` be within the retry.  Since it uses `WriteMode`, writing will restart from the beginning.

Fix retry of file download to not append #2657

---

ChangeLog.md
src/Stack/Package.hs

This fixes a performance regression introduced in 5f3ffe5ea8b4d8d1f4d1e4d15bee8b481ec6a8d4.

Parse .dump-hi files of library components only once

---

src/Stack/Config/Urls.hs

S3 is more reliable than stackage.org. See discussion:
https://www.reddit.com/r/haskell/comments/556a43/stackageorg_down/d8818rh

Download snapshots.json from S3

---

.hindent.yaml
src/Stack/ConfigCmd.hs

Needed for https://github.com/commercialhaskell/stack/pull/2537.

Implement `--global` flag for suitable `stack config set` fields

---

ChangeLog.md
src/Stack/Build/Execute.hs

Cabal-install builds `Setup.hs` files with `-threaded`, this patch changes Stack so it does too. This makes it possible to have concurrent build systems inside `Setup.hs`. Found in the context of ndmitchell/shake#490.
This was real quick and I don't know Stack internals, so it might be wrong. Tests pass, and my test in the linked issue works passes now.

Pass -threaded when building Setup.hs

---

ChangeLog.md
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Ghci.hs
src/Stack/Options/BuildParser.hs
src/Stack/Options/GhciParser.hs
src/Stack/Types/Config/Build.hs
src/setup-shim/StackSetupShim.hs
stack-7.8.yaml
stack.cabal

Here's how this works:
* Outputs a `StackSetupShim.hs` file to the build's temporary directory.
* Builds both simple setup and custom setup files using this file as an input, along with `-main-is: StackSetupShim.mainOverride`.
* When we want to run the `initialBuildSteps` cabal function, we run the setup exe with the arguments `repl stack-initial-build-steps`.  This condition is special-cased by the shim, and causes the function we want to be run.  Any other invocations of the executable get passed through to the standard simple / default setup.
In summary, this is a bit of a hack, but I think it works perfectly in all cases we care about.

Use a shim to invoke initialBuildSteps for ghci #1364

---

ChangeLog.md
doc/GUIDE.md
doc/docker_integration.md
doc/faq.md
doc/travis_ci.md
doc/yaml_configuration.md
src/Stack/Config.hs
src/Stack/Options/ConfigParser.hs
src/Stack/Options/DockerParser.hs
src/Stack/Options/GhcVariantParser.hs
src/Stack/Options/NixParser.hs
src/Stack/Setup.hs
src/Stack/SetupCmd.hs
src/Stack/Types/Build.hs
src/Stack/Types/Config.hs
test/integration/IntegrationSpec.hs

Default to using a stack-installed, isolated GHC

---

src/Stack/New.hs

When a cabal file contains a `data-files` attribute, `cabal` generates a path module.  The module name includes the package name with hyphens replaced by underscores.  Currently `stack new` only adds the variables `name` and `year` in the hastache context available in stack templates.  That breaks templates that include a `data-files` attribute when a package name contains hyphens is passed to `stack new`.
Adding a variable (name-as-varid) in the hastache context to be able to reliably be able to support such cases.  Also add another variable (name-as-module) to use the package name as a module name.

Add extra variables in the hastache context

---

src/Stack/Types/Package.hs

See https://github.com/commercialhaskell/stack/issues/2721#issuecomment-254827203.

Improve error message for missing Cabal file.

---

stack-7.8.yaml
stack-8.0.yaml
stack.cabal
stack.yaml

Not sure if I'm doing this correctly, but http-client version needs to be bumped, else https proxy does not work. See https://github.com/snoyberg/http-client/pull/235.

Bump http-client version to fix broken https proxy functionality

---

ChangeLog.md
src/Stack/Config.hs

Global project config creation respects `--resolver X`

---

src/Stack/Build/Source.hs
src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/Config/Docker.hs
src/Stack/ConfigCmd.hs
src/Stack/Init.hs
src/Stack/Options/GhcBuildParser.hs
src/Stack/Options/ResolverParser.hs
src/Stack/Setup.hs
src/Stack/Solver.hs
src/Stack/Types/Build.hs
src/Stack/Types/CompilerBuild.hs
src/Stack/Types/Config.hs
src/Stack/Types/Config.hs-boot
src/Stack/Types/Resolver.hs
src/Stack/Types/Resolver.hs-boot
src/Stack/Upgrade.hs
stack.cabal

See https://github.com/commercialhaskell/stack/issues/2407.

A stab at slimming Stack.Types.Config down.

---

ChangeLog.md
src/Stack/Setup.hs

Stack setup is unable to download a working copy of GHC under Sabayon, as it does not detect the need for a PIE variant. Sabayon is a derivative of [Hardened Gentoo](https://wiki.gentoo.org/wiki/Hardened_Gentoo), which has a patched version of GCC that does not produce the same output as Ubuntu (see below).
This PR adds support for detecting it, and also improves the logging to match what we currently have for tinfo, gmp, etc.
~~Please note that this is an *incomplete* fix, as we'll also need upload a `linux64-tinfo6-nopie` build of GHC.~~
Related: #2542.
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.3/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/4.9.3/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: …
```

Detect PIE on Hardened Gentoo

---

doc/yaml_configuration.md

I was about to patch this `git init` feature in before noticing it was already in the source code.  I was unable to find documentation for it anywhere so I thought I would add some.  The documentation is based on my preliminary understanding of the code and my own experimentation.
This is also my first pull request, so I apologize if I neglected any protocol.

Update YAML configuration docs to include `scm-init` option

---

doc/README.md

Text inside `` is rendered into \<code> tags in HTML.  The CSS style
for \<code> tags in the resulting page appears to understand line
breaks in the inner HTML of the tag as being verbatim.  Hence it is
probably wise not to break literal expressions in the markdown source
over multiple lines.

Remove verbatim linebreak

---

ChangeLog.md
src/Network/HTTP/Download.hs
src/Stack/Build/Cache.hs
src/Stack/Build/Execute.hs
src/Stack/Coverage.hs
src/Stack/Fetch.hs
src/Stack/FileWatch.hs
src/Stack/Ghci.hs
src/Stack/Init.hs
src/Stack/PackageDump.hs
src/Stack/PackageIndex.hs
src/Stack/Setup.hs
src/Stack/Solver.hs
stack-7.8.yaml
stack.cabal

Ran unit test suites. The API provides the same guarantees between these two libraries for the subset of functions being used.
Fixes #2768

Replace enclosed-exceptions with safe-exceptions

---

ChangeLog.md
doc/faq.md
src/Stack/Config.hs
src/Stack/Types/Config.hs

This removes the hard-coded `$LOCALAPPDATA\Programs\stack` directory, and uses `$STACK_ROOT\programs` instead, unifying this path for all programs. This resolves #1644 and also [my comment](https://github.com/commercialhaskell/stack/issues/996#issuecomment-258642367) on #996.
@borsboom: You noted in #1644 that it would be good to make this configurable in `stack.yaml`. That would certainly be possible, but currently I do not see how that would be useful. I think it would introduce more knobs than necessary. Is there a compelling use case for downloading and extracting GHC to a different location than the snapshots?

Allow configuring programs directory

---

ChangeLog.md
doc/GUIDE.md
src/Stack/Build.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Haddock.hs
src/Stack/Build/Installed.hs
src/Stack/Build/Source.hs
src/Stack/Config/Build.hs
src/Stack/Dot.hs
src/Stack/Ghci.hs
src/Stack/Options/BuildMonoidParser.hs
src/Stack/PackageDump.hs
src/Stack/SDist.hs
src/Stack/Types/Build.hs
src/Stack/Types/Config/Build.hs
src/Stack/Types/PackageDump.hs
src/test/Stack/PackageDumpSpec.hs

It passes all tests that are in the repo, and in my own tests on OS X it does indeed produce output that contains debugging symbols. I don't have access to any other operating systems to test on at the moment, though.
This would close #877.

DWARF debugging support

---

.travis.yml

HLint was failing because it was using --cpp-simple, which just strips
every directive, which in turn created duplicate import statements. This
commit turns off --cpp-simple and lints with the WINDOWS macro on and off.
--cpp-simple is kept on for the tests, which don't have the duplicate import
problem and some of which use CPP in more complex ways than just turning a
single variable on and off.
Tested via Travis. No need to do anything else since `.travis.yml` is the only file changed.

Fix HLint/CPP failure in Travis

---

ChangeLog.md
src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/Fetch.hs
src/Stack/PackageIndex.hs
src/Stack/Solver.hs
src/Stack/Types/BuildPlan.hs
src/Stack/Types/Config.hs
src/Stack/Types/PackageIndex.hs
src/Stack/Upgrade.hs
src/test/Stack/StoreSpec.hs
stack.cabal

I tested in a clean project and confirmed that the cabal files were found by their Git SHA.
```
/Users/michael/Documents/stack/src/test/Stack/StoreSpec.hs:60:3:
Expecting two more arguments to ‘unordered-containers-0.2.7.1:Data.HashMap.Base.Leaf’
The second argument of ‘Serial’ should have kind ‘*’,
but ‘unordered-containers-0.2.7.1:Data.HashMap.Base.Leaf’ has kind ‘*
-> * -> *’
In the instance declaration for
‘Serial m_aATT unordered-containers-0.2.7.1:Data.HashMap.Base.Leaf’
/Users/michael/Documents/stack/src/test/Stack/StoreSpec.hs:60: …
```

Switch to tarball backend as default

---

ChangeLog.md
src/Stack/GhcPkg.hs

I manually deleted the `package.cache` file, confirmed that it previously broke Stack, and with this change Stack continues to work.

Fix createDatabase by checking for package.cache

---

ChangeLog.md
src/Stack/New.hs

Basic sanity checking of using `stack new`, which worked. I'd like to have the user who reported the original problem confirm that this fixes it.

stack new always uses UTF-8 encoding

---

doc/yaml_configuration.md

Document how the `entrypoints` work wrt which docker images are created.
Fixes #2832

Clarify documentation for `i.c.entrypoints`

---

stack.cabal

Due to a use of `sinkFileCautious` introduced in 1.1.14. See https://github.com/snoyberg/conduit/commit/73b5fc28f1bb3ae52095c404ff64f07ba0da92ac

Fix version bound for conduit-extra

---

ChangeLog.md
src/Stack/Build/Haddock.hs

Fix for #781
* [x ] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x ] The documentation has been updated, if necessary. (Not neccesary)
Change was tested by:
* Running stack haddock on a project with changed code:
Output as before
* Running stack haddock on a project twice
Outputs 
C:\shared\life>stack haddock
Haddock index for local packages already up to date at:
```
C:\shared\life\.stack-work\install\1bb99e24\doc\index.html
Haddock index for local packages and dependencies already up to date at:
C:\shared\life\.stack-work\install\1bb99e24\doc\all\index.html
Haddock index for snapshot packages already up to date at:
C:\stack\snapshots\e1c674d9\doc\index.html
```

Resolved #781: stack haddock displays index.html paths

---

src/Stack/Options/GhciParser.hs
src/Stack/Types/Build.hs

```
λ ~/hobby/stack/ master* stack test missingtarget
The following target packages were not found: missingtarget
See https://docs.haskellstack.org/en/v1.3.3/build_command/#target-syntax for details.
```
Closes #2519 (also some formatting dealt with).

Add target syntax docs link to error message.

---

ChangeLog.md
doc/yaml_configuration.md
src/Stack/Build/Execute.hs
src/Stack/Package.hs
src/Stack/Types/Package.hs
src/test/Stack/GhciSpec.hs
stack-7.8.yaml
stack.cabal
stack.yaml

I'm still testing this in a more complex use case. However, the simple test case I devised was:
* `stack new foo`
* Modify the `Setup.hs` file to add `import Acme.Missiles`
* Add `acme-missiles-0.3` as an extra-dep
*   Add the following `custom-setup` block to `foo.cabal`:
```
custom-setup
setup-depends: base >= 4.6,
Cabal >= 1.24 && < 1.25,
acme-missiles
```
* Set `build-type` to `Custom`
* Confirm that without the patch, the package refuses to compile. With the patch, it compiles just fine.
@borsboom Maybe we can sync up later on adding this as an integration test case?

Cabal custom setup

---

ChangeLog.md
src/Stack/Build/Target.hs

https://github.com/commercialhaskell/stack/issues/2384
Changes:
- Friendlier error message
Tested:
- We ran the example provided in the issue

friendlier error message (Improve error message for bad build targets #2384)

---

ChangeLog.md
etc/scripts/get-stack.sh

#2898 
If system package installation fails, stack should not be installed.
I've tried running a new Ubuntu 16.04 EC2 instance, it behaves as expected: fails at first, after `apt-get update` installs stack properly.

Mention apt-get update for Ubuntu

---

ChangeLog.md
stack-7.8.yaml
stack-8.0.yaml
stack-nightly.yaml
stack.cabal
stack.yaml

See:
https://github.com/sol/hpack/pull/142
https://github.com/sol/hpack/pull/143

Upgrade to hpack 0.16.0

---

ChangeLog.md
src/Stack/BuildPlan.hs
src/Stack/Fetch.hs
src/Stack/Hoogle.hs
src/Stack/PackageIndex.hs
src/Stack/Setup.hs
src/Stack/Types/Config.hs
src/Stack/Types/PackageIndex.hs
src/main/Main.hs

OK, this is a bit involved. Ignoring cabal file revisions for a moment, consider you run `stack build` in a project using lts-7.15, and the project uses `foldl-1.2.2`. Suppose you had last updated your package index when foldl-1.2.2 wasn't available. Stack will automatically update your index before trying to build so that it can get the .cabal file for foldl-1.2.2.
Now consider a similar situation: your project uses yesod-core, which for nightly-2017-01-10 is version 1.4.30, with cabal file revision #1. If your index is missing that revision, previously you would get an error message about a missing revision. With this …

Update on missing SHA

---

ChangeLog.md
src/Stack/PackageIndex.hs
src/Stack/Types/Config.hs

This is done for backwards compatibility with any external tools relying
on the presence of a 00-index.tar file.

Copy 01-index.tar to 00-index.tar

---

doc/yaml_configuration.md
src/Hackage/Security/Client/Repository/HttpLib/HttpClient.hs
src/Stack/Config.hs
src/Stack/Fetch.hs
src/Stack/PackageIndex.hs
src/Stack/Types/Config.hs
src/Stack/Types/PackageIndex.hs
stack.cabal
stack.yaml

Normal usage of Stack will test this out plenty. I made this change because, once we switched from the Git index to HTTPS, updates became very slow, which I'm not happy with. As long as we're doing partial updates, may as well use hackage-security I suppose.
Since the hackage-security-http-client package isn't yet on Hackage, I inlined that module. Also, manually specified indices will be able to opt in or out of Hackage Security for downloads, so compatibility with existing non-HS indices will be retained.
I know the initial build will fail due to missing extra-deps. After that, I'm planning on using this myself a bit …

Use hackage security

---

.travis.yml

It seemed surprising to me that some combinations of stack.yaml and OS weren't filled out in the matrix. I'm not sure if there was a reason for this decision, so not merging myself.

Fill out Travis matrix more completely

---

ChangeLog.md
src/Path/Extra.hs
src/Stack/Package.hs

* [NA] The documentation has been updated, if necessary.
Tested using [this test repo](https://github.com/tallen-imvu/stack-ghci-i)
With these code changes, all three examples can correctly load in `stack ghci`

for 'stack ghci', don't omit hsSourceDirs that have '..' in them. #2895

---

doc/install_and_upgrade.md

The maintainers of the Archlinux community repository have been doing a very good job of keeping a lot of haskell packages very up to date. So this is in my opinion the recommended way of installing stack on the platform and this should be mentioned in the documentation.

update archlinux installation docs

---

ChangeLog.md
src/Stack/Options/NixParser.hs
src/test/Stack/NixSpec.hs
stack.cabal

Only enabling `--nix-pure` explicitly on the command line implies `--nix`.
Users who prefer to use Nix (e.g. NixOS users) will have `--nix` enabled
globally in their `~/.stack/config.yaml`. On the other hand, users who
do not have nix installed will not have a `nix` section in their global
stack config.
When distributing scripts runnable by stack (`#!/usr/bin/env stack`),
they should be runnable independent from the user's Nix preference. In
order to run in a Nix environment, however, sometimes certain tweakings
have to be made to the Nix settings:
* Disabling a pure build because of missing locale (see also #2358)
* Adding packages like `ncurses` or `zlib` that are usually present
in the user environment, but not in a pure nix-shell.
This was not possible before, since any of the …

`--nix-*` should not imply `--nix` by default

---

.travis.yml
src/Stack/Config.hs
src/Stack/PackageIndex.hs
src/Stack/Types/Config.hs

Turns out @mgsloan was right, and #2964 was caused by Hackage Security,
just indirectly. We added a feature to copy the 01-index.tar file over
to 00-index.tar for compatibility. In general, no problem. However, on
Travis, what occured was:
* Download current Stack, which uses 00-index.tar and 00-index.cache
* Run test suites, which updates 01-index.tar and copies it over to
00-index.tar
* Since the files are different, the 00-index.cache is now invalid
* Next time around, Stack looks in the wrong place in the file
for cabal files
This should fix it.

Wipe out the 00-index.cache file when copying (fixes #2964)

---

src/Network/HTTP/Download/Verified.hs
src/Stack/Build/Cache.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Source.hs
src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/Docker.hs
src/Stack/Fetch.hs
src/Stack/PackageIndex.hs
src/Stack/Setup.hs
src/Stack/Types/Config.hs
stack.cabal

As a side effect:
* Add a direct dependency to memory instead of byteable
* No new dependencies cryptohash depends on cryptonite, and byteable on memory
* Remove 3 dependencies (byteable, bytestring-base16, cryptohash
ran `stack tests` succesfully, but not sure how much that cover the code that I changed.

Use cryptonite directly instead of cryptohash

---

ChangeLog.md
doc/GUIDE.md
src/Stack/Build.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Source.hs
src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/ConfigCmd.hs
src/Stack/Ghci.hs
src/Stack/Options/GlobalParser.hs
src/Stack/Options/ScriptParser.hs
src/Stack/Path.hs
src/Stack/Runners.hs
src/Stack/Script.hs
src/Stack/Setup.hs
src/Stack/Solver.hs
src/Stack/Types/Build.hs
src/Stack/Types/BuildPlan.hs
src/Stack/Types/Config.hs
src/Stack/Types/Config.hs-boot
src/Stack/Types/Internal.hs
src/Stack/Upgrade.hs
src/main/Main.hs
src/test/Stack/BuildPlanSpec.hs
src/test/Stack/ConfigSpec.hs
src/test/Stack/NixSpec.hs
stack.cabal

This adds a basic script command. Most of the work involved has to do
with preventing config files from being loaded. Originally we planned on
creating an alternative set of config types for with and without a local
config. That turned out to be prohibitively invasive. Instead, we now
just create a dummy config file instead ~/.stack/script/lts-x.y (or
/nightly-...).
While this addresses reproducibility, it doesn't help with the speed
concerns: script is now about 100ms faster than runghc on my system for
the case where --package is provided, but it's still over a second for
Hello World. The slowdown is inherent right now in checking if the
relevant packages are installed. It would be nice to figure out a way to
optimize the package check.
Also, this should include some integration tests. …

Script command #2805

---

src/Stack/Build.hs

I adapted the `fixCodePage` function for use in my standalone [`code-page`](http://hackage.haskell.org/package/code-page) library, and while doing so I noticed a small mix-up in its implementation. `fixCodePage` uses the internal functions `fixInput` and `fixOutput` to actually change the input and output codepages respectively, but while `fixInput` is guarded by the value `setInput`, `fixOutput` isn't guarded by `setOutput`—it's guarded by `setInput` too! This seems like a mistake, unless I'm mistaken.

Guard fixOutput with setOutput instead of setInput

---

doc/travis-complex.yml

Updated the complex travis.yml.
Please review that my changes are correct. I'm not sure if the happy and alex versions also have to be updated.
I did test the stack and ghc-8.0.2 configurations in a travis.yml of mine though.

Added lts-8 and ghc 8.0.2 to travis script

---

src/Stack/Build/Installed.hs

Following from https://github.com/commercialhaskell/stack/issues/2928. I didn't test it. @conklech, could you grab this change and give it a run? I'm not really sure how to mismatch my Cabal and I don't think I want to ;)

Add warning if Cabal mismatch detected.

---

src/Stack/Build/Execute.hs
src/Stack/Build/Installed.hs

As we started discussing on Slack, and related to #2795. The original issue is no longer present in Stack due to the usage of custom setup deps now being fully supported. If I manually remove the custom-setup stanza from the glib cabal file, the problem reappears. In theory, the right solution is to notice that there's a Cabal library present in the snapshot database and use that instead. I don't want to do that though, because:
1. It will add extra code (and possibly a performance hit) to do all of the checking for Cabal library versions. I _think_ this information is already loaded up by Stack, but if not, it's an extra `ghc-pkg` call, which isn't cheap.
2. It adds some level of non-reproducibility to build plans, as the results will depend on whether we first ran `stack build Cabal` or …

Remove --upgrade-cabal recommendation

---

ChangeLog.md
stack-8.0.yaml
stack-nightly.yaml
stack.cabal
stack.yaml

This may be worth merging into the 1.4 release branch as well.

http-client 0.3.4 for SOCKS proxy support

---

ChangeLog.md
doc/ghcjs.md
src/Stack/Setup.hs
src/Stack/SetupCmd.hs
src/Stack/Solver.hs

Manually tested.
Stab at https://github.com/commercialhaskell/stack/issues/2952
It was tested with
```
stack setup --ghcjs-boot-clean \
--ghcjs-boot-options --jobs --ghcjs-boot-options 4 \
--ghcjs-boot-options --no-prof \
--ghcjs-boot-options --no-haddock \
--ghcjs-boot-options -q
```
in a project having `ghcjs` as default.

Allow to pass additional options to ghcjs-boot

---

ChangeLog.md
src/Stack/Build/Execute.hs

Support warning detection for GHC 8

---

doc/yaml_configuration.md

Apparently the location of the global `stack.yaml` has changed.

Fix location of global config file

---

src/Stack/Types/Build.hs

This seems like the simplest way to fix https://github.com/commercialhaskell/stack/issues/2984 .
I suspect it may cause unnecessary rebuilds, as there's likely a reason for these to be present in the list.  Thoughts, @snoyberg ?  The alternative seems complicated / error prone - https://github.com/commercialhaskell/stack/issues/2984#issuecomment-284611410

Have switching on/off profiling cause package dirtiness #2984

---

ChangeLog.md
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Types/Build.hs

Tested by following the repro steps in #2904.
I've made this PR against the release candidate branch since #2904 is marked as P1. @borsboom I leave it to your judgement whether this should be instead merged to master, and can update the PR accordingly.
CC @mgsloan @spikefoo

Aggressive unregister for #2904

---

src/Stack/Package.hs
src/Stack/Types/BuildPlan.hs

See https://github.com/commercialhaskell/stack/issues/3035
I think it makes sense to include this in the release candidate, since it's the first version with custom-setup.

Fix a case of unnecessary dependency rebuilding #3035

---

ChangeLog.md
src/Stack/Options/BenchParser.hs
src/Stack/Options/TestParser.hs

I could just be lazy but it is handy when fooling around with tasty framework args.
Looks like:
```
--ta,--test-arguments TEST_ARGS
Arguments passed in to the test suite program
```

Add optional shorter form for `--test-arguments`.

---

ChangeLog.md
src/Stack/Setup.hs
src/Stack/SetupCmd.hs
src/Stack/Solver.hs
src/Stack/Types/Version.hs
src/main/Main.hs

Manually tested.
Based on https://github.com/commercialhaskell/stack/issues/2386#issuecomment-233304228. Thanks @sjakobi for the pointers!

Add `--cabal-install`

---

src/Stack/Exec.hs

This reverts commit 6c876293a4ca215c2645de162aa0314f415fb754.
Running `hSetBuffering` just before exec had no effect on any actual buffering, but it screwed up the persistent terminal state in such a way that the runtime fails to reset it.  The effect was that keys like Backspace, Ctrl-C, Ctrl-D, etc. were not working correctly in programs launched inside `stack exec` and after `stack exec`.
Closes: #2884.
Reopens: #2702 (actually, that was never fixed in the first place).
> Please include the following checklist in your PR:
Tested using the example in #2702, and by running `stty sane; stty; stack exec stty; stty` (which should show the same state three times).

Revert "Set NoBuffering mode io, before exec #2702"

---

ChangeLog.md
src/Stack/Build/Execute.hs
test/integration/tests/haddock-options/Main.hs
test/integration/tests/haddock-options/files/haddock-options.cabal
test/integration/tests/haddock-options/files/src/Lib.hs
test/integration/tests/haddock-options/files/stack.yaml

Until now, the only place I can tell that these arguments are being used
is when generating index.
* Any changes that could be relevant to users have been recorded in the ChangeLog.md
Done
* The documentation has been updated, if necessary.
Do we need it?
`stack --nix test --flag stack:integration-tests stack:stack-integration-test --test-arguments "-m haddock-options"`

Actually use haddock-arguments

---

src/Stack/Clean.hs

(I don't know if either items above apply.)
This resolves #3121 with the following choices made:
1. packages listed as extra-deps are not cleaned with `stack clean`
2. extra-dep packages can still be cleaned with `stack clean <extra-dep>`
3. `stack clean --full` still cleans all packages, extra-dep or otherwise.
The 3rd choice was made conservatively since I don't use --full.
I tested this change by running it on snowdrift, given the steps below. If someone wants to suggest how a test could be made for this, I can make one and add it to the PR. (I found the integration test directory, but I'm not sure the best way to programatically test that a package has *not* been cleaned.)
Steps I used to test:
```
git clone https://chreekat@git.snowdrift.coop/sd/snowdrift.git
cd snowdrift
./build.sh …
```

Don't clean packages listed as extra-deps

---

CONTRIBUTING.md

The sentence "Once your bug has been resolved, the responsible will tag the issue as _Needs confirmation_ and assign the issue back to you." seems to be missing a word after "responsible". I added "person".

Add missing word to CONTRIBUTING.md

---

src/main/Main.hs

It seems like --local-bin-path is deprecated in favour of --local-bin.
----
I've not compiled this change, but I did run the two commands and indeed there's no deprecation warning printed for the latter.
```
❯ stack path --local-bin-path
'--local-bin-path' will be removed in a future release.
Please use '--local-bin' instead.
/home/arash/.local/bin
```
```
❯ stack path --local-bin     
/home/arash/.local/bin
```

stack uninstall: Update the static help message

---

src/Stack/Upgrade.hs

This seems a bit more accurate: When the user is already running the most recent version, the message "your version is already *more* recent" is incorrect and ever so slightly confusing. The other case -- where the user is running a more recent version than is available as a binary, for which the old message is accurate -- likely occurs much less frequently.
---

Reword message shown when binary upgrade is skipped

---

ChangeLog.md
src/Stack/Upload.hs
stack-7.10.yaml
stack.cabal
stack.yaml

Fixes #3142. I tested this by, well, running `stack upload` in MSYS2 and confirming that my password wasn't echoed back to me. This adds a fairly light dependency, `echo`.

Suppress password echoing from stack upload on MinTTY consoles

---

src/Stack/Build/Execute.hs
src/Stack/SDist.hs

I added stripping of linker warnings on ghc 7.8 on windows (x64 IIRC). I'm not sure how useful it would be in general going forwards, but it's really annoying when it occurs.
I also took liberty to improve `Stack.Build.Execute` module a bit by adding type signatures no non-obvious parts and by introducing (hopefully) descriptive enums instead of booleans.

Improve filtering of ghc messages

---

ChangeLog.md
src/Stack/Setup/Installed.hs

This is related to issue #3126 which describe the problem and solution.
I have tested it on Windows 8 and it adds bin path correctly and built the problematic module.

#3126 Use MinGW bin folder for dynamic libraries searching

---

ChangeLog.md
src/Stack/Nix.hs

Partially addresses #2287, as git is used in stack internally
to fetch package index and LTS.

When using Nix, depend on git.

---

src/System/Process/Read.hs

Rename PathException to InvalidPathException to avoid conflict with path 0.6+

---

doc/docker_integration.md

This PR creates a missing link on the docker page to the page that explains how to build docker images with stack.

doc: Link docker integration to docker section in guide

---

ChangeLog.md
src/Stack/Fetch.hs

Unpack by hash

---

doc/yaml_configuration.md

This tries to cover my confusion leading to #3162 and
https://stackoverflow.com/questions/43752580/git-location-with-subdir-but-not-root-directory

Try and document how subdirs works with git repositories.

---

src/Stack/Docker.hs

Fix a typo: transfering -> transferring

---

ChangeLog.md
src/Stack/Build/Execute.hs
test/integration/tests/3229-exe-targets/Main.hs
test/integration/tests/3229-exe-targets/files/app/Alpha.hs
test/integration/tests/3229-exe-targets/files/app/Beta.hs
test/integration/tests/3229-exe-targets/files/foo.cabal
test/integration/tests/3229-exe-targets/files/src/Foo.hs

Works like this:
* We simply look at the expected executable binary files e.g. `.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/alpha/alpha` and collect a `Map Text ExecutableBuildStatus` to determine which executable targets have or have not been built. 
* Then in `exesToBuild` we can build the user-supplied targets if all executables have been built once, otherwise we build all executables in the cabal file.
This steps around the issue described [here](https://github.com/commercialhaskell/stack/issues/3229#issuecomment-311236016), while letting us avoid build more executables than necessary.
Example output: https://gist.github.com/chrisdone/98a8dfbc7a793f4c6307e5aecddeb3ea
I added an integration test.

Build all exes once; then only specified (#3229)

---

src/Network/HTTP/Download/Verified.hs
src/Stack/Fetch.hs

Fix build with path 0.6.1

---

stack-7.10.yaml
stack-nightly.yaml
stack.cabal
stack.yaml

No code change is necessary in this case, but I bumped upper/lower bounds for `text-metrics` because `damerauLevenshtein` returns `Int` now instead of `Natural` and it's kinda safer to bump (in case there will be new code that uses the library).
Testing: manual check, try:
```
$ stack install text-merics-0.3.0
Warning: Some extra-deps are neither installed nor in the index:
* text-merics-0.3.0
Didn't see text-merics-0.3.0 in your package indices.
Updating and trying again.
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
No updates to your package list were found
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpcomplete.com/) ...The following package identifiers were not found in your indices: text-merics-0.3.0
Perhaps …
```

Use ‘text-metrics-0.3.0’

---

ChangeLog.md
doc/yaml_configuration.md
src/Stack/Config.hs

This is in response to feedback from the Haskell website working group,
who requested this change to ease the new user onboarding process.
__NOTE__ Please feel free to click on the 👍 or 👎 buttons on this description to indicate your support or opposition to this change.

Turn on --install-ghc by default

---

ChangeLog.md
src/Stack/Docker.hs

At some unknown version, `docker inspect` stopped outputting "Error: No such
image" and started outputting "Error: No such object:" when the image is
question was missing. That change broke detecting that situation.
This commit checks for either version of the message.
Tested by running `stack build` in a project that needed a docker image that wasn't on this machine. Output before commit:
```
$ ../stack/.stack-work/install/x86_64-linux-nopie/lts-8.5/8.0.2/bin/stack build -v
Version 1.4.1, Git revision 0ddbaa7fd1cfe8ec4c8cb17364dc8f0aa6d4314d (4766 commits) x86_64 hpack-0.17.0
2017-05-11 16:44:39.636920: [debug] Checking for project config at: /home/enolan/mystuff/code/emp-pl-site/stack.yaml
@(Stack/Config.hs:949:9)
2017-05-11 …
```

Fix handling of missing image message with newer versions of Docker

---

ChangeLog.md
src/Stack/Build/Haddock.hs

It turned out that Haddock expects to see packages with those names
in the GHC package DB, and omits the names otherwise.  Pointing
Haddock to the local and snapshot DBs resolved the issue.
Tested by running "stack haddock" for a local package and verifying that all the generated `index.html` files (local packages, local packages and deps, snapshot packages) list the package name for each module.

Fix #2886: include package names in the haddock index.

---

ChangeLog.md
doc/yaml_configuration.md
src/Stack/PackageLocation.hs
src/Stack/Types/BuildPlan.hs
src/Stack/Types/PackageIdentifier.hs

Generalizes HTTP(S) into archives (allowing local paths), and adds in
support for cryptographic hashes on archives.

Support archives as a package location

---

doc/GUIDE.md

The actual arg should be `--local-bin`:
> '--local-bin-path' will be removed in a future release.
> Please use '--local-bin' instead.
I tested this change simply looking at the GitHub preview 👀

Small document typo fix

---

stack.cabal

They build fine and work here.

Allow cryptonite 0.24 and path 0.6

---

.travis.yml
ChangeLog.md
src/Stack/Build.hs
src/Stack/BuildPlan.hs
src/Stack/Package.hs
src/Stack/SDist.hs
src/Stack/Types/Package.hs

Support for Stackage Nightly based on GHC 8.2.1

---

doc/GUIDE.md

* [x ] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [x ] The documentation has been updated, if necessary.
This bypasses a link to [a pass through page in the stack wiki](https://github.com/commercialhaskell/stack/wiki/Shell-autocompletion) in the Guide's section on autocompletion in favor of the page in the [haskellstack.org](https://docs.haskellstack.org/en/stable/shell_autocompletion/) to which the pass through directs readers.

Link directly to shell autocompletion on doc site

---

doc/faq.md
doc/yaml_configuration.md

This addresses #2750 - When I first started using Stack I was puzzled by projects that had `package.yaml` files, because I'd never heard of Hpack and the Stack documentation barely mentions it. The aim of this PR is to work the word "package.yaml" into the docs in a few places, so that someone wondering what a `package.yaml` file does can have a better chance of figuring it out.

Mention hpack a bit more in the docs

---

ChangeLog.md
src/Options/Applicative/Args.hs
src/Stack/Options/BuildParser.hs
src/Stack/Options/GhciParser.hs
src/Stack/Options/NixParser.hs
src/Stack/SetupCmd.hs
src/main/Main.hs
test/integration/tests/3315-multi-ghc-options/Main.hs
test/integration/tests/3315-multi-ghc-options/files/multi-ghc-options.cabal
test/integration/tests/3315-multi-ghc-options/files/src/Lib.hs
test/integration/tests/3315-multi-ghc-options/files/stack.yaml

Make --ghc-options and --ghcjs-boot-options take multiple args #3315

---

ChangeLog.md
doc/yaml_configuration.md
src/Stack/Build/Source.hs
src/Stack/Build/Target.hs
src/Stack/Config.hs
src/Stack/Ghci.hs
src/Stack/Types/Config.hs

Promote packages to local database by ghc-options #849

---

ChangeLog.md
doc/yaml_configuration.md
src/Data/Aeson/Extended.hs
src/Stack/Build/Source.hs
src/Stack/Config.hs
src/Stack/Ghci.hs
src/Stack/Types/Config.hs

Closes #3329. This also fixes a regression I introduced in the previous
commit on ghc-options, which mistakenly assumed ghc-options were
supposed to be given as a list instead of a single Text value.

Introduces $locals et al ghc-options keys

---

ChangeLog.md
src/Stack/Build/Execute.hs
src/Stack/Constants.hs
src/Stack/Script.hs
src/Stack/Types/Config.hs

Just adds in one extra commit to the original PR, which strips ANSI codes from the log files.

Kadoban ghc color output

---

ChangeLog.md
src/Stack/Build/Execute.hs
src/Stack/Constants.hs
src/Stack/Script.hs
src/Stack/Types/Config.hs

Tested `stack build` with `ghc-8.2.1` resolver and got colored error output and tested in older GHC that `stack build` does not error out (would if the new flag were being passed to old GHC).

GHC color output

---

src/Stack/Build/Execute.hs
src/Stack/Script.hs
src/Stack/Types/Config.hs
src/System/Process/Log.hs

Fixes regression introduced in the color output patch when using GHC < 8.2

Fix script base

---

ChangeLog.md
src/Stack/Types/FlagName.hs

Modify flag parser to allow sequential dashes #3345

---

src/Stack/Build/Cache.hs
src/Stack/Build/Execute.hs
src/Stack/Types/Build.hs
src/Stack/Types/GhcPkgId.hs
stack.cabal

Also ensures that only packages from an index are cached.

Include revision in precompiled cache key #3346

---

src/Stack/Build.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Source.hs
src/Stack/Config.hs
src/Stack/Dot.hs
src/Stack/Ghci.hs
src/Stack/SDist.hs
src/Stack/Snapshot.hs
src/Stack/Types/Build.hs
src/Stack/Types/BuildPlan.hs
src/Stack/Types/Package.hs
src/Stack/Types/PackageIdentifier.hs
src/Stack/Types/Resolver.hs

The concept of PSUpstream no longer makes sense: it's possible to have snapshot packages which don't come from the package index now that extensible snapshots exist. This is a tactical change to fix some broken assumptions.
Overall, the code and types could use a more significant cleanup to make things easier to follow and less error prone. I want to get this change in without getting held up further by a grander vision. I'll add comments on a separate issue explaining what I think can be improved in the future.

Remove psupstream

---

ChangeLog.md
Setup.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Source.hs
src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/Init.hs
src/Stack/Options/Completion.hs
src/Stack/Package.hs
src/Stack/SDist.hs
src/Stack/Setup.hs
src/Stack/Snapshot.hs
src/Stack/Types/Config.hs
src/Stack/Types/FlagName.hs
src/Stack/Types/Package.hs
src/Stack/Types/PackageName.hs
src/Stack/Types/Version.hs
src/Stack/Upgrade.hs
src/main/Main.hs
stack-7.10.yaml
stack-nightly.yaml
stack.cabal
stack.yaml

Upgrade to Cabal 2.0

---

ChangeLog.md
src/Path/Extra.hs
src/Stack/Build/Haddock.hs
src/Stack/PackageIndex.hs

Not sure if this fixes the problem described in #3033, but I believe this will help in cases where stack is terminated after downloading the index but before clearing the cache.

Clear index cache if it is old #3033

---

ChangeLog.md
src/Stack/Setup.hs

When both libtinfo 5 and 6 are installed on the same system, Stack currently defaults to 5. This breaks if nopie is also required, because the `no-pie` flags in [stack-setup-2.yaml](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml) differ in case between `linux64-nopie` and `linux64-tinfo6-nopie`. In the long run it would probably make sense to simply infer the correct flags within Stack instead of hardcoding them in YAML, but that's a much more complex change.
Instead, this patch changes the order these flags are tested in, so that we default to the newer version if both are present.
I've tested it by running `stack setup` on the following distros (via Docker images):
* Sabayon / Hardened Gentoo - correctly uses tinfo6-nopie now
* Ubuntu Zesty - still uses …

Prefer more recent version of libtinfo when selecting GHC build

---

.travis.yml

Attempt to solve build failure (seen [on master](https://travis-ci.org/commercialhaskell/stack/jobs/266365181#L670) and also reported [over here](https://github.com/commercialhaskell/stack/pull/2812#issuecomment-323574408)).
This failure is a result of #3314 and was seen also in build failures in #2812.

Explicitly install happy for style builds

---

ChangeLog.md
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Config/Build.hs
src/Stack/Options/BuildMonoidParser.hs
src/Stack/Path.hs
src/Stack/Types/Config.hs
src/Stack/Types/Config/Build.hs
test/integration/tests/2643-copy-compiler-tool/Main.hs
test/integration/tests/2643-copy-compiler-tool/files/Bar.hs
test/integration/tests/2643-copy-compiler-tool/files/Baz.hs
test/integration/tests/2643-copy-compiler-tool/files/Foo.hs
test/integration/tests/2643-copy-compiler-tool/files/LICENSE
test/integration/tests/2643-copy-compiler-tool/files/Setup.hs
test/integration/tests/2643-copy-compiler-tool/files/copy-compiler-tool-test.cabal

As described in #2643, this implements a mechanism for having a bin directory for tools that match a particular ghc version.  This compiler specific dir looks like is `/home/mgsloan/.stack/compiler-tools/x86_64-linux/ghc-8.0.1/bin`.  It is included on the PATH when stack is building projects and when running exec. It adds:
1) `stack path --compiler-tool-bin`, yielding a path to the dir compiler-specific tools are installed to
2) `stack build --copy-compiler-tool`, which causes executables for target packages to get copied to the compiler-specific dir.
Tested this change by using it to install a local intero.  Querying `stack exec -- which intero` yielded the correct path.  `stack path --local

Implementation of "--copy-compiler-tool" #2643

---

ChangeLog.md
etc/scripts/get-stack.sh

---
This change now makes the install script use the `-d {path}` value when checking for existing stack executables. Should close off https://github.com/commercialhaskell/stack/issues/3350. Arguably, we should also use `realpath` for the 'Installing Stack to: ...' message, no?
Here's my test logs (click dropdown):
<details>
<summary>Before</summary>
``` bash
λ ~/hobby/stack/ master mkdir foobar
λ ~/hobby/stack/ master cd foobar     
λ ~/hobby/stack/foobar/ master less ../etc/scripts/get-stack.sh | sh -s - -d .    
Stack Version 1.5.1 already appears to be installed at:
/home/lwm/.local/bin/stack
Use 'stack upgrade' or your OS's package manager to upgrade,
or pass '-f' to this script to over-write the existing binary, e.g.:
curl -sSL https://get.haskellstack.org/ | sh -s - -f
``` …

Make etc/scripts/get-stack.sh respect the -d argument

---

src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/PrettyPrint.hs
src/Stack/Setup.hs
src/main/Main.hs

Trying to find ways to improve output of stack in various ways/places, especially using `$prettyWarn` and `$prettyError` and etc.
Very open to any comments and suggestions, even if it's just that certain things are a bad idea. Never used any of the Wadler/whatever prettyprinters before at all, so I'm pretty much just making it up as I go along.
related to issue #2650
p.s. Let me know if this shouldn't be a PR until it's further along, I'm fine with deleting it and just having a branch.

explore improvements to output (especially colors)

---

.hlint.yaml
src/Stack/Package.hs
src/Stack/PrettyPrint.hs
src/Stack/Solver.hs

Use `$pretty*` functions where appropriate in `src/Stack/Package.hs`.
Related to #2650
b85364d is probably the commit most in need of review, had to do some things I barely understood to get that working.

pretty up `src/Stack/Package.hs`

---

ChangeLog.md
src/Stack/Options/DockerParser.hs

So, previously, if you ran
```shell
stack --docker-help
```
you'd see this:
```
--[no-]docker            Enable/disable using a Docker container. Implies
'system-ghc: true'
```
Well, that's not strictly true! --no-docker does not imply system-ghc: true. Only --docker does. 
Looking at the code, it's super-easy to see how this happened, but I'm inclined towards pedantry and I want my documentation to be super-clear. So, PR!
* [*] Any changes that could be relevant to users have been recorded in the ChangeLog.md
Done, in this PR
* [*] The documentation has been updated, if necessary.
This is a documentation update, of a …

Fix docker comment

---

ChangeLog.md
src/Stack/Docker/GlobalDB.hs

See issue #3400 for background.
Thanks to @mgsloan for your help on how to go about this! Turned out the fix was actually quite trivial.
A patched `stack` is already live in our CI. I will report findings here later.

Fix parallel invocation of `stack --docker` (#3400)

---

doc/travis_ci.md

Because:
> borsboom commented on Apr 17, 2017
> Since the Stack release team (er, that's me) is deprecating the Apt repositories, this should probably be closed.

Remove the hope of getting stack into travis build via apt

---

ChangeLog.md
doc/js/searchhack.js
etc/mkdocsjs/searchhack.js
mkdocs.yml

Tested here, searching for 'yaml' returns appropriate results: https://docs.haskellstack.org/en/3376-fix-search/README/

Fix readthedocs search (fixes #3376)

---

doc/faq.md

`hardening-wrapper` has been removed from Arch Linux for a while. Here is the current solution.

fix: updated solution to `-fPIC` problem

---

ChangeLog.md
appveyor.yml
src/Stack/Constants.hs
src/Stack/Options/GlobalParser.hs
src/Stack/PrettyPrint.hs
src/Stack/Runners.hs
src/Stack/Types/Config.hs
src/Stack/Types/Runner.hs
src/System/Terminal.hsc
src/Text/PrettyPrint/Leijen/Extended.hs
src/test/Stack/ConfigSpec.hs
src/test/Stack/NixSpec.hs
stack.cabal
stack.yaml

Related to #2650, detect the width of the terminal and use it for proper output.
Note: this current implementation is only ever going to work on POSIX. I don't currently have ability to dev/test on windows, though it appears that there *are* APIs that could give this info if anyone else wants to sub that in.
**Testing:** It seems to work fine on all of the OSes I have. Unfortunately, that's a pretty unrepresentative set of OSes. I mostly have linux variants and one BSD I tried on and it worked fine. I don't have access to OSX or Windows really.
If anyone can, testing on other OSes would really be good. Windows won't do any terminal detection, but the command-line option should work.
Log output doesn't seem to be messed up by this. If anyone can verify that'd be nice though. I don't use …

detect terminal width and use it for pretty-printed output

---

src/Stack/Build/Execute.hs
src/Stack/Build/Source.hs
src/Stack/Coverage.hs
src/Stack/Ghci.hs
src/Stack/Package.hs
src/Stack/Types/Package.hs
test/integration/tests/internal-libraries/Main.hs
test/integration/tests/internal-libraries/files/Setup.hs
test/integration/tests/internal-libraries/files/files.cabal
test/integration/tests/internal-libraries/files/src-bar/Main.hs
test/integration/tests/internal-libraries/files/src-baz/Baz.hs
test/integration/tests/internal-libraries/files/src-foo/Foo.hs
test/integration/tests/internal-libraries/files/src/Files.hs
test/integration/tests/internal-libraries/files/stack.yaml

This should resolve both #3364 and #3361. There is a test case included
that should address both of them as well.
This is still relatively hacky. We will eventually be overhauling the
component system more dramatically to support Backpack with #2540 (CC
@ezyang).
This may still have some problems due to the upstream issue
haskell/cabal#4763, but at least in theory we're matching the behavior
of upstream. We can consider workarounds after that issue comes to a
conclusion.
There's a new integration test that adds a sub library and foreign …

Support for Cabal 2.0 sub and foreign libraries

---

etc/scripts/get-stack.sh

The current install script at `https://get.haskellstack.org/` is attempting to detect for `rhel` when the latest RedHate Enterprise is detected as `redhatenterpriseserver`, thus the script is falling back to the `sloppy` install.
Adding `|redhatenterpriseserver` as an option after `rhel` fixes the issue and install fully completes properly and successfully with all dependent packages properly installed.

Stack installer script is not detected latest `redhatenterpriseserver` linux version

---

ChangeLog.md
src/Stack/Nix.hs

Fixes builds using the FFI, with no additional dependency footprint.

When using Nix, depend on gcc.

---

ChangeLog.md
src/Options/Applicative/Builder/Extra.hs
src/Stack/Types/GhcPkgId.hs
src/Stack/Upload.hs

Something for https://github.com/commercialhaskell/stack/issues/2159.
Here's my manual test logs:
```bash
>> :main ["upload", "."]
Getting file list for /home/lwm/hacking/hobby/stack/
Warning: In getPackageArgs: custom-setup in use, but no dependency map present
Could not find custom-setup dep: Cabal
Could not find custom-setup dep: base
Could not find custom-setup dep: filepath
Building sdist tarball for /home/lwm/hacking/hobby/stack/
Checking package 'stack' for common mistakes
Hackage username: foobar
Hackage password: 
Save hackage credentials to file at /home/lwm/.stack/upload/credentials.json [y/n]? bad input
Save hackage credentials to file at /home/lwm/.stack/upload/credentials.json [y/n]? n
NOTE: Avoid this prompt in the future by using: save-hackage-creds: false
Uploading …
```

Don't save Hackage credentials without asking first

---

src/Stack/Coverage.hs
src/Stack/PrettyPrint.hs
src/Stack/Upgrade.hs

#2650
Use pretty printing in `s/S/Upgrade`
May end up including more modules in this one since it's fairly small.

[WIP] pretty up `s/S/Upgrade`

---

CONTRIBUTING.md
doc/README.md

I was looking for things I could help with and was a bit surprised there were no `newcomer` and `awaiting pr` issues. Turns out, they are actually called `newcomer friendly` and `awaiting pull request`.
I'm not sure whether to target `stable` or `master`, since it affects both documentation for https://docs.haskellstack.org/en/stable/ and `CONTRIBUTING.md`.

Fix references to non-existing GitHub issue labels

---

ChangeLog.md
doc/faq.md
doc/yaml_configuration.md
src/Stack/Config.hs
src/Stack/Options/ConfigParser.hs
src/Stack/Package.hs
src/Stack/Solver.hs
src/Stack/Types/Build.hs
src/Stack/Types/Config.hs
src/test/Stack/ConfigSpec.hs

Resolves #3179.
I tested it with the `--with-hpack` option and without, and it works as I intended. I couldn't think of a good way to test this in code, so I did not add any tests to the test suite.
The core change is pretty basic.
* I added an `HpackExecutable` type with two cases--one for the bundled hpack, and one with the hpack command.
* I added `HpackExecutable` as a field to the `GlobalOpts` and `BuildConfig` types.
* I used `runCmd` to execute the command, which requires an `EnvOverride` to create a `Cmd` value.
* Then the remaining effort was in propagating the necessary information to the `hpack` function. 
* When `HasEnvConfig` was available, I used the `hpackExecutableL` lens to retrieve the `HpackExecutable`
* Else I passed `HpackExecutable` and `EnvOverride` as needed as …

Add hpack command line option

---

ChangeLog.md
src/Stack/Setup.hs

This change hasn't yet been tested.  Intended to fix #3188

When extracting local GHC from tarball on windows, use temp dir #3188

---

src/Stack/Build/Execute.hs
src/Stack/Build/Source.hs

Pinging @snoyberg I think the behavior here changed during the extensible snapshots stuff.  Curious if you have any idea why this bug only cropped up now, even though the involved code hasn't been changed in quite a long time.

Fix computation of new build-cache #3424

---

src/Stack/Dot.hs

Cabal has a method to render this, so we'll just call it directly.
This was just tested manually by adding the package `machines-directory` and checking the output of `stack list-dependencies --license | grep machines`. This renders properly now.
I can some tests if people think it's a good idea, I haven't because it's really just a call to an upstream library, and the code itself lives in `IO` land (which means a refactor).

Fixes automatically shown versions for licenses #3432

---

src/Stack/Constants.hs

The correct name has one more '_':
https://github.com/NixOS/nixpkgs/blob/72f530ba3310b8304b148b74ece9e6e75309666b/pkgs/development/haskell-modules/generic-stack-builder.nix#L20

Fix STACK_IN_NIX_SHELL environment variable name

---

src/Stack/BuildPlan.hs
src/Stack/Init.hs

This fixes a regression from 6047a31594367ed222c6f5cc9dc3ccfe9ea77efc that
caused _all_ the recommended snapshots to be loaded upfront.
Tested manually:
master:
```
➤ stack new bla -v
...
2017-10-06 23:07:29.736790: [debug] Decoding build plan from: /home/simon/.stack/build-plan/lts-9.6.yaml
@(Stack/Snapshot.hs:151:5)
2017-10-06 23:07:31.580566: [debug] Decoding build plan from: /home/simon/.stack/build-plan/nightly-2017-10-06.yaml
@(Stack/Snapshot.hs:151:5)
2017-10-06 23:07:33.238201: [debug] Decoding build plan from: /home/simon/.stack/build-plan/lts-8.24.yaml
@(Stack/Snapshot.hs:151:5)
2017-10-06 23:07:34.852551: [debug] Decoding build plan from: /home/simon/.stack/build-plan/lts-7.24.yaml
@(Stack/Snapshot.hs:151:5)
2017-10-06 23:07:36.510772: [debug] Decoding build plan from: …
```

init: Load snapshots on demand during resolver selection

---

ChangeLog.md
src/Stack/Build/ConstructPlan.hs

This reverts commit d1e6c480cd46def34bfacd3aeaee953ba32c7758 and resolves #3476 
The problem is caused specifically in the `PSFiles -> Nothing` branch of `installPackages`.
As the flag was no longer being passed through, packages were not being checked for being in the wanted map. This led to the local packages being built as dependencies
I tested this by running `stack --only-dependencies --dry-run` on our stack project with multiple packages. Setting the call to `resolveDepsAndInstall`'s `treatAsDep` value to `True` causes the problem and removing it removes the problem

Revert "Clean up --only-dependencies logic in ConstructPlan"

---

src/Stack/Options/ExecParser.hs
src/Stack/Types/Config.hs
src/main/Main.hs

Implements feature requested by #3264 - tested it locally with stack exec.
Welcome for any suggestions as to better methods to use/docs to update.

Implement #3264 adding --cwd to exec

---

ChangeLog.md
src/Stack/Build/Cache.hs
test/integration/tests/3431-precompiled-works/Main.hs
test/integration/tests/3431-precompiled-works/files/custom1/custom1.yaml
test/integration/tests/3431-precompiled-works/files/custom1/stack.yaml
test/integration/tests/3431-precompiled-works/files/custom2/custom2.yaml
test/integration/tests/3431-precompiled-works/files/custom2/stack.yaml

The commit ed9ccc08f327bad68dd2d09a1851ce0d055c0422 changed the behavior
of the precompiled cache to store relative instead of absolute paths.
That seems to have broken the ability to properly check if a library
exists, thereby defeating precompiled caching.
The issue that discovered this is #3431, and ascribed this to extensible
snapshots. I _think_, though I'm not 100% certain, that this bug reaches
much farther than extensible snapshots, and in fact breaks all
precompiled caches.

Do correct path checking in precompiled cache.

---

ChangeLog.md
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/SDist.hs
src/Stack/Types/Build.hs
test/integration/tests/2781-shadow-bug/Main.hs
test/integration/tests/2781-shadow-bug/files/bar/bar.cabal
test/integration/tests/2781-shadow-bug/files/bar/bench/bench.hs
test/integration/tests/2781-shadow-bug/files/bar/src/Bar.hs
test/integration/tests/2781-shadow-bug/files/foo/foo.cabal
test/integration/tests/2781-shadow-bug/files/foo/v1/Foo.hs
test/integration/tests/2781-shadow-bug/files/foo/v2/Foo.hs
test/integration/tests/2781-shadow-bug/files/stack.yaml

Added the test case I already wrote for #2781.

Force reconfigure when deps are rebuilt #2781

---

ChangeLog.md
doc/yaml_configuration.md

As per #3527 and #3514, if you custom point at a 00 index file, you get errors. Important instead to point at the 01 version. Update the example in the user manual and put it in the changelog.

Note that the 00-index.tar.gz file no longer works

---

src/Network/HTTP/Download.hs
src/Network/HTTP/Download/Verified.hs
src/Stack/Fetch.hs
src/test/Network/HTTP/Download/VerifiedSpec.hs

Tested this by adding `127.0.0.1       s3.amazonaws.com localhost` to my `/etc/hosts`, to make connections fail reliably (oh, the irony).
The output looks like this:
```
Retry number 0 after a total delay of 0 us
If you see this warning and stack fails, but running the command again solves the problem, please report here: https://github.com/commercialhaskell/stack/issues/3510
Progress: 4/6HttpExceptionRequest Request {
host                 = "s3.amazonaws.com"
port                 = 443
secure               = True
requestHeaders       = []
path                 = "/hackage.fpcomplete.com/package/text-zipper-0.10.1.tar.gz"
queryString          = ""
method               = "GET"
proxy                = Nothing
rawBody              = False
redirectCount        = 10
responseTimeout      = …
```

Print retry information if stack needs to retry network requests

---

src/Stack/Constants.hs
src/Stack/Snapshot.hs
src/Stack/Types/BuildPlan.hs

I believe this was a performance regression in the new extensible
snapshots code. In any event, this is a pretty straightforward
optimization: store a binary cache of the SnapshotDef to avoid reparsing
the large YAML files each time. In my testing, this sped up a previously
3 second `stack exec true` to about .2 seconds.

Cache snapshot def parsing

---

src/Stack/Ghci.hs
src/main/Main.hs

closes #3584
Added a note to 'templates' mentioning where the templates list comes from. Also mentioned in both 'new' and 'templates' that you can specify a file or URL for a template. It was already mentioned in 'new', but only in the description of TEMPLATE_NAME, which was easy to miss.

Expand --help output of 'new' and 'templates' commands

---

doc/GUIDE.md
doc/yaml_configuration.md

Inspired by the question [here](https://github.com/commercialhaskell/stack/issues/1910#issuecomment-344555418), I realized that yaml_configuration.md does not have full coverage of the available options.  This adds some docs for the missing options.
Also improves GUIDE.md a bit
* Removes stack-ide mention, replaces with intero
* Rearranges more resources section / moves profiling "further reading" section to the right spot
* Clarifies that `stack exec` sets PATH

yaml_configuration.md coverage for all options

---

ChangeLog.md
package.yaml
src/Stack/Package.hs
stack-nightly.yaml
stack.yaml

Upgrade to hpack 0.20.0 (fixes #3383)

---

src/Stack/SDist.hs

I think this was a mistaken change in
9f06ccfdb8fe6cc1156ce04c815731e63d3717d1. Perhaps ironically, without
this commit, we end up regularly triggering #3549 instead of only doing
so when using pvp-bounds.

Only tweak cabal file as necessary

---

ChangeLog.md
doc/yaml_configuration.md

@mgsloan @borsboom does this text reflect things appropriately?

Add warnings to docs/release notes about pvp-bounds #3550

---

src/Stack/SDist.hs

Not listing in the ChangeLog, since this is a regression with the Cabal
2 upgrade.

Strip trailing CR for file list

---

ChangeLog.md
src/Stack/Build/Source.hs
test/integration/tests/3574-extra-dep-local/Main.hs
test/integration/tests/3574-extra-dep-local/files/foo/Foo.hs
test/integration/tests/3574-extra-dep-local/files/foo/foo.cabal
test/integration/tests/3574-extra-dep-local/files/stack.yaml

Don't apply $locals to extra-deps #3574

---

doc/travis-complex.yml

* Comment out older GHC 7.6.3 and 7.8.4 (3 version policy)
* Add in cabal 8.2.2
* Switch from lts-8 to lts-9
* Add support for running stack solver as needed
* Add a comment about hpack support

Update the travis-complex example

---

src/Stack/Build.hs
src/Stack/Build/Source.hs
src/Stack/Build/Target.hs
src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/Init.hs
src/Stack/PackageLocation.hs
src/Stack/SDist.hs
src/Stack/Setup.hs
src/Stack/Snapshot.hs
src/Stack/Solver.hs
test/integration/tests/3607-stack-init-solver/Main.hs
test/integration/tests/3607-stack-init-solver/files/.gitignore
test/integration/tests/3607-stack-init-solver/files/package.yaml

No ChangeLog updates, as this is a regression added since 1.5.1. New integration test case added as well.
Fixes #3607

Ensure updated EnvOverride when using stack init --solver

---

src/Stack/Build.hs
src/Stack/Build/Source.hs
src/Stack/Build/Target.hs
src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/Ghci.hs
src/Stack/IDE.hs
src/Stack/Init.hs
src/Stack/Package.hs
src/Stack/PackageLocation.hs
src/Stack/SDist.hs
src/Stack/Snapshot.hs
src/Stack/Solver.hs
src/Stack/Types/BuildPlan.hs
src/Stack/Types/Config.hs
src/Stack/Types/Package.hs
src/Stack/Types/PackageIdentifier.hs
src/Stack/Types/Runner.hs
test/integration/lib/StackTest.hs
test/integration/tests/1336-1337-new-package-names/Main.hs

This improves on the previous warning hack to keep a cache of parsed
GenericPackageDescriptions, and avoid rerunning hpack.
There are some TODOs added in this commit. One further point of concern:
should we opt-out of caching the results of parsing index files? I'm
imagining that when loading a snapshot, this may result in a lot of
memory usage. (Then again, this may already be the case, see #3586.)

Don't parse cabal files twice

---

ChangeLog.md
src/Stack/BuildPlan.hs
src/Stack/Package.hs
src/Stack/Snapshot.hs
test/integration/tests/cabal-non-buildable-bug/Main.hs
test/integration/tests/cabal-non-buildable-bug/files/.gitignore
test/integration/tests/cabal-non-buildable-bug/files/package.yaml

Fix non-buildable bug in Cabal <= 1.22

---

src/Data/Attoparsec/Interpreter.hs
src/Network/HTTP/Download.hs
src/Network/HTTP/Download/Verified.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Source.hs
src/Stack/Docker/GlobalDB.hs
src/Stack/Fetch.hs
src/Stack/PackageIndex.hs
src/Stack/PackageLocation.hs
src/Stack/Prelude.hs
src/test/Stack/PackageDumpSpec.hs

Motivation for the first: prevent bugs like that patched in 25dfaf17e0513267e605820c8ab6ab31941ab1b7 from occurring again. `Handle` doesn't indicate at the type level whether you can read or write, so reducing usage of explicit `Handle`s is a Good Thing.
Motivation for the second is less strong, but given how little we were using `runConduitRes`, and that it carries a (small) performance penalty, I thought standardizing the `with...File` usage throughout the codebase was good thing.
These new helper functions will eventually make it into conduit-extra itself and then we can drop the definitions in `Stack.Prelude`.

Avoid withBinaryFile and runConduitRes

---

ChangeLog.md
src/Stack/BuildPlan.hs
src/Stack/Package.hs
src/Stack/Snapshot.hs
test/integration/tests/3631-build-http2/Main.hs

This is a direct continuation of my (now realized to be incorrect) patch
in 2a52ac28d28fda0b637cbb09c3c74d1de5605a1f. This ensures that tests and
benchmarks are only switched to `buildable = True` if we're enabling
them, otherwise we can end up with cyclic dependency errors.

More compat with buggy Cabal buildable deps #3631

---

ChangeLog.md
src/Stack/PackageLocation.hs

Support .tar archives #3647

---

ChangeLog.md
src/main/Main.hs

Tested via #3658 and tested that a few misc other uses of stack as an interpreter still work.  Seems to be fine, but this is potentially a change in behavior.  I think it's a positive change, though, I know of cases that it fixes, and don't know of any cases that it breaks.

Put file arguments first when stack is run as script interpreter #3658

---

.travis.yml

In case you did not notice, I hate waiting. Here's another matrix for this build. ~~I think this conflicts with https://github.com/commercialhaskell/stack/pull/3676 right now.~~ ~~Since #3676 is blocked right now, this could probably go in first and then I can rebase.~~ 
With both #3676 and this, we'd get 'annoying build' results much quicker :)

Split out the pedantic build to another matrix.

---

ChangeLog.md
doc/yaml_configuration.md
src/Stack/New.hs

Tested by running `stack new` with combinations of year param specified or not in config file and on the command line.

Fix use of and document year template parameter

---

src/Stack/Init.hs

Stack version
```
Version 1.6.1, Git revision f25811329bbc40b0c21053a8160c56f923e1201b (5435 commits) x86_64 hpack-0.20.0 
```
uses extensible snapshots, but the `stack.yaml` generated using `stack new` describes the old syntax. This PR corrects the errors and adds some description.
I think the update is correct, but I'm not sure how best to handle the `extra-deps` case — in any case, it seemed just as easy to open a PR as an issue about it.
---
Probably not relevant:

Update default generated stack.yaml to extensible snapshots

---

CONTRIBUTING.md

---
Every time I get around to actually try and fix something, I forget how to run the tests.
I must ask, do we still need `--flag stack:integration-tests`? IIRC, this was some hack to be able to load tests into GHCi? From my latest attempts here, it's quite easy to run them without all that `:cd` stuff. If we could drop that flag, then running integration tests from the CLI would be much easier to type.
View [the rendered version here](https://github.com/lwm/stack/blob/0ed202d54b3f802dc20d8149d454cdb25fe9de5b/CONTRIBUTING.md).

Add testing notes to CONTRIBUTING.md + some tidbits

---

src/Stack/Types/Build.hs

Pinging @scott-fleischman - any thoughts on why this worked with https://github.com/commercialhaskell/stack/pull/3443 ?  Maybe Cabal-1.24 was less strict about `--with-*` options?
Tested by
```
stack new issue3696
cd issue3696
stack build hpack
stack build --with-hpack=hpack
```
(reproduced the issue)
After this fix, the issue no longer occurs.

Don't pass --with-hpack to Setup.hs configure #3696

---

ChangeLog.md
src/Control/Concurrent/Execute.hs
src/Stack/Build/Execute.hs
src/Stack/SDist.hs

Also generally cleans up code related to parallel execution of tasks. Instead of
locking happening among "final tasks" (tests and benchmark running), it's now
possible to mark some tasks as work that shouldn't be done in parallel with
anything else.  This is what makes sense for benchmark running - they shouldn't
be run concurrently with either building or running tests.
Previously benchmarks and tests shared the same final task. The mechanism to
execute one task exclusively is part of Control.Concurrent.Execute. If they were
kept in the same task, then if any benchmarks were enabled, then tests would be
run without any concurrency. In order to have as much concurrency as possible,
they are now split into two different "final" tasks.
Note: Documentation fixes for …

Never run benchmarks concurrently, always output to console #3663

---

.hlint.yaml

Related: https://github.com/commercialhaskell/stack/issues/3700
I confirmed this change works with these tests:
- command:  `hlint -- src/Network/HTTP/StackClient.hs`
result: doesn't reports error.
- command:  `hlint src/Stack/New.hs` without any modification
result: doesn't reports error.
- command: `hlint src/Stack/New.hs` after modifying like (1).
result: exit with the message (2)
(1)
```diff
diff --git a/src/Stack/New.hs b/src/Stack/New.hs
index fcffc1cc..fa57755b 100644
--- a/src/Stack/New.hs
+++ b/src/Stack/New.hs
@@ -38,8 +38,8 @@ import qualified Data.Text.Lazy as LT
import           Data.Time.Calendar
import           Data.Time.Clock
import qualified Data.Yaml as Yaml
-import           Network.HTTP.Download
-import           Network.HTTP.Simple (Request, HttpException, …
```

Add hlint rules to prevent regression of #3628

---

src/Stack/BuildPlan.hs
src/Stack/Config.hs
src/Stack/Config/Docker.hs
src/Stack/Snapshot.hs
src/Stack/Solver.hs
src/Stack/Types/BuildPlan.hs
src/Stack/Types/Resolver.hs

---
Following [this comment](https://github.com/commercialhaskell/stack/compare/master...lwm:rename-resolver-snapshot?expand=1#diff-44f21bb6d216d7afb930c705712b837eL71).

ResolverSnapshot becomes ResolverStackage.

---

ChangeLog.md
src/Stack/Build/Cache.hs
src/Stack/Constants.hs
src/Stack/Types/Config.hs

Regression was in 99911566a0ac41203d8130bc3ae5fa724dd32128
I have not tested this change, since I do not currently have easy access to windows.

Avoid MAX_PATH for precompiled cache #3649

---

ChangeLog.md
src/Stack/Setup.hs

These changes are motivated by #3636 and #3521.
* `stack setup` looks for GHC bindists and installations by any OS key
that is compatible (rather than only checking a single one).   This is
relevant on Linux where different distributions may have different
combinations of libtinfo 5/6, ncurses 5/6, and gmp 4/5, and will allow
simpifying the setup-info metadata YAML for future GHC releases.
* `stack setup` no longer uses different GHC configure options on Linux
distributions that use GCC with PIE enabled by default.  GHC detects
this itself since ghc-8.0.2, and Stack's attempted workaround for older
versions caused more problems than it solved.
Tested on platforms: macOS, Arch, Ubuntu 16.04, Sabayon (Gentoo), Fedora 27, CentOS 6, CentOS 7, and Void Linux  
Also tested: installing GHCJS, …

setup: improvements to selecting bindists on Linux

---

doc/GUIDE.md

One small nitpick on the CI setup.
The rest was a pass on the user guide prompted by https://github.com/commercialhaskell/stack/issues/3633 but I kinda got carried away when I read through it. I was using a clean build from `docker run -it ubuntu:latest bash` and found a lot of the output very out of date. So, I tried to future proof the content and add links and more references to `hpack`/`package.yaml`.
Check out [the rendered version](https://github.com/lwm/stack/blob/ab352c6834b16581b2fbb00897df969afe15b906/doc/GUIDE.md).
Changes kick off [from here](https://github.com/lwm/stack/blob/ab352c6834b16581b2fbb00897df969afe15b906/doc/GUIDE.md#downloading-and-installation) and end [over here](https://github.com/lwm/stack/blob/ab352c6834b16581b2fbb00897df969afe15b906/doc/GUIDE.md#different-dat …

Take a pass at the user guide documentation

---

ChangeLog.md
doc/GUIDE.md
src/Stack/Ls.hs
src/Stack/Runners.hs
src/main/Main.hs

This PR also deprecates the existing interface. Fixes #3669 

Port `list-dependencies` under the new ls sub command

---

src/Stack/Build/Execute.hs

Instead, provide an empty stream.  Otherwise, operations which try to
use their stdin (for example, network's configure script) will fail
with a "bad file descriptor" error when they try to do something with
fd 0.
It looks like this was introduced a few days ago, in 0d2943ad291f6350049bfdde45d99bc9dc4dbaf3

Don't close stdin for subprocesses when running Setup

---

src/Stack/Build/Cache.hs
src/Stack/Constants.hs

As described in #3649, stack fails on Windows when building project dependencies because the paths it generates for cached files are too long.  #3702 and 36c1226d19e31cc8049eadc880d0f0c773f6d9ae are fixes to this but contain an off-by-one error so builds still fail when a cache path is exactly 260 characters long.  This patch fixes the off-by-one error.
Additionally, the Windows 260 character path limit is counted in 16-bit utf-16 code units, not unicode characters.  This patch also addresses this.
This is only tested on Windows, but the non-Windows functionality should not have changed.
To test this I rebuilt stack and a simple yesod app and all their dependencies using this modified stack.  This had previously failed.  I also edited the CPP constant to ensure the non-Windows branch of …

Fix off-by-one and char encoding issue #3649 #3702

---

src/Stack/Config.hs
src/Stack/Docker.hs
src/Stack/Ghci/Script.hs
src/Stack/Init.hs
src/Stack/Options/DockerParser.hs
src/Stack/PackageLocation.hs
src/Stack/Runners.hs
src/Stack/Snapshot.hs
src/Stack/Solver.hs
src/Stack/Types/BuildPlan.hs
src/Stack/Types/Docker.hs

Looks like a new version of hlint has added some suggestions for our code, which is causing CI failures for PRs (eg #3763 and #3761)
This applies the changes hlint suggests.
They all appear to be   `(blah . foo) <$> something`  ====>  `blah . foo <$> something`
Can't say this seems like the most important suggestion ever, but it seems equally readable before and after, so this seems like the easiest way to shut hlint up unless someone has an objection.

fix hlint suggestions from hlint-2.0.13

---

ChangeLog.md
src/Control/Concurrent/Execute.hs
src/Stack/Build/Execute.hs

Rationale: make user feel more "in control" when waiting for these tens to hundreds of packages to be built by providing information on what is building now.
Build progress line <details><summary>before</summary>`Progress: 3/74`</details> and <details><summary>after</summary>`Progress: 3/74; [Cabal-2.0.1.1|basement-0.0.4|old-time-1.1.0.3|simple-sendfile-0.2.26|stm-2.4.4.1|stringsearch-0.3.6.6]`</details> applying this change.
Limitations: `configure` and `copy/register` stages are not covered, would require refactoring. Since these are quite fast, covering them might not worth the effect.

Report currently building packages along with "Progress:" label

---

etc/scripts/install-many-stack-releases.hs

When comparing behavior of different stack versions, or when my development version of stack has a bug, I find it useful to be able to run older versions.  For example, `stack-1.6.3 build`, etc.
This is a hacky script which depends on `stack >= 1.4`, `wget`, `tar`, and `hub`.  It installs binaries for all the stack releases that it can download that are greater than a minimum version (a constant in the code sets it to `>= 1.0`.
Not sure if writing this script was worth it vs the manual labor, but it only took an hour or two.  Maybe it will be worth it in the long run if it benefits others.
Probably should have used `shelly`, but ohwell.

Add a script to download and install many stack releases

---

ChangeLog.md
src/Stack/Ghci.hs
src/Stack/Package.hs
src/Stack/PrettyPrint.hs
src/Stack/Types/Package.hs

Tested by running against a repro with a duplicate module, got expected error.  Tested running against the stack repo (where the rio package shares a module), and no longer get an error (the issue described in #3776)

With ghci, allow multiple packages to use the same module #3776

---

src/Stack/Build/ConstructPlan.hs
src/Stack/PrettyPrint.hs

* Makes it so that it doesn't output '-any' to describe a version range.
* Doesn't suggest "allow-newer" if some errors aren't constraint mismatches.
* Reorders them so that the recommended action comes last.  This also looks
better because it has a dedented listing of extra-deps.
* Gives a rough / brief reason why approaches other than 'stack solver' may be
preferred.
New output:

Adjustments to plan construction error messages #3766

---

doc/stack_vs_cabal_config.md
doc/stack_yaml_vs_cabal_package_file.md
doc/yaml_configuration.md
mkdocs.yml

Addresses the common question of why you need to specify dependencies in both stack.yaml and cabal files, giving (hopefully) all of the necessary background.

Stack vs cabal config files (docs)

---

src/Stack/Build/Source.hs
src/Stack/Build/Target.hs
src/Stack/Docker/GlobalDB.hs
src/Stack/Options/Completion.hs
src/Stack/PackageDump.hs
src/Stack/Runners.hs
src/Stack/Script.hs
src/Stack/Solver.hs
src/Stack/StaticBytes.hs
src/main/Main.hs

Not only did this complicate the code and add overhead, but it seems to
have confused GHC into sending incorrectly encoded output. With this
approach, GHC gets to send its output directly to stderr.
* Left out, since this is a newly introduced regression with the refactoring of the output code

Avoid stdout redirection in script --compile

---

src/Stack/Setup.hs

ease single directory requirement

---

src/Stack/Build.hs
src/Stack/Types/Config.hs

While looking into input-output-hk/stack2nix#84 I added a couple of queries to `stack query`, so I thought I’d share them in case someone finds them useful.
The change is pretty trivial, but if I had access to a Windows machine, I would make sure it still compiles on Windows, just in case.

Add more queries to `stack query`

---

ChangeLog.md
src/Stack/Build/Execute.hs
test/integration/tests/no-rerun-tests/Main.hs
test/integration/tests/no-rerun-tests/files/.gitignore
test/integration/tests/no-rerun-tests/files/package.yaml
test/integration/tests/no-rerun-tests/files/stack.yaml
test/integration/tests/no-rerun-tests/files/test/Spec.hs

Demonstrates that --no-rerun-tests does not work, and tests are in fact
still rerun.
__NOTE__ DO NOT MERGE yet. We still need to fix this, the test case just fails for now.

Fix --no-rerun-tests

---

ChangeLog.md
src/Stack/Types/Package.hs

* Also: slight refactor to use only `concat` instead of ++ in the error message
* Also: mention that a package.yaml file would also be accepted
* The code that throws this is only searching for a .cabal file, but it runs hpack on the directory immediately before that to generate a cabal file, so it's effectively looking for a package.yaml file as well
Closes #3806
I used `stack install` to install my changes, then ran that executable:

When a cabal file can't be found, warn that extra-deps could be the problem too

---

etc/scripts/get-stack.sh

This small change allows the stack installer script to recognize ElementaryOS (https://elementary.io/) as a derivative of Ubuntu so that required dependency packages get installed.

Add stack install script ElementaryOS support

---

ChangeLog.md
src/Stack/Config.hs
src/Stack/Config/Nix.hs
src/Stack/Constants.hs
src/Stack/Options/NixParser.hs
src/Stack/Script.hs
src/Stack/Types/Nix.hs
src/test/Stack/NixSpec.hs

This change is untested because I do not have convenient access to a windows box.  However, the change is trivial, it should work fine.

Disable nix on windows (#3600)

---

.travis.yml
doc/travis-complex.yml

This PR includes speedups to default `.travis.yml` that is listed in the documentation as well as one that is used for stack. All of the changes where proven to be much better experimentally. Improvements:
* despite that there are some folders that are already being cached during Travis builds, unless `.stack-work` directory is cached the whole package will be recompiled from scratch again, as well as the dependencies.
* `ncpus` setting for cabal will parallelize compilation, but since Travis already runs multiple jobs on the same machine, that setting instead of speeding up, really slows down every build. By "really" I mean as much as factor of 10. Therefore it is removed
* by default `cabal test` will not print anything to `stdout`, therefore a long running test suite can cause a build …

Improved default .travis.yml

---

stack.yaml

The content of `stack.yaml` is as suggested by `stack solver`, after changing the resolver.
`stack install` works after making this change, building `Version 1.7.0, Git revision 5286a22129ced71aa50b5177ead3180c6ad34c5c (5657 commits) x86_64 hpack-0.21.2`

Fixes #3843, by bump to LTS 10.5

---

ChangeLog.md
doc/yaml_configuration.md
src/Stack/Build/Execute.hs
src/Stack/Config/Build.hs
src/Stack/Options/BuildMonoidParser.hs
src/Stack/Prelude.hs
src/Stack/Types/Config/Build.hs
src/test/Stack/ConfigSpec.hs

See #3857.
I've tested this by building stack itself with `stack build --keep-going`.

stack build: Add --keep-tmp-files flag. Fixes #3857

---

doc/install_and_upgrade.md

I just confirmed that Ubuntu 16.04 cannot upgrade to latest stack (or do installations). The problem might extend to later Ubuntu/Debian releases, so maybe we should just drop mentions of the package for now? Adding a commit for Debian.
This PR is still for discussion on what to do in docs, feel free to take over or merge as-is. I can't look more closely at this now.

Comment out instructions for Ubuntu package

---

ChangeLog.md
stack-nightly.yaml
stack.yaml

NOTE: This is included via an extra-dep, which would constitute the
first time Stack would include a patched version of an upstream library.
This is due to the fact that
https://github.com/haskell/hackage-security/pull/203 is likely not going
to be merged, despite fixing issues affecting Stack. This leaves us with
(AFAICT) 4 choices at the Stack level:
1. Continue using the officially released upstream version of
hackage-security, bugs and all
2. Fork hackage-security on Hackage, and depend on the fork
3. Inline the code from hackage-security into Stack itself, and drop the
explicit dependency on hackage-security
4. Include hackage-security via an `extra-dep` pointing at a Git commit.
Our official builds will use the patched version of hackage-security,
and anyone building from Hackage …

Include patched hackage-security for #3073

---

stack-nightly.yaml
stack.yaml

The `ansi-terminal` package is now at `0.8.0.2` on Hackage.

Bump extra-deps to ansi-terminal-0.8.0.2

---

src/Stack/Config.hs
src/Stack/Setup.hs

GHC release team has provided linux-aarch64 bindists since GHC 8.2.1.  This adds support by `stack setup` to install them.  Note, however, that manual installation of the correct LLVM version is still required.

'stack setup' can install GHC on linux-aarch64

---

src/Data/Aeson/Extended.hs
src/Stack/Types/BuildPlan.hs
src/test/Stack/Types/BuildPlanSpec.hs

First, sorry to @lhcopetti for stealing this one - I neglected to notice you were interested in doing this.
This patch adds support for this syntax of `extra-deps`:
```
- github: commercialhaskell/rio
commit: 09654f9fcbdcd96d0f5102796b32fdac5da7260e
```
with an additional optional `subdirs` field. The above would resolve to this archive:
```
https://github.com/commercialhaskell/rio/archive/09654f9fcbdcd96d0f5102796b32fdac5da7260e.tar.gz
```
Please let me know if I should tweak anything, including adding more tests. Thanks!

Allow 'github' shorthand for extra-deps (fixes #3873)

---

stack-nightly.yaml
stack.yaml

Switch stack.yaml to old way of specifying extra-dep tarball #3903

---

src/Stack/Snapshot.hs

The recent nightly-2018-03-13 uncovered a bug in Stack: it assumes that
these two packages are present in all snapshots to apply a historical,
hacky fix. The hacky fix has not been required for quite some time, so
we simply gate on whether we're using an older snapshot or not.

Don't require yaml and persistent-sqlite in snapshots

---

ChangeLog.md
src/main/Main.hs

`stack new` unpacks the project template and then initializes the unpacked project.   When a project template contains a stack.yaml, initializing the project fails due to the presence of the stack.yaml files.  Skip the initialization if the project template contains a stack.yaml.
The change was tested by using project templates that contain stack.yaml files.

Initialize a new project only when no stack.yaml

---

ChangeLog.md
src/Stack/Build/Cache.hs
src/Stack/Build/Installed.hs
src/Stack/Build/Source.hs
src/Stack/Build/Target.hs
src/Stack/Ghci.hs
src/Stack/Package.hs
src/Stack/PackageDump.hs
src/Stack/Types/NamedComponent.hs
src/test/Stack/PackageDumpSpec.hs
test/integration/tests/3899-dont-rebuild-sublibraries/Main.hs
test/integration/tests/3899-dont-rebuild-sublibraries/files/Setup.hs
test/integration/tests/3899-dont-rebuild-sublibraries/files/files.cabal
test/integration/tests/3899-dont-rebuild-sublibraries/files/src-exe/Main.hs
test/integration/tests/3899-dont-rebuild-sublibraries/files/src-internal/Internal.hs
test/integration/tests/3899-dont-rebuild-sublibraries/files/src/Lib.hs
test/integration/tests/3899-dont-rebuild-sublibraries/files/stack.yaml

------
Tested first with the `internal-libraries` package mentioned in https://github.com/commercialhaskell/stack/issues/3899#issuecomment-375935325 and made Stack not ignore the internal library in this case.
Furthermore, tested against my own `hakyll`-based repo, to reproduce #3899.

Don't recompile in presence of sublibraries

---

doc/yaml_configuration.md

This moves one paragraph about `subdirs` to the section with other details about using git repos in `extra-deps`.

docs: move details of `subdirs` adjacent usage example

---

ChangeLog.md
src/Stack/Hoogle.hs
src/main/Main.hs

This PR introduces support for `stack hoogle --server` option to start local Hoogle server as per https://github.com/commercialhaskell/stack/issues/2310.
Here's what I did:
The testing was manual by issuing `stack hoogle --server` on the command line and making sure it works as expected.
As a side note: besides options mentioned in the issue I added `-p 8080` to start Hoogle on a non-privileged port. This is the default Hoogle behaviour since 5.0.13 (released on 2017-07-30), but I figured that there may be older versions in the wild. As there's no way to pass options directly to Hoogle via `stack hoogle` those older versions would try binding to 127.0.0.1:80 and fail without a real way to fix it apart from using `stack exec` to supply the `-p` option.

Introduce Hoogle server command line option

---

ChangeLog.md
etc/scripts/get-stack.sh

Debian, Fedora and CentOS were missing git and gnupg from the install dependencies. Nothing massive just git and gnupg were missing. Ubuntu already had these and the manual installation instruction suggested installing them.
I admit that I didn't test this, but now the dependencies match the ones on https://docs.haskellstack.org/en/stable/install_and_upgrade/#linux-generic

Fixed get-stack.sh script to match manual installation instructions

---

ChangeLog.md
doc/GUIDE.md
src/main/Main.hs

This PR introduces support for `stack unpack pkgname --to /dest/dir` option to unpack pkgname into the specified directory as per #3904.
Here's what I did:
`--to` option is optional (pun intended), the default behaviour without it remains unchanged compared to the previous Stack versions.
The following manual tests have been conducted:
- Omitting `--to`
- Specifying `--to .`
- Specifying `--to /tmp`
- Specifying `--to /directory/i/have/no/write/access/to`
- Using Unicode as a directory name `--to "असतोमा सद्गमय ।"` (who doesn't use Sanskrit to name directories these days, right?)

Add --to option to the unpack command to specify destination

---

ChangeLog.md
src/Stack/Ghci.hs
src/Stack/Types/Config.hs

Fix stack ghci ctrl c 3821

---

ChangeLog.md
src/Stack/Config.hs
src/Stack/Init.hs

`~/.stack/config.yaml` and `stack.yaml` is not terminating by newline.
It is not compliance POSIX.
[Definitions](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206)
I can not fix last template file do not terminate by newline.
This is project-templates bug.

fixed: terminating is newline

---

src/Stack/Build/Execute.hs

If multiple targets report warnings due to missing includes, there's no newline between them, making the output look funky. This fixes that (should be an innocuous fix).

Add newline between sequential warnings

---

ChangeLog.md
package.yaml
src/Stack/Docker.hs
src/Stack/FileWatch.hs
src/Stack/Prelude.hs
src/main/Main.hs

`hIsTerminalDevice` does not recognise handles to 'mintty' terminals, but `isMinTTYHandle` does. Currently, `stack` relies on `hIsTerminalDevice` in three places to detect handles to terminals and does not use `isMinTTYHandle`. This proposal introduces 'isMinTTYHandle' in those three places.
`isMinTTYHandle` was first added to package `Win32-2.5.0.0` and then made robust to an upstream (ntdll-related) bug from `Win32-2.5.3.0`. The latter constraint is added to `package.yaml`.
This has been tested only by building `stack` on Windows 10 and using it in native and 'mintty' terminals - I do not know what significance the terminal device-checking has.

Windows: use 'hIsTerminalDevice or isMinTTYHandle'

---

src/Stack/Types/Runner.hs
src/main/Main.hs

See #3992. This adds, to `main`, an initial output of an 'SGR Reset' ANSI code to `stdout`, if `stdout` is recognised as a supported terminal by `hSupportsANSI` (from the `ansi-terminal` package). For a native (ConHost) terminal on Windows 10, which is ANSI-capable, this will enable its capability to process the ANSI codes emitted by functions of the `RIO` package.
This will not fix #3992 for: (1) non-native ANSI-enabled terminals on Windows 10; or (2) terminals on legacy Windows. This is because (1) non-native ANSI-enabled terminals on Windows are not recognised as such by `hSupportsANSI` (used elsewhere by `stack`) and (2) native terminals on legacy Windows require an emulation layer to behave as if they were ANSI-enabled.
Tested by building `stack` on Windows 10 and then using it …

Fix for #3992, for native terminals on Windows 10

---

ChangeLog.md
src/Stack/Build/Execute.hs
src/Stack/Build/Installed.hs
test/integration/tests/3996-sublib-not-depended-upon/Main.hs
test/integration/tests/3996-sublib-not-depended-upon/files/Setup.hs
test/integration/tests/3996-sublib-not-depended-upon/files/files.cabal
test/integration/tests/3996-sublib-not-depended-upon/files/src-internal/Internal.hs
test/integration/tests/3996-sublib-not-depended-upon/files/src/Lib.hs
test/integration/tests/3996-sublib-not-depended-upon/files/stack.yaml

Solves #3996 by making sure `Cabal build` is called with libraries, *internal libraries*, foreign libraries and executables names (adds *internal libraries* to the list).
Otherwise, if the internal library is not listed as dependency of the main library, `Cabal configure` ignores it, `Cabal build` doesn't build it but `Cabal copy` and `Cabal register` are still looking for it. This causes the build to error, #3996.
Checklist:

Handle internal libs not listed as dependencies

---

ChangeLog.md
src/Stack/Build/ConstructPlan.hs
test/integration/tests/3940-base-upgrade-warning/Main.hs
test/integration/tests/3940-base-upgrade-warning/files/files.cabal
test/integration/tests/3940-base-upgrade-warning/files/no-base-upgrade.yaml
test/integration/tests/3940-base-upgrade-warning/files/unattainable-base.yaml

Implements the following:
1. Emit a warning when someones tries to upgrade/downgrade base.
2. Show a specific message when build plan results in base upgrade/downgrade requirement.
Here's what I did or checked out:
- Created `stack.yaml` with the following contents:
resolver: lts-11.6
extra-deps: []
- Issued `stack build ghc-mod`
- Made sure I'm getting the right error message suggesting me to pick another GHC with the matching `base`.
- Created `stack.yaml` with the following contents:
resolver: lts-11.6
extra-deps: ["base-4.9.1.0"]
- Issued `stack build ghc-mod`
- Made sure I'm getting the right warning suggesting me not to put `base` in `extra-deps`, and use another GHC version instead.

Help users not to go down the road of base upgrade/downgrade, addresses #3940

---

ChangeLog.md
src/Stack/Constants/Config.hs
src/Stack/Ghci.hs

Use the `ghciDirL` for `cabal_macros.h` in `stack ghci` command.
Example:
```
bash-3.2$ stack exec -- stack ghci -v 2>/dev/stdout | egrep '\-optP.*?cabal_macros.*? ' -o
-optP-include -optP/Users/chris/Work/stack/.stack-work/ghci/cb285e1e/cabal_macros.h
bash-3.2$ stack exec -- stack ghci -v 2>/dev/stdout | egrep '\-optP.*?cabal_macros.*? ' -o
-optP-include -optP/Users/chris/Work/stack/.stack-work/ghci/cb285e1e/cabal_macros.h
```
Here are two runs of `stack ghci` on the stack codebase. The first
compiles everything, the second loads the cached object files:
https://gist.github.com/chrisdone/7468e27683a5f202b6a5f4e146b2fb8e#file-ghci-output-txt-L146-L164
Ping @mgsloan @bitemyapp

Set cabal_macros.h work directory in stack ghci to something non-temporary

---

doc/GUIDE.md

Brief history: Two days ago I deployed a Yesod application via Docker
and found the current documentation quite confusing. I had to use
`stack -v image container` to figure out what is being done and
understand things. One of the major thing I didn't understand was how
the presence of
```
docker:
enable: true
```
will affect things as the `stack image container` was working with and
without it. I'm changing the documentation based on my experience. But
yeah, I'm open to changes and feedback if you think this can be
improved further!

Improve docker related documentation

---

ChangeLog.md
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Target.hs
src/Stack/PackageIndex.hs
src/Stack/Types/PackageIndex.hs

This PR addresses the following issue #3925
TODO:
Tested by removing the `rio` extra-dependency in the stack.yaml file and then trying to build the package with the newly generated stack executable.
```
. . .
* Recommended action: try adding the following to your extra-deps in /home/thomas/github/stack/stack.yaml:
rio-0.1.2.0@sha256:cb2a65cee1c0450815002ca890633215e4544b5c1c9f7091a950142c6efe8f3f
```

Add cabal-hash revision info when displaying recommended packages when failing to construct buildplan

---

ChangeLog.md
src/Stack/Upload.hs

Flush after prompt

---

ChangeLog.md
src/Stack/Options/BenchParser.hs
src/Stack/Options/TestParser.hs
test/integration/tests/3959-order-of-flags/Main.hs
test/integration/tests/3959-order-of-flags/files/package.yaml
test/integration/tests/3959-order-of-flags/files/stack.yaml
test/integration/tests/3959-order-of-flags/files/test/Spec.hs

This fixes #3959.
The problem is that the [switch](https://hackage.haskell.org/package/optparse-applicative/docs/Options-Applicative-Builder.html#v:switch) function returns a `Just False` which gets wrapped into `First`.
This means that the value is *always* set to either `True` or `False`
and the `First` monoid means that during options parsing the order of
the flags suddenly matters as described in #3959, because `First (Just
False)` is chosen when `mappend`ing with `First (Just True)`.
The fix is to use the [flag](https://hackage.haskell.org/package/optparse-applicative-0.14.2.0/docs/Options-Applicative-Builder.html#v:flag-39-) function that does not set a default value, so we get a `First Nothing` instead.
Note: Documentation fixes for https://docs.haskellstack.org/en/stable/ should …

Change parsers to use `flag'` instead of `switch`

---

ChangeLog.md
src/Stack/Package.hs

See https://github.com/commercialhaskell/stack/issues/4027
I've tested my changes on our codebase where previously `stack build` would eat >11G RAM, it's now <300Mb. A change without switching to a lazy Char8 wasn't sufficient (if someone wonders).
Previously `dumpHI` was traversed twice, I figured that instead of trying to merge the code to guarantee it's only traversed once, it's simpler to pre-filter the interesting content.

Fix RAM usage upon big dump-hi files parsing

---

ChangeLog.md
doc/nix_integration.md
src/Stack/Config/Nix.hs
stack.yaml

This was introduced in #3938, but breaks Docker mode under NixOS.
This PR relaxes the logic to only change the default under NixOS, rather than force Nix mode to enabled.
Fixes #4002.
Tested under NixOS using the Stack project.

Allow Nix mode to be disabled under NixOS

---

doc/maintainers/releases.md
doc/maintainers/team_process.md
etc/scripts/README.md
mkdocs.yml

Resolves  #4051 (See "Stack issues triagers" email thread w/ @snoyberg, @borsboom and @paulrzcz).
**NB: this also moves + renames the `doc/MAINTAINER_GUIDE.md` file to `doc/maintainers/releases.md`.**
I tried to figure out somehow to leave a catchall `index.md` in its place for people who may have saved links to the previous location but didn't find a way using `mkdocs`.
---

4051 - Add stack maintainer team process documentation

---

etc/scripts/get-stack.sh

When requesting root permission, always show the command and never re-use cached credentials.
* [ :heavy_check_mark: ] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [ :heavy_check_mark: ] The documentation has been updated, if necessary.
Note that the second sudo invocation doesn't prompt for password: (This also has #4074 applied.)
```
$ sudo apt remove libgmp-dev                          
[sudo] password for buck: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
libgmp-dev
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 1,612 kB disk space …
```

get-stack: allow users to use sudo carefully

---

doc/appveyor.yml

This is a workaround for haskell/cabal#5386 and #3944

Use a fixed temp dir on AppVeyor

---

ChangeLog.md
src/Stack/Setup.hs

Resolves #3841.
Recover from all errors on invoking `proc "cabal" --numeric-version`.
This reintroduces the helpful hint to `stack install cabal-install` if `stack solver` is run when `cabal` is not on PATH, instead of displaying the exception message propagated from RIO (thanks for the help, @mgsloan!).
* Ran `stack solver` on a project using an existing version of stack, with and without cabal on PATH
* Ran `stack solver` on the same project using the modified stack, with and without cabal on PATH. Verified that the helpful hint was displayed without cabal on PATH; verified that `stack solver` ran without issue with cabal on PATH

Solver cabal install hint

---

ChangeLog.md
doc/build_command.md
doc/yaml_configuration.md
src/Stack/Build/Execute.hs
src/Stack/Config/Build.hs
src/Stack/Options/BuildMonoidParser.hs
src/Stack/SDist.hs
src/Stack/Types/Config/Build.hs

* Fixes #3225
* Fixes #3508
Manual experimentation only, sorry.

Add the interleaved-output option/config value #3225

---

ChangeLog.md
src/Stack/Build/Cache.hs
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Execute.hs
src/Stack/Build/Source.hs
src/Stack/Coverage.hs
src/Stack/Package.hs
src/Stack/Types/Build.hs
test/integration/tests/3787-internal-libs-with-no-main-lib/Main.hs
test/integration/tests/3787-internal-libs-with-no-main-lib/files/exe/Main.hs
test/integration/tests/3787-internal-libs-with-no-main-lib/files/files.cabal
test/integration/tests/3787-internal-libs-with-no-main-lib/files/src-sublib/B.hs
test/integration/tests/3787-internal-libs-with-no-main-lib/files/stack.yaml
test/integration/tests/4105-test-coverage-of-internal-lib/Main.hs
test/integration/tests/4105-test-coverage-of-internal-lib/files/files.cabal
test/integration/tests/4105-test-coverage-of-internal-lib/files/src-sublib/B.hs
test/integration/tests/4105-test-coverage-of-internal-lib/files/src/Src.hs
test/integration/tests/4105-test-coverage-of-internal-lib/files/stack.yaml
test/integration/tests/4105-test-coverage-of-internal-lib/files/test/Main.hs

This checks for all the places where we need to handle internal libraries and handles them. As a result, it closes #3787, #4071 and #4105.

Consistent handling of internal libraries

---

ChangeLog.md
src/Network/HTTP/Download/Verified.hs

This changes makes the default retry strategy an exponential backoff
starting from 100 ms.
This should counteract the problem that is being tracked in #3510.
This new strategy means that it will take 12.7 seconds for stack to
fail entirely when the network cable is unplugged.
I did not add any tests, as discussed with @snoyberg.

Changed the default retry strategy

---

ChangeLog.md
doc/GUIDE.md
src/Stack/GhcPkg.hs
src/Stack/New.hs
src/Stack/Options/NewParser.hs
src/Stack/Types/TemplateName.hs

* `stack new` now allows template names of the form username/foo to download from a user other than commercialstack on Github, and can be prefixed with the service`github:`, `gitlab:`, or `bitbucket:`.
* Changelog.md has been updated
* Help text for stack new has been updated
* Tested this by temporarily adding a trace in the downloadTemplate function, to see the request it was using to download the template, and trying various new and old forms of the template name. Also created a local template and made sure that still took priority over a remote download.
* I would have liked to add an integration test, but it's hard to test things that download from remote URLs. There isn't currently a way to stub that out.
* Added documentation for the web site in the `doc` subdirectory. …

4039 namespaced templates

---

ChangeLog.md
package.yaml
src/Stack/Options/Completion.hs
src/Stack/Options/GlobalParser.hs
src/main/Main.hs
src/unix/Stack/DefaultColorWhen.hs
src/windows/Stack/DefaultColorWhen.hs
stack.yaml

Implements `--color=never` as default on Windows before Windows 10, if emulation would be required to support ANSI colour codes.
Also bumps the lts-11 resolver in `stack.yaml` to lts-11.14, in order to benefit from `ansi-terminal-0.8.0.4`.
`defaultColorWhen`, exported by new module `Stack.DefaultColorWhen`, establishes the default. That module differs, pending on whether the operating system is Windows or non-Windows (see the conditional in `package.yaml`).
`globalOptsFromMonoid` in module `Stack.Options.GlobalParser` is modified so that the default is an argument rather than a given.
A beneficial side-effect of `defaultColorWhen` on Windows is that it enables ANSI on ANSI-capable native terminals. This allows some existing code in module `Main` to be removed.
Note: Documentation fixes …

Re #4091: Pre-Windows 10, default --color=never

---

ChangeLog.md
src/Stack/PrettyPrint.hs
test/integration/tests/3942-solver-error-output/Main.hs
test/integration/tests/3942-solver-error-output/files/.gitignore
test/integration/tests/3942-solver-error-output/files/script.hs
test/integration/tests/3942-solver-error-output/files/test-stack.yml

The issue seems to have been caused by improper logging level. Fixed that and added an integration test case.
I have tested the fix in accordance with the issue + added integration test cases.

Fixes self-executing scripts not piping plan construction errors from runhaskell to terminal, issue #3942

---

mkdocs.yml

I tested this locally using `mkdocs build`, and also enabled this branch on RTFD.  If you go to https://docs.haskellstack.org/en/fix-rtfd-edit-link/README/, the __Edit on Github__ link seems to be correct now (and same for other pages).

mkdocs.yml: fix 'edit on github' link (fixes #4098)

---

etc/scripts/get-stack.sh

Don't need to invoke sudo if all deps are already installed.
Avoiding the sudo prompt where possible is going to be an improvement.
* [ :heavy_check_mark: ] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [ :heavy_check_mark: ] The documentation has been updated, if necessary.
I re-ran the script a few times, sometimes uninstalling libgmp-dev, and verified it skips `sudo apt install`
when appropriate.

get-stack: check deps before sudo

---

src/Stack/Coverage.hs
src/Stack/Hoogle.hs
src/Stack/Setup.hs
src/Stack/Setup/Installed.hs
src/Stack/Solver.hs

The only case where stdio should be inherited is when passing execution to
another process, so there should be no uses of runProcess
Most processes should also not inherit stdin, but I'm not sure if there are any
concrete issues with this in stack. I recall some prior issues where some
processes do not like being given a closed stdin, for example.
There is one remaining use of readProcessStdout_ in Stack.Docker which should
probably be fixed. However, I'm not sure what the correct implementation there
should be. The comment in the code makes it seem like it should log stderr while
reading stdout.

Fix issues with stderr being inherited by child processes

---

ChangeLog.md
src/Stack/Build/ConstructPlan.hs
test/integration/tests/3685-config-yaml-for-allow-newer/Main.hs
test/integration/tests/3685-config-yaml-for-allow-newer/files/files.cabal
test/integration/tests/3685-config-yaml-for-allow-newer/files/src/Src.hs

Tested using `stack exec -- stack install intero-0.1.23` from the stack's work directory
Fixes #3685

Point to user's config.yaml when advising 'allow-newer: true'

---

ChangeLog.md
src/Stack/New.hs

Do not apply Mustache to large files (fixes #4133)

---

ChangeLog.md
src/Stack/Build/ConstructPlan.hs
src/Stack/Build/Source.hs
src/Stack/BuildPlan.hs
src/Stack/Package.hs
src/Stack/Snapshot.hs
src/Stack/Types/BuildPlan.hs
src/Stack/Types/Package.hs

This is a fundamental change to how Stack discovers build tools, its inclusion should be discussed before we merge. We should also wait to see if it actually fixes #4125.

Use a hard-coded tool dependency map (fixes #4125)

---

ChangeLog.md
src/Stack/Ghci.hs

Before this change, 'stack ghci' would ask the user a question after doing a
build which may take a long time. The reason it was this way is that the
question required resolution of package files, and package file resolution
needed to come after the build due to #1180.
The solution here is to resolve the package files twice - once before the build, 
and once after. This isn't the most efficient solution possible, but it is a
much better user experience to ask the main target question before building
rather than after.
Tested this by running on a large project and observing that ghci functions properly, and that the main target question is asked before the build.

'stack ghci' now asks which main module to load before building

---

ChangeLog.md
package.yaml
stack-nightly.yaml
stack.yaml

Bump to hpack 0.29

---

test/integration/tests/3926-ghci-with-sublibraries/Main.hs

Due to #4148, one of the integration tests fails (the second in #4142). This PR adds a build step before starting the repl process, punting the real work of making `stack ghci` work without a previous build step for later.

Ensure we build before ghci, due to #4148.
