commercialhaskell/stack

README.md
=> Fix stackage-cli link in README

src/System/Process/Read.hs
This addresses the problem addresses issue #244, and indeed does solve the problem in tests on my local machine.
The `makeAbsolute` function is available in newer versions of `directory`, but it's a very recent addition and doesn't ship with GHC 7.8, so instead we have to replicate it inline. It's a [pretty trivial function](http://hackage.haskell.org/package/directory-1.2.2.0/docs/src/System-Directory.html#makeAbsolute), so that's not a big deal.
=> Updated System.Process.Read so it won't try to canonicalize symlinks

src/Stack/Package.hs
=> Do not include unbuildable test suites in build plan.

src/Control/Concurrent/Execute.hs, src/Stack/Build.hs, src/Stack/Build/Cache.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Source.hs, src/Stack/Build/Types.hs, src/Stack/Constants.hs
Fixes #283 and a bunch of others, see that issue for details.
=> Test suite overhaul

src/Stack/GhcPkg.hs, src/Stack/Setup.hs, src/System/Process/Read.hs
Pinging @manny-fp and @chrisdone. This seems to me to be an improvement over the current behavior of sending output immediately to the console. Do either of you see a downside to this?
=> ReadProcessException (fixes #331)

src/Stack/Build/Execute.hs
This is meant to address #312.
I decided that instead of *replacing* the "Copying ... to ..." output, I'd just add a new message at the end, since the "Copying" lines describe things as they're happening, and my new code just summarizes what was actually successfully installed.
The output looks like this:
```
Installed executables to /Users/radix/.local/bin/:
- stack-integration-tests
- stack
```
I'm sad to say that this is probably the most complex monadic code I've worked with, having never worked with transformer stacks at all, and being a very new Haskeller. So please give it an extra close look, though it's a very small change.
In particular I'm curious if there's an easy way for me to get a function of `[(a, b)] -> Map a [b]`. I ended up accumulating `[(a, [b])]` even though the [b] …
=> Add an easy-to-read message showing where exes were installed

src/Stack/Build/Source.hs
While studying the source, I've written a few clarifying comments and added some signatures. Please merge if you find these useful.
=> Add docs, comments, and type signatures

src/Stack/Build/Cache.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Source.hs, src/Stack/Build/Types.hs
=> Rename Location to InstallLocation

README.md
In my opinion, most newbie wants to know if they can [install a package
using `stack`](https://stackoverflow.com/questions/31030438/how-to-install-a-package-using-stack) (which is a direct translation from their cabal workflow). And adding that in README is essential IMO.
[ci skip]
=> Include instruction for installing package name

src/Data/Set/Monad.hs
Just update comment. filterM comment is same as mapM.
=> Fix filterM comment

src/Stack/Package.hs
=> Add include-dirs from cabal file to GHC call.

src/Network/HTTP/Download/Verified.hs
Just something I noticed while browsing the source, you can replace the custom `whenJust` helper with `for_` from `Data.Foldable` :)
Best,
Markus
=> Replace whenJust with for_ in verifiedDownload

src/Stack/Init.hs
New '--force' argument to 'stack init' overwrites the existing stack.yaml file instead of refusing the operation.
=> Add --force flag to init command

README.md
I don't know if it is wanted but I always find them pretty :)
=> License and release badge in README

src/Stack/Ide.hs
Adds support for multiple RequestUpdateSession constructors in stack-ide (see https://github.com/commercialhaskell/stack-ide/pull/15)
=> Use RequestUpdateTargets constructor in initialRequest

src/main/Main.hs
Implements #506. Is it that easy or did I miss anything special? :)
=> Drop trailing slashes in `stack path` output

src/main/Main.hs
I believe this should fix https://github.com/commercialhaskell/stack/issues/538
=> Added in support for using the --package option with ghci.

src/main/Main.hs
=> Remove `--[no-]haddock` flags from `stack haddock`

src/Stack/Setup.hs
Quickly solves https://github.com/commercialhaskell/stack/issues/566. Truly configurable approach could be done later.
```
% stack exec -- stack -v setup --reinstall               
Version 0.1.2.1, Git revision 817669d6934bc6176930facac0005b6955bc2fe7 (dirty)
2015-07-13 13:54:47.130318: [debug] Checking for project config at: /Users/ogre/Coding/stack/stack.yaml @(stack-0.1.2.1:Stack.Config src/Stack/Config.hs:445:9)
2015-07-13 13:54:47.130574: [debug] Loading project config file stack.yaml @(stack-0.1.2.1:Stack.Config src/Stack/Config.hs:468:13)
2015-07-13 13:54:47.588452: [debug] Downloading from https://www.haskell.org/ghc/dist/7.8.4/ghc-7.8.4-x86_64-apple-darwin.tar.bz2 to /Users/ogre/.stack/programs/x86_64-osx/ghc-7.8.4.tar.bz2 ... @(stack-0.1.2.1:Stack.Setup src/Stack/Setup.hs:697:5) …
```
=> Use gmake instade of make if available

src/Network/HTTP/Download.hs, src/Network/HTTP/Download/Verified.hs, src/Stack/Fetch.hs, src/Stack/Setup.hs, src/test/Network/HTTP/Download/VerifiedSpec.hs, stack.cabal
Resolves #561.
Changes:
- add `Maybe Integer` argument to progress sink of `verifiedDownload`, where `Nothing` means the total is unknown
- add `bytes` formatter and the `formatting` library as an **additional dependency**
- add progress output to `chattyDownload`
Output looks like this:
```
λ> do man <- newManager; dir <- parseAbsFile "/tmp/7z.exe"; runStdoutLoggingT $ flip runReaderT man $ chattyDownload "7z" "http://7-zip.org/a/7z1505-x64.exe" dir
[sticky] Preparing to download 7z ... 
[Debug] Downloading from http://7-zip.org/a/7z1505-x64.exe to /tmp/7z.exe ... 
[sticky] 7z: download has begun 
[sticky] 7z: 47.55 KiB / 1.27 MiB (3.66%) downloaded... 
[sticky] 7z: 97.74 KiB / 1.27 MiB (7.51%) downloaded... 
[sticky] 7z: 186.77 KiB / 1.27 MiB (14.36%) downloaded... 
[sticky] 7z: 233.18 …
```
=> Show download progress via chattyDownload

.gitignore, src/Path/IO.hs, src/Stack/Config.hs, src/Stack/Image.hs, src/Stack/Types.hs, src/Stack/Types/Config.hs, src/Stack/Types/Image.hs, src/main/Main.hs, stack.cabal
There is still more to add to this but it works (outside of docker-in-docker)
=> Stack can create docker image(s) from your executable(s)

ChangeLog.md, src/Stack/Package.hs
=> Ignore the other-extensions field

ChangeLog.md, src/Stack/Build/Execute.hs, src/Stack/Options.hs, src/main/Main.hs
=> 569 stack copy

ChangeLog.md, src/Stack/Build/Source.hs, src/Stack/BuildPlan.hs, src/Stack/Config.hs, src/Stack/Init.hs, src/Stack/Options.hs, src/Stack/Solver.hs, src/Stack/Types/Config.hs, test/integration/tests/111-custom-snapshot/Main.hs, test/integration/tests/111-custom-snapshot/files/files.cabal, test/integration/tests/111-custom-snapshot/files/my-snapshot.yaml, test/integration/tests/111-custom-snapshot/files/src/Lib.hs, test/integration/tests/111-custom-snapshot/files/stack.yaml
=> 111 custom snapshot

src/Network/HTTP/Download.hs, src/Network/HTTP/Download/Verified.hs, src/Stack/Fetch.hs, src/Stack/Setup.hs, src/test/Network/HTTP/Download/VerifiedSpec.hs, stack.cabal
Resurrection of #560, I have no idea what happened :)
=> Use `retry` package for download retry logic

src/Stack/Image.hs, src/Stack/Types/Image.hs
Because just complaining is a bit lame, I took a shot at this feature. Feel free to yell at me and tell me why this is a bad idea or what needs to be changed.
=> Allow setting the docker image name, fixes #621

src/Stack/Constants.hs, src/Stack/Image.hs, src/main/Main.hs
… or disabled. closes #659 /cc @manny-fp @cocreature @snoyberg
=> allow building containers regardless of docker builds being enabled

stack.yaml
=> Switch to LTS 3.0

ChangeLog.md, src/Stack/Config.hs, src/Stack/Setup.hs, src/Stack/Types/Config.hs, src/System/Process/Read.hs
Pinging @borsboom as well for input
=> extra-path setting

ChangeLog.md, src/Stack/Build/Execute.hs, src/Stack/Build/Haddock.hs, src/Stack/Ghci.hs, src/Stack/Setup.hs, src/Stack/Types/Compiler.hs
=> Use a cached Setup exe #801

src/Network/HTTP/Download/Verified.hs
As mentioned in #854 I think we should retry `verifiedDownload` for **some** `IOException`s.  Of course there are many cases where a retry will not have a chance of success, so I chose to make the handler as specific as possible.
Is this **too** specific, because it seems like it will be very `GHC` bound, due to the fact that we access functions from `import GHC.IO.Exception`?
=> Retry verifiedDownload for ResourceVanished IOException

src/main/Main.hs
=> Fix search path seperator issue on Windows

src/main/Main.hs
=> Add --numeric-version option

README.md
closes #928 
There was no section in the README which introduced a newbie to the contribution process. I just edited in a few simple steps for new contributors.
=> Created a section for new contributors in the README

src/Stack/Setup.hs
=> Include the location when extracting GHC tarball

src/Stack/Build/Execute.hs
Silent warning if `local-bin-path` is a symlink to a target that is on
the PATH.
Ref #840
=> Check canonicalized `local-bin-path`

GUIDE.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Types/Build.hs
Pinging @wolftune. I'll rebase and merge after #939 is complete.
=> Better travis docs

doc/install_and_upgrade.md
As discussed in https://github.com/yesodweb/yesod/issues/1082#issuecomment-145898194.
=> Doc: add advices about temporary workarounds on Windows.

ChangeLog.md, src/Stack/Build/Execute.hs
Pinging @mgsloan for review. I just (ab)used your existing code for GHCJS, please sanity check that I didn't do anything terrible.
Also pinging @ezyang, who's probably interested in this.
=> Compile custom Setup.hs instead of interpreting them (fixes #1041)

README.md
According to [discussion](https://github.com/commercialhaskell/stack/issues/1118#issuecomment-147174131), please merge to `master`.
=> Add NixOS to 'How to install'.

src/Path/Extra.hs, src/Path/IO.hs, src/Stack/Docker.hs, src/Stack/GhcPkg.hs, src/Stack/Image.hs, src/Stack/Package.hs, src/Stack/Setup.hs, src/Stack/Setup/Installed.hs, src/Stack/Types/Build.hs, src/System/Process/Read.hs, src/main/Main.hs, stack.cabal
=> Create Path.Extra for Path utilities unrelated to IO

src/Control/Concurrent/Execute.hs
sorry for minor request :/
for future requests - is it better to make conceptual or split and small :S
=> Control/Concurrent/Execute.hs : redundant do

src/Stack/Build/Haddock.hs
This change reduces the time needed to compute the transitive dependencies for the `stack` project from ~393ms to ~~~27ms~~ ~11ms on my computer.
=> Speed up generateDepsHaddockIndex

src/Stack/Setup.hs, src/main/Main.hs
Add documentation about the dataflow of the path command
Also, the name of the function "getMinimalEnvOverride" is misleading.
Should I change it?
=> Add documentation about the dataflow of the path command

src/main/Main.hs
Added both `runhaskell` -> `runghc` and `repl` -> `ghci`.
=> Address alias requests in #1241

doc/install_and_upgrade.md
Just some words telling how to get the Ubuntu version the user is running.
=> Little help for those that might want to check their Ubuntu version

src/Stack/Fetch.hs
Not sure whether `UnknownPackageNames` should have been extended too. Tell me if something can be improved.
=> Show package suggestions at the end of output

src/main/Main.hs
Result of interaction with HLint:
* η-reducing
* redundant brackets and `($)`
* redundant `do` blocks
* redundant lambdas (especially beginning from line 490)
* `\_ -> clean` → `const clean`
* `when (not …)` → `unless …`
* …and silly re-alignment of `data`-declarations
=> Cosmetic improvements of main module

src/Stack/Build/Source.hs
It should read slightly easier now.
=> Refactor `Stack.Build.Source.localFlags` a bit

doc/install_and_upgrade.md
Best practice for GPG keys on Ubuntu.
=> Get GPG key from keyserver

.travis-setup.sh, .travis.yml
Resolves https://github.com/commercialhaskell/stack/issues/1398
=> Build on travis with stack too

README.md
=> minor typo fixes

doc/nix_integration.md
fixed a couple of outdated link anchors too
=> Eyecandy update for nix_integration.md

doc/faq.md
this could possibly be amended with other options to install non-local non-hackage packages.
=> add example on how to install packages from git

src/Stack/Options.hs, src/main/Main.hs
=> make verbosity silent by default in script interpreter mode

src/System/Process/Read.hs
See http://stackoverflow.com/questions/34200998/is-a-bang-pattern-on-unit-really-needed-here.
=> Remove superfluous bang pattern

src/main/Main.hs
Without this PR it's impossible to compile stack.
=> [CRITICAL] Fix not in scope name

src/test/Stack/PackageDumpSpec.hs, test/package-dump/ghc-head.txt
See #1509.
Only has a failing test for now - I'm not sure how to fix it.
=> Deal with `ghc-pkg dump` format change in GHC HEAD.

src/Stack/Options.hs
Noticed this one line doesn't fit in with the rest of the options parser
=> very minor code consistency fixup in Options

src/Stack/Config.hs, src/Stack/Docker.hs, src/Stack/Setup.hs, src/Stack/Solver.hs, src/System/Process/Read.hs
=> give a sane error when path containing ':' is added to $PATH

doc/nix_integration.md
Instead, we use nix-instantiate and nix-env, which are core tools available on every Nix installation.
=> doc: update instructions in nix_integration.md to work without nix-repl

src/Options/Applicative/Complicated.hs, src/main/Main.hs
Please see the commit messages for more details.
=> Provide better error messages for external command and interpreter errors

src/Stack/Build/Execute.hs
=> Warn if newly installed executables won't be available on the PATH 

appveyor.yml
Changes to a comment on commented out code.
=> Less grammar mistakes

src/Stack/Ghci.hs
The message has been changed to the below, and now includes interactive loading. If nothing or anything other than the options provided under `3)` is chosen, no main is loaded.
```
* * * * * * * *
The main module to load is ambiguous. Candidates are:
1. Package `testP' component exe:testP with main-is file: C:\Users\artem\dev\haskell\stack\testP\app\Main.hs
2. Package `testP' component test:testP-test with main-is file: C:\Users\artem\dev\haskell\stack\testP\test\Spec.hs
You can specify which one to pick by:
1) Specifying targets to stack ghci e.g. stack ghci testP:exe:testP
2) Specifying what the main is e.g. stack ghci --main-is testP:exe:testP
3) Choosing 1, 2
* * * * * * * *
```
Resolves #1068
=> Added interactive Main selection

doc/ghcjs.md
=> GHCJS doc update

doc/install_and_upgrade.md
I have recently added the `stack` package into Arch's [community] repository. This PR updates the instructions to reflect the changes. Please let me know if there is any problem with the new package, thanks!
P.S. Also updated the package name in ArchHaskell repo.
=> Update Arch Linux instructions for [community]/stack package

src/Options/Applicative/Builder/Extra.hs
Per issue #1613, enable/disable flags now occupy 1 line in help output.
Summary:
- Simplified `enableDisableNoDefault` logic as hiding is no longer
specified manually.
- Helper function `enableDisableNoDefault'` no longer seemed necessary
after simplification, removed it.
- Fixed issues caused by removing the show/hide argument
- Created "dummy" extra flag with appropriate help message
Issue:
dummy argmuent actually acts as a real flag, which seems bad.
`<*` was causing the hidden actual flags to be dropped by
opt-parse. Ideally this would cause the standard unknown command
behavior.
New help output:
```
gambogi@computer:~/projects/public/stack$ stack --help
stack - The Haskell Tool Stack
Usage: stack [--help] [--version] [--numeric-version] [--docker*] [--nix*]
([--verbosity VERBOSITY] | …
```
=> Unified Enable/disable help messaging

doc/GUIDE.md
* Better caching via compiler setting
* A little more commenting
* OS X support built-in
=> Updated Travis example

ChangeLog.md
Added a few notes to change log on stack init enhancements.
=> Update changelog for stack init changes

src/Stack/BuildPlan.hs
For `stack init` - print package flags just once per set of errors instead of spamming repeatedly.
=> Do not repeat printing of package flags

stack.cabal
Detected with https://github.com/afcady/packunused
=> Delete a few unused dependencies

src/Stack/Init.hs, src/Stack/Options.hs
@harendra-kumar I ran into a bunch of issues squashing all the branch since I had previously merged master into it. I had to start a brand new branch.
This issue is in reference to #1593.
=> Have "stack init" accept a list of sub-directories

doc/README.md, doc/install_and_upgrade.md
=> Add links to unofficial FreeBSD packages

src/Stack/Config.hs, stack-7.8.yaml, stack.cabal, stack.yaml
=> Switch to ‘path-io-1.0.0’

src/Stack/PackageIndex.hs
checks tar commit-id from index archive differs with cloned repo commit-id before generating archive
:zap: :zap: :zap: 
fixes #1854
=> Only generate index archive when commit id has changed

src/Stack/Config.hs, test/integration/tests/1884-url-to-tarball/Main.hs, test/integration/tests/1884-url-to-tarball/files/stack.yaml
Fixes #1884 and adds integration test for it.
=> Fix use of package specified by a url to a tarball

src/Stack/BuildPlan.hs, src/Stack/Solver.hs
Fixes #1927. See the details in the github issue.
=> stack init: handle spurious flags in build plans

src/Stack/Build/Source.hs, src/Stack/PackageIndex.hs
See https://github.com/commercialhaskell/stack/issues/1892 for context.
=> In 'loadSourceMap', load the package caches only when necessary

src/Stack/Solver.hs
=> stack init: allow local packages to be deps of deps

doc/GUIDE.md, doc/yaml_configuration.md
It lacked some crucial information to understand the behavior unambiguously.
Also, organized it systematically.
Please review for correctness and style.
=> Update the packages section of yaml config guide

src/main/Main.hs
`stack image container` image names as options (not arguments)
=> options not args (& hindent johan-tibell 4 spaces)

src/Stack/Options.hs
=> add a flag for --verbosity silent

ChangeLog.md, src/Stack/Docker.hs, stack.cabal
=> v1.0.4.3 hotfix for deletion of ~/.ssh

src/Data/Attoparsec/Interpreter.hs, src/test/Stack/ArgsSpec.hs
Stack's script interpreter currently rejects directives inside (literate Haskell) Bird tracks:
```
% stack --version
Version 1.0.5, Git revision ffb318a7360e1c6083626dfc42dd73c2e7b397cb (dirty) (3453 commits) x86_64 hpack-0.12.0
% cat > Fail.lhs
#! /usr/bin/env stack
> -- stack --resolver lts-5.3 --install-ghc runghc --package random
> import System.Random; main = randomIO >>= (print :: Int -> IO ())
% chmod +x Fail.lhs; stack exec -- ./Fail.lhs
stack: WARNING! Expecting stack options comment at line 2, column 1
stack: WARNING! Missing or unusable stack options specification
stack: WARNING! Using runghc without any additional stack options
[..]
```
It is possible to get this working by placing the directives inside a prose comment..
```
% cat > Okay.lhs
#! /usr/bin/env stack
-- stack …
```
=> Extended the interpreter to admit interpreter directives in Bird tracks

src/Stack/Setup.hs, src/Stack/Setup/Installed.hs
Addresses #1587.
Note: tested only on 64-bit Windows.
=> Architecture-aware Windows MSYS2 path/env config 

stack.cabal, stack.yaml
https://github.com/fpco/stackage/issues/1392
=> Usr hpack-0.13

src/Data/Aeson/Extended.hs, src/Data/Monoid/Extra.hs, src/Options/Applicative/Builder/Extra.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Config.hs, src/Stack/Config/Build.hs, src/Stack/Config/Docker.hs, src/Stack/Config/Nix.hs, src/Stack/Config/Urls.hs, src/Stack/Options.hs, src/Stack/Setup.hs, src/Stack/Setup/Installed.hs, src/Stack/Types/Config.hs, src/Stack/Types/Config/Build.hs, src/Stack/Types/Docker.hs, src/Stack/Types/Image.hs, src/Stack/Types/Internal.hs, src/Stack/Types/Nix.hs, src/Stack/Types/Urls.hs, src/Stack/Types/Version.hs, src/Stack/Upgrade.hs, stack.cabal
This PR is purely about using `generic-deriving` to derive `Monoid` instances and shouldn't introduce any behaviour changes.
See #2078 for a short discussion.
=> Derive various Monoid instances with generic-deriving

mkdocs.yml
=> docs: Add permalinks to headings

stack.cabal, stack.yaml
https://github.com/fpco/stackage/issues/1428
=> Support hpack-0.14.0

doc/docker_integration.md
According to [here](https://github.com/commercialhaskell/stack/blob/47759559222cc501b5e2bbd0080963cc3229f489/src/Stack/Types/Docker.hs#L119) and [here](https://github.com/commercialhaskell/stack/blob/47759559222cc501b5e2bbd0080963cc3229f489/src/Stack/Types/Docker.hs#L241).
=> Fix typo: persistent -> persist

doc/faq.md
=> One back tick too much

doc/GUIDE.md
=> Docs: Cite package name rules in section for `stack new`

doc/yaml_configuration.md
=> Edit "Yaml Configuration" page in documention

doc/GUIDE.md
Added a description of how to use your own templates with stack in the docs.
=> Added section about own templates to GUIDE.md

ChangeLog.md, src/Stack/Solver.hs, src/Stack/Types/Config.hs
Fixes #2252.
@harendra-kumar: Could you take a look?
=> Detect resolver change in `stack solver`

src/main/Main.hs, stack.cabal
I had some difficulty figuring out the types in `interpreterHandler`, and therefore added the type annotations.
Given the small size of the change, I'll simply merge this myself if the tests pass.
=> Main.interpreterHandler: Add some type annotations

src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Source.hs, src/main/Main.hs
=> Improve debug logging for `stack build` (#2348)

src/Stack/Hoogle.hs, src/Stack/IDE.hs, src/Stack/Path.hs, src/Stack/Runners.hs, src/Stack/SetupCmd.hs, src/main/Main.hs, stack.cabal
The main motivation for this is faster builds.
=> Move code for path, setup, hoogle commands and various withXConfig utils from Main into separate modules

doc/yaml_configuration.md
=> Document urls options

doc/faq.md
=> Add FAQ entry regarding system library installation (#1384)

Setup.hs
As requested in #2450.
This PR does not switch to Template Haskell yet, that should be a separate PR.
=> List transitive deps in --version (#2450)

src/Stack/Nix.hs
In response to https://github.com/commercialhaskell/stack/issues/2435
For packages with splitted outputs, this solves the need to include both `zlib.out` & `zlib.dev` or
`ncurses.out` & `ncurses.dev` in `packages:` in stack.yaml
Now, you can just put the package name in yout stack.yaml, and the right output will be found by nix.
=> Using nix native functions to retrieve derivation output paths

src/main/Main.hs
=> Revert back to using runghc instead of "ghc -e"

.travis.yml
This caused the CI failure in https://github.com/commercialhaskell/stack/pull/2537#issuecomment-243173996.
=> Travis: Use ~/.local/bin/stack instead of ~/.cabal/bin/stack in cabal builds

src/Stack/Setup.hs
This should resolve https://github.com/commercialhaskell/stack/issues/1714
Prior, if you were using system ghc, no msys check was performed. Now, if you're using system ghc but `getInstalledTool installed $(mkPackageName "msys2") (const True) ` does not yield an msys, then you get an issue.
So a build of network with this PR now seems to bring up a message "Continuing despite missing tool: msys2" whereas before there was no warning. And now when one runs "stack setup" and it determines the system ghc is present, it doesn't bail early, but also goes and installs msys regardless.
This behavior could arguably be a bit better (with a warning instead of bailing on not finding msys) but at least teaching people to run "stack setup" is easy enough. Also it could try to be more clever about …
=> eager msys windows check

ChangeLog.md, src/Stack/ConfigCmd.hs, src/Stack/Options.hs, src/Stack/Types/Config.hs
This change adds the fields suggested in https://github.com/commercialhaskell/stack/pull/2537#issuecomment-243423410 and https://github.com/commercialhaskell/stack/pull/2537#issuecomment-243427665.
=> Extend `stack config set` with `system-ghc` and `install-ghc` options

src/Stack/Setup.hs, src/System/Process/Read.hs
=> Fix master build on 7.8 and 8.0

src/main/Main.hs
`ghc-mod` told me so.
Is there some way for the Travis build to complain about this stuff or it's already covered from the `script:` commands? In the case it is not, it could be [allowed to fail](https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail) in case it's too much overhead. I could submit a PR?
=> ghc-mod recommendation refactoring

doc/architecture.md, doc/build_command.md, doc/dependency_visualization.md, doc/faq.md, doc/ghcjs.md, doc/nonstandard_project_init.md, doc/shell_autocompletion.md, doc/yaml_configuration.md
Follow on from #2573 and https://github.com/commercialhaskell/stack/pull/2573#issuecomment-246517282.
`[ci skip] [build skip]`
=> Wrap some docs to 80 chars.

src/Stack/Upload.hs, stack-7.8.yaml, stack-8.0.yaml, stack.cabal, stack.yaml
Inspired by @blaisorblade's previous comments, I enriched the
http-client-tls API a bit.
=> Display more useful digest auth failures

src/Data/Attoparsec/Interpreter.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Source.hs, src/Stack/BuildPlan.hs, src/Stack/Config.hs, src/Stack/Docker.hs, src/Stack/Dot.hs, src/Stack/Ghci.hs, src/Stack/Hoogle.hs, src/Stack/Init.hs, src/Stack/Nix.hs, src/Stack/Options/DotParser.hs, src/Stack/Package.hs, src/Stack/PackageIndex.hs, src/Stack/Setup.hs, src/Stack/Solver.hs, src/Stack/Types/Build.hs, src/Stack/Types/Internal.hs, src/Stack/Types/Version.hs, src/System/Process/Log.hs, src/System/Process/Run.hs, src/main/Main.hs, src/test/Stack/ArgsSpec.hs, src/test/Stack/ConfigSpec.hs, src/test/Stack/SolverSpec.hs, test/integration/IntegrationSpec.hs, test/integration/lib/StackTest.hs
Working on something for https://github.com/commercialhaskell/stack/issues/2592.
I'm trying to keep the patches smaller by focusing on a single hlint suggestion at a time. Sorry about the whitespace noise, my `$EDITOR`/`hlint --refactor --refactor-options -i` did it.
=> hlint and me: remove redundant brackets

src/Stack/PackageIndex.hs
Fix #2602. I only did some quick testing yet.
=> Reclone all-cabal-hashes if --unshallow fails

src/Stack/Build/Cache.hs, src/Stack/Build/Execute.hs, src/Stack/BuildPlan.hs, src/Stack/Dot.hs, src/Stack/Ghci.hs, src/Stack/Init.hs, src/Stack/Solver.hs, src/Stack/Types/BuildPlan.hs, src/Stack/Types/Config.hs, src/Stack/Types/Package.hs, src/Stack/Types/PackageIndex.hs, src/Stack/Upload.hs, src/Text/PrettyPrint/Leijen/Extended.hs, test/integration/tests/module-added-multiple-times/Main.hs, test/integration/tests/skip-unreachable-dirs/Main.hs
Follow on from  #2606 and working on #2592. 
Covers:
Lots of formatting noise on this one too :bomb:.
=> More hlint suggested clean ups

HLint.hs, src/Options/Applicative/Builder/Extra.hs, src/Stack/Build/Cache.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Installed.hs, src/Stack/BuildPlan.hs, src/Stack/Config/Docker.hs, src/Stack/Constants.hs, src/Stack/Docker.hs, src/Stack/Ghci.hs, src/Stack/Ghci/Script.hs, src/Stack/Init.hs, src/Stack/Nix.hs, src/Stack/PackageDump.hs, src/Stack/Setup.hs, src/Stack/Solver.hs, src/Stack/Types/Build.hs, src/System/Process/Run.hs, src/test/Network/HTTP/Download/VerifiedSpec.hs, src/test/Stack/PackageDumpSpec.hs, test/integration/lib/StackTest.hs, test/integration/tests/1336-1337-new-package-names/Main.hs, test/integration/tests/1337-unicode-everywhere/Main.hs
Some questionable, some not. Shout and I will ignore them. 
Refer to [HLint manual](http://community.haskell.org/~ndm/darcs/hlint/hlint.htm) for configuration/ignore syntax.
Nearly there. Just another PR to go and then #2591 can move forward.
Ref: https://github.com/commercialhaskell/stack/issues/2592
=> Resolve HLint 'Use Foo' hints

.travis.yml, src/test/Network/HTTP/Download/VerifiedSpec.hs, src/test/Stack/PackageDumpSpec.hs
If something goes wrong, fail faster.
=> Add `fast_finish` for Travis. Add fixups for #2659.

HLint.hs, src/Data/Attoparsec/Interpreter.hs, src/Stack/Build/Cache.hs, src/Stack/Build/Execute.hs, src/Stack/BuildPlan.hs, src/Stack/Dot.hs, src/Stack/Ghci/Script.hs, src/Stack/Init.hs, src/Stack/Options/BuildParser.hs, src/Stack/Package.hs, src/Stack/PackageDump.hs, src/Stack/Setup.hs, src/Stack/Solver.hs, src/Stack/Types/BuildPlan.hs, src/Stack/Types/Config.hs, src/Stack/Types/Docker.hs, src/Stack/Types/Internal.hs, src/Text/PrettyPrint/Leijen/Extended.hs, src/main/Main.hs, src/test/Stack/NixSpec.hs, test/integration/tests/32-unlisted-module/files/src/Main.hs
~~I wasn't sure about the duplications (which I suppressed - will revisit).~~ Ignored.
~~Just dropping this one here for now.~~
~~Needs a rebase over changes in #2688 to get a clean Travis run.~~
Next is #2591!
=> Final HLint pass

CONTRIBUTING.md
As asked by @Blaisorblade in https://github.com/commercialhaskell/stack/pull/2591#issuecomment-246676805.
Added to the [Contribution guide](https://docs.haskellstack.org/en/stable/CONTRIBUTING/).
Pending the merge of #2690 and #2591.
=> Add HLint related documentation

.travis.yml, CONTRIBUTING.md, HLint.hs
Follow on from https://github.com/commercialhaskell/stack/pull/2588#issuecomment-246670280.
This could potentially take me a while to get right. My bash/travis-fu isn't great.
=> add 'style' environment for travis

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Setup.hs, src/Stack/SetupCmd.hs, src/Stack/Solver.hs
Closes #2647. Hope that covers it.
=> Deprecate `stack-setup-yaml`

etc/scripts/get-stack.sh
=> Add Alpine Linux specific processing

src/Stack/Build/Execute.hs, src/Stack/Build/Source.hs, src/Stack/Ghci.hs, src/Stack/SDist.hs, src/Stack/Types/Package.hs
Coming from https://github.com/commercialhaskell/stack/commit/a11ae47f427b9e34b4b2cea9b88008c7cebc99c3.
Refs:
* https://downloads.haskell.org/~ghc/7.8.1/docs/html/users_guide/constraint-kind.html
=> Unbork master.

src/Stack/Docker.hs
=> Redirect stdout of docker run to stderr

src/Stack/Build.hs
Fix Hlint suggestion and add missing constraint.
=> Unbork master (attempt two) ;)

stack.cabal
It builds fine and seems to work correctly here.
=> Allow unicode-transforms 0.2

src/Stack/Types/BuildPlan.hs, src/Stack/Types/Compiler.hs, src/Stack/Types/FlagName.hs, src/Stack/Types/PackageName.hs, src/Stack/Types/Version.hs, stack-7.8.yaml, stack-8.0.yaml, stack.cabal, stack.yaml
Updates to aeson-1.*.  Some code reduction due to the new general instance for Map!
=> Use aeson-1.*

ChangeLog.md, src/Network/HTTP/Download.hs, src/Stack/Docker.hs, src/Stack/New.hs, src/Stack/Setup.hs, src/Stack/Upgrade.hs, src/main/Main.hs
This PR is not yet complete, please see comments.
=> Allow binary upgrades #1238

stack.yaml
Tested with steps in linked issue.
=> Pin persistent-sqlite to 2.6. Fixes #2824

src/Stack/Build.hs, src/Stack/Build/Installed.hs, src/Stack/PackageDump.hs
Now runs correctly on Linux and OS X. Tested on Ubuntu 16.04 and OS X 10.11.4.
=> Fix DWARF heuristics (closes #2851, #2829)

src/Stack/GhcPkg.hs
This is an improvement of the previous PR I sent #2864. This modifies the code to actually pay attention to exit codes from `ghc-pkg`, so that error conditions here do not go unnoticed. In addition, it properly deals with the case where a directory exists but no package.cache file does. `ghc-pkg init` will fail in that case; this patch uses `ghc-pkg recache` to create that file. While this works, there are two other alternative behaviors:
* For simplicity, just wipe out the entire directory and then call `ghc-pkg init`. This will ensure we get to a totally clean state. However, the idea of performing a recursive directory removal like this is a bit scary, even if it's to something deep inside `.stack-work`
* Clearly some tampering with internal files has happened. We could elect instead …
=> When directory exists, use recache to create db

etc/scripts/get-stack.sh
I ran the get-stack script on a Raspberry PI running Ubuntu MATE
=> Added support for Ubuntu running on ARM

doc/install_and_upgrade.md
=> install_and_upgrade: mention Copr repo for RHEL/Centos

doc/faq.md
9007 is closed as a duplicate of 12759
=> the proper upstream ticket

doc/GUIDE.md
=> Guide: fix directory name `stack-work` -> `.stack-work`

doc/GUIDE.md
=> Fix formatting in user guide

src/Stack/Init.hs
=> Remove trailing slash for package list in `stack.yaml`.

doc/GUIDE.md, doc/MAINTAINER_GUIDE.md, doc/build_command.md, doc/coverage.md, doc/docker_integration.md, doc/faq.md, doc/ghcjs.md, doc/nonstandard_project_init.md, doc/yaml_configuration.md
=> Don't use newlines inside backticks

src/Stack/Solver.hs
Tested by getting expected results from the repro for #2888
=> For stack solver, use old index filename #2888

src/main/Main.hs
Aims to resolve https://github.com/commercialhaskell/stack/issues/2911
=> Failing when using setup --upgrade-cabal with --nix

stack.cabal
Tested by compiling the project.
=> Add a custom-setup section

doc/faq.md
=> Add documentation about getting verbose output from GHC.

doc/faq.md
=> Add small hpack note. Closes #2750.

doc/README.md
=> docs: Fix link to macOS how to install

doc/yaml_configuration.md
=> Corrected subsection links in configuration doc

src/Stack/Script.hs, src/Stack/Types/BuildPlan.hs, src/Stack/Types/Config.hs
=> Add caching for ModuleInfo

.travis.yml, src/Stack/Build.hs, src/Stack/SDist.hs, src/Stack/Types/Build.hs, src/Stack/Types/Config.hs, src/Stack/Types/Config/Build.hs, src/Stack/Types/FlagName.hs, src/Stack/Types/GhcPkgId.hs, src/Stack/Types/Image.hs, src/Stack/Types/PackageIdentifier.hs, src/Stack/Types/Version.hs, src/Stack/Upgrade.hs, src/Stack/Upload.hs, src/System/Process/Read.hs, src/test/Network/HTTP/Download/VerifiedSpec.hs, stack-8.0.yaml
=> Ghc 8.0.2 again

doc/install_and_upgrade.md
=> Docs: mentioned #2577 is fixed since GHC 8.0.2/LTS 8.0

doc/GUIDE.md
=> Add doc for Loading script in ghci

ChangeLog.md, appveyor.yml, doc/yaml_configuration.md, src/Stack/Build.hs, src/Stack/Build/Execute.hs, src/Stack/BuildPlan.hs, src/Stack/Config.hs, src/Stack/Dot.hs, src/Stack/Fetch.hs, src/Stack/Hoogle.hs, src/Stack/PackageIndex.hs, src/Stack/Setup.hs, src/Stack/Types/Config.hs, src/Stack/Types/PackageIndex.hs, src/Stack/Upgrade.hs, src/main/Main.hs, stack.cabal
I've also [sent an email](https://groups.google.com/d/msg/haskell-stack/bTFm6bOhErY/uyTDlpqDBwAJ) to the mailing list to ask for feedback if this change is acceptable.
=> Remove Git-based index support entirely

src/Stack/Config/Build.hs
> Please include the following checklist in your PR:
Built and ran hlint.
=> Fix another hlint suggestion to make Travis happy

ChangeLog.md, src/Stack/Docker.hs
fixes #3092
*I testing this with `stack build --test --bench --haddock`*
=> Nub the list of a user's groups

ChangeLog.md, src/Stack/Build/Execute.hs, src/Stack/Config/Build.hs, src/Stack/Options/BuildMonoidParser.hs, src/Stack/Types/Config/Build.hs, test/integration/tests/haddock-options/Main.hs
Closes #3099
`stack --nix test --flag stack:integration-tests stack:stack-integration-test --test-arguments "-m haddock-options"`
=> Make `haddock --hyperlinked-source` configurable.

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/SDist.hs, src/Stack/Types/Config.hs, src/Stack/Upload.hs, src/main/Main.hs
=> pvp-bounds -revision

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Types/Config.hs, src/Stack/Upload.hs, src/main/Main.hs
=> Upload cleanup, and save-hackage-creds option

doc/yaml_configuration.md
=> Improve the doc on `~/.stack/global-project/stack.yaml`

src/Stack/Init.hs
=> Use https for docs link in default stack.yaml

ChangeLog.md, src/Stack/Script.hs
=> Script on windows

src/Stack/Setup/Installed.hs
Saw [the failure](https://travis-ci.org/commercialhaskell/stack/jobs/231877834#L1407-L1413) on https://github.com/commercialhaskell/stack/pull/3173/commits/9f8eb94dc10151eea0a5e89f3c8ac6a0d7d1026e.
=> Remove name shadowing (fix CI failure)

doc/install_and_upgrade.md
=> Fix reference to Homebrew FAQ on compiling

doc/GUIDE.md
=> Fix GHCi → ghci

ChangeLog.md
@mgsloan in #3205 I haven't rebased before editing changelog, so the entry was for the wrong unreleased version.
=> Fix changelog after #3205

doc/README.md, doc/faq.md, doc/install_and_upgrade.md
=> Website working group changes

stack.cabal
Builds fine and basic function works here.
=> Allow errors 2.2

doc/travis-complex.yml
Fixes #3199
> Please include the following checklist in your PR:
> 
> * [ ] Any changes that could be relevant to users have been recorded in the ChangeLog.md
> * [ ] The documentation has been updated, if necessary.
Not sure this should be documented in the changelog, since the travis.yml template is not part of the stack distribution.
This is how [I do it in temporary](https://github.com/feuerbach/temporary/blob/master/.travis.yml#L192), and it seems to work fine.
=> travis-complex.yml: run tests when building with cabal

ChangeLog.md, src/Stack/Upgrade.hs
=> --git-branch

src/Stack/Snapshot.hs, src/Stack/Types/Resolver.hs
=> Fix relative custom snapshot location parsing

doc/yaml_configuration.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Target.hs, src/Stack/Config.hs, src/Stack/Fetch.hs, src/Stack/Init.hs, src/Stack/PackageIndex.hs, src/Stack/Setup.hs, src/Stack/Snapshot.hs, src/Stack/Types/BuildPlan.hs, src/Stack/Types/Config.hs, src/Stack/Types/PackageIdentifier.hs, src/Stack/Types/PackageIndex.hs, src/Stack/Upgrade.hs, src/test/Stack/StoreSpec.hs
=> Allow specifying cabal file by revision number

.github/ISSUE_TEMPLATE.md
=> Bring Stack version message current in Github template

ChangeLog.md, src/Stack/PackageIndex.hs, src/Stack/Snapshot.hs, src/Stack/StaticBytes.hs, src/Stack/Types/BuildPlan.hs, src/Stack/Types/PackageIdentifier.hs, src/Stack/Types/PackageIndex.hs, src/test/Stack/StaticBytesSpec.hs, stack.cabal
=> Static bytes

src/Stack/Build/Installed.hs, src/Stack/Config.hs, src/Stack/Fetch.hs, src/Stack/PackageIndex.hs, src/Stack/Setup.hs, src/Stack/Setup/Installed.hs, src/Stack/Types/Build.hs, src/Stack/Types/Package.hs
=> Fixes and cleanups

src/Stack/Setup.hs, stack-7.10.yaml, stack-nightly.yaml, stack.cabal, stack.yaml
Candidate fix for #2822. And let me add:
Fixes #416.
~@bonds is testing it.
@bonds: beware that I rebased this PR, hence pull with care! Probably you want to reset to this version.~
=> Check OpenBSD release to determine correct bindist

ChangeLog.md, doc/ghci.md, src/Stack/Ghci.hs, src/Stack/Ghci/Script.hs, src/Stack/Options/GhciParser.hs, src/test/Stack/Ghci/ScriptSpec.hs, src/test/Stack/GhciSpec.hs
=> Have "stack ghci" load modules all at once instead of grouped by pkg #3309

src/Stack/Clean.hs
More informative exception as requested here - https://github.com/commercialhaskell/stack/pull/1649#issuecomment-316919816
=> Better stack clean errors #1649

ChangeLog.md, src/Stack/Snapshot.hs
=> Delete invalid snapshot files #3319

ChangeLog.md, src/Stack/Setup.hs
Not tested, should work, though!  Asking #3243 reporter to try it out.
=> Install alex and happy if needed before booting ghcjs #3243

src/Stack/Types/Build.hs
=> add some help for a confusing error when you have no LICENSE file

stack-7.10.yaml, stack-nightly.yaml, stack.cabal, stack.yaml
=> Allow extra 1.6

ChangeLog.md, src/Stack/Upgrade.hs
=> Improve `stack upgrade --help` messages

doc/GUIDE.md
Small typo fix in the documentation
=> minor documentation fix, --no-executable-stripping

src/Stack/BuildPlan.hs, src/Stack/Ghci.hs, src/Stack/Package.hs, src/Stack/SDist.hs, src/Stack/Snapshot.hs, test/integration/tests/3390-unbuildable-test/Main.hs, test/integration/tests/3390-unbuildable-test/files/files.cabal, test/integration/tests/3390-unbuildable-test/files/src/Lib.hs, test/integration/tests/3390-unbuildable-test/files/stack.yaml, test/integration/tests/3390-unbuildable-test/files/test/Spec.hs
Included a new test case for this. It would be really nice to clean up the package types at some point. Fixes #3390.
=> Unbuildable test stanzas don't cause problems

src/Stack/Build/Target.hs, src/Stack/Snapshot.hs
=> Remove the "implicitly added" messages (closes #3398)

doc/nonstandard_project_init.md
I believe this was the intent of that section, otherwise the wording is rather poor.
=> Fix up Using Cabal file section

etc/scripts/get-stack.sh
=> get-stack.sh linux mint support

Setup.hs
=> Fix a typo in Setup.hs

ChangeLog.md, src/Stack/Build/ConstructPlan.hs, test/integration/lib/StackTest.hs, test/integration/tests/2195-depend-on-exe/Main.hs, test/integration/tests/2195-depend-on-exe/files/files.cabal, test/integration/tests/2195-depend-on-exe/files/stack.yaml
=> Check for deps on exe-only packages #2195

ChangeLog.md, src/Stack/Options/ScriptParser.hs, src/Stack/Script.hs
This should address #3454.
cc: @mgsloan
=> add --ghc-options to stack script

etc/scripts/stack.yaml, src/main/Main.hs, stack-nightly.yaml, stack.cabal, stack.yaml
=> WIP: Manny build updates

src/Stack/Ghci.hs
=> Warn when no targets are used with ghci #3544

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Fetch.hs, src/Stack/Types/Config.hs, test/integration/tests/3520-revision-matching/Main.hs, test/integration/tests/3520-revision-matching/files/.gitignore, test/integration/tests/3520-revision-matching/files/bad-stack.yaml, test/integration/tests/3520-revision-matching/files/good-stack.yaml, test/integration/tests/3520-revision-matching/files/package.yaml, test/integration/tests/3520-revision-matching/files/src/Foo.hs
=> Better errors for 00-index, and ignore-revision-mismatch #3520

ChangeLog.md, src/Stack/Build/Execute.hs
(very) simple implementation of #3552.
=> 3552 log tests complete

doc/GUIDE.md, src/Data/Attoparsec/Interpreter.hs, stack-nightly.yaml
=> Support conduit-extra 1.2.0

ChangeLog.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/SDist.hs, src/Stack/Types/Build.hs
=> Automatically run autoreconf -i when needed #3534

ChangeLog.md, src/Stack/Setup.hs, src/Stack/Types/Config.hs
=> SHA256 support for GHC setup info

src/Path/CheckInstall.hs
Working on prettying up more log/warn/error output in various places.
=> [WIP] colorize warn output in s/P/CheckInstall

src/Stack/Build/Execute.hs, src/Stack/Prelude.hs, src/main/Main.hs, src/test/Stack/PackageDumpSpec.hs, stack-nightly.yaml, stack.yaml
@borsboom Your call if this gets included in Stack 1.6.
=> Support unliftio-0.2.0.0 #3625

ChangeLog.md, src/Stack/SDist.hs
=> Better cabal file checking

.travis.yml, etc/scripts/get-hlint.sh
Something for https://github.com/commercialhaskell/stack/issues/3674.
=> Use binary release of HLint

package.yaml
=> fix links to git repo (for issue tracker and source)

.travis.yml
Not sure if that breaks the build, so I'll test it.
=> Don't include compiler value - we don't use it here

ChangeLog.md, doc/MAINTAINER_GUIDE.md, doc/faq.md, doc/ghcjs.md, doc/nix_integration.md, doc/yaml_configuration.md
This PR fixes a few typos in the documentation. It was generated using https://github.com/tbroadley/github-spellcheck-cli.
=> docs: fix typos

doc/README.md
This adds a few lines explaining how to use ghci when tweaking stack.
CC @mgsloan
=> Add ghci workflow to the documentation

src/Stack/Upgrade.hs
This fixes #3745, I believe.
Maybe there's a good way to actually add a test for this?
=> Clone into tmp dir when upgrading

doc/faq.md
Relates to: #3518 #2712 #3630 #3648
=> faq update: ld errors about recompiling with -fPIC

doc/GUIDE.md
=> Use package.yaml in GUIDE.md

src/Stack/Build/Source.hs, src/Stack/Build/Target.hs, src/Stack/Docker/GlobalDB.hs, src/Stack/Options/Completion.hs, src/Stack/PackageDump.hs, src/Stack/Runners.hs, src/Stack/Solver.hs, src/Stack/StaticBytes.hs, src/main/Main.hs
This should fix the recent Travis style build failures.
=> Fix recent hlint style recommendations

ChangeLog.md, doc/GUIDE.md, doc/stack_yaml_vs_cabal_package_file.md, doc/travis-complex.yml, doc/yaml_configuration.md, mkdocs.yml, src/Stack/Build/Execute.hs, test/integration/tests/no-rerun-tests/Main.hs, test/integration/tests/no-rerun-tests/files/.gitignore, test/integration/tests/no-rerun-tests/files/package.yaml, test/integration/tests/no-rerun-tests/files/stack.yaml, test/integration/tests/no-rerun-tests/files/test/Spec.hs
=> Merge in stable

ChangeLog.md, src/Stack/Snapshot.hs
=> Improved error messages for snapshot parse exceptions

ChangeLog.md, package.yaml, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Installed.hs, src/Stack/Dot.hs, src/Stack/Package.hs, src/Stack/SDist.hs, src/Stack/Types/Package.hs, src/Stack/Types/VersionIntervals.hs, src/test/Stack/DotSpec.hs, stack-nightly.yaml, stack.yaml
=> Switch to Cabal 2.2 (prerelease)

test/integration/README.md
CC @borsboom @mgsloan @DebugSteven
=> Add integration test docs

stack-nightly.yaml, stack.yaml
=> Use patched Cabal to fix #3919

.travis.yml
=> Use travis_wait to avoid getting timed out

package.yaml
=> Add -rtsopts to ghc-options of stack executable

src/Stack/Nix.hs, stack.yaml
Fixes #2944 
Let me know to what release the changelog belongs :)
---
* [ x] The documentation has been updated, if necessary.
=> #2944: Compile Cabal-simple with gmp when using Nix

src/Stack/Package.hs
- Removed a redundant 'WARNING' from the hpack ignoring warning
- Obsessed a bit about the coloration and output of the same warning
Will do some more coloration within the next few days and put it in here. This is basically ready to merge at any time though if there's any hurry to. (Will change this note if that stops being the case)
=> [WIP] Ongoing warning/error/log output fixes and coloration

doc/install_and_upgrade.md
Fixing small typos in documentation.
=> Fix small typos

src/Stack/Config/Nix.hs
Stack only works under NixOS in Nix mode - see #2586. However, it still defaults to `--no-nix`, which means that it's broken by default.
This PR changes that behaviour to always enable Nix mode when running in NixOS.
Tested by running `stack ghci` under Sabayon Linux and NixOS.
=> Enable Nix mode by default when running under NixOS

src/Stack/Build/Execute.hs
This fixes a regression versus the 1.6 branch. @borsboom do you want me to cherry pick this onto the 1.7 branch?
=> Silence warnings from ghc-pkg register

package.yaml, src/Stack/Setup/Installed.hs
fix Travis CI.
I believe that this change will not affect users and will only affect CI results.
However, I'm not sure if it really changes `optP-Wno-nonportable-include-path`.
=> Fix travis

ChangeLog.md, src/Stack/GhcPkg.hs, src/Stack/Setup/Installed.hs
=> Make ghc-pkg calls less noisy

doc/install_and_upgrade.md
See: https://github.com/Homebrew/homebrew-core/blob/master/Aliases/stack
=> Update Homebrew formula name

doc/travis-complex.yml
=> Move to GHC 8.4.3 in travis-complex

src/Stack/PrettyPrint.hs
=> Prettyprinting colors should also have a background that contrasts #4047

doc/appveyor.yml
=> Use a build matrix for AppVeyor

ChangeLog.md, src/Stack/Ghci.hs, src/Stack/Prelude.hs, src/Stack/Setup.hs, src/Stack/Upload.hs
=> Create utilities for prompting, and use for ghci target prompt

doc/yaml_configuration.md
=> docs: Super minor typo fix

ChangeLog.md, package.yaml, src/Data/Monoid/Map.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Config.hs, src/Stack/Types/Config.hs
See #3753 and the PR that this supersedes, https://github.com/commercialhaskell/stack/pull/3781
=> Have project ghc-options append to config.yaml ghc-options #3753

src/Stack/Prelude.hs
=> Another case where some stderr from children leaked through

ChangeLog.md, doc/GUIDE.md, src/Stack/Setup.hs, src/Stack/SetupCmd.hs
=> Deprecate the --upgrade-cabal flag (fixes #4070)

src/Stack/Upgrade.hs
See comment in code.
Compiles, but not yet tested on Windows (in part because my own stack is 'up to date').
=> Fix #3992 Windows 10: Work around upstream git clone issue

ChangeLog.md, doc/GUIDE.md, src/Stack/New.hs, src/Stack/Types/TemplateName.hs, src/main/Main.hs
=> Get stack templates help from Github file #4039

ChangeLog.md, src/Stack/Build/Execute.hs, src/Stack/Prelude.hs
=> Fix invalid "While building Setup.hs" #3934

ChangeLog.md, package.yaml, src/main/Main.hs, stack-nightly.yaml, stack.yaml
=> Switch to githash to include some unmerged bugfixes in gitrev

src/Stack/Build/ConstructPlan.hs
=> Solve one of the failing integration tests from #4142

test/integration/tests/3942-solver-error-output/files/test-stack.yml
=> Bump resolver to lts-11.6 to make test pass by using proper compiler version

.gitignore
=> Expanded .gitignore

doc/README.md
=> Add uninstall section, fixes #4170

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
This introduces three separate issue templates in place of the current single template.
=> Separate issue templates for bugs, questions, and features

subs/pantry/src/Pantry.hs, subs/pantry/src/Pantry/Storage.hs, subs/pantry/src/Pantry/Types.hs
Now `stack build` fails on
```
warningsParserHelper = undefined
```
=> Implement loading from url with caching in SQLite

package.yaml, src/Stack/Package.hs, stack.yaml
=>  Require hpack >= 0.29.6 

ChangeLog.md, appveyor.yml, src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Source.hs, src/Stack/Ghci.hs, src/Stack/Hoogle.hs, src/Stack/Package.hs, src/Stack/SDist.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/Types/Package.hs, src/Stack/Upgrade.hs, src/main/Main.hs, test/integration/lib/StackTest.hs, test/integration/tests/2643-copy-compiler-tool/Main.hs, test/integration/tests/watched-files/Main.hs, test/integration/tests/watched-files/files/.gitignore, test/integration/tests/watched-files/files/Main.hs, test/integration/tests/watched-files/files/package.yaml, test/integration/tests/watched-files/files/stack.yaml
=> Fixes during pantry work

snapshot.yaml, stack-nightly.yaml, stack.yaml
=> Avoid GPL-3 libs haskell/cabal#4883

subs/pantry/package.yaml, subs/pantry/test/Pantry/Internal/StaticBytesSpec.hs
Turned unit tests into property tests, they all still pass and are not significantly slower.
=> Turned unit tests into property tests

src/Stack/Build/Source.hs, src/Stack/Build/Target.hs, src/Stack/Config.hs, src/Stack/Ghci.hs, src/Stack/IDE.hs, src/Stack/Options/Completion.hs, src/Stack/Package.hs, src/Stack/SDist.hs, src/Stack/Solver.hs, src/Stack/Types/Config.hs, src/main/Main.hs, src/test/Stack/ConfigSpec.hs, subs/pantry/pantry.cabal, subs/pantry/src/Pantry.hs, subs/pantry/src/Pantry/Types.hs, subs/pantry/test/Pantry/FileSpec.hs
=> Defer loading of project cabal files

ChangeLog.md, package.yaml, snapshot.yaml, src/Stack/Package.hs, src/Stack/SDist.hs, stack-nightly.yaml, subs/pantry/package.yaml, subs/pantry/pantry.cabal, subs/pantry/src/Pantry/Types.hs
=> Migrate to Cabal 2.4

doc/README.md
=> Update package.yaml, not .cabal file

etc/scripts/with-vagrant.sh, etc/vagrant/centos-6-x86_64/Vagrantfile, etc/vagrant/debian-7-amd64/Vagrantfile, etc/vagrant/debian-7-i386/Vagrantfile, test/integration/tests/cabal-solver/Main.hs
=> Changes to release 1.9

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
=> Revert to having 1.7.1 instead of 1.9.1 in templates

doc/yaml_configuration.md
Just a typo - doesn't need any tests
=> Minor typo

src/Stack/Types/Config.hs
Comparing to other messages, apparently a single quote is missed here.
=> Typo fix. Missing single quote.

ChangeLog.md
=> Fix issue links correctly.

doc/install_and_upgrade.md
[#2240 (comment)](https://github.com/commercialhaskell/stack/issues/2240#issuecomment-438371825)
=> Add http-proxy info in install_and_upgrade.md

src/Stack/Dot.hs, test/integration/tests/4101-dependency-tree/Main.hs
Resolves this: https://github.com/commercialhaskell/stack/pull/4339#discussion_r234820183
=> Print versions of dependencies properly

subs/pantry/src/Pantry.hs
Fixes #4473
* Currently released Stack already does this
=> Switch to FP Complete's Hackage mirror

.azure/azure-nightly-template-osx.yml, .azure/azure-nightly-template-windows.yml, azure-nightly-pipeline.yml, test/integration/IntegrationSpec.hs, test/integration/tests/4095-utf8-pure-nix/Main.hs, test/integration/tests/4105-test-coverage-of-internal-lib/Main.hs, test/integration/tests/4220-freeze-command/Main.hs
=> Nightly builds for Stack

ChangeLog.md, src/Stack/IDE.hs, src/main/Main.hs
See #4482 for commentary.
This is a hand-written merge to avoid conflicts when `stable` gets merged into `master` since the code here has diverged significantly.
=> Add --stdout flag to `stack ide` commands (master version)

src/Stack/Script.hs
Tested locally, do we need a regression test for this?
Fixes #4472
=> Not yet installed packages should be discovered by stack script

ChangeLog.md, src/Stack/Setup.hs
=> Cherry pick FreeBSD 12 fix #4359 from master

ChangeLog.md, src/main/Main.hs
=> Correct the help text corresponding to templates subcommand

src/test/Stack/Types/TemplateNameSpec.hs
=> Fix some hlint warnings

subs/pantry/test/Pantry/ArchiveSpec.hs, test/integration/tests/hpack-repo/Main.hs, test/integration/tests/hpack-repo/files/files.cabal, test/integration/tests/hpack-repo/files/src/Lib.hs, test/integration/tests/hpack-repo/files/stack.yaml
Checklist to fill out when I get there:
=> WIP (DO NOT MERGE YET): Fixing 4377

subs/pantry/src/Pantry/Archive.hs
=> Improve error message on absolute symlinks

subs/curator/src/Curator/Snapshot.hs
Run curator locally with new `build-constraints.yaml` (to be pushed to Stackage soon) and `curator snapshot` no longer complains about not-existent packages.
Continuation of work on #4217
=> Don't include disabled snapshot packages into flags and hidden

subs/curator/src/Curator/Snapshot.hs
=> Broken dependency graph as an error giving error exit code in curator

doc/appveyor.yml, doc/travis-complex.yml
=> Updated CI matrices

ChangeLog.md, src/Stack/Runners.hs, src/Stack/Script.hs
Note the changelog entry, which explains a downside to this approach.
=> Faster compiled scripts

doc/yaml_configuration.md
@afcowie How does this clarification look?
=> doc/yaml_configuration.md: clarify setup-info behaviour

src/Stack/Config.hs, test/integration/tests/override-compiler/Main.hs, test/integration/tests/override-compiler/files/stack.yaml
=> Fix for not working compiler override in stack.yaml

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Source.hs, src/Stack/Types/Compiler.hs
These are unrelated to the changes in your branch, but an hlint upgrade seems to have broken CI for the stable branch.
=> Fix hlint warnings

ChangeLog.md, src/Stack/Setup.hs, src/Stack/SetupCmd.hs, src/Stack/Solver.hs, src/Stack/Types/Version.hs, src/main/Main.hs
=> Remove --upgrade-cabal

test/integration/lib/StackTest.hs, test/integration/tests/3863-purge-command/Main.hs
=> Fix 3863-purge-command integration failure

src/Stack/Config.hs, src/Stack/Runners.hs, src/Stack/Script.hs, src/Stack/Types/Config.hs
=> Cleanup StackYamlLoc

src/Stack/Docker.hs, src/Stack/Nix.hs, src/Stack/Runners.hs, src/main/Main.hs
This set of changes should avoid any behavioral changes fairly obviously. This paves the way to make some less obviously safe changes.
=> Another set of Stack.Runners and related cleanups

test/integration/tests/4101-dependency-tree/Main.hs
Running the integration tests on Azure at:
https://dev.azure.com/commercialhaskell/stack/_build/results?buildId=788
=> Fix integration test for #4101

doc/GUIDE.md
=> Clarify that there is no precompile snapshot

ChangeLog.md, src/Stack/Setup.hs
=> Less verbose stack setup on Windows (fixes #1212)

src/Stack/Init.hs
It's more or less trivial change
=> Fix YAML portion in generated stack.yaml comments

src/Stack/BuildPlan.hs, src/Stack/Init.hs, src/Stack/Snapshot.hs, src/Stack/Solver.hs, src/Stack/Types/BuildPlan.hs, src/Stack/Types/Config.hs, subs/pantry/src/Pantry/Types.hs, subs/pantry/test/Pantry/TypesSpec.hs, test/integration/tests/nice-resolver-names/Main.hs, test/integration/tests/nice-resolver-names/files/.gitignore, test/integration/tests/nice-resolver-names/files/package.yaml
=> Nicer resolver names

ChangeLog.md, src/Stack/Options/ConfigParser.hs, src/Stack/Package.hs, src/Stack/Path.hs, src/Stack/Setup.hs, src/Stack/Types/Build.hs, src/Stack/Types/Config.hs
=> Make libs and includes order-dependent (fixes #4527)

ChangeLog.md, src/Stack/Build/Execute.hs
=> Apply GHC options when building Setup.hs (fixes #4526)

ChangeLog.md, doc/GUIDE.md, doc/appveyor.yml, doc/azure/azure-linux-template.yml, doc/azure/azure-osx-template.yml, doc/azure/azure-pipelines.yml, doc/azure/azure-simple.yml, doc/azure/azure-windows-template.yml, doc/azure_ci.md, doc/faq.md, doc/install_and_upgrade.md, doc/maintainers/ghc.md, doc/maintainers/team_process.md, doc/nonstandard_project_init.md, doc/travis-complex.yml, doc/yaml_configuration.md, etc/dockerfiles/stack-build/README.md, etc/dockerfiles/stack-build/build.sh, etc/dockerfiles/stack-build/lts-12.26/Dockerfile, etc/dockerfiles/stack-build/lts-13.11/Dockerfile, etc/dockerfiles/stack-build/lts-13.3/Dockerfile, etc/scripts/mirror-ghc-bindists-to-github.sh, mkdocs.yml, src/Stack/Docker.hs, src/Stack/Setup.hs, src/main/Main.hs
=> Merge stable into master

ChangeLog.md, src/Stack/Docker.hs
=> Warn on missing PATH in Docker image (fixes #2742)

src/Stack/Build/ConstructPlan.hs
This fixes a limitation where we wouldn't ignore global packages
previously. Fixes #3861
=> Ignore dependencies in snapshot

ChangeLog.md, src/Stack/Build/Execute.hs, src/Stack/Types/Build.hs, test/integration/tests/3861-ignore-bounds-in-snapshots/Main.hs, test/integration/tests/3861-ignore-bounds-in-snapshots/files/.gitignore, test/integration/tests/3861-ignore-bounds-in-snapshots/files/package.yaml, test/integration/tests/3861-ignore-bounds-in-snapshots/files/snapshot.yaml, test/integration/tests/3861-ignore-bounds-in-snapshots/files/stack-bad.yaml, test/integration/tests/3861-ignore-bounds-in-snapshots/files/stack-good.yaml
=> Always exact configuration

src/Stack/Build/ConstructPlan.hs
=> Nicer out-of-range message (fixes #4375)

etc/scripts/get-stack.sh
See #4124 for motivation. @borsboom does this make sense? And does it apply to debian as well?
=> Include netbase on Ubuntu and Debian (fixes #4124)

src/Stack/Script.hs
=> Move stack.yaml config check in script command (fixes #4669)

azure-nightly-pipeline.yml, azure-pipelines.yml
This should hopefully fix cache-s3 issue.
=> Change bucket name 

ChangeLog.md, src/Stack/Docker.hs, src/Stack/Prelude.hs
=> Fix --docker throwing exceptions on expected subcommand failure

.azure/azure-nightly-template-linux.yml, .azure/azure-nightly-template-osx.yml, .azure/azure-nightly-template-windows.yml, ChangeLog.md, etc/scripts/integration-tests.sh, package.yaml, src/Stack/Build/Target.hs, src/Stack/Config.hs, src/Stack/ConfigCmd.hs, src/Stack/Freeze.hs, src/Stack/Options/Completion.hs, src/Stack/Runners.hs, src/Stack/Script.hs, src/Stack/Types/Config.hs, src/main/Main.hs, test/integration/IntegrationSpec.hs, test/integration/tests/2433-ghc-by-version/files/run.sh
* Fixes #3705 
* Fixes #3887 
* Fixes #4699
=> Load up user config when using scripts

subs/curator/src/Curator/Repo.hs
=> Use proper nightly names (with leading zeroes) in commits

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Build/Execute.hs, src/Stack/Config/Build.hs, src/Stack/Options/BuildMonoidParser.hs, src/Stack/Types/Config/Build.hs
=> Use interleaved output by default

CONTRIBUTING.md
=> Add CI build rules to CONTRIBUTING.md

src/test/Stack/ArgsSpec.hs, src/test/Stack/ConfigSpec.hs, src/test/Stack/NixSpec.hs, src/test/Stack/SourceMapSpec.hs
* Turns log level to silent
* Tweaks test names to fit on one line
=> Less chatty tests

src/Stack/Build/Execute.hs, src/Stack/SDist.hs
Prefix package names to test suite output, and right pad package names for alignment.
=> Improved interleaved output

CONTRIBUTING.md, package.yaml, test/integration/IntegrationSpec.hs, test/integration/README.md
It's a bit of a fix for already committed integration test runner updates.
=> Integration tests filter

ChangeLog.md, src/Stack/Build/Execute.hs
=> Disabled the shadowed dependencies workaround (fixes #3554)

ChangeLog.md, src/Stack/Options/TestParser.hs
=> Allow multiple --test-arguments to be passed (fixes #2226)

ChangeLog.md, src/Stack/Ghci.hs, src/Stack/Options/GhciParser.hs, src/main/Main.hs, test/integration/tests/3315-multi-ghc-options/Main.hs
=> stack ghci --ghc-options multi args (fixes #3315)

subs/pantry/src/Pantry/Hackage.hs
=> Ensure cache occurs even with interrupts

subs/pantry/src/Pantry/SQLite.hs
I put together a local repro of the locking bug, tried a number of solutions, and ultimately settled on this one. For posterity, here is how I tested this:
In `Main.hs`:
```haskell
{-# LANGUAGE NoImplicitPrelude, OverloadedStrings #-}
import RIO
import RIO.Process
import Pantry
import Path.IO
data App = App
{ appSimple :: !SimpleApp
, appPantry :: !PantryConfig
}
instance HasLogFunc App where
logFuncL = (lens appSimple undefined).logFuncL
instance HasProcessContext App where
processContextL = (lens appSimple undefined).processContextL
instance HasPantryConfig App where
pantryConfigL = lens appPantry undefined
main :: IO ()
main = runSimpleApp $ do
root <- resolveDir' "pantry-dir"
withPantryConfig root defaultHackageSecurityConfig HpackBundled 5 $ \pc -> do
sa <- ask
runRIO (App sa pc) $ …
```
=> Take a lock on the Pantry database for all actions (fixes #4471)

subs/curator/src/Curator/Snapshot.hs, subs/pantry/src/Pantry.hs, subs/pantry/src/Pantry/Types.hs
=> Optional snapshot publication timestamp

subs/curator/src/Curator/Snapshot.hs, subs/pantry/app/Pantry/OldStackage.hs, subs/pantry/src/Pantry/Types.hs
=> Add timestamp during conversion

src/Stack/SourceMap.hs, src/Stack/Types/Config.hs, subs/curator/app/Main.hs, subs/curator/src/Curator/Snapshot.hs, subs/curator/src/Curator/Unpack.hs, subs/pantry/src/Pantry.hs, subs/pantry/src/Pantry/Internal.hs, subs/pantry/src/Pantry/Types.hs, subs/pantry/test/Pantry/GlobalHintsSpec.hs
* loadGlobalHints caches inside the pantry dir
* More Has instances for PantryApp
* Use a Snapshot, not a RawSnapshot, in curator
=> Minor pantry cleanups

subs/curator/app/Main.hs, subs/curator/src/Curator/Constants.hs, subs/curator/src/Curator/Repo.hs
=> Extract github repos into explicit constants

subs/curator/app/Main.hs
Another minor fix for constraints reuse in curator
=> Delete old constraints file befor downloading from Github

subs/pantry/src/Pantry/Types.hs
This minor fix was discussed in Slack
=> No null compiler in snapshot output

ChangeLog.md, src/Stack/Build/Execute.hs, src/Stack/Constants.hs, src/Stack/Types/Build.hs, subs/pantry/package.yaml, subs/pantry/src/Pantry/Internal/Companion.hs, subs/pantry/src/Pantry/SQLite.hs
=> Lock the dist directory (fixes #2730)

src/main/BuildInfo.hs, src/main/Main.hs
This reduces the amount of recompilation that has to happen when
iterating on the code base.
=> Remove CPP and TH in Main module

doc/GUIDE.md, doc/README.md, doc/faq.md, doc/yaml_configuration.md
=> Fix #4726: Improve docs on stack's programs path, on Windows

ChangeLog.md, package.yaml, src/Stack/Runners.hs, src/unix/System/Terminal.hsc, src/windows/System/Terminal.hs
=> Win terminal size

subs/pantry/src/Pantry.hs, subs/pantry/src/Pantry/Types.hs
Thanks to @qrilka for identifying
=> Drop unneeded pliIdent

src/Stack/Storage.hs
=> Remove duplicated words

src/main/Main.hs
@borsboom This addresses #4796. Since it's a bug fix, it should be included in this release, even though we're after code freeze. Can you confirm this is the right branch to merge to (v2.1), and review/merge if so?
=> Reload config files with --file-watch

src/Stack/Prelude.hs, src/unix/System/Permissions.hs
I'll kick off integration tests on this
=> Non atomic write on windows

subs/pantry/src/Pantry/SQLite.hs
This bypasses a very weird SIGBUS error with Docker on OS X, see
comments added in this commit.
=> Avoid resource-pool in storage code

ChangeLog.md, doc/docker_integration.md, src/Stack/Config/Docker.hs, src/Stack/Docker.hs, src/Stack/Options/DockerParser.hs, src/Stack/Types/Docker.hs
I'm targeting the `rc/v2.1` branch since this feature is useful to me right now and it's not a complicated change.  But I'm also happy to rebase it against `master` if we don't want to risk adding it at this stage.
=> Option to set Docker volume mount mode (closes #4692)

doc/docker_integration.md
=> docker_integration.md: update wording of stack-exe compatibility

src/Stack/Types/Config.hs
I still think the original was nicer, but it's easier this way :)
=> Appease hlint

package.yaml
=> Remove unused dependencies

.azure/azure-nightly-template-osx.yml, ChangeLog.md, subs/pantry/src/Pantry/Repo.hs
=> Use --force-local only for Windows

ChangeLog.md, src/Stack/Build/Cache.hs, src/Stack/Build/Execute.hs
=> Do not rerun failed tests

doc/GUIDE.md
Fix https://github.com/commercialhaskell/stack/issues/4831
=> Fix minor typo in docs

ChangeLog.md, package.yaml, src/Stack/Build/Cache.hs, src/Stack/Config.hs, src/Stack/Docker.hs, src/Stack/Nix.hs, src/Stack/Runners.hs, src/Stack/Setup.hs, src/Stack/Storage/Project.hs, src/Stack/Storage/User.hs, src/Stack/Storage/Util.hs, src/Stack/Types/Config.hs, src/test/Stack/ConfigSpec.hs
=> Split up user and project storage (fixes #4893)

subs/pantry/src/Pantry/Repo.hs, test/integration/tests/git-submodules/Main.hs
=> Create tarball such that it works in gnu tar & bsd tar

test/integration/lib/StackTest.hs, test/integration/tests/1438-configure-options/Main.hs, test/integration/tests/1884-url-to-tarball/Main.hs, test/integration/tests/2643-copy-compiler-tool/Main.hs, test/integration/tests/2997-ensure-warnings-output/Main.hs, test/integration/tests/3861-ignore-bounds-in-snapshots/Main.hs, test/integration/tests/3863-purge-command/Main.hs, test/integration/tests/4181-clean-wo-dl-ghc/Main.hs, test/integration/tests/4754-rebuild-haddocks/Main.hs, test/integration/tests/4783-doctest-deps/Main.hs, test/integration/tests/copy-bins-works/Main.hs
=> Fix Windows integration test suite

ChangeLog.md
=> Changelog fixup

etc/scripts/get-stack.sh
Inform user about '-d DESTDIR' option to install to different location.
=> get-stack.sh: update help text if already installed

ChangeLog.md, snapshot-lts-12.yaml, snapshot-nightly.yaml, snapshot.yaml
=> Upgrade pantry

ChangeLog.md, src/Stack/Hoogle.hs
Tested manually: building hoogle takes some time and also the latest version has some dependency bounds issues.
Fixes #4905
=> Use proper installed Hoogle path

doc/travis-complex.yml
Just a small change; I use an automated script to pull this from stable so this is something that would help me greatly.  Feel free to close if this is not in line with the philosophy of this travis file or documentation.
Thanks!
(Not sure if this checklist applies, since I'm just essentially editing documentation :))
=> update travis-complex.yml to use lts-14 instead of lts-13

ChangeLog.md, src/Stack/Build/Execute.hs, src/Stack/GhcPkg.hs
Fixes #4951
Also includes a minor improvement hint from @lehins
=> Fix GHC version for batched unregistration

ChangeLog.md, src/Stack/Hoogle.hs
Tested locally
@snoyberg this also fixes misplaced changelog from #4958
=> Hoogle from snapshot

ChangeLog.md, doc/lock_files.md, doc/pantry.md, package.yaml, snapshot-lts-12.yaml, snapshot-nightly.yaml, snapshot.yaml, src/test/Stack/LockSpec.hs
=> Don't compare generated cabal files

.azure/azure-nightly-template-windows.yml, etc/scripts/build-stack-installer.hs, etc/scripts/release.hs
=> Build windows installer

snapshot-lts-12.yaml, snapshot-nightly.yaml, snapshot.yaml
=> Bump http-download version

ChangeLog.md, doc/GUIDE.md, src/Stack/Upload.hs
the Probem is described in #5139
=> Issue 5139/credentials by env variables

doc/dependency_visualization.md
=> install Graphviz to get dot binary

doc/maintainers/docker.md, etc/dockerfiles/stack-build/README.md, mkdocs.yml
(cc @jeffhappily @snoyberg @NorfairKing)
=> Add Docker image maintenance documentation

src/Network/HTTP/StackClient.hs, src/Stack/New.hs, src/Stack/Setup.hs
=> 4524 Always use verified downloads

ChangeLog.md, package.yaml, src/Stack/Runners.hs, src/unix/System/Terminal.hsc, src/windows/System/Terminal.hs
=> Remove terminal size

snapshot-lts-11.yaml, snapshot-lts-12.yaml, snapshot-nightly.yaml, src/Network/HTTP/StackClient.hs, src/Stack/New.hs, src/Stack/Setup.hs
=> Fix integration test

.azure/azure-linux-template.yml, .azure/azure-nightly-template-linux.yml, .azure/azure-nightly-template-osx.yml, .azure/azure-nightly-template-windows.yml, .azure/azure-osx-template.yml, .azure/azure-windows-template.yml, azure-nightly-pipeline.yml, doc/azure/azure-linux-template.yml, doc/azure/azure-osx-template.yml, doc/azure/azure-windows-template.yml
=> Nightly pipeline on every pr

.azure/azure-nightly-template-windows.yml, etc/scripts/release.hs
=> Fix makensis exception

src/Stack/Docker.hs
The error was caused by lack of support for leading zeros in Cabal's
Distribution.Version that was used for Docker version parsing. The fix
introduces middle step of parsing the version using Data.Version
and converting it to Distribution.Version. Fix #5193
I tested it by running it on my machine which has Docker version 19.03.8, build afacb8b installed
and observed that the error disappeared after introducing my changes.
=> Fix Docker version parsing error

ChangeLog.md, package.yaml, stack.cabal
=> Bump to v2.4.0

doc/nonstandard_project_init.md
Wrapped the links in Issues Referenced sections in markdown angle
brackets which makes them clickable links in the resulting html.
Tested by visiting each link that was modified.
=> Made all Issues Referenced links clickable

ChangeLog.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Options/BuildParser.hs, src/Stack/Types/Config/Build.hs, test/integration/tests/5272-only-locals/Main.hs, test/integration/tests/5272-only-locals/files/.gitignore, test/integration/tests/5272-only-locals/files/package.yaml, test/integration/tests/5272-only-locals/files/src/Foo.hs, test/integration/tests/5272-only-locals/files/stack.yaml
=> Add the --only-locals flag (closes #5272)

.azure/azure-linux-template.yml, ChangeLog.md, src/Stack/Docker.hs
=> Make stack yaml absolute for Docker

stack-ghc-84.yaml, stack-ghc-88.yaml, stack.yaml
See https://github.com/commercialhaskell/pantry/pull/25
I hope this pr will be the solution of https://github.com/commercialhaskell/stack/issues/5004 .
=> Pantry bump: support multiple relative link like ../../

.github/workflows/unit-tests.yml, stack-ghc-810.yaml
This is the version for `master`.
=> Add stack-ghc-810.yaml and Github Actions job

etc/scripts/get-stack.sh
Pop!_OS uses the same repos and release schedule as Ubuntu, so is largely compatible with Ubuntu packages. Tested locally with:
```sh
$ curl -sSL https://raw.githubusercontent.com/piperswe/stack/8832b19e3e66ffc419d638730ba481e45f62cb17/etc/scripts/get-stack.sh | sh
```
=> Add Pop!_OS compatibility

stack-ghc-810.yaml, stack-ghc-84.yaml, stack-ghc-88.yaml, stack.yaml
=> Bump rio version

doc/README.md, doc/install_and_upgrade.md, doc/maintainers/ghc.md, doc/maintainers/releases.md
=> Stable into master

ChangeLog.md, package.yaml, stack-ghc-810.yaml, stack-ghc-84.yaml, stack-ghc-88.yaml, stack.cabal, stack.yaml
CC @brandon-leapyear for https://github.com/commercialhaskell/pantry/issues/27
=> Handle missing blobs in Pantry cache

.github/workflows/integration-tests.yml, etc/scripts/README.md, etc/scripts/release.hs
Adds to Github Actions workflow, and removes from `release.hs`.
=> Automate signing and uploading stack bindists to Github release

doc/GUIDE.md
This is a followup to #5420. It should contain one commit, updating the user guide.
=> GUIDE: scripting: document --compile, --optimize

src/main/Main.hs
As reported in https://github.com/commercialhaskell/stack/pull/5494/checks?check_run_id=1987494996
Trivial refactor
=> Use fromRight from hlint suggestion

src/Stack/Storage/Project.hs, src/Stack/Storage/User.hs
Tests are passing here with the new dependencies.
=> Fix compatibility with persistent 2.11

ChangeLog.md, stack-ghc-810.yaml, stack-ghc-84.yaml, stack-ghc-88.yaml, stack.yaml
=> Bump pantry for #5509

ChangeLog.md, stack-ghc-810.yaml, stack-ghc-84.yaml, stack-ghc-88.yaml, stack.yaml
=> hi-file-parser bump

ChangeLog.md, src/Stack/Runners.hs
Fixes https://github.com/commercialhaskell/stack/issues/5000
Needs testing /cc @NorfairKing
=> Runners/Nix: allow entering nix-shell from another nix-shell

ChangeLog.md, src/Stack/Setup.hs
=> Use unpacked dir name (fixes 5545)

ChangeLog.md, package.yaml, stack-ghc-88.yaml, stack-nightly.yaml, stack.cabal, stack.yaml
=> Bump pantry version

README.md
=> Update community links

ChangeLog.md, etc/scripts/release.hs, src/Stack/Setup.hs
=> Download from haskellstack.org when possible #5288

doc/yaml_configuration.md
=> Fix broken link to architecture

doc/README.md
This contributes to https://github.com/commercialhaskell/stack/issues/5533
IDK if this should target stable, we can change it if that is not the case.
=> README: add note for windows users, to add stack to the list of trusted applications

doc/GUIDE.md
I find the `stack exec bash` workflow very convenient. Figured it would be helpful for others.
Is updating the changelog necessary for this PR?
=> Suggest using `stack exec` to create a subshell

doc/GUIDE.md
=> Fix typo in GUIDE.md

stack-ghc-902.yaml
=> Bump to lts-19.3 in stack-ghc-902.yaml

stack-ghc-902.yaml
=> Update stack-ghc-902.yaml for pantry-0.5.5

stack-ghc-902.yaml
=> Bump stack-ghc-902.yaml for lts-19.4

doc/build_command.md
Please also shortly describe how you tested your change. Bonus points for added tests! N/A
=> Fix #5722 Document `--keep-tmp-files` option in guide

stack-ghc-902.yaml
=> Bump stack-ghc-902.yaml for lts-19.5

stack-ghc-902.yaml
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using stack.
=> Bump stack-ghc-902.yaml for lts-19.6

stack-ghc-902.yaml
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building stack.
=> Bump stack-ghc-902.yaml for lts-19.7

stack-ghc-902.yaml
=> Bump stack-ghc-902.yaml for lts-19.11

src/Stack/Path.hs
When testing `stack path` for https://github.com/commercialhaskell/stack/issues/3446 I noticed that stack was doing (relatively) slow IO multiple times, and tracked it back to the `runHaddock` calls, which in both instances are loading the configuration for each call. Running `stack path --compiler-bin --verbose` on stack itself I get this output on v2.7.3:
```
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
2021-12-05 10:14:04.265641: [debug] Checking for project config at: /home/dan/projects/stack/stack.yaml
2021-12-05 10:14:04.266509: [debug] Loading project config file stack.yaml
2021-12-05 10:14:04.282529: [debug] (SQL) SELECT COUNT(*) FROM "last_performed" WHERE ("action"=?) AND ("timestamp">=?); [PersistInt64 1,PersistUTCTime 2021-12-04 …
```
=> Avoid doing slow IO twice when running `stack path`

stack-ghc-902.yaml
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building Stack.
=> Bump stack-ghc-902.yaml for lts-19.16

doc/yaml_configuration.md
This also reorganises the order of the some of the existing content. It is not intended to make any substantive change to the existing content, only to further document Stack's behaviour.
=> Extend documentation of setup-info etc

doc/GUIDE.md
Principally conforms the use of 'Stack', when not referring to specific commands.
=> Tidy up GUIDE.md

src/Stack/Setup.hs
=> Pass 'with-gcc:' specified compiler to 'stack setup', fixes #5493

ChangeLog.md, etc/scripts/get-stack.sh
The fix was relatively simple and did not change intended functionality so I did not conduct any tests. Fixes #5792
=> Fix get_isa logic

README.md
Show the badges as before but also link to the tests.
=> Link to unit tests and integration tests.

src/Stack/Init.hs, src/Stack/Storage/Project.hs, src/Stack/Storage/User.hs, src/Stack/Storage/Util.hs
See https://downloads.haskell.org/~ghc/9.4.1-alpha2/docs/users_guide/9.4.1-notes.html#language
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building Stack with GHC 9.4.1.
=> Fix warnings when built with GHC 9.4.1

ChangeLog.md, doc/GUIDE.md, doc/README.md, src/main/Main.hs
The information is tailored to the configuration and operating system.
Also updates the online guidance.
=> Make `stack uninstall` informative

doc/GUIDE_advanced.md
Additions to the documentation only.
=> Update master docs for `stack ls tools`

src/Stack/ConfigCmd.hs, src/main/Main.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack.
=> Fix help for `stack config`

doc/nix_integration.md, doc/yaml_configuration.md
Aims to improve structure, reduce duplication and increase consistency.
=> Tidy up the Nix integration documentation

src/Stack/Path.hs
Fixes all the `stack path` options that need to be run 'using Haddock'.
This essentially reverses #5645. It turns out that two separate `Config` are required, in order for each `EnvConfig` to be created correctly.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack with a simple `stack new myProject` project.
=> Fix #5840 `stack path --local-doc-root` returns correct path

src/Stack/Build/Execute.hs, src/Stack/PackageDump.hs, src/Stack/Setup.hs, test/integration/tests/stackage-3185-ignore-bounds-in-snapshot/files/README.md
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack, including the setup of a new version of GHC.
=> Fix #5482 Update references to `fpco` repositories involving redirection

src/Stack/Lock.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building Stack and using it with a lock file that is not valid YAML (and also a valid one).
=> Fix #5846 Report file name when a lock file not parsed

src/test/Stack/ConfigSpec.hs, src/test/Stack/NixSpec.hs
=> Bump two Spec tests for more recent LTS/GHC

.github/workflows/integration-tests.yml
Also tries to fix artifacts being uploaded to 'wrong' draft GitHub release.
=> Fix #5868 Try to repair trigger of steps in workflow

etc/scripts/release.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on CI to test.
=> Fix release.hs on Windows

.github/workflows/integration-tests.yml
This pull request is draft while I investigate the CI.
=> Fix #5895 Fix integration tests on macOS

ChangeLog.md, src/main/Main.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack.
=> Extend in-tool help for `stack upgrade`

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Types/Config.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack on Windows 11.
=> Fix #5870 Introduce package-index key

test/integration/tests/git-submodules/Main.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on CI to test CI.
=> Fix #5908 Set `protocol.file.allow always` in `git-submodules` test

doc/maintainers/stack_errors.md
=> Re #5911 Inventory of Stack's errors

doc/maintainers/stack_errors.md, src/Stack/Config.hs, src/Stack/Constants.hs, src/Stack/Types/Config.hs
=> RE #5911 Tidy up exceptions in Stack.Config

doc/maintainers/stack_errors.md, src/Stack/ConfigCmd.hs
=> Re #5911 Tidy up exceptions in Stack.ConfigCmd

doc/maintainers/stack_errors.md, src/Stack/Setup.hs
=> Re #5911 Tidy up exceptions in Stack.Setup

stack-macos.yaml, stack-macos.yaml.lock
=> Try bump to process-1.6.16.0 on macOS

doc/maintainers/stack_errors.md, src/Stack/Runners.hs
=> Re #5911 Tidy up exceptions in Stack.Runners

doc/maintainers/stack_errors.md, src/Stack/Config/Nix.hs
=> Re #5911 Tidy up exceptions in Stack.Config.Nix

doc/maintainers/stack_errors.md, src/Stack/Init.hs
=> Re #5911 Tidy up exceptions in Stack.Init

doc/maintainers/stack_errors.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Haddock.hs, src/Stack/BuildPlan.hs, src/Stack/Types/Build.hs
=> Re #5911 Tidy up exceptions in Stack.Build.x and Stack.BuildPlan

doc/maintainers/stack_errors.md, src/Stack/Clean.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on the CI.
=> Re #5911 Tidy up exceptions in Stack.Clean

doc/maintainers/stack_errors.md, src/Stack/Storage/User.hs
=> Re #5911 Tidy up exceptions in Stack.Storage.User

doc/maintainers/stack_errors.md, src/Stack/Script.hs
=> Re #5911 Tidy up exceptions in Stack.Script

doc/maintainers/stack_errors.md, src/Stack/Dot.hs, src/Stack/Lock.hs, src/Stack/Package.hs, src/Stack/Types/Build.hs, src/Stack/Types/Package.hs, src/Stack/Types/TemplateName.hs, src/Stack/Upgrade.hs
=> Re #5911 Tidy up exceptions in various modules

doc/maintainers/stack_errors.md, src/Stack/Prelude.hs, src/Stack/Setup.hs, src/main/Main.hs
=> Re #5911 Add pretty exceptions and use in Stack.Setup

doc/maintainers/stack_errors.md, src/main/Main.hs
=> Re #5911 Tidy up exceptions in Main.hs

doc/maintainers/stack_errors.md, src/Stack/Setup.hs, src/Stack/Upload.hs
=> Re #5911 Tidy up exceptions in Stack.Upload

package.yaml, src/Stack/Prelude.hs, stack-macos.yaml, stack-macos.yaml.lock, stack.cabal, stack.yaml, stack.yaml.lock
Please also shortly describe how you tested your change. Bonus points for added tests! Built and used Stack on Windows. Relying on CI for rest.
=> Bump to rio-prettyprint-0.1.3.0, for `PrettyException`

doc/maintainers/stack_errors.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Prelude.hs, src/Stack/Types/Build.hs, src/Stack/Types/Config.hs, src/Stack/Types/Version.hs, src/Stack/Upload.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack generating error [S-4804].
=> Fix #5944 Make Stack Error: [S-4804] pretty

etc/scripts/release.hs, src/Stack/Build/Execute.hs, src/Stack/Prelude.hs, src/Stack/Setup.hs, src/Stack/Types/Build.hs, src/main/Main.hs, test/integration/tests/1438-configure-options/Main.hs, test/integration/tests/3942-solver-error-output/Main.hs
Also takes into account configured Stack colours, and adds a helper `blankLine`.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building Stack and using on Windows. Relying on CI for other operating systems.
=> Pretty Error: S-7282, S-7011, S-6374

doc/maintainers/stack_errors.md, src/Stack/Config.hs, src/Stack/Prelude.hs, src/Stack/Setup.hs, src/Stack/Storage/Project.hs, src/Stack/Storage/User.hs, src/Stack/Storage/Util.hs, src/Stack/Types/Build.hs, src/Stack/Types/Config.hs, src/Stack/Types/Storage.hs, src/Stack/Upload.hs, src/main/Main.hs, stack.cabal
Also updates the error documentation, generally.
Also conforms the Haddock documentation of pretty exceptions in various modules.
Also refactors some import lists, in passing, with a longer term view to a more consistent approach.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building on Windows. Relying on CI for other operating systems.
=> Fix Pantry #58 Handle [S-536] in Stack

doc/maintainers/stack_errors.md, src/Stack/Init.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack on Windows, but also relying on the CI.
=> Re #5955 Prettier Stack.Init exceptions

package.yaml, src/Stack/Prelude.hs, stack.cabal, stack.yaml, stack.yaml.lock
Please also shortly describe how you tested your change. Bonus points for added tests! Built and used Stack on Windows. Relying on CI.
=> Bump to rio-prettyprint-0.1.4.0

doc/maintainers/stack_errors.md, src/Network/HTTP/StackClient.hs, src/Stack/BuildPlan.hs, src/Stack/Constants.hs, src/Stack/Init.hs, src/Stack/New.hs, src/Stack/Prelude.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using on Windows. Relying on CI for other operating systems.
=> Fix #5955 Prettier `stack new` exceptions

doc/maintainers/stack_errors.md, src/Stack/BuildPlan.hs, src/Stack/Init.hs, src/Stack/Types/Build.hs, src/Stack/Types/Config.hs
=> Re #5955 Prettier NoMatchingSnapshot, ResolverMismatch, ResolverPartial

src/Stack/Config.hs, src/Stack/Docker.hs, src/Stack/Init.hs, src/Stack/Types/Config.hs, src/Stack/Types/Version.hs, src/Stack/Upgrade.hs, src/main/BuildInfo.hs, src/main/Main.hs
Also reformats some import lists, long lines and function signatures.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack on Windows. Relying on CI for other operating systems.
=> Use `stackVersion` consistently

src/Data/Monoid/Map.hs, src/Path/CheckInstall.hs, src/Stack/Config/Build.hs, src/Stack/Config/Docker.hs, src/Stack/Options/BuildParser.hs, src/Stack/Options/DotParser.hs, src/Stack/Options/ExecParser.hs, src/Stack/Options/GhciParser.hs, src/Stack/Options/NewParser.hs, src/Stack/Options/NixParser.hs, src/Stack/Options/SDistParser.hs, src/Stack/Options/TestParser.hs, src/Stack/Types/Docker.hs, src/Stack/Types/Nix.hs, src/Stack/Types/Package.hs
Also, some reformatting of the same modules
=> Add export lists

src/Options/Applicative/Args.hs, src/Stack/Config/Nix.hs, src/Stack/Constants.hs, src/Stack/GhcPkg.hs
Also, some reformatting of same modules.
Please also shortly describe how you tested your change. Bonus points for added tests! Built on Windows; relying on CI.
=> Add explicit import lists

cabal.config, package.yaml, src/Stack/Storage/Util.hs, stack-ghc-9.4.3.yaml, stack-ghc-9.4.3.yaml.lock, stack.cabal, stack.yaml, stack.yaml.lock
Also adds explicit import list to Stack.Storage.Util.
=> Fix #5984 Move Stack to persistent-2.14.4.3

src/Stack/Setup.hs
My idea is that the default `setup-info` dictionary will continue to use the `linux64-tinfo6` key for Linux distributions that can support `libc6` 2.32 (eg Fedora >= 33 (2.32), Ubuntu 22.04 (2.35)) and will provide a new `linux64-tinfo6-libc6-pre2.32` for Linux distributions that can only support `libc6` < 2.32 (eg Debian 10 (up to 2.28), Debian 11/Ubuntu 20.04 (up to 2.31), Fedora 27 (up to 2.26)). `linux64-tinfo6` and `linux64-tinfo6-libc6-pre2.32` will be the same pre-GHC 9.4.x. From GHC 9.4, `linux64-tinfo6` will use the 'Fedora 33' version of GHC and `linux64-tinfo6-libc6-pre2.32` will use the 'Debian 10' version of GHC.
Please also shortly describe how you tested your change. Bonus points for added tests! I am unable to test this idea. I rely on Linux users to comment.
=> Fix #5881 Add tag if supports only libc6 < 2.32

doc/maintainers/stack_errors.md, src/Stack/Build/Target.hs, src/Stack/Ghci.hs, src/Stack/Types/Build.hs
=> Prettier target parse errors

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml, package.yaml, stack.cabal, stack.yaml, stack.yaml.lock
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building Stack, but also relying on CI.
=> Fix #5885 Move Stack to Cabal-3.8.1.0

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on CI to test CI.
=> Fix/check adding to PATH on Windows in CI

.hlint.yaml, src/Path/Extra.hs, src/Stack/Build/Cache.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Source.hs, src/Stack/ComponentFile.hs, src/Stack/Config.hs, src/Stack/ConfigCmd.hs, src/Stack/Constants/Config.hs, src/Stack/Coverage.hs, src/Stack/Ghci.hs, src/Stack/Init.hs, src/Stack/New.hs, src/Stack/Package.hs, src/Stack/PackageDump.hs, src/Stack/PackageFile.hs, src/Stack/SDist.hs
GHC 7.8 compatibility is no longer a consideration.
=> Apply hlint 'Use fmap'

.github/workflows/lint.yml, .hlint.yaml, src/Network/HTTP/StackClient.hs, src/Options/Applicative/Builder/Extra.hs, src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Source.hs, src/Stack/ComponentFile.hs, src/Stack/Coverage.hs, src/Stack/Dot.hs, src/Stack/Hoogle.hs, src/Stack/Init.hs, src/Stack/Nix.hs, src/Stack/Options/Completion.hs, src/Stack/Package.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/Types/Build.hs, src/Stack/Types/Config.hs, src/Stack/Upgrade.hs, src/Stack/Upload.hs, src/System/Process/Pager.hs, test/integration/tests/3315-multi-ghc-options/files/src/Lib.hs, test/integration/tests/335-multi-package-flags/files/src/Lib.hs, test/integration/tests/796-ghc-options/files/src/Lib.hs, test/integration/tests/git-submodules/Main.hs
The hints once considered not useful do appear to be useful when applied to Stack's current code.
=> Increase scope of, and apply, HLint suggestions

Setup.hs, package.yaml, src/test/Spec.hs, src/test/Stack/ArgsSpec.hs, src/test/Stack/Build/ExecuteSpec.hs, src/test/Stack/Build/TargetSpec.hs, src/test/Stack/Config/DockerSpec.hs, src/test/Stack/ConfigSpec.hs, src/test/Stack/DotSpec.hs, src/test/Stack/Ghci/ScriptSpec.hs, src/test/Stack/GhciSpec.hs, src/test/Stack/LockSpec.hs, src/test/Stack/NixSpec.hs, src/test/Stack/PackageDumpSpec.hs, src/test/Stack/Types/TemplateNameSpec.hs, src/test/Stack/UploadSpec.hs, stack.cabal, test/integration/lib/StackTest.hs
=> Use export lists

src/Network/HTTP/StackClient.hs, src/Options/Applicative/Builder/Extra.hs, src/Path/CheckInstall.hs, src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Source.hs, src/Stack/Build/Target.hs, src/Stack/BuildPlan.hs, src/Stack/ComponentFile.hs, src/Stack/Config.hs, src/Stack/Docker.hs, src/Stack/Dot.hs, src/Stack/Ghci.hs, src/Stack/Hoogle.hs, src/Stack/Init.hs, src/Stack/Lock.hs, src/Stack/New.hs, src/Stack/SDist.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/Setup/Installed.hs, src/Stack/Types/Build.hs, src/Stack/Upload.hs, src/main/Main.hs, src/unix/System/Permissions.hs, src/windows/System/Terminal.hs
=> Other Hlint suggestions which appear sensible

src/Stack/Config/Nix.hs, src/Stack/Setup.hs
=> Alternatives to `case () of` structures

doc/maintainers/stack_errors.md, src/Path/CheckInstall.hs, src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Haddock.hs, src/Stack/Config.hs, src/Stack/ConfigCmd.hs, src/Stack/Coverage.hs, src/Stack/Docker.hs, src/Stack/GhcPkg.hs, src/Stack/Ghci.hs, src/Stack/Hoogle.hs, src/Stack/Init.hs, src/Stack/New.hs, src/Stack/PackageDump.hs, src/Stack/Prelude.hs, src/Stack/Runners.hs, src/Stack/SDist.hs, src/Stack/Setup.hs, src/Stack/Setup/Installed.hs, src/Stack/SourceMap.hs, src/Stack/Types/Build.hs, src/Stack/Types/Config.hs, src/Stack/Types/Storage.hs, src/Stack/Upload.hs, src/main/Main.hs, src/test/Stack/PackageDumpSpec.hs, test/integration/tests/1198-multiple-exes-with-same-name/Main.hs, test/integration/tests/3940-base-upgrade-warning/Main.hs
Some testing done by building and using Stack on Windows, while trying to trigger various warning messages.
=> Make all existing logWarn messages pretty

ChangeLog.md, doc/maintainers/stack_errors.md, src/Stack/Config.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Types/Config.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack.
=> Fix #6014 Improve error message for invalid STACK_WORK/--work-dir

src/Stack/Build/Target.hs, src/Stack/Types/Build.hs
=> Fix #6018 Better error messages for target parse failures

.github/workflows/integration-tests.yml, ChangeLog.md, doc/environment_variables.md, src/Stack/Constants.hs, src/Stack/New.hs
=> Fix #6034 Allow authenticated requests to GitHub REST API

doc/maintainers/stack_errors.md, src/Stack/Lock.hs
=> Prettier error S-1353

doc/maintainers/stack_errors.md, src/Stack/Prelude.hs, src/Stack/Setup.hs, src/Stack/Types/Build.hs
=> Prettier errors S-2476 and S-4764

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Target.hs, src/Stack/Config.hs, src/Stack/Ghci.hs, src/Stack/Hoogle.hs, src/Stack/Init.hs, src/Stack/Lock.hs, src/Stack/New.hs, src/Stack/Prelude.hs, src/Stack/Setup.hs, src/Stack/Storage/Util.hs, src/Stack/Upload.hs, src/main/Main.hs
=> Add prettyThrowIO and prettyThrowM to Stack.Prelude

doc/maintainers/stack_errors.md, src/Stack/Build/Execute.hs, src/Stack/Types/Build.hs
=> Re #6046 Fix S-6739 error

ChangeLog.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Types/Config.hs, test/integration/tests/6046-missing-sublib-unregister/Main.hs, test/integration/tests/6046-missing-sublib-unregister/files/foo.cabal1, test/integration/tests/6046-missing-sublib-unregister/files/foo.cabal2, test/integration/tests/6046-missing-sublib-unregister/files/src/Lib.hs, test/integration/tests/6046-missing-sublib-unregister/files/src/Sub.hs, test/integration/tests/6046-missing-sublib-unregister/files/stack.yaml
Also adds documentation.
Tests that it appears to fix the reported problem, by building and using Stack on Windows. Relying on the CI otherwise.
=> Fix #6046 Unregister local packages for sub libraries

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Source.hs, src/Stack/FileWatch.hs
`Data.Map.Strict.mergeWithKey` is described as deprecated and users are told to prefer `Data.Map.Merge.Strict.merge`.
=> Replace mergeWithKey with merge

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml
=> Add pkg-config to GitHub Hosted Runner for macOS

test/integration/tests/cabal-sublibrary-dependency/Main.hs, test/integration/tests/cabal-sublibrary-dependency/files/files.cabal, test/integration/tests/cabal-sublibrary-dependency/files/src/Lib.hs, test/integration/tests/cabal-sublibrary-dependency/files/src/Sub/Sub.hs, test/integration/tests/cabal-sublibrary-dependency/files/stack.yaml, test/integration/tests/cabal-sublibrary-dependency/files/subproject/src/Lib.hs, test/integration/tests/cabal-sublibrary-dependency/files/subproject/src/SubLib.hs, test/integration/tests/cabal-sublibrary-dependency/files/subproject/src/Subproject/Lib.hs, test/integration/tests/cabal-sublibrary-dependency/files/subproject/src/Subproject/SubLib.hs, test/integration/tests/cabal-sublibrary-dependency/files/subproject/subproject.cabal
=> Update cabal-sublibrary-dependency test

src/Stack/Build/ConstructPlan.hs
Refactors existing `addDep` to break it up into its three main steps: (1) check if the package name is in the lib map; (2) check if the package name is already in the call stack or the package name is not in the combined map; and (3) the core of the function.
=> Refactor `Stack.Build.ConstructPlan.addDep`

doc/maintainers/stack_errors.md, src/Stack/Coverage.hs
=> Prettier errors S-2321, S-6361 and S-9975

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Haddock.hs, src/Stack/Config.hs, src/Stack/Config/Nix.hs, src/Stack/Coverage.hs, src/Stack/Docker.hs, src/Stack/FileWatch.hs, src/Stack/Ghci.hs, src/Stack/Hoogle.hs, src/Stack/IDE.hs, src/Stack/List.hs, src/Stack/New.hs, src/Stack/Prelude.hs, src/Stack/SDist.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/SetupCmd.hs, src/Stack/Unpack.hs, src/Stack/Upload.hs, src/main/Main.hs, src/windows/System/Terminal.hs, test/integration/tests/multi-test/Main.hs
This seeks to introduce pretty information logging within Stack itself.
=> Use pretty information logging.

ChangeLog.md, src/Stack/Build.hs, test/integration/tests/cabal-sublibrary-dependency/Main.hs
=> Fix #6072 Exclude internal libs from checkSubLibraryDependencies

doc/maintainers/stack_errors.md, src/Stack/Build.hs, src/Stack/Types/Build.hs
=> Prettier error S-7086

src/Stack/Build/ConstructPlan.hs, src/Stack/Types/Build.hs, test/integration/tests/3685-config-yaml-for-allow-newer/Main.hs
=> Prettier warnings in Stack's M monad

doc/maintainers/stack_errors.md, src/Stack/Config.hs, src/Stack/Types/Config.hs
Also makes clear it can also relate to duplicated extra-deps.
=> Prettier error S-5470

doc/maintainers/stack_errors.md, src/Stack/SourceMap.hs, src/Stack/Types/Build.hs
=> Prettier error S-8664

package.yaml, src/main/Main.hs, stack.cabal, stack.yaml, stack.yaml.lock
=> Add handleAnyPrettyException

CONTRIBUTING.md, test/integration/IntegrationSpec.hs
A very small yet useful option added to integration tests : not running some of them.
=> feat: provide not match option for not running several integration tests

ChangeLog.md, src/Stack/Options/GlobalParser.hs, src/Stack/Options/LogLevelParser.hs, src/main/Main.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using on Windows 11. Relying on CI for other OS.
=> Fix #5326 Apply script interpreter verbosity default after processing arguments

src/Options/Applicative/Builder/Extra.hs, src/Options/Applicative/Complicated.hs, src/Stack/Options/BenchParser.hs, src/Stack/Options/BuildMonoidParser.hs, src/Stack/Options/BuildParser.hs, src/Stack/Options/CleanParser.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Options/DockerParser.hs, src/Stack/Options/DotParser.hs, src/Stack/Options/ExecParser.hs, src/Stack/Options/GhcBuildParser.hs, src/Stack/Options/GhcVariantParser.hs, src/Stack/Options/GhciParser.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Options/HaddockParser.hs, src/Stack/Options/HpcReportParser.hs, src/Stack/Options/InitParser.hs, src/Stack/Options/LogLevelParser.hs, src/Stack/Options/LsParser.hs, src/Stack/Options/NewParser.hs, src/Stack/Options/NixParser.hs, src/Stack/Options/PackageParser.hs, src/Stack/Options/ResolverParser.hs, src/Stack/Options/SDistParser.hs, src/Stack/Options/ScriptParser.hs, src/Stack/Options/SetupParser.hs, src/Stack/Options/TestParser.hs, src/Stack/Options/UploadParser.hs, src/main/Stack/CLI.hs
=> Greater consistency in in-app help messages

src/Path/CheckInstall.hs, src/Path/Extended.hs, src/test/Stack/ArgsSpec.hs, src/test/Stack/ConfigSpec.hs, src/test/Stack/DotSpec.hs, src/test/Stack/GhciSpec.hs, src/test/Stack/LockSpec.hs, src/test/Stack/NixSpec.hs, src/test/Stack/PackageDumpSpec.hs, src/test/Stack/UploadSpec.hs, src/unix/System/Terminal.hsc, test/integration/IntegrationSpec.hs, test/integration/lib/StackTest.hs
=> Add explicit imports

ChangeLog.md, doc/build_command.md, src/Stack/Build/Execute.hs, src/Stack/Options/BuildParser.hs, src/Stack/Types/BuildOpts.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack and examining debug output to review Cabal commands.
=> Fix #2868 Add --PROG-option to stack build

ChangeLog.md, doc/build_command.md, src/Stack/Build/Execute.hs, src/Stack/Options/BuildParser.hs, src/Stack/Types/BuildOpts.hs
The merger proved to be premature.
=> Unfix #2868 Reverse #6083

ChangeLog.md, doc/maintainers/stack_errors.md, doc/uninstall_command.md, src/Stack/Setup.hs, src/Stack/Uninstall.hs, src/main/Stack/CLI.hs
=> Fix #5584 Improve uninstallation of Stack-supplied tools

doc/maintainers/stack_errors.md, src/Stack/Unpack.hs
=> Prettier errors S-2628 and S-3515

doc/maintainers/stack_errors.md, src/Stack/Upgrade.hs
=> Prettier Stack.Upgrade errors

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml
=> Update CI to once again not distinguish Windows

doc/maintainers/stack_errors.md, src/Stack/Setup.hs
=> Make `stack setup` errors prettier

package.yaml, stack.cabal
Identified using the `prune-juice` tool.
=> Prune unused dependencies from package.yaml

etc/dockerfiles/arm64.Dockerfile
=> Try to fix locale in ARM64 Docker file

src/Stack/Setup.hs
=> Light reformatting

ChangeLog.md, src/Stack/Hoogle.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack on Windows. Relying on CI for other operating systems.
=> Fix #6139 Avoid unnecessary 'Found acceptable Hoogle in index'

.github/workflows/integration-tests.yml
=> Add some documentation to the CI

.github/workflows/integration-tests.yml, test/integration/tests/4095-utf8-pure-nix/Main.hs, test/integration/tests/4095-utf8-pure-nix/files/package.yaml
=> Fix #6147 Re-enable test 4095-utf8-pure-nix

ChangeLog.md, doc/maintainers/releases.md, etc/scripts/README.md, etc/scripts/release.hs
=> Fix #6148 Remove -static suffix from the static Linux/x86_64 binaries

etc/scripts/release.hs
=> Add explicit import lists and some reformatting

doc/maintainers/stack_errors.md, src/Stack/Hoogle.hs
=> Prettier error S-3025

.github/workflows/integration-tests.yml
=> Re #6156 Use NSIS 3.08 'large strings' build

src/Stack/Build/Execute.hs
=> Minor reformatting

src/Stack/Constants/Config.hs
=> Reformat, improve Haddock documentation

ChangeLog.md, doc/global_flags.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Types/GlobalOpts.hs, src/Stack/Types/GlobalOptsMonoid.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows. Relying on CI for other operating systems.
=> Fix #6167 Allow plan debug info from the command line

test/integration/tests/3926-ghci-with-sublibraries/Main.hs, test/integration/tests/4270-files-order/Main.hs, test/integration/tests/module-added-multiple-times/Main.hs
=> Re #6170 Update tests to provide move info on failure

src/Stack/Build/ConstructPlan.hs
The call stack only needs to be updated to create the context for the `addDep`.
=> Reorganise checkCallStackAndAddDep

test/integration/lib/StackTest.hs
=> Reformat and some refactoring

ChangeLog.md, doc/build_command.md, doc/yaml_configuration.md, src/Stack/Build/Execute.hs, src/Stack/Config/Build.hs, src/Stack/Options/BuildMonoidParser.hs, src/Stack/Types/BuildOpts.hs
=> Fix #6178 Add `--progress-bar` option to `stack build`

doc/maintainers/stack_errors.md, src/Stack/SDist.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested S-6439 locally.
=> Prettier stack sdist errors

ChangeLog.md, src/Stack/Script.hs
=> Fix #6189 Script files may lack an extension

src/main/Stack/CLI.hs
=> Don't hard-code program name in help output

src/Network/HTTP/StackClient.hs, src/Stack/Docker.hs, src/Stack/Ls.hs, src/Stack/Package.hs, src/Stack/PackageFile.hs, src/Stack/Setup.hs, src/test/Stack/ConfigSpec.hs, src/windows/System/Terminal.hs, test/integration/IntegrationSpec.hs
=> Add explicit imports by removing hiding

src/Stack/Setup.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally with `ghc-9.8.0.20230809`.
=> Fix #6206 Use short temp path in `withUnpackedTarball7z`

src/Stack/Build/Source.hs, src/Stack/Setup.hs, src/Stack/Types/EnvConfig.hs, src/Stack/Types/FileDigestCache.hs, stack.cabal
=> Re #6184 Minor refactoring/reformatting

ChangeLog.md
This is draft pending the release of the `pantry` dependency.
=> Move to `tar-conduit-0.4.0`

src/Stack/Build/ConstructPlan.hs, src/Stack/Prelude.hs, src/Stack/Types/Build/Exception.hs, src/Stack/Types/ProjectConfig.hs, test/integration/tests/3685-config-yaml-for-allow-newer/Main.hs, test/integration/tests/4897-boot-package-pruned/Main.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally. Relying, in part, on CI.
=> Fix #6213 Better messages when build plan not constructed

doc/dot_command.md
=> Fix typo in CLI docs

src/Stack/Setup.hs
=> Fix misuse of prettyThrow... for exceptions caught elsewhere

ChangeLog.md, src/Stack/Setup.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Alpine Linux (on WSL2). Relying on CI for other operating systems.
=> Re #6218 Only consider musl GHC build if musl libc present

CONTRIBUTING.md, ChangeLog.md, src/Stack/Build.hs, src/Stack/Coverage.hs, src/Stack/Setup.hs
=> Drop Cabal < 1.24.0.0

CONTRIBUTING.md, Setup.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on CI, but also need to do some other testing.
=> Fix #6234 Add corresponding `replHook`

src/Stack/Build/Execute.hs, src/Stack/GhcPkg.hs
=> Fix #6225 Avoid use of GHC_PACKAGE_PATH

.devcontainer/.gitignore, .devcontainer/GHC.Dockerfile, .devcontainer/README.md, .devcontainer/scripts/usr/local/bin/onCreateCommand.sh
=> Finalise Dev Containers

.github/workflows/lint.yml, .hlint-test.yaml, src/Stack/Exec.hs, src/Stack/Options/Completion.hs
=> Update HLint application

src/Control/Concurrent/Execute.hs
=> Refactor `runActions'`

doc/list_command.md, doc/maintainers/stack_errors.md, src/Stack/List.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows 11 and relying on CI for other operating systems.
=> Prettier error S-4926

src/Stack/Build/ConstructPlan.hs
=> Fix #6249 Do not warn, if build-tool is package executable

ChangeLog.md, doc/hpc_command.md, src/Stack/Coverage.hs, tests/integration/tests/3997-coverage-with-cabal-3/Main.hs, tests/integration/tests/4105-test-coverage-of-internal-lib/Main.hs, tests/integration/tests/multi-test/Main.hs
Distinguishes logging from the summary reports themselves.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally. Also relying on CI.
=> Re #6250 Output summary reports to stdout, not stderr

ChangeLog.md, src/Stack/Setup.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows. Will test locally on macOS/AArch64.
=> Add AArch64 to Stack's preferred platforms

src/Stack/Upgrade.hs
=> Fix stack upgrade warning message

.devcontainer/GHC.Dockerfile, .devcontainer/devcontainer.json, .devcontainer/ghc-9.6.3/devcontainer.json, doc/dev_containers.md, stack-ghc-9.6.3.yaml
=> Update Dev Containers

ChangeLog.md, doc/nix_integration.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Constants.hs, src/Stack/Runners.hs, src/Stack/Types/Config.hs, src/Stack/Types/ConfigMonoid.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Linux (on WSL2).
=> Fix #6269 Implement notify-if-nix-on-path

ChangeLog.md, src/Stack/Build/Execute.hs
=> Fix #6276 Haddock > 2.17.2 provides --hyperlinked-source

src/Stack/BuildPlan.hs, src/Stack/Package.hs
=> Fix #6278 No need to test for GHC >= 8.0

ChangeLog.md, src/Stack/Build/Cache.hs, src/Stack/Build/Execute.hs
=> Fix #6280 Simpler hash for pre-compiled package cache keys

tests/integration/tests/script-extra-dep/files/script.hs
=> Bump script-extra-dep test

tests/integration/tests/internal-libraries/Main.hs, tests/integration/tests/internal-libraries/files/stack.yaml
=> Re #6286 Skip new GHC setup for test `internal-libraries`

.github/workflows/integration-tests.yml
=> Re #6286 Report disk space usage during CI

ChangeLog.md, doc/build_command.md, src/Stack/Build/Execute.hs, src/Stack/Build/Haddock.hs, src/Stack/Config/Build.hs, src/Stack/Constants.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Limited testing locally, on Windows.
=> Re #6270 Step 3, create archive files of Haddock documentation

doc/maintainers/stack_errors.md, src/Stack/Upload.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on CI. Some testing locally.
=> Re #6270 Step 5 Improve stack upload error messages

doc/maintainers/stack_errors.md, src/Stack/Exec.hs
=> Clear a STAN suggestion.

doc/maintainers/stack_errors.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Types/Build/Exception.hs
=> Clear STAN suggestion

.stan.toml, src/Stack/Build.hs, src/Stack/Build/Execute.hs, src/Stack/ConfigCmd.hs
=> Clear Stan suggestion; replace NE.fromList with NE.nonEmpty

.stan.toml, src/Stack/Init.hs
=> Clear Stan suggestion; eliminate minimumBy

.stan.toml, src/Stack/Types/Build/Exception.hs
=> Clear Stan suggestion; eliminate partial `minimum`

.stan.toml, doc/maintainers/stack_errors.md, src/Network/HTTP/StackClient.hs, src/Stack/Ghci.hs
=> Clear Stan suggestion; avoid `Data.List.(!!)`

.stan.toml, src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Haddock.hs, src/Stack/BuildPlan.hs, src/Stack/CLI.hs, src/Stack/Clean.hs, src/Stack/ComponentFile.hs, src/Stack/Config.hs, src/Stack/New.hs
=> Reformatting, for consistency

src/Stack/Build/ConstructPlan.hs
=> Replace RWST with WS stack on top of (RIO Ctx)

src/Stack/Build/ConstructPlan.hs, src/Stack/Types/Build.hs, src/Stack/Types/Package.hs, src/Stack/Types/ParentMap.hs
=> Add Haddock documentation to existing code

src/Stack/Build/Execute.hs
=> Fix #6318 Register sublibraries if no library

src/Stack/Build/Source.hs, src/Stack/Types/NamedComponent.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on CI,
=> Fix #6323 Fix splitComponents; make a helper function of NamedComponent

src/Stack/Ghci.hs
=> Formatting, for consistency

package.yaml, src/Stack/Component.hs, src/Stack/Types/CompCollection.hs, src/Stack/Types/Component.hs, stack.cabal
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on CI. Local testing of Haddock documentation.
=> Use Haddock hyperlinks, not URLs

src/Stack/Build/ConstructPlan.hs
The motivation is to make `addPackageDeps` and its key constituent parts easier to follow.
=> Refactor body of addPackageDeps into helper functions

src/Stack/Types/Build/Exception.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on CI here, but will test locally.
=> Fix #6346 Improve error message S-4804

.stan.toml, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Target.hs, src/Stack/Coverage.hs, src/Stack/Ghci.hs, src/Stack/Init.hs, src/Stack/List.hs, src/Stack/New.hs, src/Stack/Prelude.hs, src/Stack/SDist.hs, src/Stack/Types/Build/Exception.hs, src/Stack/Types/Config/Exception.hs, src/Stack/Unpack.hs
=> Use `fromPackageId` and `fromPackageName` to shorten code

.devcontainer/devcontainer.json
=> Dev Containers: Update HLS to v2.5.0.0

cabal.config
- Fix https://github.com/commercialhaskell/stack/issues/6359
=> Update for pantry-0.9.3

ChangeLog.md, package.yaml, stack-ghc-9.6.3.yaml, stack-ghc-9.6.3.yaml.lock, stack.cabal, stack.yaml, stack.yaml.lock
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows 11. Relying on CI.
=> Fix #6364 Better error message if `resolver:` value is a number

src/Stack/ComponentFile.hs, src/Stack/PackageFile.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows 11. Relying of CI.
=> Fix #6365 Gather test suite files

doc/new_command.md
See also https://github.com/haskell/cabal/issues/9507.
=> Fix #6363 Improve docs on package/project names

ChangeLog.md, src/Stack/Types/GhcPkgId.hs, src/Stack/Types/PackageName.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows 11. Relying on CI.
=> Fix #6369 Accept package names, in fact, acceptable to Cabal

.stan.toml, ChangeLog.md, doc/unpack_command.md, src/Stack/CLI.hs, src/Stack/Config.hs, src/Stack/Constants.hs, src/Stack/Options/UnpackParser.hs, src/Stack/Unpack.hs
=> Fix #6374 Implement `stack unpack --candidate`

src/Stack/Build/Cache.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Target.hs, src/Stack/Component.hs, src/Stack/ComponentFile.hs, src/Stack/Ghci.hs, src/Stack/Init.hs, src/Stack/List.hs, src/Stack/New.hs, src/Stack/Package.hs, src/Stack/Types/CompCollection.hs, src/Stack/Types/Component.hs, src/Stack/Types/Dependency.hs, src/Stack/Types/NamedComponent.hs
Minor refactorings and additions for component based builds
=> Misc refactorings

src/Stack/Build/Installed.hs, src/Stack/Component.hs, src/Stack/Package.hs, src/Stack/PackageFile.hs, src/Stack/Prelude.hs, src/Stack/Types/CompCollection.hs, src/Stack/Types/Dependency.hs
=> Foldr in prelude

doc/maintainers/stack_errors.md, package.yaml, src/Stack/Setup.hs, src/Stack/Types/Build/Exception.hs, stack.cabal, stack.yaml, stack.yaml.lock
A precursor for providing more information about how to install GHC manually.
=> Re #6379 Prettier S-6362

ChangeLog.md, doc/unpack_command.md, src/Stack/Unpack.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows 11. Relying on CI.
=> Fix #6395 Update package index before seeking most recent package version

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Haddock.hs, src/Stack/Build/Installed.hs, src/Stack/DependencyGraph.hs, src/Stack/PackageDump.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/SourceMap.hs, src/Stack/Types/DumpPackage.hs, tests/unit/Stack/PackageDumpSpec.hs
This is a test case, for a single constructor, to get an impression of what it takes to remove prefixes.
=> Remove dp prefix from DumpPackage field names

src/Stack/Build/Installed.hs, src/Stack/Types/DumpPackage.hs
=> Remove sd prefix from SublibDump field names

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Source.hs, src/Stack/Build/Target.hs, src/Stack/Clean.hs, src/Stack/Config.hs, src/Stack/Coverage.hs, src/Stack/DependencyGraph.hs, src/Stack/Exec.hs, src/Stack/Ghci.hs, src/Stack/IDE.hs, src/Stack/Options/Completion.hs, src/Stack/Path.hs, src/Stack/SDist.hs, src/Stack/Setup.hs, src/Stack/Storage/Project.hs, src/Stack/Types/Build/ConstructPlan.hs, src/Stack/Types/BuildConfig.hs, src/Stack/Types/EnvConfig.hs, src/Stack/Types/PackageFile.hs, tests/unit/Stack/ConfigSpec.hs
=> Remove bc prefix from BuildConfig field names

src/Stack/Build.hs, src/Stack/Build/Cache.hs, src/Stack/Build/Source.hs, src/Stack/Coverage.hs, src/Stack/DependencyGraph.hs, src/Stack/Ghci.hs, src/Stack/SDist.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/Types/Build/ConstructPlan.hs, src/Stack/Types/EnvConfig.hs
=> Remove envConfig prefix from EnvConfig field names

src/Stack/Build/Execute.hs, src/Stack/Build/ExecuteEnv.hs, src/Stack/Build/ExecutePackage.hs
=> Remove ee prefix from ExecuteEnv field names

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Package.hs, src/Stack/Storage/Project.hs, src/Stack/Types/Build.hs
=> Remove configCache prefix from ConfigCache field names

src/Stack/Config.hs, src/Stack/Config/Nix.hs, src/Stack/Nix.hs, src/Stack/Runners.hs, src/Stack/Types/Nix.hs, tests/unit/Stack/NixSpec.hs
=> Remove nix prefix from NixOpts field names

.stan.toml, src/Stack/Config.hs, src/Stack/Config/Docker.hs, src/Stack/Docker.hs, src/Stack/Runners.hs, src/Stack/Types/Docker.hs, src/unix/Stack/Docker/Handlers.hs, src/windows/Stack/Docker/Handlers.hs
=> Remove docker prefix from DockerOpts field names

.stan.toml, src/Stack/Build/Execute.hs, src/Stack/SDist.hs
* **[x]** The documentation has been updated, if necessary
=> Re #6411 Complete module split

src/Stack.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Config.hs, src/Stack/ConfigCmd.hs, src/Stack/Init.hs, src/Stack/List.hs, src/Stack/New.hs, src/Stack/Options/Completion.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Path.hs, src/Stack/Runners.hs, src/Stack/Script.hs, src/Stack/Types/GlobalOpts.hs, src/Stack/Types/Runner.hs, src/Stack/Unpack.hs, src/Stack/Upgrade.hs, tests/unit/Stack/ConfigSpec.hs, tests/unit/Stack/NixSpec.hs
=> Remove global prefix from GlobalOpts field names

src/Stack/Config.hs, src/Stack/Config/Docker.hs, src/Stack/Init.hs, src/Stack/Options/Completion.hs, src/Stack/Types/Project.hs, src/Stack/Types/ProjectAndConfigMonoid.hs, tests/unit/Stack/ConfigSpec.hs
=> Remove project prefix from Project field names

src/Stack/Setup.hs, src/Stack/SetupCmd.hs
=> Remove sopts prefix from SetupOpts field names

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Types/Build.hs
=> Remove tco prefix from TaskConfigOpts field names

.stan.toml, src/Stack/Config.hs, src/Stack/Init.hs
=> Fix reported ambiguity

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Source.hs, src/Stack/BuildPlan.hs, src/Stack/Config.hs, src/Stack/DependencyGraph.hs, src/Stack/Ghci.hs, src/Stack/SDist.hs, src/Stack/Script.hs, src/Stack/SourceMap.hs, src/Stack/Types/SourceMap.hs
=> Remove cp prefix from CommonPackage field names

src/Stack/Build.hs, src/Stack/Build/Cache.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/ExecuteEnv.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Build/Haddock.hs, src/Stack/Types/ConfigureOpts.hs
=> Remove bco prefix from BaseConfigOpts field names

src/Stack/Config/Nix.hs, src/Stack/Options/NixParser.hs, src/Stack/Types/Nix.hs
=> Remove nixMonoid prefix from NixOptsMonoid field names

src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Source.hs, src/Stack/Build/Target.hs, src/Stack/BuildPlan.hs, src/Stack/Clean.hs, src/Stack/Config.hs, src/Stack/Coverage.hs, src/Stack/DependencyGraph.hs, src/Stack/Exec.hs, src/Stack/Ghci.hs, src/Stack/Hoogle.hs, src/Stack/IDE.hs, src/Stack/Options/Completion.hs, src/Stack/SDist.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/SourceMap.hs, src/Stack/Types/BuildConfig.hs, src/Stack/Types/EnvConfig.hs, src/Stack/Types/SourceMap.hs
=> Remove sm sma smw smt prefixes from field names

src/Stack/Config.hs, src/Stack/Types/Casa.hs
=> Remove casaMonoid prefix from CasaOptsMonoid field names

src/Stack/Config.hs, src/Stack/Config/Docker.hs, src/Stack/Types/Docker.hs
=> Remove dockerMonoid prefix from DockerOptsMonoid field names

src/Stack/Config.hs, src/Stack/Init.hs, src/Stack/Types/Resolver.hs
=> Remove snapshots prefix from Snapshots field names

src/Stack/ComponentFile.hs, src/Stack/PackageFile.hs, src/Stack/Types/PackageFile.hs
=> Remove ctx prefix from GetPackageFileContext field names

src/Stack/CLI.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Types/GlobalOptsMonoid.hs, tests/unit/Stack/NixSpec.hs
=> Remove globalMonoid prefix from GlobalOptsMonoid field names

ChangeLog.md, doc/ls_command.md, src/Stack/Ls.hs, src/Stack/Options/LsParser.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows 11. Relying on CI.
=> Fix #6229 Add `stack ls dependencies --filter '$locals'`

src/Stack/Build/Cache.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/ExecuteEnv.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/DependencyGraph.hs, src/Stack/Docker.hs, src/Stack/Dot.hs, src/Stack/Hoogle.hs, src/Stack/Ls.hs, src/Stack/Package.hs, src/Stack/Setup.hs, src/Stack/Storage/Project.hs, src/Stack/Types/ConfigureOpts.hs, src/Stack/Types/Dependency.hs, src/Stack/Types/DependencyTree.hs, src/Stack/Types/DockerEntrypoint.hs, src/Stack/Types/DotOpts.hs, src/Stack/Types/DownloadInfo.hs, src/Stack/Types/EnvSettings.hs, src/Stack/Types/VersionedDownloadInfo.hs
co/ConfigureOpts, dv/DepValue, dl/DepLibrary, payload/DotPayload, downloadInfo/DownloadInfo, and es/EnvSettings.
=> Remove prefixes from various type field names

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Haddock.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Source.hs, src/Stack/Build/Target.hs, src/Stack/BuildPlan.hs, src/Stack/Config.hs, src/Stack/Coverage.hs, src/Stack/DependencyGraph.hs, src/Stack/Exec.hs, src/Stack/Ghci.hs, src/Stack/Hoogle.hs, src/Stack/Init.hs, src/Stack/Options/Completion.hs, src/Stack/SDist.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/SourceMap.hs, src/Stack/Types/BuildOptsCLI.hs, src/Stack/Types/Project.hs, src/Stack/Types/ProjectAndConfigMonoid.hs, src/Stack/Types/SourceMap.hs, src/Stack/Upgrade.hs
=> Different approach to avoiding some ambiguity with record updates

src/Stack/Ghci/Script.hs, src/Stack/Lock.hs, src/Stack/Ls.hs, src/Stack/Prelude.hs, src/Stack/Storage/Project.hs, src/Stack/Storage/User.hs, src/Stack/Types/BuildOptsMonoid.hs, src/Stack/Types/ConfigMonoid.hs, src/Stack/Types/Docker.hs, src/Stack/Types/Storage.hs
=> Remove prefixes from newtype fields

doc/dev_containers.md
- Related to https://github.com/commercialhaskell/stack/pull/6401
---
=> Dev Containers: Update documentation

.stan.toml, src/Stack/Build/Cache.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Storage/Project.hs, src/Stack/Types/Build.hs, src/Stack/Types/ConfigureOpts.hs
=> Rename fields of ConfigureOpts, and related

.devcontainer/.gitignore, .devcontainer/devcontainer.json, .devcontainer/ghc-9.8.1/devcontainer.json, doc/dev_containers.md
- Remove section 'Persistence' in documentation
No updates to ChangeLog.md required.
=> Dev Containers: Do not mount the user's home directory

.github/workflows/integration-tests.yml, .github/workflows/lint.yml, .github/workflows/stan.yml, .github/workflows/unit-tests.yml, .hlint-test.yaml, .hlint.yaml, src/Stack/Coverage.hs, src/Stack/Ghci.hs, src/Stack/PackageFile.hs, src/Stack/Runners.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on (updated) CI.
=> Fix #6469 Update GitHub workflow actions

.github/workflows/integration-tests.yml
=> Adopt macos-14 GitHub-hosted runner (macOS/AArch64)

ChangeLog.md, doc/build_command.md, src/Stack/Build/ExecutePackage.hs
=> Apply --haddock-for-hackage only to local packages

ChangeLog.md, src/Stack/Build/ExecutePackage.hs
=> Re #6270 Fix `--haddock-arguments` with `--haddock-for-hackage`

.stan.toml, ChangeLog.md, doc/developing_on_windows.md, doc/maintainers/stack_errors.md, doc/yaml_configuration.md, package.yaml, src/Stack/Config.hs, src/Stack/Constants.hs, src/Stack/Setup.hs, src/Stack/Setup/Installed.hs, src/Stack/Types/Config.hs, src/Stack/Types/Config/Exception.hs, src/Stack/Types/ConfigMonoid.hs, src/Stack/Types/MsysEnvironment.hs, stack.cabal, tests/integration/tests/6465-msys-environment/Main.hs, tests/integration/tests/6465-msys-environment/files/Main.hs, tests/integration/tests/6465-msys-environment/files/Setup.hs, tests/integration/tests/6465-msys-environment/files/foo.cabal, tests/integration/tests/6465-msys-environment/files/stack.yaml
Please also shortly describe how you tested your change. Bonus points for added tests! Also adds an integration test.
=> Fix #6457 Allow MSYS2 environment to be configured

.stan.toml, src/Options/Applicative/Builder/Extra.hs, src/Stack.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/ExecuteEnv.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Build/Haddock.hs, src/Stack/Config.hs, src/Stack/Docker.hs, src/Stack/Ghci.hs, src/Stack/Hoogle.hs, src/Stack/Ls.hs, src/Stack/New.hs, src/Stack/PackageDump.hs, src/Stack/SDist.hs, src/System/Process/Pager.hs, tests/integration/lib/StackTest.hs, tests/integration/tests/4101-dependency-tree/Main.hs, tests/integration/tests/717-sdist-test/files/package-with-failing-test/test/Test.hs, tests/integration/tests/skip-unreachable-dirs/Main.hs
=> Refactor to use whenJust

ChangeLog.md, src/Stack/Init.hs, src/Stack/Types/Project.hs, tests/integration/tests/nice-resolver-names/Main.hs
=> Re #6466 stack init prefers snapshot to resolver

src/Stack/Config.hs, src/Stack/List.hs, src/Stack/Unpack.hs
=> Eliminate some code duplication

ChangeLog.md, doc/config_command.md, src/Stack/ConfigCmd.hs
=> Fix known bugs in stack config set snapshot/resolver

doc/pantry.md
=> Fix typo in doc/pantry.md

ChangeLog.md, package.yaml, stack-ghc-9.8.1.yaml, stack-ghc-9.8.1.yaml.lock, stack.cabal, stack.yaml, stack.yaml.lock
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally and relying on CI.
=> Fix #5536 Depend on pantry-0.9.3.3

.stan.toml, ChangeLog.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Init.hs, src/Stack/Types/Config.hs, src/Stack/Types/ConfigMonoid.hs, src/Stack/Types/GlobalOpts.hs, src/Stack/Types/Snapshot.hs
See the additions to the online documentation.
=> Fix #6496 Add default-init-snapshot option

src/Stack/Build/Haddock.hs, src/Stack/Build/Target.hs, src/Stack/BuildPlan.hs, src/Stack/ConfigCmd.hs, src/Stack/Coverage.hs, src/Stack/Init.hs, src/Stack/Options/BuildParser.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Options/GhciParser.hs, src/Stack/Options/LsParser.hs, src/Stack/Types/Build/Exception.hs, src/Stack/Types/Config/Exception.hs
=> Re #6492 Prefer 'project packages' to 'local packages'

ChangeLog.md, doc/ghc_command.md, doc/maintainers/stack_errors.md, doc/runghc_command.md, src/Stack/Exec.hs, src/Stack/Options/ExecParser.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows. Relying on CI.
=> Fix #2530 Handle --package values as intended

doc/build_command.md, src/Stack/Build/Haddock.hs
=> Fix #6511 Organise docs for components so that links work

ChangeLog.md, doc/upload_command.md, doc/yaml_configuration.md, package.yaml, src/Stack/Config.hs, src/Stack/Options/UploadParser.hs, src/Stack/Types/Config.hs, src/Stack/Types/ConfigMonoid.hs, src/Stack/Types/UploadOpts.hs, src/Stack/Upload.hs, stack.cabal
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally by uploading Stack 2.15.3 documentation with `--no-save-hackage-creds`.
=> Fix #5290 Add `--[no-]save-hackage-creds` to `stack upload`

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Config.hs
=> Fix #6516 Update default `urls` key

ChangeLog.md, src/Stack/Ghci.hs, src/Stack/Options/GhciParser.hs
=> Fix #4822 Remove `stack ghci --skip-intermediate-deps`

ChangeLog.md, doc/build_command.md, src/Stack/Build/Haddock.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows with a simple two-package project.
=> Fix #6520 Avoid archiving Haddock for Hackage when inappropriate

.stan.toml, src/Stack/Build/ExecuteEnv.hs
=> Re #6524 Minor refactoring

src/Stack/CLI.hs
=> Fix #3644 Improve in-app help for stack init, stack new

.stan.toml, ChangeLog.md, src/Stack/Build/ExecuteEnv.hs
=> Fix #6524 Exclude snapshot package DB for `build-type: Configure`

ChangeLog.md, doc/yaml_configuration.md, package.yaml, src/Stack/Config.hs, src/Stack/Types/ConfigMonoid.hs, stack.cabal, stack.yaml, stack.yaml.lock
=> Fix #5638 Add global-hints-location option

ChangeLog.md, cabal.config, doc/global_flags.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Types/ConfigMonoid.hs, stack-ghc-9.8.1.yaml, stack-ghc-9.8.1.yaml.lock
=> Fix #6521 Add `--[no-]hpack-force` flag

src/Stack/CLI.hs
=> Fix #4983 Add in-app documentation of hidden options

ChangeLog.md, doc/config_command.md, src/Stack/Config.hs, src/Stack/ConfigCmd.hs, src/Stack/Runners.hs, src/Stack/Types/Config.hs, src/Stack/Types/ConfigMonoid.hs
Also adds links to existing online documentation.
Also rewords existing in-app documentation, for consistency.
Also renames fields to mirror option name.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows. Relying on CI for other operating systems.
=> Fix #6546 Add `stack config set recommend-stack-upgrade`

ChangeLog.md, doc/build_command.md, src/Stack/Build/Target.hs
=> Fix #5467 Report error if package identifier does not parse

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml
=> Bump CI for macos-14 becoming macos-latest

ChangeLog.md, doc/list_command.md, src/Stack/CLI.hs, src/Stack/List.hs
=> Re #6561 Extend `stack list` to packages indirectly in snapshot

ChangeLog.md, doc/ls_command.md, src/Stack/CLI.hs, src/Stack/Ls.hs, src/Stack/Options/DotParser.hs, src/Stack/Options/LsParser.hs
=> Fix #6561 Add `stack ls globals`

src/Stack/Options/BuildParser.hs
=> Fix #6564 Improve in-app documentation for --flag

ChangeLog.md, doc/build_command.md, doc/yaml_configuration.md, src/Stack/Build/Source.hs
=> Fix #6565 Include Cabal flags set manually in the source map hash

.devcontainer/devcontainer.json, .devcontainer/ghc-9.8.2/devcontainer.json
* Remove 'GHC 9.8.1'; Add 'GHC 9.8.2'
* Update HLS to v2.8.0.0
---
=> Dev Containers: Update

src/Stack/Setup.hs
=> Fix #6584 Remove duplicate action

src/Stack/Options/BuildParser.hs, src/Stack/Options/LsParser.hs
=> Fix #6591 Improve in-app documentation

.devcontainer/ghc-9.10.1/devcontainer.json
=> Dev Container: Add 'GHC 9.10.1'

.devcontainer/GHC.Dockerfile
- HLS and HLint are custom-built and only available at glcr.b-data.ch
---
=> Dev Container: Use GHC images from Quay

ChangeLog.md, src/Stack/Script.hs
=> Fix #6600 Don't use 'raw' `withConfig` with `stack script`

.stan.toml, ChangeLog.md, src/Stack/Config.hs, src/Stack/ConfigCmd.hs, src/Stack/Constants.hs, src/Stack/Types/Build/Exception.hs
=> Fix #6611 Drop support for deprecated config locations

.devcontainer/devcontainer.json, .devcontainer/ghc-9.10.1/devcontainer.json, .devcontainer/ghc-9.8.2/devcontainer.json, .devcontainer/scripts/usr/local/bin/postCreateCommand.sh
- Update postCreateCommand
- Fix https://github.com/commercialhaskell/stack/issues/6620
---
=> Dev Containers: Update HLS to v2.9.0.0

ChangeLog.md, src/setup-shim/StackSetupShim.hs
=> Fix #6621 Remove Haddock style comments

ChangeLog.md, doc/build_command.md, doc/yaml_configuration.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Config.hs, src/Stack/Options/BuildParser.hs, src/Stack/Types/Build/Exception.hs, src/Stack/Types/BuildOptsCLI.hs, src/Stack/Types/BuildOptsMonoid.hs, src/Stack/Types/Config.hs
=> Fix #6501 Add `stack build --[no-]allow-newer`

.stan.toml, ChangeLog.md, doc/configure/yaml/project.md, doc/tutorial/building_existing_projects.md, src/Stack/Config.hs, src/Stack/Init.hs
Also updates `stack init` messages to take advantage of that.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally.
=> Fix #6628 Treat consecutive line ends as a single blank line

ChangeLog.md, doc/configure/yaml/non-project.md, src/Stack/Build/ExecutePackage.hs, src/Stack/Config.hs, src/Stack/Types/Config.hs, src/Stack/Types/ConfigMonoid.hs
=> Fix #6638 Add `notify-if-no-run-tests` and `notify-if-no-run-benchmarks`

src/Stack/Build/Execute.hs
=> Remove redundant let

.devcontainer/GHC.Dockerfile
=> Dev Containers: Update handling of timezone setting

ChangeLog.md, doc/maintainers/stack_errors.md, src/Stack/Config.hs
=> Fix #6647 Trigger S-8432 whenever space in Stack's 'programs' directory

ChangeLog.md, src/setup-shim/StackSetupShim.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Can build locally with GHC 9.12.20241014. Relying on CI.
=> Fix #6653 Change `StackSetupShim.hs` for `Cabal-3.14.0.0`

package.yaml, stack-ghc-9.10.1.yaml, stack-ghc-9.10.1.yaml.lock, stack-ghc-9.8.3.yaml, stack-ghc-9.8.3.yaml.lock, stack.cabal, stack.yaml, stack.yaml.lock
=> Fix #6655 Specify hi-file-parser >= 0.1.7.0

tests/unit/Stack/ArgsSpec.hs
=> Fix #6665 Avoid partial functions

tests/integration/tests/haddock-options/Main.hs
=> Re #6666 Re-activate test haddock-options

ChangeLog.md, src/Stack/Setup.hs
=> Bump 'not tested with' to be GHC > 9.11 and Cabal > 3.13

.devcontainer/ghc-9.12.1/devcontainer.json
=> Dev Containers: Add 'GHC 9.12.1'

ChangeLog.md, doc/commands/config_command.md, doc/commands/setup_command.md, doc/configure/global_flags.md, doc/configure/yaml/non-project.md, src/Stack/Config.hs, src/Stack/ConfigCmd.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Setup.hs, src/Stack/SetupCmd.hs, src/Stack/Types/Config.hs, src/Stack/Types/ConfigMonoid.hs
Tested locally with various combinations of:
* not setting or setting `install-ghc: true/false`
* not specifying or specifying `--[no-]install-ghc`;
* not setting or setting `install-msys: true/false`; or
* not specifying or specifying `--[no-]install-msys`.
Tested `stack config set install-msys` locally.
Tested various combinations of `stack --[no-]install-ghc --[no-]install-msys setup` locally.
=> Fix #6675 Add install-msys and ancillary matters

.github/workflows/integration-tests.yml
Please also shortly describe how you tested your change. Bonus points for added tests! Testing with CI.
=> Fix #6682 Update to NSIS 3.10 'large strings' special build

.stan.toml, src/GHC/Utils/GhcPkg/Main/Compat.hs, src/Network/HTTP/StackClient.hs, src/Path/Find.hs, src/Stack/Build/Cache.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/ExecuteEnv.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Build/Haddock.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Source.hs, src/Stack/Build/Target.hs, src/Stack/ComponentFile.hs, src/Stack/Config.hs, src/Stack/Constants.hs, src/Stack/Docker.hs, src/Stack/New.hs, src/Stack/Package.hs, src/Stack/PackageDump.hs, src/Stack/PackageFile.hs, src/Stack/Prelude.hs, src/Stack/Setup/Installed.hs, src/Stack/Types/Package.hs, src/Stack/Types/PackageName.hs, src/Stack/Types/TemplateName.hs
=> Minor reformatting of signatures, for consistency

ChangeLog.md, stack.yaml, stack.yaml.lock
=> Fix #6685 Bump to Hpack 0.38

.stan.toml, src/Stack/BuildPlan.hs, src/Stack/ComponentFile.hs, src/Stack/Config.hs, src/Stack/Ghci.hs, src/Stack/Init.hs, src/Stack/Types/Snapshot.hs
=> Consistency of terminology in in-app documentation

ChangeLog.md, doc/configure/yaml/non-project.md
Please also shortly describe how you tested your change. Bonus points for added tests! N/A
=> Upgrade allow-newer-deps from experimental

ChangeLog.md, doc/commands/config_command.md, doc/topics/lock_files.md, src/Stack/CLI.hs, src/Stack/ConfigCmd.hs
=> Fix #6696 Add `stack config build-files`

.stan.toml, src/Stack/Build.hs, src/Stack/Build/Execute.hs, src/Stack/Build/ExecuteEnv.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Coverage.hs, src/Stack/Setup.hs, src/Stack/Types/ConfigureOpts.hs, src/Stack/Types/EnvConfig.hs, src/unix/System/Terminal.hsc, src/windows/System/Terminal.hs
=> Fix #6712 Remove redundant code paths

doc/maintainers/stack_errors.md, package.yaml, src/GHC/Utils/GhcPkg/Main/Compat.hs, src/Stack/GhcPkg.hs, src/Stack/Types/GhcPkgExe.hs, stack.cabal
=> Re #6711 On unregister, move recache outside of try

doc/maintainers/stack_errors.md, src/Stack/Build/ExecutePackage.hs
=> Re #6711 Add debug info to copyPreCompiled

src/Stack/Build/ExecutePackage.hs, src/Stack/GhcPkg.hs
=> Re #6711 Add debug info to copyPreCompiled and ghcPkg

.stan.toml, ChangeLog.md, doc/commands/script_command.md, src/Stack/Build/ExecutePackage.hs
=> Fix #6711 Workaround ghc-pkg bug by deleting GHC_PACKAGE_PATH

.devcontainer/GHC.Dockerfile, .devcontainer/devcontainer.json, .devcontainer/ghc-9.10.1/devcontainer.json, .devcontainer/ghc-9.12.1/devcontainer.json, stack-ghc-9.10.1.yaml, stack-ghc-9.12.2.yaml, stack.yaml
- Related to https://github.com/benz0li/ghc-musl/commit/53efca3dc38c0534603d53aa585ac3d71aada152
---
=> Use `int-native` subtagged images

.devcontainer/devcontainer.json, .devcontainer/ghc-9.10.1/devcontainer.json, .devcontainer/ghc-9.12.1/devcontainer.json, stack-ghc-9.10.1.yaml, stack-ghc-9.12.2.yaml
=> Switch back to regular images

package.yaml, src/Stack/Options/BuildParser.hs, src/Stack/Options/DotParser.hs, src/Stack/Options/FlagsParser.hs, src/Stack/Options/GhciParser.hs, stack.cabal
=> Refactoring to put shared flags parser in its own module

package.yaml, src/Stack/Options/HpcReportParser.hs, src/Stack/Options/PvpBoundsParser.hs, src/Stack/Options/SDistParser.hs, src/Stack/Options/UploadParser.hs, stack.cabal
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows. Relying on CI.
=> Reduce code duplication, re pvpBoundsParser

src/Stack/Upload.hs
=> Prettier output for loadAuth info

package.yaml, src/Stack/Build/ExecutePackage.hs, src/Stack/Coverage.hs, src/Stack/IDE.hs, src/Stack/Ls.hs, src/Stack/Options/HpcReportParser.hs, src/Stack/Options/LsParser.hs, src/Stack/Options/SetupParser.hs, src/Stack/Path.hs, src/Stack/Setup.hs, src/Stack/SetupCmd.hs, src/Stack/Types/Docker.hs, src/Stack/Types/HpcReportOpts.hs, src/Stack/Types/LsOpts.hs, src/Stack/Types/SetupOpts.hs, src/unix/System/Terminal.hsc, src/windows/System/Terminal.hs, stack.cabal
Also adds missing Haddock documentation.
=> Move types into own modules, for consistency

.stan.toml, package.yaml, src/GHC/Utils/GhcPkg/Main/Compat.hs, src/Stack/CLI.hs, src/Stack/ConfigCmd.hs, src/Stack/Options/ConfigEnvParser.hs, src/Stack/Options/ConfigSetParser.hs, src/Stack/Types/ConfigSetOpts.hs, src/Stack/Types/EnvSettings.hs, stack.cabal
=> Refactor Stack's config command

src/Stack/Build/Installed.hs, src/Stack/Build/Target.hs, src/Stack/BuildPlan.hs, src/Stack/Package.hs, src/Stack/Types/SourceMap.hs
Also adds missing Haddock documentation.
=> Refactor getDefault in Stack.BuildPlan.removeSrcPkgDefaultFlags

src/Stack/Build/Cache.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Ghci.hs, src/Stack/Lock.hs, src/Stack/Path.hs, src/Stack/SourceMap.hs
=> Add missing Haddock documentation

src/Stack/BuildInfo.hs, src/Stack/Config/ConfigureScript.hs, src/Stack/PackageFile.hs, src/Stack/Types/AddCommand.hs, src/Stack/Types/Cache.hs, src/Stack/Types/Config/Exception.hs, src/Stack/Types/DotConfig.hs, src/Stack/Types/GhcOptionKey.hs, src/Stack/Types/GhcOptions.hs, src/Stack/Types/GlobalOpts.hs, src/Stack/Types/PackageFile.hs
=> Add missing Haddock documentation.

src/Stack/Types/AllowNewerDeps.hs
=> Simplify deriving of instances

doc/commands/build_command.md, doc/commands/unpack_command.md, doc/configure/global_flags.md, doc/configure/yaml/non-project.md, doc/glossary.md, doc/topics/custom_snapshot.md, doc/tutorial/index.md, doc/tutorial/project_configuration.md
Improving documentation. See:
* #6751
=> Fix #6751 Be more specific about snapshots and GHC boot packages

.devcontainer/ghc-9.10.2/devcontainer.json, .devcontainer/ghc-9.12.2/devcontainer.json
=> Dev Containers: Update experimental GHC versions

.devcontainer/init
=> Dev Containers: Fix initializeCommand

ChangeLog.md, doc/configure/yaml/non-project.md, package.yaml, stack-ghc-9.12.2.yaml, stack-ghc-9.12.2.yaml.lock, stack.cabal, stack.yaml, stack.yaml.lock
=> Update for changes in pantry-0.11.0

ChangeLog.md, doc/configure/yaml/non-project.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Config.hs, src/Stack/Types/Config.hs, src/Stack/Types/ConfigMonoid.hs, tests/integration/tests/3940-base-upgrade-warning/Main.hs
=> Fix #6799 Add notify-if-base-not-boot and update warning

src/Stack/DependencyGraph.hs, src/Stack/Dot.hs, src/Stack/Ls.hs, src/Stack/Types/DependencyTree.hs
See:
* #6784 
Also introduces `DependencyGraph` synonym.
=> Re #6784 Refactor and reformat dot-related modules

src/Stack/Types/Build.hs
See commit 216c46eee8f843bea0581f5303d5aefe764c043b
=> Remove dead code

ChangeLog.md, src/Stack/Setup.hs
=> Treat GHC 9.12 and Cabal-3.14 as tested
