commercialhaskell/stack

.gitlab-ci.yml, etc/dockerfiles/stack-build/lts-12.0/Dockerfile
This also adds the gitlab-ci configuration to build lts-12.x images, and removes the gitlab-ci configuration for lts-10.x images (since there haven't been any of those for months now).
Tested by running the gitlab-ci job, confirming that the `lts-12.0` tag appeared on [docker hub](https://hub.docker.com/r/fpco/stack-build/tags/), and testing that `stack new --resolver=lts-12.0 x && cd x && stack docker pull && stack --docker build` works.
=> etc/dockerfiles: add stack-build:lts-12.x

ChangeLog.md, src/Stack/Build/Execute.hs
=> Pass --quickjump to Haddock for GHC 8.4 and later

doc/ghci.md
This documents the #2790 and #4148 bugs as we decided in #4177 to only
document this behavior for 1.8.1 release and solve them later.
=> Document that `stack ghci` works best only after `stack build`.

src/Stack/PrettyPrint.hs
This implements the suggestion in #4183. Tested on macOS, giving this 'after' result (see #4183 for the equivalent 'before' result):
=> Fix #4183 Make PrettyPrint styles background-agnostic

test/integration/tests/upload/Main.hs, test/integration/tests/upload/files/FakeHackage.hs, test/integration/tests/upload/files/gpg-disabled/gpg.bat, test/integration/tests/upload/files/gpg-disabled/gpg2.bat
See #4167 for context. This is an attempt to fix the upload integration test on Windows; currently I'm still getting a hanging process when running the real test, but not via a manual `stack runghc`.
=> Adapt upload integration test for Windows

src/test/Stack/Types/TemplateNameSpec.hs
This is a small spec to go along with https://github.com/commercialhaskell/stack/pull/4103.
This shows the behavior of template name parsing in the `stack new` command.  There are some significant differences when run on windows vs unix.
* [ x] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [ x] The documentation has been updated, if necessary.
I did install Stack on windows to write this, and if there are any Stack devs that run windows I would appreciate if you can confirm it passes on your machine.
=> Issue #4039 - Spec for template name parsing in `stack new`

test/integration/tests/upload/files/FakeHackage.hs
This seems the intended behavior and improves behavior on Mac.
The testing is what's described on https://github.com/commercialhaskell/stack/issues/4191#issuecomment-408705732, I'm fixing my GPG setup and rerunning integration tests.
=> upload integration test: Fix invocation to getAddrInfo

test/integration/tests/3942-solver-error-output/files/no-deps/package.yaml, test/integration/tests/3942-solver-error-output/files/one-deps/package.yaml, test/integration/tests/3942-solver-error-output/files/script.hs, test/integration/tests/3942-solver-error-output/files/test-stack.yml
Fixes #4178.
This creates two fake packages, rather than using a real one which might be included in stackage (as broke this test).
=> Fix integration test 3942-solver-error-output

ChangeLog.md, src/Stack/Config/Nix.hs
Hardcoding GHC versions for Nixpkgs makes assumptions which are frequently
violated: that the user has the latest Nixpkgs and that the user is using the
latest Stack. Instead of hardcoding the latest minor version in each major
branch, the latest minor version in the user's Nixpkgs is selected for the
wanted regular branch.
I tested this change against the test suite and by running `stack ghc -- --version` both inside and outside a project, against GHC versions that are and are not in my local copy of Nixpkgs.
=> Do not hardcode GHC versions for Nixpkgs

subs/pantry/src/Pantry/Hackage.hs
With this `stack build` seems to work for `xlsx`
=> No blob key check as archive could contain outdated cabal file

package.yaml, src/Path/CheckInstall.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Coverage.hs, src/Stack/DefaultStyles.hs, src/Stack/Ghci.hs, src/Stack/Options/Completion.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Package.hs, src/Stack/PrettyPrint.hs, src/Stack/Runners.hs, src/Stack/SDist.hs, src/Stack/Setup.hs, src/Stack/Types/Config.hs, src/Stack/Types/PrettyPrint.hs, src/Stack/Types/Runner.hs, src/Text/PrettyPrint/Leijen/Extended.hs, src/main/Main.hs, src/test/Network/HTTP/Download/VerifiedSpec.hs, src/test/Stack/ConfigSpec.hs, src/test/Stack/NixSpec.hs
These changes do not affect the existing functionality of stack but provide a foundation for the next steps of suggestion #4205.
After the changes, Stack's styles are implemented as type `Style` in new module `Stack.PrettyPrint`, which also defines a `StyleSpec` as `(Text, [SGR])` (the first item providing the name of the key) and `Styles` as `Data.Array.IArray.Array Style StyleSpec`. Package `array` is added as a dependency in `package.yaml`, accordingly.
Given the use of `cyan` in the original instance of `Display` for `(PackageName, NamedComponent)`, a new _style_ `PkgComponent` (with key `package-component`) is added to `Style`.
Given the use of `green` in `displayMilliseconds`, it is assumed the intended style was `Good`.
Functions like `StyleWarning`, `StyleError` can be, and are, …
=> Fix #4205 (Step 0): Annotate with Style, not [SGR]

doc/install_and_upgrade.md
Updates an outdated instruction for upgrading stack in Ubuntu and Debian.
=> Fixes #4234

ChangeLog.md, package.yaml, src/Stack/Options/GlobalParser.hs, src/Stack/Types/Config.hs, src/Stack/Types/StylesUpdate.hs
This builds on step 0 (commit https://github.com/commercialhaskell/stack/commit/68718a784a0eec52968540ea3de3885f1ae707a0). It adds the `--stack-colors=STYLES` global option. The functionality is primarily implemented via `readStyles` in module `Stack.Config`. `GlobalOptsMonoid` is extended to include `globalMonoidStyles`; a list of `(Style, StyleSpec)` that are then used to update the array that is `defaultStyles`.
24-bit colour is now a possibility and so package `colour` is added as a dependency in `package.yaml`.
`ChangeLog.md` is updated, accordingly.
Tested by building - `stack test` - on Windows 10 and using the new option.
=> Fix #4205 (Step 3): Add `--stack-colors=STYLES`

ChangeLog.md, src/Stack/Ls.hs, src/main/Main.hs
This builds on step 0 (commit https://github.com/commercialhaskell/stack/commit/68718a784a0eec52968540ea3de3885f1ae707a0). It adds `stack ls stack-colors` to the `stack ls` command, in module `Stack.Ls`. The command's functionality is provided by `listStylesCmd`. The rest of the changes add the `optparse-applicative` plumbing.
The `ls` command documentation, in module `Main`, is updated.
`ChangeLog.md` is updated.
Please also shortly describe how you tested your change. Bonus points for added tests! 
This has been tested by building - `stack test` - on Windows 10 and using the new function with its various options.
=> Fix #4205 (Step 5): Add `stack ls stack-colors`

subs/curator/app/Main.hs, subs/curator/package.yaml
Currently runs previous steps before the selected one. Should it behave like that or should only the chosen step be performed, or do we want to toggle that with a flag?
Ping @snoyberg
=> [pantry] curator CLI

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Ls.hs, src/Stack/Options/Completion.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Runners.hs, src/Stack/Types/Config.hs, src/Stack/Types/PrettyPrint.hs, src/Stack/Types/Runner.hs, src/Stack/Types/StylesUpdate.hs, src/Text/PrettyPrint/Leijen/Extended.hs, src/main/Main.hs, src/test/Network/HTTP/Download/VerifiedSpec.hs, src/test/Stack/ConfigSpec.hs, src/test/Stack/NixSpec.hs
This builds on step 0 (commit https://github.com/commercialhaskell/stack/commit/68718a784a0eec52968540ea3de3885f1ae707a0), step 3 (commit https://github.com/commercialhaskell/stack/commit/62866ceef2fafee00ebb034ab08751169bb0e8c8) and step 5 (commit https://github.com/commercialhaskell/stack/commit/3d388accc6862e082a0531e65fe109817d7a643c) and is the final major proposed commit that pulls everything together to implement #4205. It adds the `stack-colors:` non-project-specific option to `config.yaml` (or `stack.yaml`). The documentation in `yaml_configuration.md` is updated, accordingly.
To allow the composition of yaml and command line options, in module `Stack.Types.Runner`, `runnerStyles :: !Styles` becomes `runnerStylesUpdate :: !StylesUpdate`. Consequent changes are made throughout and …
=> Fix #4205 (Step 4): Add `stack-colors` to `config.yaml`

doc/yaml_configuration.md
Adds documentation, from commit https://github.com/commercialhaskell/stack/commit/ca7e3fd2ec13845c438209fe69629bb589bc3e93.
=> Fix #4205 Add documentation

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Build/Execute.hs, src/Stack/Config/Build.hs, src/Stack/Options/BuildMonoidParser.hs, src/Stack/Types/Config/Build.hs
=> Add the ddump-dir option/config value #4225

ChangeLog.md, src/unix/Stack/DefaultColorWhen.hs, src/windows/Stack/DefaultColorWhen.hs
Adopt the standard proposed at http://no-color.org/, that colour should not be added by default if the `NO_COLOR` environment variable is present, by adapting `defaultColorWhen` in module `Stack.DefaultColorWhen` (which varies depending on whether the operating system is Windows or Unix-like).
Tested on Windows 10 by building - `stack test` - and using the built tool, as below:
=> Fix (in part) #4204: Honour `NO_COLOR` variable

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Options/Completion.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Runners.hs, src/Stack/Types/Config.hs, src/Stack/Types/Runner.hs, src/main/Main.hs
This pull request allows the global option `--color=<WHEN>` to be set also in a yaml configuration file.
Tested on Windows 10 by building - `stack test` - and then using. Principally tested by reference to the output of the new `stack ls stack-colors` command, as follows:
* `stack ls stack-colors` gives a report with colour Examples (as expected)
* `stack --color=never ls stack-colors` gives a report without colour Examples (as expected)
* set `color: never` in `config.yaml`, `stack ls stack-colors` gives a report without colour Examples (as expected)
* set `color: never` in `config.yaml`, `stack --color=always ls stack-colors` gives a report with colour Examples (as expected)
* set `color: dummy` in …
=> Fix (in part) #4204: Add `color:` to `config.yaml`

doc/GUIDE.md
This commit replaces a reference to `stack list-dependencies`, which generates a deprecation warning, with `stack ls dependencies`, which doesn't.
=> list-dependencies is deprecated

src/unix/Stack/DefaultColorWhen.hs
Merged #4260 was missing some imports in the unix version.
Tested by building on macOS 10.13.6.
=> Repair PR #4260: Add imports to Stack.DefaultColorWhen

package.yaml, src/Stack/Setup.hs, src/unix/System/Uname.hsc, src/unix/cbits/uname.c
Due to https://github.com/commercialhaskell/stack/issues/3515 I wasn't able to test if Stack builds with this change, but changes made for `bindings-uname` do work.
=> Pull bindings-uname package into Stack and fix it to work with FreeBSD.

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Ls.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Types/Config.hs
This implements the final part of #4205. Although it is 'cosmetic', it is in the tradition of GHC and other Haskell tools (eg hlint) accepting alternative spellings.
This pull request allows the British English spelling of 'color' (colour) as aliases. Implemented at the command line for `--color`, `--stack-colors` and `stack ls stack-colors`. Implemented in yaml configuration files for `color:` and `stack-colors:` (in each case, the American spelling is the alternative that has priority).
The documentation in `yaml_configuration.md` is updated, accordingly.
Tested on macOS 10.13.6 and on Windows 10 by building - `stack test` - and then using the built tool, including:
* `stack --help`
* `stack ls …
=> Fix #4205 (step 6): Alias 'colour' for 'color'

ChangeLog.md, src/Stack/Nix.hs, test/integration/tests/4095-utf8-pure-nix/Main.hs, test/integration/tests/4095-utf8-pure-nix/files/ShowUnicode.hs, test/integration/tests/4095-utf8-pure-nix/files/package.yaml, test/integration/tests/4095-utf8-pure-nix/files/stack.yaml
=> Use en_US.UTF-8 for pure nix mode

ChangeLog.md, subs/pantry/src/Pantry/Archive.hs, subs/pantry/test/Pantry/ArchiveSpec.hs
=> Fix takeSubDir to match whole directory names

src/Stack/Build/Source.hs, src/Stack/Build/Target.hs, src/Stack/Dot.hs, src/Stack/Ghci.hs, src/Stack/Options/BuildParser.hs, src/Stack/Options/PackageParser.hs, src/Stack/Types/Config/Build.hs
This replaces a case of "Maybe blindness" (like boolean blindness),
using descriptive data constructors to indicate what the Nothing and
Just cases mean.
=> ApplyCLIFlag

src/Stack/Freeze.hs, src/Stack/Snapshot.hs, src/Stack/Types/BuildPlan.hs, src/Stack/Unpack.hs, subs/curator/app/Main.hs, subs/curator/src/Curator/Snapshot.hs, subs/curator/src/Curator/Unpack.hs, subs/pantry/src/Pantry.hs, subs/pantry/src/Pantry/Types.hs
A single snapshot YAML file is in fact just a layer in the creation of a
snapshot. In the current code, Stack will ask Pantry to perform the
parsing of the individual layers, and then combine the layers into its
own representation of a snapshot. This means that the code for this is
less easily testable, and other tooling (e.g., stack2nix) will not have
access to this logic.
This commit separates out the idea of a snapshot and a snapshot layer at
the type level. The next commit will be a simple change to the Stack
codebase to use the updated names, but keep the layer combining logic it
currently has. A future, somewhat more involved change will drop the
duplicated logic from Stack entirely and rely on Pantry's logic
exclusively.
=> Separate out Snapshot and SnapshotLayer

src/Stack/Build/Source.hs, src/Stack/Ghci.hs, src/Stack/Package.hs, src/Stack/Types/Package.hs, test/integration/tests/4270-files-order/Main.hs, test/integration/tests/4270-files-order/files/cbits-ordering.cabal, test/integration/tests/4270-files-order/files/cbits/a_dependent.c, test/integration/tests/4270-files-order/files/cbits/a_dependent.h, test/integration/tests/4270-files-order/files/cbits/the_dependency.c, test/integration/tests/4270-files-order/files/src/Lib.hs, test/integration/tests/4270-files-order/files/stack.yaml
While investigating issue #4270 I came to a conclusion what the reason was indeed https://ghc.haskell.org/trac/ghc/ticket/13786 in conjunction with the fact that stack (unlike cabal-install) uses `Set` datatype while producing arguments list for ghci which leads to manually crafted c files order to be discarded. I tried to replace Set with simple lists and the issue seems gone. Tests run fine.
Could some of the developers have a look at this and either review the changes or suggest another way to deal with the issue?
=> Do not use Set for files

ChangeLog.md, src/Stack/IDE.hs, src/main/Main.hs
With the `--cabal-files` flag active `stack ide packages` will print the paths to packages' cabal-files instead of just the package name. Having the full path to all packages within a Stack project will allow me to expose a more unified project representation in  [`cabal-helper`](https://github.com/DanielG/cabal-helper) in light of upcoming `cabal new-build` support.
---
=> Add `--cabal-files` flag to `ide packages` command

doc/GUIDE.md
`We've already used 'stack exec' used multiple times in this guide.` should be `We've already used 'stack exec' multiple times in this guide.`
=> removed typo in GUIDE.md

ChangeLog.md, package.yaml, src/Stack/Package.hs, src/Stack/SDist.hs, stack-nightly.yaml, stack.yaml
=> Use Cabal 2.4 for the 1.9 branch

ChangeLog.md, subs/pantry/src/Pantry/Repo.hs
Related to https://github.com/commercialhaskell/stack/issues/1764 and a subtle fix for what was implemented in https://github.com/commercialhaskell/stack/pull/1852, this changes the logic for packages identified by git locations so that submodules are properly updated. The process now looks like this:
1. clone the repo
2. `reset --hard` to a specific commit
3. update submodules (recursively)
The problem with the existing implementation is that a hard reset (`git reset --hard`) doesn't update submodules so the state of submodules in a package will always be whatever's on the default branch.
I tested a similar version of this patch against the [v1.9.0.1 …
=> Update git package submodules after clone and reset

subs/pantry/src/Pantry/Repo.hs
Commit 8bda49d9bd6030920a6c23aa82fcc98b6cd8137b introduced the `git submodule` command into `Pantry.Repo.getRepo'`. Tests suggest that, on Windows 10, this suffers from the same upstream bug as `git clone` (see https://github.com/commercialhaskell/stack/issues/3992#issuecomment-401207463 .)
This pull request proposes the same 'fix'; on Windows 10, re-enable ANSI capability after the `git submodule` command is used.
Tests on Windows 10 suggest the fix works as intended. (Tested by adding some temporary dummy lines of code at the relevant point to output ANSI codes to `stdout` and seeing how the native Windows 10 console deals with them.)
Please include the following …
=> Fix #3797 (Windows 10: re `git submodule` usage)

src/Stack/Init.hs
`stack` version: `master` as of `a299ac652fde49d3b4b6a199c1a206220826da68`
Stack no longer parses the `location` syntax, but still suggests it to users in examples in a `stack.yaml` produced by `stack new`. 
This PR moves the suggestions to an improved comment section for `extra-deps`.
=> Remove suggestions for legacy `packages` syntax

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Types/Config.hs, src/test/Stack/ConfigSpec.hs, subs/pantry/src/Data/Aeson/Extended.hs, subs/pantry/src/Pantry/Types.hs, subs/pantry/test/Pantry/TypesSpec.hs
=> Make snapshot: a synonym for resolver

etc/scripts/get-stack.sh
Allows users with Centos 6 who have an lsb_release command to be pointed to the proper gmp4 linked binary download when using `curl -sSL https://get.haskellstack.org | sh`
If a CentOS user has command `lsb_release`, the VERSION variable for `distro_info()` will be "6.xx", not just "6".  Since `try_lsb()` is the first test done in `distro_info()`, if the user has `lsb_release`, and any version of CentOS 6, the case statement will not point the user to the correct gmp linked binary.
NOTE:  I can't perform the test for stack 1.9 because an update to the `sudocmd()` function fails... not sure if that's just a temporary edit to the function, but will need to be fixed.  Happy to make another pull request for that if needed.
On testing:  I tested by only running the distro_info() function at the …
=> Update get-stack.sh for centos 6

doc/faq.md
Add FAQ for macOS linker error due to LLVM and Apple Clang binaries both in `PATH`
=> Add FAQ for #4328

ChangeLog.md, etc/scripts/get-stack.sh
KDE Neon is based on Ubuntu, so the Ubuntu installer should work fine.
=> Support KDE Neon distribution

doc/install_and_upgrade.md
Adding documentation update per issue #4349, to help simplify the installation experience for users who are located in mainland China. I decided to add this to the "installation" section instead of the "yaml configuration" section, since stack new basically can't get up and running until this has been accounted for.
===================
=> Update install page for China

ChangeLog.md, package.yaml, src/main/Main.hs, stack-lts-12.yaml, stack-nightly.yaml, stack.yaml
=> Compile without a Git dir #4364

ChangeLog.md, src/Stack/New.hs, test/integration/lib/StackTest.hs, test/integration/tests/variables-in-template-file-names/Main.hs, test/integration/tests/variables-in-template-file-names/files/.gitignore, test/integration/tests/variables-in-template-file-names/files/template.hsfiles
=> Allow variables in filenames in templates

ChangeLog.md, src/Stack/Dot.hs, src/Stack/Options/DotParser.hs, test/integration/tests/4101-dependency-tree/Main.hs, test/integration/tests/4101-dependency-tree/files/files.cabal, test/integration/tests/4101-dependency-tree/files/src/Main.hs, test/integration/tests/4101-dependency-tree/files/stack.yaml
Fixes #4101 
I think this is pretty discoverable by `stack ls dependencies --help` so I didn't add anything to the docs.
Unfortunately, manually. The `listDependencies` function was directly printing and had no tests and I built on top of that without much thought of testing. So, I couldn't add any automated tests.
Here is output from `stack ls dependencies --depth=0 --tree` on the stack repository:
```
Packages
├── curator mkVersion [2,0,0,0]
├── pantry mkVersion [0,1,0,0]
└── stack mkVersion [1,10,0]
```
Depth=1 onwards, the output becomes really large, so I will not paste it here.
Additionally, if you could me some pointers around how to test this, I would be happy to add tests.
=>  Add option to print dependencies as tree

ChangeLog.md, src/Stack/Config.hs, src/Stack/Runners.hs, src/Stack/Setup.hs, src/Stack/Types/Config.hs, src/main/Main.hs, test/integration/tests/4181-clean-wo-dl-ghc/Main.hs, test/integration/tests/4181-clean-wo-dl-ghc/files/foo.cabal, test/integration/tests/4181-clean-wo-dl-ghc/files/stack.yaml
`stack clean` always download the ghc even if it already deleted.
```shell
$ stack --version
Version 1.10.0, Git revision 65dd1d673a75d867325bb1c70f5170386900dd80 (dirty) (6415 commits) x86_64 hpack-0.29.6
$ stack clean
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Preparing to download ghc-7.10.2 ...^C
```
=> To prevent download ghc when using `stack clean`.

doc/build-overview.md
This follows the changes appeared in #617
* [ x ] The documentation has been updated, if necessary.
It's a documentation fix.
=> Assume non-existing flags as errors

ChangeLog.md, src/Stack/Package.hs, test/integration/IntegrationSpec.hs, test/integration/lib/StackTest.hs, test/integration/tests/4270-files-order/files/stack.yaml
This is a fix for a test `4270-files-order`, the main point of it is in af36e04 other commits improve Stack integration tests a bit.
Integration tests succeed locally.
=> Fix test 4270

test/integration/tests/4101-dependency-tree/Main.hs, test/integration/tests/4101-dependency-tree/files/stack.yaml
That's a fix for a new test. Fix in #4402 also resolved a similar problem (apart from fixing GHCi behavior) - its stack was using LTS-12 while integration tests use `install-ghc:false` - https://github.com/commercialhaskell/stack/blob/ca9ee4c6a5ca2474f627e814e8463bb1b9dcae94/test/integration/IntegrationSpec.hs#L84
I guess it's worth to check new integration tests when they appear whether they use the default resolver. This way we could prevent this kind of problem.
=> Use default resolver for test 4101-dependency-tree

dot-dir-locals.el
Removed in this PR option was made obsolete in hindent 5
emacs-specific change, tested locally
=> Remove obsolete hindent-style

doc/GUIDE.md, doc/README.md, doc/SIGNING_KEY.md, doc/architecture.md, doc/build_command.md, doc/coverage.md, doc/custom_snapshot.md, doc/dependency_visualization.md, doc/docker_integration.md, doc/faq.md, doc/ghci.md, doc/ghcjs.md, doc/install_and_upgrade.md, doc/maintainers/ghc.md, doc/maintainers/msys.md, doc/maintainers/releases.md, doc/maintainers/team_process.md, doc/nix_integration.md, doc/nonstandard_project_init.md, doc/shell_autocompletion.md, doc/stack_yaml_vs_cabal_package_file.md, doc/travis_ci.md, doc/yaml_configuration.md
These changes ought to go to the `stable` branch but the bot that submitted [PR #4436](https://github.com/commercialhaskell/stack/pull/4436) was targeting `master`.
---
=> Replace RawGit CDN for doc warning SVG with jsDelivr - see #4436

.travis.yml, ChangeLog.md
Targeting stable as this means all relevant branches can straightforwardly benefit from the change.
This may require a little back and forth with CI.
I suggest we also change the travis templates, too, before merging.
=> Have travis build after trusty support is deprecated

src/Stack/Setup.hs
Expanded the already present workaround for finding libtinfo on Arch linux (when `ldconfig -p` doesn't find it) to also work in 64 bit Slackware.
Basically also searches the directory `/usr/lib64/` in addition to `/usr/lib/` for libtinfo or ncurses libraries (see discussion in #4362 and others).
Do we want to add `/lib/` and `/lib64/` or any other paths to the list of checked directories?
I haven't written any haskell in a long time (I stumbled upon this issue while trying to get back into it) so any suggestions and criticisms on the code are more than welcome; it actually doesn't look really readable to me as is but considering it is a (temporary) workaround for such a limited issue I think it doesn't matter.
I don't think this change requires a changelog or documentation update since it …
=> Workaround for libtinfo detection on Slackware64 14.2, solves #4362.

src/Stack/Setup.hs
Fixes #4466 
I'm not quite sure how to cover this in tests: it appears that currently our integration tests don't clean `$PATH` and making that looks to be a noticeable effort: for that we need to check all of the current integration tests and fix any that will fail. @snoyberg I guess it makes sense to do that in a separate issue?
=> use proper $PATH (with GHC available) doing source map hashing

doc/travis-simple.yml
Travis CI is deprecating container based build environments. See https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures for more.
Tested by pushing the configuration to travis. See [this sample travis build](https://travis-ci.org/IsumiF/leetcode-hs/jobs/472522777/config).
=> Choose virtual machine based infrastructure

ChangeLog.md, src/Stack/IDE.hs, src/main/Main.hs
Backport to of #4312 to `stable`. I was hoping this would have landed in a realease by now, didn't realise there was a big project happening on master.
FYI: This will be necessary for haskell-ide-engine to keep ineroperating with Stack once cabal new-build support lands there.
=> Add `--cabal-files` flag to `ide packages` command (backported to stable)

ChangeLog.md, src/Stack/IDE.hs, src/main/Main.hs
The `stack ide` commands use `logInfo` to write output. This seems to end up on
stderr, which is quite annoying to pick up for tools. This new flag sends output
to stdout instead.
This is a follow-up to #4477.
Since it loolks like `stable` gets merged into `master` occationally I am pushing this to `stable` first and then sending a PR with a hand written merge into `master` since just having two unrelated commits on the two branches seems to have [caused problems](https://github.com/commercialhaskell/stack/commit/530219ad56907a3806006ce1515a408da7df9fdc) before. Not sure this is the right thing to do, I'm open to suggestions.  PR: #4483
=> Add --stdout flag to `stack ide` commands

doc/faq.md
Added procedure to re-enable GHC inserting -no-pie automatically if it is disabled by default.
This solution is described in #4497.
=> Add solution to "-fPIC" section in faq.md

ChangeLog.md, snapshot.yaml
lts-11.22 includes fsnotify-0.2.1.1, which listens to Modify events on
Linux rather than CloseWrite events. For many applications the
difference is neglible because writing a file will result in both
events, but if you run stack inside of docker on Mac this breaks
the --file-watch option because the file sharing integration only
emits Modify events, never CloseWrite events.
fsnotify-0.3.0.1 changed to listen to Modify events rather than
CloseWrite events. Switching to the new version fixes the issue.
I built stack against fsnotify-0.2.1.1 inside a docker container and verified that `--file-watch`
did *not* recompile when editing a file from MacOS on a …
=> Fixes #4506 - Add fsnotify-0.3.0.1 to snapshot.yml

subs/pantry/src/Pantry/Storage.hs, subs/pantry/src/Pantry/Types.hs
Tested it manually with a DB created with Stack sources before #4439 was merged
Fixes #4519 
@snoyberg is it OK to reference `$STACK_ROOT` in Pantry error messages? It doesn't look clean to me but I'm not sure how to deal with it better in this case
=> No FK checks during migrations and better error if migration fails

ChangeLog.md, src/Stack/Script.hs
Here's an example.  The contents of `~/tmp/hmm.hs` is:
```haskell
#!/usr/bin/env stack
-- stack --resolver lts-13.0 script --compile --ghc-options "-i"
main :: IO ()
main = putStrLn "hmm
```
running it results in
```
ghc: unrecognised flag: --ghc-arg=-i                                                                          
Usage: For basic information, try the `--help' option.
Received ExitFailure 1 when running
Raw command: /home/mgsloan/.stack/programs/x86_64-linux/ghc-8.6.3/bin/ghc -hide-all-packages -fdiagnostics-color=always -packagebase --ghc-arg=-i /home/mgsloan/tmp/hmm.hs
Run from: /home/mgsloan/tmp/
```
Note that `stack --resolver lts-13.0 script --ghc-options "-i"` (no use of `--compile`)  works fine
=> Fix use of "--ghc-options" with "stack script --compile"

.azure/azure-linux-template.yml, .azure/azure-nightly-template-linux.yml, .azure/azure-nightly-template-osx.yml, .azure/azure-nightly-template-windows.yml, .azure/azure-osx-template.yml, .azure/azure-windows-template.yml
=> Simplify Azure CI config and match it up with Stack docs

ChangeLog.md, src/Stack/Script.hs
This issue was brought to my attention by https://github.com/rcook .  The primary problem is that stack scripts can only import modules if the script is run from the same directory as the modules.  However, I realized that this implies a gnarlier issue, which is that since `-i` isn't being passed to `runghc`, it will use the work dir as a search dir for imports.
This also addresses part of the problem described in #3377 , which was a difference in how imports are treated when `--compile` is used.
Here's a concrete example.  The contents of `~/tmp/hmm.hs` is
```haskell
#!/usr/bin/env stack
-- stack --resolver lts-13.0 script
import Yargh
main :: IO ()
main = yargh
```
The contents of `~/tmp/Yargh.hs` is
```haskell
module Yargh where
yargh :: IO ()
yargh = putStrLn "works!"
```
The contents …
=> Have "stack script" set import search path #3377

.azure/azure-nightly-template-linux.yml, .azure/azure-nightly-template-osx.yml, .azure/azure-nightly-template-windows.yml
Recently the integration test has been getting timeouts, so this PR bumps it to 4 hours (previously it was 3 hour).
=> Bump azure timeouts

ChangeLog.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Source.hs, src/Stack/Build/Target.hs, src/Stack/Ghci.hs, src/Stack/Setup.hs, src/Stack/SourceMap.hs, src/Stack/Types/SourceMap.hs, subs/curator/src/Curator/Snapshot.hs, subs/pantry/package.yaml, subs/pantry/pantry.cabal, subs/pantry/src/Pantry.hs, test/integration/tests/345-override-bytestring/files/stack.yaml
Tested manually, plan to run integration tests.
Failure to build global packages as targets results in 2 errors (using `stack.yaml` from #4510 with `time` overriden):
```
$ stack build directory --dry-run
Error: While constructing the build plan, the following exceptions were encountered:
Can't use GHC boot package directory when it has an overriden dependency, you need to add the following as explicit dependencies to the
project: 
unix
Some different approaches to resolving this:
* Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build configuration. This can be
convenient when dealing with many complicated constraint errors, but results may be unpredictable.
Plan construction failed. …
```
=> Globals (GHC boot packages) pruning

src/Stack/Build/Target.hs
This change assumes #4547 to get merged soon.
Excluding these revisions shaves off some time from Stack invocation, e.g. without it I see for `time stack path`:
```
real	0m3,561s
user	0m3,292s
sys	0m0,321s
```
and after applying it:
```
real	0m1,628s
user	0m1,602s
sys	0m0,077s
```
=> No latest global revisions for target parsing

src/Stack/Build/Execute.hs
CI didn't run on the final commit. I've learned to run `hlint` _before_ I push!
=> Fix hlint warning introduced in #4544

src/Stack/Build/ConstructPlan.hs
This in addition to #4557 shaves off some added slowness in #4479 
On `master` I get locally for `time stack exec -- stack build --dry-run`:
```
real	0m17,832s
user	0m17,737s
sys	0m0,228s
```
With this applied:
```
real	0m5,300s
user	0m5,184s
sys	0m0,240s
```
=> Postpone revision retrieval for executables until they're needed

src/Stack/Build/ConstructPlan.hs
Actually I've fixed it earlier in https://github.com/commercialhaskell/stack/tree/curator-stackage-build-with-stack as I caught it during Stackage build. And it was me who added it as a part of #4479 - sorry
Fixes #4572
=> Don't error out on missing latest revision while constructing a build plan

ChangeLog.md, doc/architecture.md, doc/faq.md
Relates to #3049, #4475, #4488.
=> Document how stack uses the Cabal library in Architecture.md

subs/pantry/src/Pantry.hs, subs/pantry/src/Pantry/Archive.hs, subs/pantry/src/Pantry/Hackage.hs, subs/pantry/src/Pantry/Repo.hs
=> Retrieve (and cache) archive once when doing location completion

src/Stack/Build/Execute.hs, test/integration/tests/4453-detailed/files/test/Spec.hs
It fixes a test from #4498 and the implementation it was supposed to test.
Fixes #4577
=> Detailed test suite type fix

src/Stack/Build/ConstructPlan.hs
Tested manually. Also run integration tests and fixed #4585 along the way.
Fixes #4221 
Probably we could add example from #4221 as a new integration test
=> Proper filter for tasks required by dependencies

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Installed.hs
Fixes #4578 
With https://github.com/commercialhaskell/stack/blob/master/doc/build-overview.md being implemented we now have local installs of snapshot packages getting marked as mutable, i.e. having mutable (local) dependencies. This change removes reinstallation of those packages from snapshots.
=> Allow local installs of mutable snapshot packages

subs/pantry/src/Pantry/Repo.hs, subs/pantry/src/unix/System/IsWindows.hs, subs/pantry/src/windows/System/IsWindows.hs
Both the pantry and stack packages had the same module name, which
prevented `stack ghci` from working. This rename resolves the problem.
=> Rename duplicated System.Permissions module

src/Stack/Build/Haddock.hs
I've tested it using https://github.com/qrilka/test-internal-haddock. Without this patch I get
```
Updating Haddock index for local packages and dependencies in
/home/qrilka/ws/h/stack-tests/test-internal/.stack-work/install/x86_64-linux-tinfo6/d542db1939a9b706609e6e30f7207fbc656b1f8b91ec7d78f8c9c350b2157d09/8.6.3/doc/all/index.html
Received ExitFailure 1 when running
Raw command: /home/qrilka/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.3/bin/haddock --optghc=-package-db=/home/qrilka/.stack/snapshots/x86_64-linux-tinfo6/d542db1939a9b706609e6e30f7207fbc656b1f8b91ec7d78f8c9c350b2157d09/8.6.3/pkgdb --optghc=-package-db=/home/qrilka/ws/h/stack-tests/test-internal/.stack-work/install/x86_64-linux-tinfo6/d542db1939a9b706609e6e30f7207fbc656b1f8b9 …
```
=> Fix building haddocks for packages with internal libraries

ChangeLog.md, src/Options/Applicative/Complicated.hs, src/Stack/Config.hs, src/Stack/ConfigCmd.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Options/ScriptParser.hs, src/Stack/Script.hs, src/Stack/Types/Config.hs, src/main/Main.hs, test/integration/tests/relative-script-snapshots/Main.hs, test/integration/tests/relative-script-snapshots/files/subdir/script.hs, test/integration/tests/relative-script-snapshots/files/subdir/snapshot.yaml, test/integration/tests/script-extra-dep/Main.hs, test/integration/tests/script-extra-dep/files/script.hs
Builds on top of #4591, since otherwise we'd have significant merge conflicts.
=> Script extra deps

ChangeLog.md, src/Options/Applicative/Complicated.hs, src/Stack/Config.hs, src/Stack/ConfigCmd.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Script.hs, src/Stack/Types/Config.hs, src/main/Main.hs, test/integration/tests/relative-script-snapshots/Main.hs, test/integration/tests/relative-script-snapshots/files/subdir/script.hs, test/integration/tests/relative-script-snapshots/files/subdir/snapshot.yaml
Previously, any relative paths in a script's --resolver flag would be
considered relative to the current working directory. It's more logical
and consistent to have it relative to the directory the script lives in.
This makes the change.
Possible argument: it's a bit weird to put the resolver root into the
GlobalOptsMonoid value. Overall it seems like the best option to me, but
I'm open to other approaches.
=> Proper relative paths for script resolvers

ChangeLog.md, src/Stack/Ghci.hs
Turns
1. Package `p' component exe:myexe with main-is file ...
into
1. Package `p' component p:exe:myexe with main-is file ...
so that you can easily copy-paste it into
stack ghci p:exe:myexe
---
=> stack ghci: Make shown options easily copy-pastable.

doc/pantry.md, src/Stack/Config.hs, src/Stack/Ghci.hs, src/Stack/Types/BuildPlan.hs, src/Stack/Types/SourceMap.hs, subs/curator/app/Main.hs, subs/curator/src/Curator/Snapshot.hs, subs/pantry/src/Pantry.hs, subs/pantry/src/Pantry/Types.hs
It doesn't seem to match our overall approach to other config files.
Instead of giving a user-friendly name, I've modified the one place that
was displaying the name to instead display the location of the snapshot.
=> Remove names from snapshots

ChangeLog.md, subs/pantry/src/Pantry/Repo.hs, test/integration/tests/git-submodules/Main.hs
Add support for Git submodules (recursive or not) in Pantry. Useful when a git repository containing submodules is used as a Stack "extra-deps".
A test has been added: it tries to `stack setup` a package that has an "extra-deps" on a package contained in a sub-submodule of a Git repo.
Also export the function `withRepo` that I use to implement #4567.
=> Add support for Git repositories with submodules

doc/lock_files.md
=> Add documentation for lock files

subs/pantry/src/Pantry/Types.hs
Since we no longer require this field, the previous code would spit out
a warning if it was present. This is extremely noisy for a field that
used to be required. Instead: just ignore the field if present.
=> Avoid a warning for names in snapshots

ChangeLog.md, src/Stack/Clean.hs, src/Stack/Config.hs, src/Stack/Constants/Config.hs, src/Stack/Runners.hs, src/Stack/Setup.hs, src/Stack/Types/Config.hs, src/main/Main.hs
When running `stack clean`, the entire .stack-work/dist directory will
now be deleted, not just the subdirectory for the current GHC/Cabal
combination.
=> stack clean does not need ghc-pkg (fixes #4480)

test/integration/tests/script-extra-dep/files/script.hs
This PR fixes this failure:
``` shellsession
Running test script-extra-dep
Running: /home/sibi/.local/bin/stack script.hs
Error: While constructing the build plan, the following exceptions were encountered:
In the dependencies for acme-missiles-0.3:
stm needed, but the stack configuration has no specified version  (latest matching version is 2.5.0.0)
needed since acme-missiles is a build target.
Some different approaches to resolving this:
* Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build configuration. This can be convenient when dealing with many
complicated constraint errors, but results may be unpredictable.
* Recommended action: try adding the following to your extra-deps in …
```
=> Fix test failure for script-extra-dep

test/integration/tests/relative-script-snapshots/files/subdir/snapshot.yaml
`stm` package is one of the dependency of `acme-missiles`, so that
also needs to be added as part of `packages` section of the
`snapshot.yaml` file.
=> Fix test failure for relative-script-snapshots

test/integration/tests/mutable-deps/files/filepath-1.4.1.2/System/FilePath/Internal.hs
Without this, this results in an build error like this:
``` shellsession
$ ./run-single-test.sh mutable-deps
Running test mutable-deps
Running: /home/sibi/.local/bin/stack build
directory-1.3.0.2: unregistering (missing dependencies: filepath)
filemanip-0.3.6.3: unregistering (missing dependencies: directory, filepath)
filepath-1.4.1.2: unregistering (local file changes: System/FilePath/Internal.hs)
files-1.0.0: unregistering (missing dependencies: filemanip)
filepath-1.4.1.2: configure (lib)
filepath-1.4.1.2: build (lib)
--  While building package filepath-1.4.1.2 using:
/home/sibi/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.0.1.0 build lib:filepath --ghc-options " -ddump-hi -ddump-to-file"
Process exited …
```
=> Fix integration test for mutable-deps

doc/GUIDE.md, src/Stack/Clean.hs, src/Stack/Options/CleanParser.hs, src/main/Main.hs, test/integration/tests/3863-purge-command/Main.hs, test/integration/tests/3863-purge-command/files/new-template.cabal, test/integration/tests/3863-purge-command/files/src/Lib.hs, test/integration/tests/3863-purge-command/files/stack.yaml
Fixes #3863 and potentially fixes #2278 
I tested out `stack clean` and `stack purge`. It seems like theyre doing what they should be. Also added a small spot in the guide.md explaining the commands a little more indepth.
=> Make stack clean be more thorough by default

src/Stack/Runners.hs, src/Stack/Types/Config.hs, src/main/Main.hs
=> SkipDocker data constructor never used

ChangeLog.md, mkdocs.yml, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Source.hs, src/Stack/Docker.hs, src/Stack/Types/Compiler.hs
=> Docker: fix pull missing images with `--docker-auto-pull` (fixes #4598)

src/Stack/Build/Target.hs, src/Stack/Config.hs, src/Stack/ConfigCmd.hs, src/Stack/Freeze.hs, src/Stack/Ls.hs, src/Stack/Options/Completion.hs, src/Stack/Path.hs, src/Stack/Runners.hs, src/Stack/Setup.hs, src/Stack/Solver.hs, src/Stack/Types/Config.hs, src/Stack/Upgrade.hs, src/main/Main.hs, src/test/Stack/ConfigSpec.hs, src/test/Stack/NixSpec.hs
This is an internal cleanup that removes some unneeded data types and
paves the way for future simplifications. There should be no behavior
changes from this change.
=> Remove the MiniConfig and LoadConfig data types

.azure/azure-nightly-template-linux.yml, .azure/azure-nightly-template-osx.yml, .azure/azure-nightly-template-windows.yml
This will fix integration tests (like `stack-init-solver`)
which depends on the cabal executable.
I tested that this PR works on a separate CI job here:
https://dev.azure.com/psibi2000/stack-issue-debug/_build/results?buildId=737
=> Bring cabal-install executable into $PATH for integration test

src/Stack/Config.hs, src/Stack/ConfigCmd.hs, src/Stack/FileWatch.hs, src/Stack/Hoogle.hs, src/Stack/Ls.hs, src/Stack/Options/Completion.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Path.hs, src/Stack/Runners.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/Types/Config.hs, src/Stack/Upgrade.hs, src/main/Main.hs, src/test/Stack/ConfigSpec.hs, src/test/Stack/NixSpec.hs
This yet again avoids behavioral changes, and opens the way for future
cleanups.
=> Use RIO Runner instead of explicit GlobalOpts

.azure/azure-nightly-template-osx.yml, package.yaml, subs/pantry/src/Pantry/Repo.hs, test/integration/lib/StackTest.hs, test/integration/tests/git-submodules/Main.hs
Summary of changes:
* Brings GNU Tar in the OSX environment
* Add --force-local option to the Tar args.
* Make the test code portable. ( I was guessing that the code was failing in Windows because of all the `runShell` and converted it to proper Haskell code. But I guess that's not necessarily required)
I tested the code changes in another CI and this code seems to work fine: https://dev.azure.com/psibi2000/stack-issue-debug/_build/results?buildId=758
=> Fix nightly test for git-submodules

ChangeLog.md, src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Source.hs, src/Stack/Dot.hs, src/Stack/Ls.hs, src/Stack/Options/DotParser.hs, src/Stack/Package.hs, src/Stack/Runners.hs, src/Stack/SourceMap.hs, src/Stack/Types/Config.hs, src/Stack/Types/Package.hs, src/main/Main.hs
The previous approach in #4405 would no longer work, due to @qrilka's explanation in https://github.com/commercialhaskell/stack/pull/4405#issuecomment-473820049. This implementation adds a new flag `--global-hints` which allows the user to bypass the need for an installation of GHC. We could arguably flip the default to not requiring GHC to be installed.
This will close #4390.
=> Make dot and ls dependencies not require GHC

src/Stack/Build/ConstructPlan.hs
Before:
```
* Recommended action: try adding the following to your extra-deps in /Users/yom/forks/servant/stack.yaml:
aeson-1.4.2.0@sha256:8166752a9669597db375343df19805069595fed9c613f98504e418849f40fe18
attoparsec-iso8601-1.0.1.0@sha256:acba3fc2fcd8b9b3177219c44ca26c0dc0f32e4af9cfaafc0845786fc5f488ef
free-5.1@sha256:71aa48c5a5dde71ed2a7f3d1d23c6d3a66580859444f55c8b38dd1bb205aa298
http-types-0.12.3@sha256:f35229edb1bc7b3ae27f961b2407dadb5bfa69d43a8f5337ab46cdc79ca4afe9
lens-4.17@sha256:534febcd710980b3c30efe12813e865b09fc6086a4ed6b7a6a8885f27caee3a6
semigroupoids-5.3.2@sha256:7a00aa24d8129b153f19991b96341e6f725ba77cef46b151c84d6dac1d12b47e
tagged-0.8.6@sha256:b5e1de3b14ff198b548928f686e5e8783301dc231413f751c23f4ee10cd47a7c
```
After:
```
* Recommended action: try adding the following to …
```
=> Print "try adding ... to your extra-deps" as YAML

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Source.hs, src/Stack/BuildPlan.hs, src/Stack/GhcPkg.hs, src/Stack/Init.hs, src/Stack/PackageDump.hs, src/Stack/Setup.hs, src/Stack/Snapshot.hs, src/Stack/Solver.hs, src/Stack/SourceMap.hs, src/Stack/Types/Config.hs, src/test/Stack/PackageDumpSpec.hs
There may be additional places where the typeclass needs to be added as
a constraint, I don't claim to have found all cases.
=> Introduce the HasCompiler typeclass (fixes #4639)

ChangeLog.md, src/Stack/ConfigCmd.hs, src/Stack/Setup.hs, src/main/Main.hs, test/integration/tests/620-env-command/Main.hs, test/integration/tests/620-env-command/files/.gitignore, test/integration/tests/620-env-command/files/Main.hs, test/integration/tests/620-env-command/files/run.sh
=> Add the config env command (fixes #620)

ChangeLog.md, doc/yaml_configuration.md, subs/pantry/src/Pantry.hs, subs/pantry/src/Pantry/Hackage.hs, subs/pantry/src/Pantry/Types.hs
* [X ] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [X ] The documentation has been updated, if necessary.
This change simply exposes the same functionality which cabal already implements and exposes using "--ignore-expiry" flag.
=> Implemented "ignore-expiry" flag as in "cabal --ignore-expiry

ChangeLog.md, src/Stack/Build/Execute.hs
Tested manually on an intermediate Stackage snapshot (`lens` vs `lenz` ambiguity in `language-nix` tests)
This overrides #4533 and makes  https://github.com/sol/doctest/pull/218 unnecessary
=> Use GHC_ENVIRONMENT to resolve module name ambiguity in doctests

src/Stack/Build.hs, src/Stack/Constants.hs, src/Stack/Docker.hs, src/Stack/Dot.hs, src/Stack/Ghci.hs, src/Stack/Hoogle.hs, src/Stack/Ls.hs, src/Stack/Nix.hs, src/Stack/Options/Completion.hs, src/Stack/Path.hs, src/Stack/Runners.hs, src/Stack/SDist.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/Upgrade.hs, src/main/Main.hs
Following discussion on #4636, it looks like the user file locking is no longer needed, and we can make Docker/Nix an either/or choice. This PR does just this. Removing the file lock code unlocks a number of simplifications. Following that, I cleaned up the reexec logic to be a bit cleaner. Then I added a number of further simplifications.
At the end of this, we're much more explicit about when reexecing inside Docker/Nix is desired via a `ShouldReexec` parameter to `withConfig`, which I think is the best case scenario. There may still be some cases where we want to tweak the behavior, but that can occur in later PRs.
=> No user file locks #4636

doc/pantry.md, subs/pantry/src/Pantry/Archive.hs
Fixes #4579.
I haven't updated the changelog; not sure where the update should go.
For tests, I could create an integration test which makes a git repo and creates a symbolic link out of the repo. It wouldn't need git-annex, but it would trigger the same error. Does that sound worthwhile?
---
=> Indicate where git-annex will lead to pantry error

src/Stack/Setup.hs
Fixes: #4462
Tested with
```console
$ stack install
Copying from /home/anders/haskell/stack/.stack-work/install/x86_64-linux-tinfo6/custom-snapshot-for-building-stack-with-ghc-8.2.2-kf0nGp8fCCJ3/8.2.2/bin/curator to /home/anders/.local/bin/curator
Copying from /home/anders/haskell/stack/.stack-work/install/x86_64-linux-tinfo6/custom-snapshot-for-building-stack-with-ghc-8.2.2-kf0nGp8fCCJ3/8.2.2/bin/stack to /home/anders/.local/bin/stack
Copied executables to /home/anders/.local/bin:
- curator
- stack
$ stack upgrade --force-download --verbose
Version 1.10.0, Git revision fce9fe335b902776b683420ea2ee45461b0fd97c (6718 commits) x86_64 hpack-0.31.1
2019-03-26 00:03:26.077371: [info] Current Stack version: 1.10.0, available download version: 1.9.3
2019-03-26 00:03:26.077749: [info] Forcing …
```
=> stack upgrade: Call getExecutablePath before overwriting ourself

doc/nonstandard_project_init.md
=> Remove incorrect Git repo documentation (fixes #4425)

doc/GUIDE.md
Removed the redundant word "above" in the sentence: 
> Then run the above stack init command above again and it will succeed.
=> Remove redundant word

ChangeLog.md, src/Options/Applicative/Builder/Extra.hs, src/Stack/Build/Execute.hs, src/Stack/Config.hs, src/Stack/Config/Build.hs, src/Stack/Config/Docker.hs, src/Stack/Config/Nix.hs, src/Stack/Options/BuildMonoidParser.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Options/DockerParser.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Options/NixParser.hs, src/Stack/Options/TestParser.hs, src/Stack/Prelude.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/Types/Config.hs, src/Stack/Types/Config/Build.hs, src/Stack/Types/Docker.hs, src/Stack/Types/Nix.hs, src/test/Stack/ConfigSpec.hs
Fixes #893. The implementation strategy is to replace `First Bool` with
either a `First True` or `First False` so that we can use the type to
ensure we display the correct default. This results in a lot of changes
to the codebase, but they are all type directed.
Alternatively, we could introduce a typeclass here to reduce some
boilerplate, but I prefer the more explicit approach.
=> Include default flag values in --help

doc/GUIDE.md
Changes include:
Moving the reference to hpack from the external dependencies section to the stack init section.
- Rationale: The section about adding acme-missiles is mainly about showing how to resolve external packages that is not found in the snapshots. Dropping the reference to hpack and packages.yml is out of place as that talks about the various files stack works with. Which is why I think moving it to the stack init section is more proper, as that section talks about initiating a project for stack usage.
Rework the section that talks about how to add acme-missile
- Rationale: The inclusion of hpack and how the sentence was structured did not make the instruction to update the build-depends section clear. The build-depends was also not highlighted, hence not making it super obvious …
=> Making the stack init and External Dependencies section clearer

ChangeLog.md, doc/docker_integration.md, src/Stack/Config/Docker.hs, src/Stack/Options/DockerParser.hs, src/Stack/Types/Docker.hs
=> Enable docker-auto-pull by default (fixes #3332)

ChangeLog.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Haddock.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Source.hs, src/Stack/GhcPkg.hs, src/Stack/Ghci.hs, src/Stack/PackageDump.hs, src/Stack/Path.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/Setup/Installed.hs, src/Stack/SetupCmd.hs, src/Stack/Snapshot.hs, src/Stack/Solver.hs, src/Stack/SourceMap.hs, src/Stack/Types/Compiler.hs, src/Stack/Types/Config.hs, src/main/Main.hs, src/test/Stack/PackageDumpSpec.hs, test/integration/tests/2433-ghc-by-version/Main.hs, test/integration/tests/2433-ghc-by-version/files/.gitignore, test/integration/tests/2433-ghc-by-version/files/fake-path/ghc, test/integration/tests/2433-ghc-by-version/files/fake-path/ghc-pkg, test/integration/tests/2433-ghc-by-version/files/foo.hs, test/integration/tests/2433-ghc-by-version/files/run.sh
If you enable system-ghc, and have multiple versions of GHC available,
Stack will now find the appropriate one based on the version-suffixed
name.
Note: the code in Stack.Setup is _really_ difficult to follow at this
point. This PR makes the situation a bit worse, to avoid making this
diff larger than it has to be. A later PR to clean up Stack.Setup would
be a great idea.
=> Find GHC on PATH via version suffixes (fixes #2433)

ChangeLog.md, src/Stack/Upload.hs, src/test/Stack/UploadSpec.hs
=> Hackage creds are read-only (fixes #2159)

src/Options/Applicative/Builder/Extra.hs, test/integration/tests/copy-bins-works/Main.hs, test/integration/tests/copy-bins-works/files/package.yaml, test/integration/tests/copy-bins-works/files/src/Main.hs, test/integration/tests/copy-bins-works/files/stack.yaml
Discovered with --copy-bins, so I wrote the test based on that.
=> Fix typo that prevents flags from being enabled

ChangeLog.md, doc/docker_integration.md, src/Stack/Options/ExecParser.hs, src/Stack/Types/Config.hs, src/main/Main.hs
Perhaps the purpose for `--plain` was lost over time with refactorings, but I haven't been able to understand from the codebase what the flag is supposed to be doing.
=> Remove the --plain option for the exec family

ChangeLog.md, src/Stack/Init.hs, test/integration/tests/2465-init-no-packages/Main.hs, test/integration/tests/2465-init-no-packages/files/.gitignore
=> Allow empty stack init (fixes #2465)

ChangeLog.md, src/Stack/BuildPlan.hs, test/integration/tests/4408-init-internal-libs/Main.hs, test/integration/tests/4408-init-internal-libs/files/.gitignore, test/integration/tests/4408-init-internal-libs/files/foo.cabal
=> stack init works for internal libs (fixes #4408)

.azure/azure-nightly-template-linux.yml, .azure/azure-nightly-template-osx.yml, .azure/azure-nightly-template-windows.yml, etc/scripts/integration-tests.sh, package.yaml, src/Stack/Config.hs, test/integration/IntegrationSpec.hs, test/integration/tests/2433-ghc-by-version/files/run.sh
This makes a number of changes, including:
* stack-integration-tests is now an executable, not a test suite
* Output for test progress is displayed immediately
* Much smarter setup of the temporary home directory (just keep pantry)
* Modify the Azure scripts to call appropriately
=> Rewrite IntegrationSpec for streaming output

snapshot-lts-12.yaml, snapshot-nightly.yaml, snapshot.yaml, src/Stack/Storage.hs, subs/pantry/package.yaml, subs/pantry/src/Pantry/Hackage.hs, subs/pantry/src/Pantry/SQLite.hs, subs/pantry/src/Pantry/Storage.hs, subs/pantry/src/Pantry/Types.hs
This makes two basic changes to the code:
* Avoids a connection pool, which forces the SQLite connection to be
closed at the end of each call to withStorage. This seems unfortunate;
we would like to be able to maintain connections. However, SQLite seems
to view such connections as holding a write lock even when not in the
middle of a database transaction.
* Uses an explicit file lock on the two longest-running write
operations: migration and Hackage population. Ideally the locking
mechanism in SQLite would be sufficient for this, but (1) Hackage
population can take a long time, and (2) evidence has shown that it
doesn't behave as we expect it to.
This may be insufficient for preventing the bug described in #4471, in
which case we may need to apply withWriteLock to more calls. However,
I'd …
=> Take a write lock before using Pantry database #4471

ChangeLog.md, src/Stack/Setup.hs, test/integration/tests/4706-ignore-ghc-env-files/Main.hs, test/integration/tests/4706-ignore-ghc-env-files/files/.gitignore, test/integration/tests/4706-ignore-ghc-env-files/files/Main.hs, test/integration/tests/4706-ignore-ghc-env-files/files/package.yaml
CC @phadej @tfausak 
This fixes #4706. Since GHC 8.0, GHC will now implicitly read in from a
.ghc.environment.* file, which can cause commands like `stack exec ghci`
to fail. Due to the use case of `stack exec`, it doesn't make sense to
try to create our own environment file, but instead tell GHC to ignore
it. Unfortunately, the ability to ignore environment files was only
added in GHC 8.4.4. This patch:
* Unsets any `GHC_ENVIRONMENT` variable already set outside of Stack
* When using GHC 8.4.4 or later, sets the variable to `-`
This will help work around situations where `cabal new-build` creates an
environment file without the user's awareness. This may be somewhat
superfluous in the future depending on changes to either GHC or
cabal-install, but shouldn't present any harm for the …
=> Modify the GHC_ENVIRONMENT env var in Stack.Setup

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Config/Nix.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/Setup/Installed.hs, src/Stack/SetupCmd.hs, src/Stack/Types/Compiler.hs, src/Stack/Types/Config.hs, subs/curator/src/Curator/Snapshot.hs, subs/pantry/src/Pantry.hs, subs/pantry/src/Pantry/Types.hs, test/integration/lib/StackTest.hs, test/integration/tests/build-ghc/Main.hs
This patch adds the experimental support for building GHC from source. We can now specify a specific GHC to build from source in `stack.yaml` with the following syntax:
```
compiler-build:
git: GHC_GIT_REPO
commit: COMMIT
flavour: FLAVOUR
```
In the setup phase Stack uses Hadrian to build a GHC binary distribution
with the specified flavour and installs it into
STACK_ROOT/programs/ARCH/ghc-git-COMMIT-FLAVOUR.
The built compiler can be used with the following configuration:
```
compiler: ghc-git-COMMIT-FLAVOUR
```
As GHC may rely on unreleased version of the global packages (e.g.
Cabal), you may have to add some extra-deps as follows:
```
extra-deps:
- git: GHC_GIT_REPO
commit: COMMIT
subdirs:
- libraries/Cabal/Cabal
- libraries/...
```
=> Build GHC from source (#4567)

doc/README.md, doc/install_and_upgrade.md, etc/scripts/get-stack.sh
This also adds some extra text to the docs pointing people to the manual installation instructions if they prefer not to use the script.  (ping @jkachmar)
=> Inform the user why sudo is necessary in get-stack (fixes #4672)

ChangeLog.md, src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Haddock.hs, src/Stack/Build/Installed.hs, src/Stack/GhcPkg.hs, src/Stack/PackageDump.hs, src/Stack/Path.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/SetupCmd.hs, src/Stack/SourceMap.hs, src/Stack/Types/Config.hs, src/main/Main.hs, src/test/Stack/PackageDumpSpec.hs
This is a refactoring of a bunch of code in Stack.Setup and related modules to make it possible to begin caching GHC information. These changes already improve the behavior of Stack slightly, such as
* Warning on untested or unsupported GHC/Cabal versions
* Avoiding redundant global package checks
* Checking for multiple system GHCs in a sensible order
I'm opening up this PR first for review, and once this is merged, I'll work on the caching logic, which will allow us to bypass a few expensive external process calls on each Stack invocation.
=> Prepare to cache GHC info

subs/curator/src/Curator/Snapshot.hs
It's a change in curator only, doesn't affect Stack itself.
The problem was reported in https://github.com/commercialhaskell/stackage/issues/4475
Tested locally using constraints allowing the latest versions of LambdaHack and Allure.
=> Allow dependencies between sublibraries in curator

src/Stack/Build/Execute.hs, src/Stack/Prelude.hs
This is intended to address intermittent integration test failures,
which started as a result of the new integration test runner. This is a
weird corner case, but here goes:
* ./configure scripts will fail if run with `stdin` closed. We already
work around this in Stack.Build.Execute in the OTLogFile case
* However, in the OTConsole case, we use the sinkProcessStderrStdout
functions, which inherits stdin
* The current behavior can be classified as a bug: we don't want
subprocesses to be exposed to stdin in general.
* Reviewer request: I've checked the other use cases for
sinkProcessStderrStdout, and I believe in _all_ cases we do not want the
subprocess to have such stdin access. Please confirm I haven't made a
mistake.
* The new integration test runner explicit uses `setStdin closed`... …
=> Set empty input to sinkProcessStderrStdout

azure-pipelines.yml
New rules are as follows:
• Run CI if commits are pushed to stable, master branch
• Run CI for all new PR's
• Run CI for branches starting with `ci/`
=> New CI build rules

ChangeLog.md, src/Stack/Setup.hs, src/Stack/Storage.hs, src/Stack/Types/Compiler.hs, src/Stack/Types/Config.hs, src/Stack/Types/GhcPkgId.hs
This bypasses a few relatively expensive external process executions on
each Stack invocation, namely `ghc --info` and `ghc-pkg dump`.
=> Cache GHC information in the SQLite database

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Types/Build.hs, src/Stack/Types/Config.hs
Add `ghc-option` to hide source paths when using ghc >= 8.2 as detailed in #3784.
- The default output for compiling modules should hide the source paths
- The entry `hide-source-paths` in `stack.yaml` set to `false` should restore including the source paths
- The entry `hide-source-paths` in `stack.yaml` set to `true` should hide the source paths (as the default behavior)
E.g.:
When enabled:
```
...
[1 of 2] Compiling Lib
[2 of 2] Compiling Paths_test_pr
...
```
When disabled:
```
...
[1 of 2] Compiling Lib              ( src/Lib.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/Lib.o )
...
```
=> GHC Hide Source Paths

src/Stack/Setup.hs
This should hopefully fix #4727, by finding the Haddock executable even
though the copy without a version suffix is unavailable.
=> Prefer compilers including the version number

ChangeLog.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Storage.hs, src/Stack/Types/Build.hs
=> Reconfigure on new PATH env var (fixes #3138)

ChangeLog.md, README.md, src/Stack/Setup.hs, src/Stack/Setup/Installed.hs
See #4086. This commit removes the ability to build GHCJS within Stack.
=> Reduce GHCJS support

subs/curator/app/Main.hs
=> Disable interleaved output when building Stackage with curator

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Source.hs, src/Stack/BuildPlan.hs, src/Stack/Config.hs, src/Stack/Dot.hs, src/Stack/Ghci.hs, src/Stack/Package.hs, src/Stack/SDist.hs, src/Stack/SourceMap.hs, src/Stack/Types/Build.hs, src/Stack/Types/Config.hs, src/Stack/Types/Package.hs, src/Stack/Types/SourceMap.hs, test/integration/tests/1438-configure-options/Main.hs, test/integration/tests/1438-configure-options/files/.gitignore, test/integration/tests/1438-configure-options/files/package.yaml, test/integration/tests/1438-configure-options/files/stack-everything.yaml, test/integration/tests/1438-configure-options/files/stack-locals.yaml, test/integration/tests/1438-configure-options/files/stack-name.yaml, test/integration/tests/1438-configure-options/files/stack-targets.yaml
Addresses #1438
Two points for discussion on this PR:
* Should we also be adding `configure-options` to Pantry snapshots, like we have support for `ghc-options`?
* Should we attempt to fold the `ghc-options` values into this field? I think not, since some commands use `ghc-options` but don't use `configure-options` (like `ghci`)
=> Add configure-options settings (fixes #1438)

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Target.hs, src/Stack/Config.hs, src/Stack/Hoogle.hs, src/Stack/Runners.hs, src/Stack/Storage.hs, src/Stack/Types/Cache.hs, src/Stack/Types/Config.hs, src/Stack/Unpack.hs, src/Stack/Upgrade.hs, subs/curator/src/Curator/Snapshot.hs, subs/pantry/src/Pantry.hs, subs/pantry/src/Pantry/Hackage.hs
=> Recommend Stack upgrade when appropriate (fixes #1681)

package.yaml
This will be the unstable Stack 2 development branch.  Release candidate branch will be cut as v2.1.0, and first Stack 2 full release will be v2.1.1.  See [version scheme](https://docs.haskellstack.org/en/stable/maintainers/releases/#version-scheme).
=> package.yaml: bump stack version to 2.0.0

subs/pantry/src/Pantry/SQLite.hs
* Include indication of whether it's Pantry or Stack
* Don't mention anything for the first 5 seconds to avoid spamming the
user
Since there are now two different delays involved, I've extracted the
"talkUntil" logic to its own function. In theory, this could be added as
a library function with some more cleanup.
=> Nicer DB locked messages

.gitignore, subs/pantry/.hindent.yaml, subs/pantry/package.yaml, subs/pantry/src/Pantry.hs, subs/pantry/src/Pantry/Archive.hs, subs/pantry/src/Pantry/Hackage.hs, subs/pantry/src/Pantry/Internal/Stackage.hs, subs/pantry/src/Pantry/Storage.hs, subs/pantry/src/Pantry/Tree.hs, subs/pantry/src/Pantry/Types.hs
* Exposed few modules needed for stackage-server
* Addition of few class instances and exports needed for stackage-server
* Made pantry compatible with PostgreSQL. Improved speed and safety by added database aware queries. 
* Fixed concurrent blob and file name writes in multi-connection sql pool setting. Added few more exports needed for stackage-server
* Removed redundant constraints and switched many queries to `MonadIO`
* Added .cabal files to gitignore for all subs
* Added .hindent file for pantry with width set to `2`, since that is what majority of code has.
Please also shortly describe how you tested your change. …
=> Additions necessary for integration of pantry into stackage-server:

test/integration/tests/4220-freeze-command/Main.hs
`publish-date` was added to snapshots and thus hashes and file sizes are now different.
Currently we have "reverse" failure on Azure because of S3 cache - https://dev.azure.com/commercialhaskell/stack/_build/results?buildId=1483
We need to clear caches before merging this
=> Fix freeze test (publish-date field was added to snapshots)

snapshot-lts-12.yaml, snapshot-nightly.yaml, snapshot.yaml
Specifically, we're adding in this commit:
https://github.com/snoyberg/filelock/commit/4f080496d8bf153fbe26e64d1f52cf73c7db25f6
Without this change, very often on large builds we end up in a situation
where:
* Multiple threads are working in parallel
* Thread A needs to work with the database
* Thread A takes a file lock on the database
* Thread B forks a child process, which inherits the database lock
* Thread A releases the file lock
* Thread C attempts to take the file lock, but is blocked by B's child
As a demonstration, lsof showed me this on my system:
```
COMMAND     PID    USER   FD   TYPE DEVICE SIZE/OFF       NODE NAME
stack     20216 michael   12w   REG    1,4        0 8613331527 stack.sqlite3.pantry-write-lock
Cabal-sim 22736 michael   12w   REG    1,4        0 8613331527 …
```
=> Use patched filelock with CLOEXEC

subs/pantry/src/Pantry/Types.hs, subs/pantry/test/Pantry/TypesSpec.hs
This fixes the warnings about extraneous fields, by having `PackageMetadata` content parsed within the `WarningParser` which tracks which fields are used. This does _not_ fully address #4789, please do not close that issue when merging this.
=> Fix some misplaced parse warnings #4789

subs/pantry/src/Pantry.hs, subs/pantry/src/Pantry/Types.hs
The completed package information already contains the package name,
bypassing the need for a package completion call if the cache (lock
file) already contains that information. This bypasses a spurious
warning about lacking cryptographic hashes, and likely improves
performance, for the repo and archive cases.
This wasn't discovered initially because the Hackage use case never had
an overhead: the specification of a RPLIHackage already contains the
package name in all cases.
=> Get package name from completed information #4789

ChangeLog.md, etc/scripts/get-stack.sh
Tested this by running the script against MX Linux 18.2 and Debian Stretch.
During testing I noticed that the dpkg-query check in apt_get_install_pkgs always assumes
that the packages are installed even when they aren't. This happens only on MX and not on
Debian and is probably a subtle behavior change between the /bin/sh versions in MX and Debian testing (I am not entirely sure though). This check was introduced in commit b46e5a7 a few days
back, reverting that to the previous version works fine in MX and Debian stretch. Please let me know if this is a problem, I'll try to find an alternative fix.
=> MX linux support

src/Stack/Build/Execute.hs
In module `Stack.Setup`, `pacman` is used to add the `perl` and `autoconf` packages to stack's MSYS2.
In module `Stack.Build.Execute`, the code uses command `sh autoreconf -i` for Windows, instead of just `autoreconf -i`.
The implementation involves two hacks:
1. `pacman` and `sh autoreconf -i` seem to clear and not restore ANSI capability on native Windows terminals. A hack restores the ANSI capability (using the same hack that was once used for `git clone` - fix #4121).
2. MSYS2's current `perl` package (5.28.1-2) is broken. So the `perl` installed by stack is downgraded to 5.28.0-1, which works. This will need to be revisited once `perl` is fixed on MSYS2.
This has been tested on Windows 10 (only) by deleting stack's MSYS2 (so that stack reinstalls it) and by then building the …
=> Fix #4778: autorun `autoreconf` on Windows too

doc/install_and_upgrade.md, etc/scripts/get-stack.sh
Adds a note about installing additional headers on more recent macOs versions, when `xcode-select --install` is not enough. Follow up from https://github.com/commercialhaskell/stack/issues/4426#issuecomment-488641809
=> Add note about installing SDK headers on macOs >= 10.14

ChangeLog.md, package.yaml, src/Stack/Config.hs, src/unix/System/Info/ShortPathName.hs, src/windows/System/Info/ShortPathName.hs
In module `Stack.Config`, function `configFromConfigMonoid`, a stack user is informed if the stack 'programs' path contains a space character. If the path also does not have an alternative short ('8 dot 3') name, the user is further warned of the implications for packages that make use of the GNU project's `configure` shell script.
New modules `System.Info` are added to `src/windows` and `src/unix` to re-export `getShortPathName` from the `System.Win32.Info` module of the `Win32` package in the case of Windows and do nothing in the case of Unix-like operating systems. This avoids the need for C preprocessor (CPP) directives in `Stack.Config`.
`ChangeLog.md` is updated, accordingly.
Tested on Windows 10 with 'programs' paths that do and do not contain space characters and, in the latter …
=> Fix #4726: On Windows, inform or warn about 'programs' path with space

src/Stack/Storage.hs
These were added while the sqlite database schema was still in flux, mainly so that CI builds wouldn't fail.  That part of the schema has been stable for long enough now that there shouldn't be any old databases in the wild anymore.
=> Remove 'SafeToRemove' fields and defaults from persistent schema

subs/curator/app/Main.hs, subs/curator/src/Curator.hs, subs/curator/src/Curator/Legacy.hs
I've checked that this provides enough information for Stack 1.9.3 to parse and use the generated snapshot files, and do not believe we need to produce any of the additional information that was in these files. I wanted to check with you @qrilka: where do you believe is the most logical place to put the code for adding the legacy snapshot file to the lts-haskell and stackage-nightly repos?
=> Generate legacy snapshots

ChangeLog.md, src/Stack/Options/DotParser.hs, src/Stack/Types/Config.hs, src/main/Main.hs
This PR makes good on the warning originally threatened in `stack-1.7.1`.
=> Remove `list-dependencies` command

doc/azure/azure-linux-template.yml, doc/azure_ci.md, doc/build-overview.md, doc/pantry.md, doc/travis-complex.yml, package.yaml, snapshot-lts-12.yaml, snapshot-nightly.yaml, snapshot.yaml, subs/hi-file-parser/test-files/iface/x32/run.sh, subs/pantry/package.yaml, subs/rio-prettyprint/src/Text/PrettyPrint/Leijen/Extended.hs
- Update to latest nightly and lts-12 snapshots
- Remove extraneous dependency constraints
- Update docs with current GHC versions
=> Pre-release package and snapshot updates

doc/README.md
Update the tree of files created by running `stack new` in the README. In particular, include `package.yaml`, which is referenced in the text below.
=> Update list of files created by 'stack new' in README

src/System/Process/Pager.hs
When we used ShellCommand to launch a pager found on PATH (`less' or
`more') the pager cannot be launched when its path contained spaces and
other shell-specific characters.  This commit fixes that by using
RawCommand to launch any pager discovered via findExecutable.
Signed-off-by: Fred Miller <fghzxm@outlook.com>
Put a `less` executable into a path containing spaces and add that path to the front of `PATH`, then run `stack ls snapshots`.  Master fails while this branch succeeds.
=> Use RawCommand when launching pager found on PATH

etc/scripts/get-stack.sh
This checks each dependency individually and then only `apt-get install`s the ones that are missing.
@rkaippully Can you please try this out on MX Linux and let me know if it works?  You ran into trouble with the last fix I attempted.
=> get-stack.sh: fix apt package detection (fixes #4816)

subs/pantry/src/Pantry/Types.hs
Noticed the error message "you may delete **Pantry** database" even for `stack.sqlite3`.  This fixes it.
=> Fix DB name in migrate error message

src/Stack/Dot.hs, src/Stack/Options/DotParser.hs, src/test/Stack/DotSpec.hs
Fixes #4845 
**Please also shortly describe how you tested your change. Bonus points for added tests!**
The tests and the implementation both were wrong, I fixed both. However I have found that the behaviour of `pruneGraph` function is a bit weird. But that is how it has been since the beginning, so I am not very sure if I should report a bug. Here are my observations:
1. The `dontPrune` parameter is not always respected. I wrote this property to verify what I thought should've been the behaviour and it does not pass:
```haskell
prop "dontPrune packages are not pruned" $ do
let resolvedGraph = runIdentity …
```
=> Compare package names to be pruned correctly

doc/nonstandard_project_init.md
Direct readers to the part of the docs where custom snapshots are explained.
=> Documentation: Replace placeholder by internal link

ChangeLog.md, subs/pantry/ChangeLog.md, subs/pantry/src/Pantry/Repo.hs
This was [making it impossible to pin to a specific commit when using relative file paths as repo URLs](https://stackoverflow.com/a/56573316/625403).
I tested this change by running `stack test` three times:
1. Before I made any changes, tests pass
1. After intentionally implementing my change incorrectly, tests fail
1. After a correct implementation of my change, tests pass again
=> Don't change directories when cloning a repo

ChangeLog.md, src/Stack/Nix.hs
Tested running `stack new --nix` manually
Fixes #4864
=> Allow nix mode commands to run outside of a project

ChangeLog.md, src/Stack/Prelude.hs
=> Wait for children to exit correctly (fixes #4888)

ChangeLog.md
It was missed in #4424, It will be a breaking change for people using `ls dependencies --tree`, so it is especially worth mentioning in the changelog.
=> Add changelog entry for `ls dependencies json`

doc/install_and_upgrade.md
fixes #4881
Removes links to no-longer existing stack bindists (like linux-gmp4).  Also switches to static bindist where available.
=> docs: update linux bindist links

stack-lts-12.yaml, stack-nightly.yaml, stack.yaml
This is for convenience of being able to use 'stack build --docker'
without needing to specify an image.
Also removed obsolete commented out 'image:' sections.
=> Add disabled 'docker:' section to 'stack*.yaml'

ChangeLog.md, subs/pantry/src/Pantry/SQLite.hs
Tested both against existing databases that had WAL enabled before, and a new STACK_ROOT with new databases.  In the former case, WAL remained enabled on the existing databases, and in the latter case WAL was not enabled on the new databases.
=> Disable WAL mode for SQLite databases (fixes #4876)

ChangeLog.md, src/Stack/Lock.hs
Fixes #4887
Tested manually, I don't think that we need an integration test for this change.
=> Use lock file locations when resolving project dependencies

ChangeLog.md, doc/yaml_configuration.md, subs/pantry/ChangeLog.md, subs/pantry/src/Pantry/Types.hs
* Fixes #3731
* Fixes #4927
* Fixes #4928
=> Ignore hackage-security expiry by default

azure-nightly-pipeline.yml, azure-pipelines.yml, doc/azure/azure-pipelines.yml
This fixes an integration test failure (see
https://github.com/commercialhaskell/stack/pull/4939#issuecomment-510066631)
=> Azure CI: bump macOS to Mojave (10.14)

doc/yaml_configuration.md
The rendering of this is funny:  https://docs.haskellstack.org/en/stable/yaml_configuration/#4928httpsgithubcomcommercialhaskellstackissues4928
=> doc: Fix a link that was interpreted as a title

ChangeLog.md, src/Stack/Config.hs
It seems that warn messages are [not shown when running a script](https://github.com/commercialhaskell/stack/issues/3007) so the more straigthforward way is change the log level of the relevant message. Not sure it it could have a unwanted consequence.
It fixes #5001.
I've tested the change manually running a script to check the message is actually shown.
=> Show warning about `local-programs-path` with spaces on windows when running scripts

ChangeLog.md, src/Stack/Build/Haddock.hs
* [N/A] The documentation has been updated, if necessary.
Tested by generating haddocks for a package and confirming by`grep`ing all the output that no absolute links are generated.  Also spot checked that links are correct.
@qrilka It looks like the links changed to absolute in !4596.  I don't understand the original bug that fixed well enough to know whether my changes here will cause any problems, so please test it.
=> Haddock use relative paths in output (fixed #4971)

ChangeLog.md, src/Stack/Setup.hs
Confirmed by @DanBurton by running a Stackage Nightly build with GHC 8.8.
=> Remove warning for using Stack with GHC 8.8 and Cabal 3.0

azure-nightly-pipeline.yml
@borsboom pinged me that nightly pipeline seems to be missing in the
UI. Analyzing it further, I found that the nightly pipeline in the
dashboard has zero scheduled builds. The likely reason for this seems
to be because of new deployment of azure pipelines.
The good news is now we can control the nightly builds using the yaml
file itself (this wasn't possible before when we added azure builds to
stack initially). This PR does that and make sure we don't rely on UI
for the CI configuration anymore.
=> Enable nightly builds again for master branch

azure-nightly-pipeline.yml
@borsboom pinged me that nightly pipeline seems to be missing in the
UI. Analyzing it further, I found that the nightly pipeline in the
dashboard has zero scheduled builds. The likely reason for this seems
to be because of new deployment of azure pipelines.
The good news is now we can control the nightly builds using the yaml
file itself (this wasn't possible before when we added azure builds to
stack initially). This PR does that and make sure we don't rely on UI
for the CI configuration anymore.
=> Enable nightly build for stable branch

doc/GUIDE.md
Documents mandatory for profiling `--profile` key for `stack exec`.
I'm building project with `stack clean --full && stack build --profile`.
With the code from the current wiki: ` stack exec -- vector-try-exe +RTS -p` it will not find `vector-try-exe`.
With the updated code from this commit: ` stack exec --profile -- vector-try-exe +RTS -p` it will run fine.
=> Documenting --profile usage with stack exec

ChangeLog.md, etc/scripts/mirror-ghc-bindists-to-github.sh, package.yaml, snapshot-nightly.yaml, src/Stack/Config.hs, src/Stack/Dot.hs, src/Stack/FileWatch.hs, src/Stack/Options/DotParser.hs, src/System/Process/Pager.hs, src/main/Main.hs, src/test/Stack/DotSpec.hs, test/integration/tests/4101-dependency-tree/Main.hs, test/integration/tests/4101-dependency-tree/files/files.cabal, test/integration/tests/4101-dependency-tree/files/stack.yaml
The merge that @chrisdone did was correct, but shouldn't have been merged to stable (it should have remained on master). We _could_ do a force-push to stable to undo that and restore the previous commit (eb9f921e86e31d5df97d1b4041ae5c5e737b8ec2). This PR instead reverts both Chris's merge and a small commit I added on top to fix integration tests.
Once this is merged in, we would need to also revert this revert on master to avoid losing Chris's changes on master later. I have a branch for that ready to go: https://github.com/commercialhaskell/stack/pull/new/undo-revert-on-master.
@borsboom would you prefer the force-push approach or the revert+double revert approach?
=> Revert bad merge on stable

.gitignore, ChangeLog.md, doc/install_and_upgrade.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Setup.hs, src/Stack/SetupCmd.hs, src/Stack/Types/Config.hs, src/main/Main.hs
This PR comes to fix various issues related to how `stack` decides where to resolves it's tooling locations, for the initial purpose of using `stack` offline or behind a firewall. 
* See the documentation changes and the changelog for details on the new behaviors.
Stack 2 broke the previous behavior of the `setup-info` field - which now does not overwrite the default location. [#2983](https://github.com/commercialhaskell/stack/issues/2983), [#2913](https://github.com/commercialhaskell/stack/issues/2913)
This existing breakage allowed for a backwards-compatible implementation of the wanted behavior - via the `setup-info-locations` yaml config for remote locations, and using `setup-info` for inline configuration only.
Also, as the `--stack-setup-yaml` CmdArg has been deprecated for 3 years, …
=> Setup-info configurability

doc/coverage.md
A missing closing brace left the text being show as:  "… to be rebuilt (see #1940."
=> Fix small typo in coverage.md

ChangeLog.md, src/Stack/Config.hs
issue: https://github.com/commercialhaskell/stack/issues/5103
* [ x ] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [ x ] The documentation has been updated, if necessary.
Test case:
```
stack test   673 examples, 0 failures
stack --resolver global   is ok
stack --resolver nightly is ok
stack --resolver lts-14   is ok
stack --resolver lts-14.13 is ok
```
=> fix "--resolver global " needs network 

doc/install_and_upgrade.md
I have added a new section "Install Older Versions" to
the end of doc/install_and_upgrade.md, which tells
users how to find a specific version of stack on
the release page, and also shows how one could add
some lines to their appveyor.yml to download and
install a specific version of stack.
I have not added anything to doc/ChangeLog.md.
I tested my changes by previewing the markdown
on GitHub, checking that the formatting was okay,
and also checking that the links worked.
=> Install specific versions of stack #5067

doc/GUIDE.md
I found minor points in this section of the guide that made me want to rewrite it:
* people recognize debugging symbols as a broader subject than DWARF as title
* `now` is not informative to the reader
* No mention of having to pass `--ghc-options="-g"` flag
* No help on how to do things in windows was present, taking into consideration windows "native" debugging tools such as `WinDbg` which need PDB and thus is not supported, but might be feasible.
I hope that it will be more clear for windows users especially but also for linux and macOS users about which flags to pass. I also hope that someone by reading this will look into getting the windows native platform tools working if a PDB file can be produced. Though i am a bit hesitant about leaving this last part in actually.
=> Update GUIDE.md about debugging symbols

.azure/azure-nightly-template-windows.yml
@jeffhappily and I were debugging some integration test failures on CI, and believe this fix should do the trick for failing Windows builds. Sibi: is there a reason why this may cause problems?
=> Remove the TMP env var on Windows integration tests

Setup.hs, snapshot-lts-12.yaml, snapshot-nightly.yaml, snapshot.yaml, src/Stack/Build.hs, src/Stack/Build/Execute.hs, src/Stack/Package.hs, src/Stack/SDist.hs, src/Stack/Types/Package.hs, src/Stack/Types/Version.hs, src/test/Stack/DotSpec.hs, test/integration/tests/cabal-public-sublibraries/Main.hs, test/integration/tests/cabal-public-sublibraries/files/Setup.hs, test/integration/tests/cabal-public-sublibraries/files/files.cabal, test/integration/tests/cabal-public-sublibraries/files/src/Lib.hs, test/integration/tests/cabal-public-sublibraries/files/src/Sub.hs, test/integration/tests/cabal-public-sublibraries/files/stack.yaml, test/integration/tests/cabal-sublibrary-dependency/Main.hs, test/integration/tests/cabal-sublibrary-dependency/files/Setup.hs, test/integration/tests/cabal-sublibrary-dependency/files/files.cabal, test/integration/tests/cabal-sublibrary-dependency/files/src/Lib.hs, test/integration/tests/cabal-sublibrary-dependency/files/src/Sub/Sub.hs, test/integration/tests/cabal-sublibrary-dependency/files/stack.yaml, test/integration/tests/cabal-sublibrary-dependency/files/subproject/src/Lib.hs, test/integration/tests/cabal-sublibrary-dependency/files/subproject/src/SubLib.hs, test/integration/tests/cabal-sublibrary-dependency/files/subproject/subproject.cabal
=> Upgrade to Cabal 3

doc/nix_integration.md
nix repl has been integrated into the nix command and
the nix-repl package has been removed.
- github text search
=> doc/nix_integration.md: nix-repl -> nix repl

doc/travis-complex.yml
Based on this Travis configuration validation report:
- `root`: deprecated key `sudo` (The key `sudo` has no effect anymore.)
=> `sudo: false` removed
- `root`: missing `os`, using the default `linux`
=> `os: linux` added at top-level
- `root`: key `matrix` is an alias for `jobs`, using `jobs`
=> `matrix` renamed to `jobs` at top-level
With the changes in this PR, the warnings go away.
=> travis-complex.yml: Address validator warnings and hints

src/Stack/Build/ConstructPlan.hs, test/integration/tests/4897-boot-package-pruned/Main.hs, test/integration/tests/4897-boot-package-pruned/files/directory/directory.cabal, test/integration/tests/4897-boot-package-pruned/files/files.cabal, test/integration/tests/4897-boot-package-pruned/files/stack.yaml
Fixes #4897.
* [N/A] Any changes that could be relevant to users have been recorded in the ChangeLog.md
* [N/A] The documentation has been updated, if necessary.
---
Manual test:
```shell
cabal get process-1.6.5.0 &&
cd process-1.6.5.0 &&
cabal get unix-2.7.2.2 &&
cat >stack.yaml <<EOF &&
resolver: lts-13.26
packages: [.]
extra-deps: [./unix-2.7.2.2]
EOF
"${LOCALLY_BUILT_STACK}" build
```
```
Error: While constructing the build plan, the following exceptions were encountered:
In the dependencies for process-1.6.5.0:
directory must match …
```
=> Tell the user that a boot package was pruned

doc/faq.md
=> Add solution for Missing ghc bindist for linux64-ncurses6 in FAQ

.azure/azure-nightly-template-windows.yml, .azure/azure-windows-template.yml
Separate from #5188, this applies the change directly to master. If this is merged, then #5188 should be closed and #5162 should be rebased.
=> CI: Build Windows 64-bit only

src/Stack/Build/Cache.hs, src/Stack/Build/Execute.hs, src/Stack/Constants/Config.hs
This resolves issue #5147 appearing because a path for setup-config for a
package depend on OS and Cabal versions and is stored in .stack-work
inside package directory
Tested locally using repro provided by @lehins in #5147
=> Include setup-config modification time into reconfigure checks

doc/azure/azure-linux-template.yml, doc/azure/azure-osx-template.yml, doc/azure/azure-pipelines.yml, doc/azure/azure-windows-template.yml, doc/azure_ci.md
This is based on the config I've been using across my projects recently.
Changes:
* No longer builds with Cabal. It was too difficult to make that work.
* Does not include the style build. Most projects don't want it I think.
* Updates image names.
* Puts all Azure config under the .azure directory.
* Update the matrix, and names the matrix entries on the GHC version.
=> Updated Azure CI docs

doc/azure/azure-pipelines.yml, doc/azure/azure-simple.yml, doc/azure_ci.md
@snoyberg I missed reviewing your https://github.com/commercialhaskell/stack/pull/5209 , so here is my proposed changes. We can iterate on this if you disagree on parts of the MR. Thanks!
=> Update documentation related to Azure CI

doc/faq.md
The FAQ section on handling additional dependencies is out of date, and should describe using `extra-deps` instead of packages. This updates it to do that.
=> Update packages -> extra-deps in FAQ

ChangeLog.md, src/Stack/Setup.hs
=> Remove warning about GHC 8.10/Cabal 3.2

etc/scripts/get-stack.sh
Tested on [a1.xlarge](https://aws.amazon.com/ec2/instance-types/a1/) instance running a Raspbian Buster armhf chroot inside aarch64 Ubuntu. LTS version is 13.11. LLVM version is 7.0.1.
Still needs this notorious hack for compilation to work: https://gist.github.com/proger/28b1bf9222828a9cd77a74a480aee5f3
I also needed to re-run `stack setup` with 
```
export LD_LIBRARY_PATH=$(echo /home/ubuntu/.stack/programs/arm-linux/ghc-8.6.3/lib/ghc-8.6.3/*  | tr ' ' :)
```
because of some weird ld.so behaviour when loading ghc-pkg:
```
/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v8l.so (0xf7ad1000)
libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xf7a4f000)
libHSterminfo-0.4.1.2-ghc8.6.3.so => …
```
=> get-stack.sh: get_isa to detect armv7l/armv8l

doc/GUIDE.md, doc/faq.md
`stack --solver` and the `--solver` argument got removed a while ago.
Documentation referencing it will confuse people, so remove it.
* No changes, just a documentation update
* This is, in fact, a doc update.
Just verified that it still rendered sanely. I'd encourage people with more context to look over my changes and give comments and feedback.
All best,
Adam
=> Remove stale documentation. Fix for issue #5251

src/Stack/Build/Execute.hs
I needed this for debugging an issue related to multiple libraries per package that occurred on the Stackage build server.
=> Better debug info for invariant violated

stack-ghc-84.yaml, stack-ghc-88.yaml, stack.yaml
We've been hoping for https://github.com/takano-akio/filelock/pull/7 to
get merged and released. However, this is dragging on, and we'd rather
use the released version of all packages in releases. Ultimately the
interruptible FFI issue isn't serious enough to warrant continuing to
use the non-released version of filelock.
=> Use released filelock

doc/install_and_upgrade.md
The Fedora Copr repo link was pointing to an obsolete repository, containing stack 1.9.3, so I've updated the link to point to the newer repo.
=> Update Fedora repo in the install guide

.azure/azure-linux-template.yml, .azure/azure-nightly-template-linux.yml, etc/scripts/release.hs, package.yaml, stack.cabal, stack.yaml
=> Static linux

src/Stack/SDist.hs
Follows the change in https://github.com/commercialhaskell/pantry/pull/22
Fixes the only build failure with Cabal 3.2
=> Fix compatibility with Cabal 3.2

ChangeLog.md, src/Stack/Types/Build.hs
Many users don't get that when they see an error like
[tons of output]
--  While building package hopenssl-2.2.4 using:
[one bit line more output]
they have to scroll up (potentially multiple terminal pages!) to the last output starting with e.g. `hopenssl >`.
This adds an explicit call to scroll up to that section, so that this user confusion can be reduced.
I haven't tested this at all because it's just a simple string change I made on a whim and hopw CI will do it for me :)
=> Add tip to scroll up on package build failure.

etc/scripts/get-stack.sh
Small PR to fix installation using installation script in alpine linux. `do_alpine_install` is commented out in 87ff1220c579ec03cff8874d6ee59e87b1b0aec0 but it still occurred in the installation. That caused an error as shown below.
```
/workdir # ./etc/scripts/get-stack.sh
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/2) Installing libbz2 (1.0.6-r7)
(2/2) Installing perl (5.28.2-r1)
Executing busybox-1.30.1-r2.trigger
OK: 44 MiB in 16 packages
Detected Linux distribution: alpine
./etc/scripts/get-stack.sh: line 465: do_alpine_install: not found
```
This PR fixes this by simply skipping the branch for alpine in `do_distro` and make the script try "generic" installation. I …
=> Fix stack installation in alpine

ChangeLog.md, doc/docker_integration.md, src/Stack/Config/Docker.hs, src/Stack/Docker.hs, src/Stack/Options/DockerParser.hs, src/Stack/Types/Docker.hs
Adds a new configuration key `docker-network` to allow overwriting the `--net` argument passed to docker. This is not possible via `--docker-run-args='--net=…'` because the latter adds an additional conflicting `--net` arg passed to docker rather than overwriting the existing one.
If `docker-network` is not set `--net=host` is passed to docker to retain the current behaviour.
For testing I found it necessary to use this commit on the release branch. Otherwise stack wouldn't find a Docker-compatible stack executable for the current version. I used a test project that spawns a web server with the following docker configuration in the stack.yaml file:
```
docker:
enable: true
network: bridge
run-args:
- --publish=8080:8080
```
=> add docker network option (fixes #5121)

ChangeLog.md, src/Stack/SDist.hs
This fixes `stack sdist` broken when using pvp-bounds, see
https://github.com/commercialhaskell/stack/issues/5289. This is a
regression after https://github.com/commercialhaskell/stack/pull/5156.
When using pvp-bounds we pretty-print an updated package description
back to .cabal file. If a set of sublibraries used in a dependency is
empty (from cabal-the-library perspective) then `instance Pretty
Dependency` from
https://hackage.haskell.org/package/Cabal-3.0.0.0/docs/src/Distribution.Types.Dependency.html#line-58
will just print an empty set there:
build-depends: vector : {} <0.13
This leads to the following error when using `stack sdist`:
- 46:16:
unexpected Sublibrary dependency syntax used. To use this syntax the package needs to specify at least 'cabal-version: 3.0'. Alternatively, if …
=> Do not remove sublibrary information when adding pvp-bounds

etc/scripts/get-stack.sh
Part of https://github.com/commercialhaskell/stack/issues/3569
It confused a user at https://discourse.haskell.org/t/install-inconsistency-ghcup-and-stack/1042
=> Explain why user should add HOME_LOCAL_BIN to PATH

ChangeLog.md, doc/build_command.md, src/Stack/Build.hs, src/Stack/Options/BuildParser.hs, src/Stack/Types/Config/Build.hs, src/Stack/Types/Package.hs
Resolves #5310
Tested manually
=> Make file watching take targets into account

ChangeLog.md, doc/pantry.md, doc/yaml_configuration.md, src/Stack/BuildPlan.hs, src/Stack/Config.hs, src/Stack/Config/Docker.hs, src/Stack/Ls.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Types/Config.hs, src/Stack/Types/Resolver.hs, src/test/Stack/Config/DockerSpec.hs, src/test/Stack/ConfigSpec.hs, stack-ghc-84.yaml, stack-ghc-88.yaml, stack.yaml
This PR adds the new yaml option `snapshot-location-base`, which overrides the default location of snapshot synonyms (LTS/Nightly). It requires [this (commercialhaskell/pantry#20)](https://github.com/commercialhaskell/pantry/pull/20) corresponding PR for `pantry`.
https://github.com/commercialhaskell/pantry/pull/20 adds to `PantryConfig` a new field `pcSnapshotLocation :: SnapName -> RawSnapshotLocation` which allows to configure how a snapshot name expands to its location. 
When `snapshot-location-base` is not supplied, `stack` just uses the `defaultSnapshotLocation` provided by pantry. When the user supplies a URL in the `snapshot-location-base` field, say:
```yaml
snapshot-location-base: https://example.com/snapshots/location/
```
then the custom snapshot location is defined as …
=> Make snapshot locations configurable

ChangeLog.md, src/Stack/Ghci.hs
Tested using https://github.com/fduxiao/mal taken from https://github.com/haskell/haskell-ide-engine/issues/1564
It's not quite clear why `stack-head repl mal:exe:mal-exe` doesn't work. I have a suspicion that we could need component-based builds but I didn't investigate it deeper.
=> Fix repl for test components

ChangeLog.md, src/Stack/Coverage.hs, test/integration/tests/3997-coverage-with-cabal-3/Main.hs, test/integration/tests/3997-coverage-with-cabal-3/files/package.yaml, test/integration/tests/3997-coverage-with-cabal-3/files/src/Lib.hs, test/integration/tests/3997-coverage-with-cabal-3/files/stack.yaml, test/integration/tests/3997-coverage-with-cabal-3/files/test/Main.hs
Fixes #3997 
Added a test making sure that `stack test --coverage` for a minimal library + test suite builds a coverage report. Maybe it should be generalized to run on the latest / matrix of LTS versions?
=> Fix building coverage report with Cabal 3

src/Stack/Coverage.hs
Fixed typo in table's "border" attribute. It didn't affect table style before because its every child draws own border.
=> Fix typo in Stack/Coverage.hs

ChangeLog.md, src/Stack/Build/Execute.hs, src/Stack/Build/Source.hs, src/Stack/Types/Package.hs
As the issue (#5125) suggests, modified time makes using a stack cache in CI very difficult (if at all possible). This PR suggests making a change in how the build process marks a file as dirty.
Summary of changes:
- When checking the build cache, always create a digest and use that to check against the cache if it exists.
- Note: let's discuss here about also checking for size.
- When adding unlisted files to the build cache don't check for pre build time. 
- This was a strange call to make to begin with and looking into the commit history it looks like it was a patch for an issue about Template Haskell (#838). Removing this check does not break the fix. I ran the two test cases mentioned in the issue with latest stack version and with the modified one from this PR and it did not cause a …
=> Remove ModTime check during build (#5125)

ChangeLog.md, doc/yaml_configuration.md, package.yaml, src/Stack/Config.hs, src/Stack/Runners.hs, stack.cabal, stack.yaml
Adds a new helper function `Stack.Config.withNewLogFunc`, used in `Stack.Config.configFromConfigMonoid` and in `Stack.Runners.withRunnerGlobal`. As indicated in the code comments, the function runs the provided action with a new `LogFunc`, given a `StylesUpdate`.
Depends on `rio-0.1.18.0`, which now includes colours in `LogOptions`, and `rio-prettyprint-0.1.1.0`.
However, I have not been able to identify why the 'SQL'-type debug log messages pick up the `LogFunc` from `withRunnerGlobal` and not the `LogFunc` fron `configFromConfigMonoid` - or by what mechanism the `LogFunc` is picked up in lines such as the one below (taken from `Stack.Storage.User.loadCompilerPaths` - the line generates a 'SQL'-type debug log message):
```haskell
mres <- withUserStorage $ getBy $ UniqueCompilerInfo $ …
```
=> Fix #5356 Allow all colours to be customised

doc/install_and_upgrade.md
I had to install it today on an older version of Amazon Linux.
=> Add zlib-devel to the list of prerequisites on CentOS

src/Stack/Config.hs
The 'SQL' debug log messages take their logging function from the environment, not from the `configRunner` of the `Config`. This proposed change uses a new helper function, `withLocalLogFunc`, to modify that part of the environment.
Tested by building, installing and using `stack` with the change on Windows 10 version 2004.
=> Fix #5364 Add the new LogFunc to the environment too

package.yaml, stack.cabal
When building `stack` with `stack build` on Windows 10 version 2004 (the version currently in the respository), I get the following warnings:
```
Cabal file warning inC:\Users\mikep\Documents\Code\GitHub\stack\stack.cabal@694:5: The field "build-tools" is deprecated in the Cabal specification version 2.0. Please use 'build-tool-depends' field
Cabal file warning inC:\Users\mikep\Documents\Code\GitHub\stack\stack.cabal@563:5: The field "build-tools" is deprecated in the Cabal specification version 2.0. Please use 'build-tool-depends' field
Cabal file warning inC:\Users\mikep\Documents\Code\GitHub\stack\stack.cabal@441:5: The field "build-tools" is deprecated in the Cabal specification version 2.0. Please use 'build-tool-depends' field
Cabal file warning …
```
=> Fix 'cabal file warnings', when building stack

doc/README.md
Adds an introductory sentence under the 'How to install' heading to make clear that the rest of the section applies both to Unix-like operating systems and to Windows, not just to the former (which is how the poster of #5321 says they misunderstood the current content).
=> Fix #5321 Spell out that stack installs on Un*x and Windows

ChangeLog.md, src/Stack/New.hs
Checklist:
Manually tested by running the command described in the issue ticket after making sure I was running the correct `stack` executable:
```
stack new hello-world \ 
github:tkachuk-labs/nix-concur-replica \
-p organization:tkachuk-labs \
-p env-prefix:HELLO_WORLD \
--resolver lts-14.27
```
Checked generated folders and imports in `*.hs` files and they're now correctly PascalCase'd.
=> Fixes #5376

src/Stack/Package.hs
This is a proposal to address #5392.
It basically passes the Cabal version down to the place where it's needed to generate the directory paths that hold auto-generated files, `resolveComponentFiles`. These directories are then used in addition to the `hs-source-dirs` directories to find `.hs` files for a component's modules.
I'm only superficially familiar with the `stack` codebase, but it seems that at least this doesn't break any of the tests.
=> Also resolve auto-generated component files.

src/Stack/Config.hs, src/Stack/Options/BuildParser.hs, src/Stack/Options/ExecParser.hs, src/Stack/Options/ScriptParser.hs, src/main/Main.hs
Adds, to `stack exec --help`, `If the command is absent, the first of any arguments is taken as the command.`
Given that change, expands the meta variables to `COMMAND` (from `CMD`) and `ARGUMENT(S)` (from `ARG`). The `(S)` is used to indicate one or more arguments.
Changes the example from `stack exec -- ghc-pkg describe base` to `stack exec ghc-pkg -- describe base`, to follow the alternative actually presented by `stack exec --help`.
So, the output of `stack exec --help` becomes (on Windows):
```
Usage: stack.exe exec COMMAND
[-- ARGUMENT(S) (e.g. stack exec ghc-pkg -- describe base)]
[--[no-]ghc-package-path] [--[no-]stack-exe]
[--package PACKAGE(S)] [--rts-options RTSFLAG] [--cwd DIR]
[--setup-info-yaml URL] [--snapshot-location-base URL]
[--help]
Execute a command. If the command is …
```
=> Fix #5322 Extend `stack exec --help` docs and consequent changes

src/Stack/Ghci.hs
I tested by trying out the repro from #5407
=> Warn, not error, on duplicate modules (fixes #5407)

src/Stack/Setup.hs
Due to monadic nature of the platform detection (`getOSKey`), each platform we want to runs `stack` from needs to be explicitly spelled out.
This change only affects the specified platform by allowing to install additional tools and `ghc`s.
=> Support Linux Sparc

src/Stack/Options/BuildMonoidParser.hs, src/Stack/Path.hs
Updates `stack build` help text to reflect that, under `stack path`, `local-bin-path` is deprecated and replaced by `local-bin`.
Updates `stack path` help text to reflect Windows default in addition to default for Unix-like OSs.
Tested by building and using on Windows 10 version 2004.
=> Fix `stack build` & improve `stack path` help text

etc/scripts/get-stack.sh
Using current `get-stack.sh` script on windows results in this prompt when `stack` is already present which naturally causes the script to fail on CI if stack was restored with cache or was already installed (eg. Github Actions already has stack installed):
```
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
Scanning the drive for archives:
1 file, 16509987 bytes (16 MiB)
Extracting archive: C:\Users\RUNNER~1\AppData\Local\Temp\tmp.LHN5OanPDA\stack.zip
--
Path = C:\Users\RUNNER~1\AppData\Local\Temp\tmp.LHN5OanPDA\stack.zip
Type = zip
Physical Size = 16509987
Would you like to replace the existing file:
Path:     C:/hostedtoolcache/windows/stack/2.5.1/x64\stack.exe
Size:     72569344 bytes (70 MiB)
Modified: 2020-10-15 15:26:04
with the file from archive:
Path: …
```
=> Do not prompt user when overwriting stack binary on Windows

ChangeLog.md, src/Stack/Ghci.hs
Resolves #5421. Tested manually
=> Proper subpackage cwd in stack repl

ChangeLog.md, src/Network/HTTP/StackClient.hs, src/Stack/New.hs
Resolves #5422 
Tested manually
=> GitHub API URL to support arbitrary default branches for templates

ChangeLog.md, doc/GUIDE.md, package.yaml, src/Stack/List.hs, src/main/Main.hs, stack.cabal
currently not working for core ghc libs with resolver
```
$ stack list zlib
zlib-0.6.2.2
$ stack --resolver lts-13 list zlib
Selected resolver: lts-13.30
zlib-0.6.2
```
=> add 'list' command to query package-version in snapshot

ChangeLog.md, etc/scripts/mirror-ghc-bindists-to-github.sh, package.yaml, src/Options/Applicative/Builder/Extra.hs, src/Options/Applicative/Complicated.hs, src/Stack/Storage/Project.hs, src/Stack/Storage/User.hs, stack-ghc-810.yaml, stack.cabal
This is intended to be a hackage-only patch release so that `stack` builds with the latest persistent and optparse-applicative versions.
=> Support build with persistent-2.11 and optparse-applicative-0.16

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Build.hs, src/Stack/Build/Execute.hs, src/Stack/Config.hs, src/Stack/Ghci.hs, src/Stack/SDist.hs, src/Stack/Types/Config.hs
Resolves #4006
This `explicit-setup-deps` unnecessary and thus it was removed
Tested manually
=> Initialize custom-setup deps for stack dist

ChangeLog.md, src/Stack/Config/Nix.hs, src/Stack/Nix.hs
This is handy for two reasons:
- ghc currently passed relies on importing nixpkgs from $NIX_PATH
that is against best practices
- one might want to refer to a compiler outside nixpkgs, for example
haskell.nix
I've tested it locally and it works as I expect it.
=> Nix: support passing ghcVersion to shell.nix

.gitignore, package.yaml, src/Control/Concurrent/Execute.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Precompiled.hs, src/Stack/Build/Source.hs, src/Stack/Dot.hs, src/Stack/PackageDump.hs, src/Stack/SDist.hs, src/Stack/Types/Build.hs, src/Stack/Types/Config.hs, src/Stack/Types/ConstructPlan.hs, src/Stack/Types/Execute.hs, src/Stack/Types/Package.hs, src/main/Main.hs, stack.cabal
- Rename lpWanted to lpShouldBeBuilt
- Move printPlan and displayTask in thee Build.hs file (where Plan and Task are defined)
- Isolate the merging of planTasks and planFinals into their own function (and remove mergeWithKeys as it's recommended to not use it in its haddock) defined in Build.hs.
- A reorganization of toAction which transforms a task into an action. This was using very redundantly the Task constructor, and the task -> action is likely to change with component builds.
- Rename W and M in ConstructPlan to more sensible names. Minor other changes there (changed the misnamed packageDepsWithTools).
- Refactor Execute.hs and split the Precompiled/installed stuff into their own module.
- Various haddock additions.
- Remove PackageDepsOracle (unused)
- Split ConstructPlan in 2 …
=>  Minor refactoring and improvements

ChangeLog.md, src/Stack/Package.hs, src/Stack/Setup.hs, stack-ghc-810.yaml, stack-ghc-84.yaml, stack-ghc-88.yaml, stack.yaml
=> Catch all errors from hi-file-parser

ChangeLog.md, doc/faq.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Constants.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Package.hs, src/Stack/Types/Config.hs
Instead of just having a hard-coded list of preprocessor extensions, this adds a configuration option for custom preprocessor extensions.
Fixes #3491 as suggested in https://github.com/commercialhaskell/stack/issues/3491#issuecomment-336742261
TODO:
I have manually tested the option on an external repo. It updates on changes as expected.
=> Add a new option for custom preprocessor extensions

ChangeLog.md, doc/GUIDE.md, package.yaml, src/Stack/Options/SDistParser.hs, src/Stack/Options/UploadParser.hs, src/Stack/Upload.hs, src/main/Main.hs, stack.cabal
This adds a `--candidate` flag to the `upload` command to upload
a package candidate rather than publishing the package.
This is useful for checking that everything looks right before
publishing. (see https://hackage.haskell.org/upload#candidates)
I have tested that passing the `--candidate` flag creates a package candidate on hackage.
=> Adds Flag to Upload Package Candidate

.github/workflows/unit-tests.yml
Found this when taking Stack's github actions as an example for my project :)
E.g. on https://github.com/commercialhaskell/stack/runs/2238843841?check_suite_focus=true checking the "Cache dependencies" step logs shows:
```
Cache not found for input keys: Linux---bust1.
```
Which clearly has no hashes in cache name
Could this be related to #5511 @snoyberg ?
=> Cache stack.yaml  from a variable properly

ChangeLog.md, src/Stack/Types/Build.hs
Closes #5430 
Indenting the error output of builds makes it so that emacs and vim cannot detect and track errors in the output.
I tested this by running this version of stack inside of my emacs and building a project that produces errors. I confirmed that compilation-mode works with `--no-interleaved-output` turned on.
=> Remove indentation for error output

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Constants.hs, src/Stack/Setup.hs
The build script has been renamed from `build.stack.sh` to `build-stack` (and `build-stack.bat` on Windows).
Fixes #5528.
The fix has been tested manually with recent GHC versions.
=> Fix path to Hadrian build script for GHC source builds

doc/build_command.md
=> Docs: remove obsolete sidenote re: lack of `stack run`

ChangeLog.md, src/Stack/Setup.hs
=> Sanity check does not include GHC_PACKAGE_PATH

.github/workflows/arm64-release.yml, etc/dockerfiles/arm64.Dockerfile, etc/scripts/release.hs
This also updates release.hs to use a more recent resolver, since
otherwise we'll have trouble on ARM64 with conflicting LLVM
installations. Unlike #5552, I took the simple workaround here of
installing GHC 8.6.5 in addition to the more recent GHC needed by
release.hs.
=> Add a GitHub Actions workflow for ARM64

ChangeLog.md, src/Stack/Types/Build.hs, stack.yaml, test/integration/tests/5180-ghc-rts-flags/Main.hs, test/integration/tests/5180-ghc-rts-flags/files/files.cabal, test/integration/tests/5180-ghc-rts-flags/files/src/Lib.hs, test/integration/tests/5180-ghc-rts-flags/files/stack.yaml
I added an integration test that ensures `stack` builds successfully when passing RTS options to GHC.
Fixes #5180
=> Allow passing RTS options to GHC in stack.yaml

src/Stack/Build/Execute.hs, src/Stack/Storage/Project.hs, src/Stack/Storage/User.hs
Unit tests are passing with the change to pantry:
https://github.com/commercialhaskell/pantry/pull/39
=> Fix compatibility with GHC 9

ChangeLog.md, src/Stack/Options/ScriptParser.hs, src/Stack/Script.hs
This is a feature I've wanted for a while but never got around to writing. For the `--optimize` and `--compile` versions of `stack script`, it can be nice to simply build the executable without running. This introduces such as `--no-run` flag.
=> Add a --no-run flag to the script command

ChangeLog.md, src/Stack/Setup.hs
Avoids finding spurious other executables. See:
https://gitlab.haskell.org/ghc/ghc/-/issues/20074
=> Use findExecutablesInDirectories during stack setup

.github/workflows/integration-tests.yml, test/integration/lib/StackTest.hs, test/integration/tests/1336-1337-new-package-names/Main.hs, test/integration/tests/3850-cached-templates-network-errors/Main.hs, test/integration/tests/git-submodules/Main.hs
We've been hitting GitHub rate limiting on a few tests. This commit both
busts the cache of a broken integration test suite (hopefully), and
disables those test runs on Mac.
=> Cache bust and disable some Mac tests

src/Stack/New.hs
=> Correct a typo in src/Stack/New.hs

ChangeLog.md, src/Stack/Build/Cache.hs, src/Stack/Build/Execute.hs
Tested by running the new Stack while making some tweaks on the Stack code base. Observed that it didn't repeatedly reconfigure.
=> Track changes to setup-config #5578

package.yaml, stack.cabal
=> Drop unneeded regex-applicative-text dep

ChangeLog.md, src/Stack/Ghci.hs
This pull request is a fix for https://github.com/commercialhaskell/stack/issues/5434
I tested like below.
- added package flags (stack:disable-git-info and stack:hide-dependency-versions) to stack.yaml
- execute `stack exec stack -- ghci`
- show BuildInfo.versionString' and confirmed flags in stack.yaml were used
=> FIX #5434: use stack.yaml's package flags in stack ghci

ChangeLog.md, package.yaml, stack-ghc-88.yaml, stack-nightly.yaml, stack.cabal, stack.yaml
=> Bump rio version for extra-path bug

ChangeLog.md, src/Stack/Build/Execute.hs
It looks like a user can't override location `ghc` and `ghc-pkg`, because these options are ignored in  `ensureConfig`. 
I prefer to leave `findExecutable` checking and I've just removed obviously mistaken adding "--with-ghc/ghc-pkg=" to the path.
=> Fixed a bug with ignoring `cpPkg` and `cpCompiler` fields.

ChangeLog.md, src/Stack/Setup.hs
**THIS IS UNTESTED** because I don't have an M1 Mac.  However, `stack --arch=aarch64 --resolver=ghc-8.10.5 setup` does download the correct bindist and tries to install it on my Intel Mac (but of course this fails with "Bad CPU type in executable").
Note: this will _only_ work with GHC 8.10.5 right now, since that's the only GHC version with an aarch64 bindist for macOS.  You can use `stack --resolver=ghc-8.10.5 setup` to test.
One potential downside of this change: `stack setup` on M1 Macs will not, by default, work with any GHC <8.10.5, since there aren't aarch64 bindists available (before this change, `stack setup` always uses the x86 bindist even on M1 Macs, so this wasn't an issue).  Users will have to use `--arch=x86_64` to force the use of Rosetta.  Mac users are pretty accustomed …
=> `stack setup` installs GHC for aarch64 on M1 Macs

ChangeLog.md, package.yaml, src/Stack/Config.hs, src/Stack/Setup.hs, stack-ghc-88.yaml, stack-nightly.yaml, stack.cabal, stack.yaml
Fixes #5411
Depends on https://github.com/commercialhaskell/pantry/pull/41
----
on cardano-wallet:
```
$ /home/hasufell/git/stack/dist-newstyle/build/x86_64-linux/ghc-8.10.7/stack-2.7.4/build/stack/stack build
Cloning 46ce81050f4015abd40c6bdf0a1ed30fa54e375a from https://github.com/input-output-hk/cardano-addresses
Cloning 7497a29cb998721a9068d5725d49461f2bba0e7a from https://github.com/input-output-hk/optparse-applicative
Cloning cb0f19c85e5bb5299839ad4ed66af6fa61322cc4 from https://github.com/input-output-hk/cardano-base
Cloning 07397f0e50da97eaa0575d93bee7ac4b2b2576ec from https://github.com/input-output-hk/cardano-crypto
Cloning 6aa1cd0a64a464371b94d4ac182e7e2cddc83a36 from https://github.com/input-output-hk/cardano-ledger-specs
Cloning 4c59442958072657812c6c0bb8e0b4ab85ce1ba2 from …
```
=> Fix cloning per subdirectory wrt #5411

ChangeLog.md, doc/GUIDE.md, src/Stack/Upload.hs, src/main/Main.hs, src/test/Stack/UploadSpec.hs
Closes #5513
Usage example:
```bash
$ HACKAGE_KEY=foobar stack upload .
```
> Please also shortly describe how you tested your change.
`stack test` was all green.
Tested scenarios:
1. Key set but wrong: Tried to upload the package with wrong API key set. `stack upload` reported finding the key, and then bounced off Hackage authentication as expected.
2. Key set and correct: Successfully uploaded a package candidate to Hackage. Removed the candidate afterwards.
3. Key not set: `stack upload` asked for username and password. I gave these (correct ones), and uploaded a package candidate to Hackage. Removed the candidate afterwards.
> Bonus points for added tests!
Included a test for the function detecting a set `HACKAGE_KEY` env var.
I want to thank @pbrisbin here for helping me get back on …
=> stack upload: Support authentication with Hackage API key

doc/nix_integration.md
=> Fix typo in doc/nix_integration.md

ChangeLog.md, src/Stack/Build/Cache.hs, src/Stack/Build/Execute.hs, src/Stack/Constants/Config.hs, test/integration/lib/StackTest.hs, test/integration/tests/5680-share-package-across-projects/Main.hs, test/integration/tests/5680-share-package-across-projects/files/package-a/package.yaml, test/integration/tests/5680-share-package-across-projects/files/package-a/src/Lib.hs, test/integration/tests/5680-share-package-across-projects/files/package-a/stack.yaml, test/integration/tests/5680-share-package-across-projects/files/package-b/package.yaml, test/integration/tests/5680-share-package-across-projects/files/package-b/src/Lib.hs, test/integration/tests/5680-share-package-across-projects/files/package-b/stack.yaml, test/integration/tests/5680-share-package-across-projects/files/package-c/package.yaml, test/integration/tests/5680-share-package-across-projects/files/package-c/src/Lib.hs, test/integration/tests/5680-share-package-across-projects/files/package-c/stack.yaml
This fixes a regression that was introduced in f64188016aea9fb34554f29858423aec0860ae4e (the fix for #5578).  Now, a package will be reconfigured if the project it's being built from (and therefore the local package database it gets installed to) changes.
How I tested:
* A new integration test is added in `test/integration/tests/5680-share-package-across-projects`
=> Fix failure to find package when a dependency is shared between projects (#5680)

src/Stack/Build.hs, src/Stack/Build/Execute.hs, src/Stack/BuildPlan.hs, src/Stack/ConfigCmd.hs, src/Stack/Init.hs, src/Stack/New.hs, src/Stack/Package.hs, src/Stack/Script.hs, src/Stack/Setup.hs, src/Stack/Types/Package.hs, src/Stack/Types/Resolver.hs, stack-ghc-902.yaml, stack.cabal
Uses C pre-processor (CPP) directives to not disturb the existing code that builds with versions of GHC before 9.0.2.
Tested by building `stack` on Windows 11. The built `stack` executable was, in turn, then tested by using it to build `stack` on Windows 11.
After building:
~~~
❯ stack --version
Version 2.7.6, Git revision 79cdfa1b6ddc5b9c06ad8dea1930d4868fe91b56 (8411 commits) RELEASE-CANDIDATE x86_64
Compiled with:
- Cabal-3.4.1.0
...
- aeson-2.0.3.0
...
- base-4.15.1.0
...
- hpack-0.34.6
...
- mintty-0.1.3
...
- pantry-0.5.4
...
~~~
I think documentation of the use of `stack` is unaffected.
One motivation for this was seeing that @snoyberg had updated `pantry-0.5.4` to support `aeson-2.0.0.0`.
=> Allow stack to build with lts-19.1 (GHC 9.0.2)

src/Stack/Build/Installed.hs, src/Stack/Config.hs, src/Stack/Options/Completion.hs, src/Stack/Package.hs, src/Stack/SDist.hs, src/Stack/Storage/Project.hs, src/Stack/Storage/User.hs, src/Stack/Types/Config.hs
This follows on from #5696 but relates to compiler warnings as opposed to just the threshold of the package building.
Clears:
~~~
src\Stack\Storage\Project.hs:42:9: warning: [-Wdeprecations]
In the use of ‘mkDeleteCascade’
(imported from Database.Persist.TH):
Deprecated: "You can now set update and delete cascade behavior directly on the entity in the quasiquoter. This function and class are deprecated and will be removed in the next major ersion."
|
42 |       , mkDeleteCascade sqlSettings
|         ^^^^^^^^^^^^^^^
src\Stack\Storage\User.hs:55:9: warning: [-Wdeprecations]
In the use of ‘mkDeleteCascade’
(imported from Database.Persist.TH):
Deprecated: "You can now set update and delete cascade behavior directly on the entity in the quasiquoter. This function and class are deprecated and …
=> Clear GHC 8.10.7 and 9.0.2 compiler warnings

CONTRIBUTING.md
The proposed addition is based on @snoyberg's comment at https://github.com/commercialhaskell/stack/pull/5696#issuecomment-1086678998. I hope I captured the intended policy accurately.
=> Add backwards conpatability to CONTRIBUTING.md

src/Path/Extended.hs, src/Stack/Docker.hs, src/Stack/Package.hs, src/Stack/Script.hs
`stack.yaml` currently uses resolver `lts-17.15`, which provides `path-0.7.0`.
This pull request removes unnecessary `#if MIN_VERSION_path(0,7,0)`.
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on the CI.
=> Remove unnecessary CPP directives

src/Stack/Types/Build.hs
Clears the redundancy identified by GHC 9.2.2, namely:
~~~
src\Stack\Types\Build.hs:319:13: warning: [-Woverlapping-patterns]
Pattern match is redundant
In a case alternative: [] -> ...
|
319 | [] -> []
| ^^^^^^^^
src\Stack\Types\Build.hs:320:13: warning: [-Woverlapping-patterns]
Pattern match is redundant
In a case alternative: [cause] -> ...
|
320 | [cause] -> ["One possible cause of this issue is:\n* " <> cause]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
~~~
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on the CI.
=> Clear Stack.Types.Build.missingExeError redundancy

src/Stack/Options/GlobalParser.hs, src/main/Main.hs
The existing option parser of `stack new` borrows from the parser of `stack init`. This pull request extends the documentation of `stack init --help`, so that `stack new --help` makes more sense. The introduction to `stack new` also now mentions that initialisation may be involved or can be forced.
=> Fix #5618 Improve documentation of `stack new`

ChangeLog.md, src/Stack/Clean.hs, src/main/Main.hs
The existing:
~~~haskell
cleanCmd = withConfig NoReexec . withBuildConfig . clean
~~~
wraps `clean` in `withBuildConfig`, but that ends in `initProjectStorage projectStorageFile` and, so, uses one of the very files (`projectStorageFile`) that `stack clean -full` will attempt (and fail) to delete.
This pull request moves the `withBuildConfig` to wrap only the function that yields the list of files to be deleted (`dirsToDelete cleanOpts`), so that `projectStorageFile` is not in use when the file comes to be deleted.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building `stack` and using `stack clean --full`.
=> Fix #5714, so files to be deleted by `stack clean --full` are not in use

doc/GUIDE.md
=> Fix #5664 Improve STACK_ROOT documentation

src/Stack/Build/ConstructPlan.hs
Clears
~~~
src/Stack/Build/ConstructPlan.hs:1222:22-43: Warning: Use max
Found:
if x > y then x else y
Perhaps:
max x y
~~~
=> Fix CI hlint message

ChangeLog.md, src/Stack/Coverage.hs
The fix:
* adapts the existing `Stack.Coverage.displayReportPath` to require the log message prefix to be specified (not assume that it is 'The' in all cases);
* modifies the existing use of `displayReportPath` to specify the initial 'The'; and
* applies modified `displayReportPath` to the report that begins 'An index of the generated HTML coverage reports'.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building, and using, `stack` with the change.
=> Fix #5727 Remove inconsistency in pretty formatting of `--coverage`

ChangeLog.md, src/Stack/Build/ConstructPlan.hs, stack-ghc-902.yaml, stack.cabal, stack.yaml
`hpack-0.35.0`, released 24 April 2022, has some important extensions to the `package.yaml` format. See https://hackage.haskell.org/package/hpack-0.35.0/changelog.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building, and using, `stack`.
=> Bump to providing `hpack-0.35.0`

src/Stack/Init.hs
Currently, `Stack.Init.getRecommendedSnapshots` yields all the snapshots at https://s3.amazonaws.com/haddock.stackage.org/snapshots.json. This pull request filters out the LTS that `stack` documents that it does not support.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building `stack` and using as described in #5543.
=> Fix #5543 Filter all LTSs to yield supported LTSs

ChangeLog.md, src/Stack/Coverage.hs
Currently, `Stack.Coverage.generateHpcUnifiedReport` assumes that a unified coverage report will be redundant if there is only one `*.tix` file. However, that is not necessarily the case. For example, one package may test the library of another package that does not test its own library.
As an interim solution, this proposed pull request suggests that a unified report should always be produced if there is one or more `*.tix` files, even if it may be redundant in some circumstances.
A more complex solution would be to have a more complex test that determines whether a unified report would be truely redundant if there is only one `*.tix` file.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building, and using, `stack`.
=> Fix #5713 Don't assume unified coverage report redundant if only one *.tix file

doc/yaml_configuration.md
Yesterday, I didn't get that this dot is **not** a placeholder for `no-matter-what`, but one for the current directory, and spent long hours trying to generate a valid hie.yaml for a multi-package project :(
=> move relevant sentence closer to the example

doc/GUIDE.md, doc/developing_on_windows.md, doc/maintainers/msys.md, doc/maintainers/releases.md, doc/yaml_configuration.md, mkdocs.yml
Updates the guide to updating MSYS2 in `msys.md`.
Also updates references in the documentation to refer consistently to MSYS2 by MSYS2.
=> Update MSYS2-related documentation

doc/maintainers/msys.md
The code blocks are still not rendering properly in HTML (sorry), despite rendering fine in VS Code. This is my second attempt to fix that.
=> Fix markdown code blocks not rendering in HTML

doc/maintainers/msys.md
MkDocs is limited in respect of the formatting of code blocks outside of the document root. See https://www.mkdocs.org/user-guide/writing-your-docs/ and https://python-markdown.github.io/extensions/fenced_code_blocks/.
This (hopefully) fixes the residual rendering problems introduced by my recent changes to `msys.md`.
=> Fix code block formatting

ChangeLog.md, etc/scripts/build-stack-installer.hs, etc/scripts/release.hs
Fixes #5643.
* I ran `stack etc/scripts/release.hs release` locally and installed stack again through the generated installer. I then verified in the registry that `DisplayVersion` is set correctly, and that `winget list stack` now properly shows the installed version (2.7.4).
=> Add Windows registry DisplayVersion (#5643)

doc/GUIDE.md
Reformats `GUIDE.md` to trim long lines outside of code blocks. No changes are made to the content.
The motivation for this is to provide a better foundation for some future pull requests.
=> Tidy GUIDE.md - no content changes

ChangeLog.md, doc/GUIDE.md, src/Stack/Config.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Script.hs, src/Stack/Types/Config.hs
This proposed pull request adds a `--force-script-no-run-compile` flag (disabled by default) that forces the `--no-run` and `--compile` options with `stack script`.
This enables a command like `stack --force-script-no-run-compile Script.hs` to behave like `stack script ... --no-run --compile -- Script.hs` but without having to list all the other arguments in the stack interpreter options comment (represented by `...`) on the command line.
Also adds an explanation to the online documentation.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using `stack`.
=> Fix #5755 Add --script-no-run-compile flag

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml
Also bumps Github Action `actions/cache` from v1 to v3.
=> Fix #5765 Add caching to CI on Windows

.gitignore
I like to be able to build projects with either stack or cabal. I saw #5677 and tried it, noticing that the cabal build products aren't ignored by git. This change ignores those in `dist-newstyle/`.
=> Ignore dist-newstyle folder.

doc/nix_integration.md, stack.cabal
Rewritten some paragraphs in an active voice, added more background info of Nix in some places to make it easier for Nix beginners to use it with Stack, and added a section on how to use Stack with NixOS and Nix flakes.
It answers my question in https://github.com/commercialhaskell/stack/issues/5773.
Feel free to edit as you wish, maintainers.
=>  Expand Nix integration docs with more context and NixOS section

ChangeLog.md, src/Stack/New.hs
The problem was caused by `applyMustache` (in `Stack.New.applyTemplate`) containing the relevant `logInfo` action, and being applied repeatedly by `mapM`.
This solution moves the `logInfo` action outside the `mapM`, modifies `applyMustache` to yield also the missing keys, and accumulates the missing keys (`mapAccumLM`) as each of the `files` is processed.
`ChangeLog.md` is also updated. Tested by building and using Stack.
=> Fix #5780 Accumulate missing keys before logging

ChangeLog.md, src/Options/Applicative/Complicated.hs
For example, before the change, `stack ls` yields only:
~~~
Missing: COMMAND
Usage: stack.exe ls COMMAND [--setup-info-yaml URL]
[--snapshot-location-base URL] [--help]
List command. (Supports snapshots, dependencies and stack's styles)
~~~
After the change, `stack ls` yields the more informative:
~~~
Usage: stack.exe ls COMMAND [--setup-info-yaml URL]
[--snapshot-location-base URL] [--help]
List command. (Supports snapshots, dependencies and stack's styles)
--setup-info-yaml URL    Alternate URL or relative / absolute path for stack
dependencies
--snapshot-location-base URL
The base location of LTS/Nightly snapshots
--help                   Show this help text
Available commands:
snapshots                View local snapshot (default option)
dependencies …
=> Fix #809 Use `showHelpOnEmpty`

CONTRIBUTING.md
The new content is largely taken from https://www.snoyman.com/blog/2021/01/stack-governance/, with some minor stylistic changes and the addition of a little introductory welcome and context.
I thought `CONTRIBUTING.md` was the best place to put it because, if I were thinking about contributing something, that would be the first file that I opened.
@snoyberg, I hope this is in order. I did not know where to look to understand the list of current 'maintainers' of Stack. I think it would be useful to list them publicly. At the end of the existing material, there is a reference to a Slack channel that refers to you and @borsboom by name. Your blog post above indicates your desire to move to Matrix/Element, if that would coordinate with the Haskell Foundation. Is there any update/correction …
=> Fix #5787 Add info about goals, governance and support

ChangeLog.md, package.yaml, stack-ghc-902.yaml, stack-ghc-922.yaml, stack.cabal, stack.yaml
=> Bump pantry to 0.5.6 commercialhaskell/pantry#53

src/Stack/Config.hs, src/Stack/Options/ExecParser.hs, src/Stack/Options/ScriptParser.hs
Changes the help text for `--package`, see #5455.
Tested with:
```
> stack run stack -- repl --help
Usage: stack repl [TARGET/FILE] [--pedantic] [--ghci-options OPTIONS]
[--ghc-options OPTIONS] [--flag PACKAGE:[-]FLAG]
[--with-ghc GHC] [--[no-]load] [--package PACKAGE(S)]
[--main-is TARGET] [--load-local-deps] [--[no-]package-hiding]
[--only-main] [--trace] [--profile] [--no-strip] [--[no-]test]
[--[no-]bench] [--setup-info-yaml URL]
[--snapshot-location-base URL] [--help]
Run ghci in the context of package(s) (experimental) (alias for 'ghci')
TARGET/FILE              If none specified, use all local packages. See
https://docs.haskellstack.org/en/stable/build_command/#target-syntax
for details. If a path to a .hs or .lhs file is
specified, it will be loaded.
--pedantic …
```
=> Help text allows multiple use for --package.

src/Options/Applicative/Complicated.hs, src/main/Main.hs
I was hacking around on Stack today, familiarising myself with some of the startup code and playing around adding some logging. I noticed this type, and found it to be adding quite a lot of indirection. Once I figured out what it was doing I thought it seemed logical to make some of the type aliases concrete, as they are only operating on a single type. I think this makes the type signatures less confusing here. I've also moved out a type alias to a place that seems like a suitable home :smile: 
-------
I believe this change should be …
=> Alter command types to be less abstract

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Setup.hs, src/Stack/Types/Config.hs, test/integration/tests/ghc-install-hooks/Main.hs, test/integration/tests/ghc-install-hooks/files/.gitignore, test/integration/tests/ghc-install-hooks/files/foo.hs, test/integration/tests/ghc-install-hooks/files/run.sh
This adds GHC installation hooks. The feature is described in the documentation. I tested it with the newly added integration test.
=> Support custom GHC installation hooks

ChangeLog.md, src/Stack/Ls.hs, src/Stack/Path.hs, src/Stack/Setup.hs, src/Stack/Setup/Installed.hs, src/main/Main.hs
This proposed pull request adds a `tools` subcommand to the `stack ls` command, in order to list stack's installed tools (in order) at the command line. A `--filter TOOL_NAME` option is provided to filter the tools listed by name (the default being no filter).
The existing help for `stack path --programs` is extended to refer to the existence of `stack ls tools`.
The primary motivation for this was to allow Windows users to find easily the full name of the stack-supplied MSYS2 tool(s) (by using `stack ls tools --filter msys2`) - without having to investigate the structure under the stack root. The full name is useful to know in setting the `PKG_CONFIG_PATH` environment variable manually. (See #1586.)
However, it would also allow all users to find easily the installed version(s) of GHC (by …
=> Add `stack ls tools` subcommand

doc/GUIDE.md
I tried following these instructions but didn't realize I needed to update both `package.yaml` and `stack.yaml` and 
encountered the same "Could not find module ‘Acme.Missiles’" problem [**godzsa** did three years ago](https://stackoverflow.com/questions/48251027/cannot-add-extra-deps-to-stack-project) 
so I suggest this recap for beginners.
=> Add explicit details for `acme-missiles` example

etc/scripts/get-stack.sh
`arch` command is not installed at default.
see coreutils document:
> arch is not installed by default, so portable scripts should
> not rely on its existence.
https://www.gnu.org/software/coreutils/manual/html_node/arch-invocation.html
ref: https://github.com/google/fscrypt/issues/92#issuecomment-365712796
closes: #5629
---
=> Use `uname -m` instead of `arch` comamnd

package.yaml, stack.cabal
Stack advises that it should be built with Stack, but some users wish to use Cabal (the tool) to build Stack. This is possible if the upper bound on `persistent` is specified.
=> Fix #5677 Add upper bound for `persistent` in `package.yaml`

src/Stack/Package.hs
`-DFOO` options can be passed directly to ghc, but
cpp-options may include flags for the preprocessor,
such as `-std=c99`, so we need to pass it via `-optP`.
Fixes #5532
@fendor
=> Fix how cpp-options are passed to ghci wrt #5532

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Build/Execute.hs, src/Stack/Config/Build.hs, src/Stack/Options/BuildMonoidParser.hs, src/Stack/Types/Config/Build.hs, src/test/Stack/ConfigSpec.hs
Retains the existing `--[no-]cabal-verbose`, as an alternative flag on the command line.
As with the existing flag, the new option can be set in configuration files. The new option has priority in configuration files.
Error messages are provided if the specified verbosity is not recognised by Cabal (the library).
The `ChangeLog.md` and documentation are updated accordingly.
Tested by building Stack on Windows 11, and using it with various combinations of options at the command line and/or in a `stack.yaml` file.
=> Fix #1369 Add build option `--cabal-verbosity=VERBOSITY`

doc/Stack_and_VS_Code.md, mkdocs.yml
The use of the 'Haskell' extension for Visual Studio Code (VS Code), the extent of its current integration with Stack, and the possible implications of that for Stack's position relative to other build tools for Haskell (namely, Cabal (the tool)) have been the subject of some extensive discusion recently on the [Haskell Community](https://discourse.haskell.org/), under a number of Topics.
This proposed pull request seeks to add documentation on Stack and VS Code and the current position. Its objective is to capture that there are current viable workarounds to the limitations and that future developments may see the extension able to work well with Stack.
=> Add docs on Stack and VS Code

src/Stack/Setup.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Taken from #5763 development and tested as part of the testing of that.
=> Fix #5758 Warn only if GHC > 9.2 or > Cabal > 3.6

src/Stack/Package.hs, stack-ghc-923.yaml
GHC 9.2.3 comes with `Cabal-3.6.3.0`. From `Cabal-3.6.0.0` the type of `Distribution.Types.BuildInfo.hsSourceDirs` changed from:
~~~
BuildInfo -> [FilePath]
~~~
to:
~~~
BuildInfo -> [SymbolicPath PackageDir SourceDir]
~~~
where type `SymbolicPath from to` represents relative paths.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested as part of #5763. Stack built with GHC 9.2.3 reveals upstream bugs on macOS - see #5763.
=> Allow stack to build with GHC 9.2.3 (nightly-2022-07-29)

.github/workflows/hlint.yml, .github/workflows/unit-tests.yml, .github/workflows/yamllint.yml, .hlint.yaml, .yamllint.yaml, mkdocs.yml, package.yaml, stack-ghc-902.yaml, stack-ghc-922.yaml, stack.yaml
The vscode editor showed problems with `.hlint.yaml`. I was able to reproduce these before fixing them by installing and configuring yamllint for which I added a GitHub action. In reviewing `.hlint.yaml` I saw that we should have been adding our errors before any ignores. Added a comment introducing why we have the "Use alternative" ignore. The ignore for "Too strict maybe" was repeated so I reduced this duplication collecting the within modules together. For YAML linting I'm ignoring most of `.gitub/workflows/`, `doc` and `test` folders.
I pulled the hlint action out of the unit-tests action and used `haskell/actions/setup-hlint` for the set up.
=> Lint YAML especially `.hlint.yaml`.

.github/workflows/stan.yml, .gitignore, .stan.toml, package.yaml, stack.cabal
Adds a gh-action for [stan](https://kowainik.github.io/projects/stan). Both the project and stan need to be built with the same GHC version. All of the triggered checks are excluded. We can chip away at the hints once this action is set up.
=> Add stan gh-action and ignore triggered checks

ChangeLog.md, src/Stack/Ls.hs
Explains that local snapshots are identified by hash codes.
Also explains that, on a terminal, the `stack ls snapshots` command uses a pager if one is available (and how).
Also removes the redundant `Stack.Ls.listDependenciesCmd`.
Also corrects the incorrect output of `stack ls snapshots local` on Windows.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack (on Windows).
There are other improvements that could be made to `stack ls snapshots` (for example: `local` is of little use - `remote` would be the better default; the `lts` and `nightly` filters make no sense for `local`), which would change the existing behviour (rather than correct it). This pull request does not address those other improvements.
=> Fix #5312 Better help for `stack ls snapshots local`

package.yaml, src/Stack/ConfigCmd.hs, src/Stack/YamlUpdate.hs, stack.cabal
> Sadly, we do not have a format-and-comment-preserving YAML parser/writer available that I'm aware of. There are other cases where Stack has to modify the the stack.yaml with the same problem. It's really annoying.
https://github.com/commercialhaskell/stack/issues/3136#issuecomment-296629195
I tested with the `stack.yaml` file in this repo. Want to get this reviewed before adding tests. The commands I used for testing were:
```
> cabal run stack -- config set system-ghc true
> cabal run stack -- config set system-ghc false
> cabal run stack -- config set install-ghc true
> cabal run stack -- config set install-ghc false
> cabal run stack -- config set resolver lts-19.17
> cabal run stack -- config set resolver nightly
```
I …
=> Use original YAML to preserve top-level order.

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Options/GhcBuildParser.hs, src/Stack/Options/GhcVariantParser.hs, src/Stack/Types/Config.hs
Tested by building and using Stack with the `--ghc-variant=int-native` option and GHC 9.4.2, using:
~~~yaml
resolver: ghc-9.4.2
packages:
- .
ghc-variant: int-native
setup-info:
ghc:
windows64-int-native:
9.4.2:
url: https://downloads.haskell.org/~ghc/9.4.2/ghc-9.4.2-x86_64-unknown-mingw32-int_native.tar.xz
content-length: 282584664
sha1: 6469af0cc463ee15826cda353784cfea6c81f439
sha256: e5267e340da903be81a55f12d63637ed5c493b6d5232bb87149ae4bf420ae0dd
~~~
=> Fix #5833 Add `int-native` GHC variant

.github/workflows/integration-tests.yml
Without these changes, the following things can go wrong in forks:
1. when one pulls in an update to `master`, the the workflow will run, and then get stuck waiting for a self-hosted-runner
2. if one _had_ a self-hosted-runner, signing would fail unless one also had a signing secret
3. if one had both of the above and had an organization that restricts permissions, then the workflow could fail because it doesn't ask for write permissions
Beyond that, the [GitHub's …
=> Integration tests in forks

.github/workflows/integration-tests.yml
1. I tried pulling in the latest `master` hoping everything would work: https://github.com/check-spelling/stack/runs/8276358068?check_suite_focus=true
-- it didn't, apparently the value comparison logic didn't end up w/ the values we wanted
2. I tried a number of combinations... https://github.com/check-spelling/stack/actions
3. This combination did the right thing for forks w/o the secret: https://github.com/check-spelling/stack/runs/8277415398?check_suite_focus=true
4. …
=> Use distinct output for boolean logic

cabal.project
People (like me) that might like to use cabal to work on stack shouldn't need to first resolve dependencies. We can help with that. Before this fix:
```
> cabal build all --enable-tests --enable-benchmarks
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: stack-2.10.0 (user goal)
[__1] trying: template-haskell-2.19.0.0/installed-2.19.0.0 (dependency of
stack)
[__2] next goal: persistent (dependency of stack)
[__2] rejecting: persistent-2.14.2.0 (conflict: stack => persistent>=2.13.3.5
&& <2.14)
[__2] skipping: persistent-2.14.1.0, persistent-2.14.0.3, persistent-2.14.0.2,
persistent-2.14.0.1 (has the same characteristics that caused the previous
version to fail: excluded by constraint '>=2.13.3.5 && <2.14' from 'stack')
[__2] rejecting: …
```
=> Adds a cabal.project file.

src/Path/Find.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Source.hs, src/Stack/Coverage.hs, src/Stack/GhcPkg.hs, src/Stack/Ghci.hs, src/Stack/Ghci/Script.hs, src/Stack/New.hs, src/Stack/SDist.hs, src/Stack/Setup.hs, src/Stack/Setup/Installed.hs, src/main/Main.hs
Pretty simple import fixes.
Importing `Data.List` qualified wherever it's used  (and removing it when only `map` is used, because it's from `base`)
=> import `Data.List` qualified as "-Wcompat-unqualified-imports" says

src/setup-shim/StackSetupShim.hs
Using Stack 2.9.1 to build a package with a dependency on `Cabal` and `process` and:
~~~yaml
resolver: lts-19.25 # GHC 9.0.2 (comes with Cabal-3.4.1.0)
extra-deps:
- Cabal-3.8.1.0
- Cabal-syntax-3.8.1.0
- process-1.6.15.0
~~~
yields error:
~~~
process                      > configure
process                      > [1 of 2] Compiling Main             ( C:\Users\mikep\AppData\Local\Temp\stack-d0efe7ccadb373e9\process-1.6.15.0\Setup.hs, C:\Users\mikep\AppData\Local\Temp\stack-d0efe7ccadb373e9\process-1.6.15.0\.stack-work\dist\d53b6a14\setup\Main.o )
process                      > [2 of 2] Compiling StackSetupShim   ( C:\sr\setup-exe-src\setup-shim-Z6RU0evB.hs, C:\Users\mikep\AppData\Local\Temp\stack-d0efe7ccadb373e9\process-1.6.15.0\.stack-work\dist\d53b6a14\setup\StackSetupShim.o )
process …
=> Fix Ambiguous module name `Distribution.PackageDescription`

etc/dockerfiles/arm64.Dockerfile
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on the CI to test.
=> Fix #5871 For AArch64, use Debian 10 rather than Ubuntu 20.04

ChangeLog.md, doc/yaml_configuration.md, package.yaml, src/Stack/Config.hs, src/Stack/Types/Config.hs, stack-macos.yaml, stack-macos.yaml.lock, stack.cabal, stack.yaml, stack.yaml.lock
See also the related Pantry pull request: https://github.com/commercialhaskell/pantry/pull/61.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack on Windows 11.
This pull request is draft until the corresponding Pantry pull request is accepted.
=> Fix #5870 Provide default for `hackage-security` key

ChangeLog.md, doc/GUIDE_advanced.md, src/main/Main.hs, test/integration/tests/internal-libraries/Main.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack on Windows 11.
=> Fix #5902 Change behaviour of `stack --no-install-ghc setup`

ChangeLog.md, doc/GUIDE_advanced.md, src/Stack/ConfigCmd.hs
This approach to `set` for a sequence of keys (here `package-index`, `download-prefix` - the first non-top-level key for `set`) chimes (deliberately) with the existing approach to `query` (eg `stack query locals stack version`).
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack on Windows 11.
=> Fix #5870 Add `stack config set package-index download-prefix` command

doc/maintainers/stack_errors.md, src/Stack/Coverage.hs
=> Re #5911 Tidy up exceptions in Stack.Coverage

CONTRIBUTING.md, ChangeLog.md, doc/GUIDE.md, src/Stack/Config.hs, src/Stack/Constants.hs, src/Stack/Path.hs, src/Stack/Types/Config.hs
This patch implements basic XDG support, as requested in #4243, with the
following logic:
- Environment variable override takes precedence as before.
- If the old-style `~/.stack` directory exists, use it.
- Otherwise, put the global `config.yaml` in a subdirectory of
`XDG_CONFIG_HOME`, and the rest in a subdirectory of `XDG_DATA_HOME`.
I tested this in a clean VM with no prior `stack` installed, with the following commands:
```bash
vagrant@bullseye:~$ tree -a
.
├── .bash_logout
├── .bashrc
├── .profile
└── .ssh
└── authorized_keys
1 directory, 4 files
vagrant@bullseye:~$ /vagrant/build/stack new test
[...]
vagrant@bullseye:~$ tree -a
.
├── .bash_logout
├── .bashrc
├── .config
│   └── stack
│       └── config.yaml
├── .local
│   └── share
│       └── stack
│           ├── pantry
│   …
```
=> Add XDG support

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Haddock.hs, src/Stack/Build/Source.hs, src/Stack/Package.hs, src/Stack/SDist.hs, src/Stack/Types/Dependency.hs, src/Stack/Types/Package.hs, stack.cabal
This is a preparation work for #5920. It really is a simple review of unused fields and I had to move all the Dependency related types to a dedicated module because having them in Package made circular imports when moving dependencies to Components. 
@mpilgrem
=> Simple refactoring

doc/maintainers/stack_errors.md, src/Options/Applicative/Builder/Extra.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/BuildPlan.hs, src/Stack/Constants.hs, src/Stack/Dot.hs, src/Stack/Hoogle.hs, src/Stack/Ls.hs, src/Stack/Package.hs, src/Stack/SDist.hs, src/Stack/Types/Build.hs, src/Stack/Types/TemplateName.hs
Also prefers `RIO`'s `impureThrow` to `Control.Exception`'s `throw`.
Please also shortly describe how you tested your change. Bonus points for added tests! Relying mainly on CI.
=> Re #5911 Tidy up exceptions in Stack.SDist, Stack.Hoogle and various other

src/Stack/Options/BuildMonoidParser.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Options/DockerParser.hs, src/Stack/Options/GhcBuildParser.hs, src/Stack/Options/GhcVariantParser.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Options/HpcReportParser.hs, src/Stack/Options/LogLevelParser.hs, src/Stack/Options/PackageParser.hs, src/Stack/Options/ResolverParser.hs, src/Stack/Options/ScriptParser.hs
Also, some reformatting of the same modules.
Please also shortly describe how you tested your change. Bonus points for added tests! Built on Windows; relying on CI for rest.
=> Add export lists and explicit imports

etc/dockerfiles/arm64.Dockerfile
Stack had used GHCup's Stack 2.9.1 because of problems with Stack's Stack 2.9.1.
=> Revert to Stack's Stack 2.9.3 in arm64.Dockerfile

ChangeLog.md, src/Stack/FileWatch.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested by building and using Stack on Windows. Relying on CI for other operating systems.
=> Fix #5978 Handle pretty exceptions with `--file-watch`

ChangeLog.md, src/Stack/Package.hs
=> Fix #5973 `stack ghci` makes use of Cabal file `default-language` keys

ChangeLog.md, doc/GUIDE.md, doc/path_command.md, src/Stack/Constants.hs, src/Stack/Path.hs
=> Fix #6003 Remove deprecated `stack path` flags

doc/README.md
This back tick causes the command to be incorrect
=> Remove back tick from documentation

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml
After a number of false starts, I finally worked out how to fix the problem of replacing the GitHub hosted runner-supplied Stack 2.9.1 (which cannot build Stack) with Stack 2.9.3 (which can).
Relying on CI to test CI.
=> Fix the GitHub Actions CI

ChangeLog.md, src/Stack/Setup.hs, src/Stack/Upgrade.hs
I have tested the following on Windows (see further below) but I am unable to test myself on non-Windows. Can any non-Windows/x86_64 users of Stack assist with testing?
I understand that, on Windows, you can rename the file of a running executable but you can't overwrite it. That was reflected in the existing code at `Stack.Setup.downloadStackExe` (extract):
~~~haskell
case platform of
Platform _ Cabal.Windows | FP.equalFilePath (toFilePath destFile) currExe -> do
old <- parseAbsFile (toFilePath destFile ++ ".old")
renameFile destFile old
renameFile tmpFile destFile
_ -> renameFile tmpFile destFile
~~~
I moved that same logic into a new helper function `relocateStackExeFile`:
~~~haskell
relocateStackExeFile ::
HasTerm env
=> Path Abs File
-- ^ Path to the currently running executable
-> …
=> Fix #5968 New approach to overwriting existing Stack executable

doc/pantry.md
I spent some time trying to understand why `github: user/repo` in `extra-deps` does not work if repo contains git submodules.
Probably it worth to explicitly mention the difference between `git` and `github` in documentation.
ref #5603
=> Document a difference between `git` and `github` in `extra-deps`

cabal.config, cabal.project
A small maintenance bump in the cabal project to match the stack project. Added a note about using `with-compiler`.
=> Bump the cabal project to match lts-20.0 in stack.yaml.

src/Stack/Build.hs, src/Stack/Build/Execute.hs, src/Stack/ComponentFile.hs, src/Stack/Coverage.hs, src/Stack/FileWatch.hs, src/Stack/GhcPkg.hs, src/Stack/Ghci.hs, src/Stack/PackageDump.hs, src/Stack/Setup.hs, src/Stack/SourceMap.hs
`HasTerm env` implies `HasLogFunc env`.
=> Remove redundant `HasLogFunc env` constraints

src/Path/Extra.hs, src/Stack/Build/Execute.hs, src/Stack/ComponentFile.hs, src/Stack/Ghci.hs, src/Stack/PackageFile.hs
As discussed in the corresponding issue, `resolveFile` can throw an error that `forgivingAbsence` does not 'forgive', if the path is to a file that does not exist and it contains elements that `parseAbsFile` will reject as not being a valid absolute path to a file.
This pull request replaces that with a new helper function `forgivingResolveFile` that handles the actual error that `resolveFile` might throw: `InvalidAbsFile`.
=> Fix #5866 Replace duff `forgivingAbsence $ resolveFile ...`

src/Path/Extra.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Target.hs, src/Stack/ComponentFile.hs, src/Stack/Ghci.hs, src/Stack/PackageFile.hs
`forgivingResolveDir` corresponds to `forgivingResolveFile`, but for directories. See https://github.com/commercialhaskell/stack/pull/6028.
Fixes `InvalidAbsDir`, thrown by `Stack.Build.Target.parseRawTargetDirs`.
Also removes some redundant `liftIO` where `forgivingResolveFile` or `forgivingResolveFile'` was used.
=> Add forgivingResolveDir

src/Stack/Build/Target.hs
A rough fix for #6032. If it merits more work, I'll be happy to tidy it up, add a change log and some tests. What do you think?
The new behaviour:
```
$ stack build stack-yaml ghc-9.2.4.cabal2stack.yaml --dry-run
Error: [S-8506]
Stack failed to parse the target(s).
While parsing, Stack encountered the error:
Directory not found: ghc-9.2.4.cabal2stack.yaml. Is this a typo? Can I suggest: --stack-yaml ghc-9.2.4.cabal2stack.yaml
Stack expects a target to be a package name (e.g. my-package), a package identifier (e.g. my-package-0.1.2.3), a package component
(e.g. my-package:test:my-test-suite), or, failing that, a relative path to a directory that is a local package directory or a parent
directory of one or more local package directories.
```
```
$ stack build …
```
=> Check if target might be a project-level configuration file, not a missing directory

ChangeLog.md, doc/maintainers/stack_errors.md, src/Stack/Build.hs, src/Stack/Types/Build.hs
=> Fix #6050 Drop Cabal versions before 1.22.

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml
`pkg-config` is now supplied in the GitHub Hosted Runner for macOS. See https://github.com/actions/runner-images/pull/7125.
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on CI to test CI.
=> pkg-config supplied in GitHub Hosted Runner for macOS

src/Stack/Package.hs, src/Stack/Types/Build.hs, src/Stack/Types/Package.hs
Also, extends `Stack.Types.Build.configureOptsNoDir` (`toDepOption`, for Cabal's `--dependency` option) to recognise when a package identifier's name refers to a sub-library dependency.
Please also shortly describe how you tested your change. Bonus points for added tests! Relying on CI,
=> Add sub-library dependencies to Package type

src/Stack/Config.hs, src/Stack/Docker.hs, src/windows/System/Posix/User.hs, stack.cabal
=> Fix #6069 Avoid unix-compat's System.PosixCompat.User

doc/GUIDE.md
The current link points to a non-existing anchor on the `GUIDE_advanced.md` page.  It seems reasonable to link directly to the `template` command page, when the text says `see the stack templates command documentation`.
=> doc: `stack new` links directly to `template_command.md`

ChangeLog.md, doc/script_command.md, src/Stack/Options/ScriptParser.hs, src/Stack/Script.hs
This adds a new option `stack script --use-root` which will write the intermediate files like `Main.hi` and `Main.o` and the executable itself `Main` to a unique subdirectory under the new `~/.stack/scripts` directory (to avoid conflicts) so that the intermediate files don't clutter up your project directory.
New `~/.stack/scripts` directory structure:
```
~/.stack/scripts/
├── %2FUsers%2Fjohn%2FMain.hs/
│   ├── Main
│   ├── Main.dyn_hi
│   ├── Main.hi
│   └── Main.o
├── %2FUsers%2Fjohn%2FMain2.hs/
└── %2FUsers%2Fjohn%2Fother%2FMain.hs/
```
Paths are escaped via URL encoding.
Resolves https://github.com/commercialhaskell/stack/issues/6079
=> stack script --use-root

ChangeLog.md, src/Stack/Build/ConstructPlan.hs
=> Fix #6086 Correct warning when allow-newer-deps but allow-newer is false

src/Stack/Build/ConstructPlan.hs
=> Fix #6086 Improve allow-newer-dep messages

ChangeLog.md, doc/build_command.md, doc/yaml_configuration.md, package.yaml, src/Stack/Build/Source.hs, src/Stack/Config.hs, src/Stack/Options/BuildParser.hs, src/Stack/Types/ApplyProgOptions.hs, src/Stack/Types/Build.hs, src/Stack/Types/BuildOpts.hs, src/Stack/Types/Config.hs, src/Stack/Types/ConfigMonoid.hs, stack.cabal
Also adds apply-prog-options configuration option.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested in a similar way to #6083, but also checked that flags are considered to have changed if options changed.
=> Fix #2868 Add --PROG-option to stack build

ChangeLog.md, doc/upgrade_command.md, src/Stack/Options/UpgradeParser.hs, src/Stack/Upgrade.hs, src/main/Stack/CLI.hs
=> Fix #3708 By default, don't overwrite a Stack executable not named stack

.github/workflows/unit-tests.yml, ChangeLog.md, src/main/BuildInfo.hs
Also extend CI to include `stack build --flag stack:disable-git-info`.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally and also relying on extended CI.
=> Fix #6125 Restore building Stack with Cabal flag disable-git-info

src/Stack/ComponentFile.hs
For some large packages in our project `getPackageFiles` has always quite a long time to complete, but it seems much worse in 9.4.x. (~7.5 seconds on my machine with stack 2.11 and ghc 9.4.5). Profiling showed it spent most of its time checking the the files from `usages` in `.hi` files existed. 
When I checked what paths it was checking and how often I found that every `.hi` file mentioned many `.so` files (~150) and each of these files was being checked it existed for each `.hi` file.
This change attempts to collect up known resolution mappings whilst walking the `.hi` files so the resolution effort doesn't get repeated.
This takes our slowest `getPackageFiles` call down to ~3.6 seconds with the profile now showing the cost is mostly parsing the `.hi` files.
I've included before and …
=> don't repeatedly resolve common usage paths

ChangeLog.md, doc/build_command.md, src/Stack/IDE.hs, src/Stack/Types/SourceMap.hs, src/main/Stack/CLI.hs
In a project (`stack.yaml`) with hundreds of packages I want a quick way to list test suites only.
```
$ ~/.local/bin/stack ide targets --help
Usage: stack ide targets [--exes] [--tests] [--benchmarks] [--stdout] 
[--setup-info-yaml URL] [--snapshot-location-base URL] 
[--help]
List all available Stack targets.
--exes                   List exes (list with --tests and --benchmarks). The
default is to list every target but you can use
--exes with --tests and --benchmarks to limit the
output to 1, 2 or 3 of these component types.
--tests                  List tests (list with --exes and --benchmarks).
--benchmarks             List benchmarks (list with --exes and --tests).
--stdout                 Send output to the standard output stream instead of
the default, the …
```
=> Add ide target component types

ChangeLog.md, src/Stack/Setup.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested that it does not break `stack setup` on Windows. Not tested that it solves the reported issue. Relying on CI for other operating systems.
=> Fix #5412 sanityCheck passes GHC flag -hide-all-packages

ChangeLog.md, src/Stack/Constants/Config.hs, src/Stack/Types/CompilerPaths.hs
This makes the dist build paths more consistent: clearly differentiated by ghc minor versions.
I tested by building stack with a stack including this change.
There is a bit more rationale in the commit message.
=> distRelativeDir: use ghc version instead of Cabal version 

cabal.config, cabal.project, package.yaml, src/Stack/Config.hs, src/Stack/Docker.hs, src/Stack/Storage/Util.hs, src/windows/System/Posix/User.hs, stack.cabal, stack.yaml, stack.yaml.lock
Fixes #6159 
I tested by building locally with ghc-9.4 stackage nightly (before lts-21.0 was released)
=> allow building with Stackage lts-21

test/integration/lib/StackTest.hs, test/integration/tests/3926-ghci-with-sublibraries/Main.hs, test/integration/tests/4270-files-order/Main.hs, test/integration/tests/module-added-multiple-times/Main.hs
=> Partial fix #6170 Move nextPrompt after replCommand

ChangeLog.md, src/Stack/Build/Execute.hs
This PR introduces truncating long build progress lines which are spamming narrow terminal window. Like this:
Before this PR _(repro: `stack --stack-root=/home/adziahel/.cache/stacktmp/root --terminal-width=20 build --fast`)_
The issue here is multifold and unclear — it's either the terminal processes `^A^K` before each `logSticky` poorly (because of incorrect terminfo), or it's bug in GNOME VTE, or is it `logSticky` ignores actual terminal width — could be all of these, if we're unlucky enough.
This PR replaces the tail of progress line with ellipsis (see screenshot below), preventing spamming terminal with repeating progress lines.
After this PR _(repro: `stack exec stack -- --stack-root=/home/adziahel/.cache/stacktmp/root --work-dir=.stackworktmp build --fast`)_
Please include the …
=> Ellipsize build progress output line

src/Stack/Setup.hs
Current stack seems to work fine with ghc-9.6 and Cabal-3.10 afaict.
TBH I don't find these warnings very helpful and they always lag into the stablized ghc minor versions.
ie we are already at ghc-9.6.2 but stack is still saying it is untested:
```
Warning: Stack has not been tested with GHC versions above 9.6, and using 9.6.2,
this may fail.
Warning: Stack has not been tested with Cabal versions above 3.10, but version
3.10.1.0 was found, this may fail.
```
I feel like it would be better even to either bump the warning by another major version
(9.8 is just around the corner) or just drop them entirely?  I don't feel they are
providing that much value: if stack really breaks it should be fairly obvious anyway.
=> Stack.Setup: bump version warnings to ghc-9.8 and Cabal-3.12

ChangeLog.md, doc/maintainers/stack_errors.md, doc/yaml_configuration.md, src/Stack/Build/Execute.hs, src/Stack/Config/ConfigureScript.hs, src/Stack/Constants.hs, src/Stack/Setup.hs, src/unix/System/Permissions.hs, src/windows/System/Permissions.hs, stack.cabal
`Stack.Setup.buildGhcFromSource` no longer uses the `-c` flag of `hadrian` but seeks to run the GHC repository's `boot` python script and `configure` sh script.
`Stack.Setup.buildGhcFromSource` requires MSYS2 tools, so - borrowing the pattern of `WithGHC env` - defined `newtype WithMSYS env` and `runWithMSYS`.
The GHC repository does not provide its `configure` file, so it has to be created by applying `autoreconf`. It also requires `aclocal`. Moved `ensureConfigureScript` out of `Stack.Build.Execute.ensureConfig` to new module `Stack.Config.ConfigureScript` and extended the help on Windows to refer to `aclocal` and the MSYS2 package `autotools`.
GHC's configure script requires ghc, happy and alex on the PATH. So, (1) it is run in Stack's environment, making use of the `stack.yaml` at …
=> Fix #6180 Take a different approach to building GHC from source

ChangeLog.md, doc/yaml_configuration.md, src/Stack/SDist.hs
Also improves related online documentation.
=> Fix #6202 Restore `stack sdist --pvp-bounds lower`

src/Stack/Build/Source.hs, src/Stack/FileDigestCache.hs, src/Stack/Setup.hs, src/Stack/Types/EnvConfig.hs, stack.cabal
On a project with many local packages I had "suprising" pauses in logged activity when running `stack build --verbose` and these always "nagged" me. Tonight I went in and found thta these pauses contribute to 2-3s of "dead time" before a `--file-watch` triggererd build would start working on my `.hs` file changes.
So I started to add strategic `bracketDebug` till I localized the dead "time" in `checkBuildCache`. And found the work there to be duplicate between the various packages. Lots of `.so` files my packages share (mostly boot libs, that can be quite big) would get hashed many times over.
So I implemented the simplest possible cache that has the lifetime of a build triggered by `--file-watch` to deduplicate these hash attempts. It shaved 2-3 seconds from my build and this is a lot as …
=> Fix digest computation duplication

.github/workflows/integration-tests.yml, ChangeLog.md, etc/dockerfiles/arm64.Dockerfile
This pull request is draft while I experiment with the CI.
=> Fix #6142 Build statically-linked Linux/Aarch64 Stack

ChangeLog.md, src/Stack/Constants.hs, src/Stack/Setup.hs, src/unix/Stack/Constants/UsrLibDirs.hs, src/windows/Stack/Constants/UsrLibDirs.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested on Alpine Linux (on WSL2). Relying on CI for other operating systems.
=> Fix #6218 Detect musl libc in `Stack.Setup.getGhcBuilds`

cabal.config
=> Fix #6242 GHC 9.4.7: cabal build: Error: cabal: Could not resolve dependencies

ChangeLog.md, src/Stack/Setup.hs, stack.cabal
=> Fix #6257 Allow MSYS2 to install on different drive to sys temp dir's

ChangeLog.md, doc/new_command.md, src/Stack/New.hs, src/Stack/Options/NewParser.hs
=> Fix #6264 Add `--no-init` flag to `stack new`

ChangeLog.md, src/Stack/Build/Execute.hs
=> Fix #6267 Avoid *.hi and *.o in stack-exe-src directory

ChangeLog.md, doc/build_command.md, doc/path_command.md, doc/yaml_configuration.md, src/Stack/Build/Execute.hs, src/Stack/Config/Build.hs, src/Stack/Options/BuildMonoidParser.hs, src/Stack/Types/BuildOpts.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Some testing one locally on Windows.
=> Re #6270 Step 1, provide `--haddock-for-hackage`

ChangeLog.md, src/Stack/New.hs
When using `stack new` with a custom template, an error is thrown when trying to make a `package.yaml` at a subdirectory. For example, with a template like this:
```text
{-# START_FILE {{name}}/package.yaml #-}
... yaml contents ...
```
`stack new` would throw this error:
```text
❯ stack new my-new-project jship/default
Downloading template jship/default to create project my-new-project in directory my-new-project/...
Downloaded /Users/jship/.stack/templates/jship/default.hsfiles.
Error: [S-9490]
Stack failed to use the template jship/default, as the template does not contain a Cabal or package.yaml file.
```
This behavior is from the current version of the code checking for an exact match with the string `"package.yaml"`: https://github.com/commercialhaskell/stack/blob/74a36d636b848fe4a8c …
=> Relax template package.yaml check to support packages in a subdirectory

doc/upload_command.md, package.yaml, src/Network/HTTP/StackClient.hs, src/Stack/BuildInfo.hs, src/Stack/CLI.hs, src/Stack/Constants.hs, src/Stack/Options/UploadParser.hs, src/Stack/SDist.hs, src/Stack/Upload.hs, stack.cabal
Also adds a manual Cabal flag `disable-stack-upload` to `package.yaml`, to facilitate the debugging of `stack upload`.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows 11, including by using it to add Haddock documentation to a package candidate for `stack-2.14.0` on Hackage.
=> Re #6270 Step 4 Upload document archive to Hackage

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Setup.hs, src/Stack/Types/Config.hs, src/Stack/Types/ConfigMonoid.hs
=> Fix #6293 Allow warnings about untested GHC/Cabal to be muted

src/Path/Extra.hs, src/Stack/Setup.hs
=> Clear a STAN suggestion

doc/maintainers/stack_errors.md, src/Data/Attoparsec/Interpreter.hs, src/Options/Applicative/Complicated.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/CLI.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Some testing locally on Windows.
=> Clear STAN-0001 suggestion

src/Stack/Docker.hs, src/Stack/Runners.hs, src/Stack/Types/Runner.hs
The Stan tool reports:
~~~text
File:         src\Stack\Docker.hs
Module:       Stack.Docker
LoC:          652
Observations: 1
Extensions from .cabal:
Extensions from module: NoImplicitPrelude, OverloadedStrings, RecordWildCards
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃  ✦ ID:            OBS-STAN-0212-axv1UG-562:18
┃  ✦ Severity:      Error
┃  ✦ Inspection ID: STAN-0212
┃  ✦ Name:          Anti-pattern: unsafe functions
┃  ✦ Description:   Usage of unsafe functions breaks referential transparency
┃  ✦ Category:      #Unsafe #AntiPattern
┃  ✦ File:          src\Stack\Docker.hs
┃
┃   561 ┃
┃   562 ┃ entrypointMVar = unsafePerformIO (newMVar False)
┃   563 ┃                  ^^^^^^^^^^^^^^^
┃
┃  💡 Possible solution:
┃      ⍟ Remove 'undefined' or at …
=> Eliminate unsafePerformIO

.stan.toml, src/Stack/Ghci.hs, src/Stack/Types/Build/Exception.hs
I could see no reason to retain the existing `foldl`. The combining function did not appear to be non-strict in its first argument.
=> Clear Stan suggestion: replace `foldl` with `fold'`

.stan.toml, doc/maintainers/stack_errors.md, src/GHC/Utils/GhcPkg/Main/Compat.hs
=> Clear Stan suggestions

.stan.toml, src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/SDist.hs, src/Stack/Types/Build.hs, src/Stack/Types/Package.hs
Also removes `packageIdent`, duplicating `packageIdentifier`.
=> Fix #6313 Make `taskProvides` a function, not a field of `Task`

src/Stack/Build/ConstructPlan.hs, src/Stack/Types/Build/Exception.hs, src/Stack/Types/ParentMap.hs
=> Rationalise `ParentMap` type synonym, given its actual use

src/Stack/Build.hs, src/Stack/Build/Cache.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Source.hs, src/Stack/Build/Target.hs, src/Stack/ComponentFile.hs, src/Stack/Coverage.hs, src/Stack/Ghci.hs, src/Stack/Package.hs, src/Stack/PackageDump.hs, src/Stack/PackageFile.hs, src/Stack/SDist.hs, src/Stack/Types/Build.hs, src/Stack/Types/NamedComponent.hs, src/Stack/Types/Package.hs
=> Use 'sub-library' terminology consistently

.stan.toml, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/SDist.hs, src/Stack/Types/Build.hs
The motivation for this is similar to the approach to `taskProvides`: the `taskAnyMissing` field is determined by the value of other fields.
Also reorders test as `(taskAnyMissingHackEnabled && taskAnyMissing task)`.
Also passes `TaskType` rather than `Task`, to avoid use of `TaskType` values with dummy fields.
Also improves related Haddock documentation and code comments.
=> Make `taskAnyMissing` a function, not field

src/Stack/Build/Installed.hs, src/Stack/PackageDump.hs, src/Stack/Types/Package.hs
Renames the `ExtraGlobal` data constructor of `InstalledPackageLocation` as `ExtraPkgDb`.
Provides types `PackageDatabase` and `PackageDbVariety`. The former replaces the use of `Maybe (InstalledPackageLocation, Path Abs Dir)`, where `Nothing` was used to represent the global package database (now there is data constructor `GlobalPkgDb`). The latter replaces the use of `Maybe InstalledPackageLocation`, where `Nothing` was also used to represent the global package database (now there is data constructor `GlobalDb`).
Also updates and corrects existing Haddock documentation. For example `Sink` is deprecated as a type synonym.
=> Add Haddock documentation and further types

.stan.toml, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/BuildPlan.hs, src/Stack/Component.hs, src/Stack/Dot.hs, src/Stack/Ghci.hs, src/Stack/Package.hs, src/Stack/SDist.hs, src/Stack/Types/CompCollection.hs, src/Stack/Types/Dependency.hs, src/Stack/Types/Package.hs
This is simply the further consequences of the design merged in #6334.
In particular, it removes the ugly wart that was `PackageDescriptionPair` and realise most of the plan/changes that I described and proposed in https://github.com/commercialhaskell/stack/issues/5920#issue-1428884484
=> Package components followup

doc/install_and_upgrade.md
=> docs: Update Arch Linux package URL in install_and_upgrade.md

.stan.toml, ChangeLog.md, doc/GUIDE.md, src/Stack/Build/Execute.hs
For #6342, have the build show which compiler version is being used by appending "with ghc-x.y.z".
```
$ ~/.local/bin/stack build --test --no-run-tests        
Warning: WARNING: This stack project is generated.
hlint-plugin> configure (lib)
Configuring hlint-plugin-1.0.2...
hlint-plugin> build (lib) with ghc-9.0.2
Preprocessing library for hlint-plugin-1.0.2..
Building library for hlint-plugin-1.0.2..
[1 of 2] Compiling HLint.Plugin.Settings
[2 of 2] Compiling HLint.Plugin
hlint-plugin> copy/register
Installing library in /.../hlint-plugin/.stack-work/install/x86_64-linux
/77e1e65734194babbef5a670a7fffc8ad1833c81e4c13562134c9a797b54872d
/9.0.2/lib/x86_64-linux-ghc-9.0.2/hlint-plugin-1.0.2-JOPnvvxdmWa2Izg7q332qw
Registering library for hlint-plugin-1.0.2..
```
```
$ ~/.local/bin/stack …
```
=> Build _ with ghc-x.y.z

.stan.toml, package.yaml, src/Stack/Build/Cache.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Installed.hs, src/Stack/Ghci.hs, src/Stack/Package.hs, src/Stack/SDist.hs, src/Stack/Types/Build/ConstructPlan.hs, src/Stack/Types/Installed.hs, src/Stack/Types/Package.hs, stack.cabal
Because it's not going to stay a "Package" thing in the future if we build at the component level
=> refactoring: put installed stuff into a dedicated types package

.stan.toml, ChangeLog.md, src/Stack/Build/Execute.hs
This was introduced in https://github.com/commercialhaskell/stack/commit/b511d707909e214749dec5f400b80e775d35f3dd
8 years later I cannot reproduce the referenced issues under linux on a 128 thread machine building a repository with 265 local packages: https//github.com/mbj/stratosphere. I have to assume that the action concurrency / dependency tracking system is now much more durable than it was years ago. And or cabal bugs got fixed.
This change speeds up a clean build of [stratosphere](https://github.com/mbj/stratosphere) significantly.
Before this patch, after: `git clean -f -d -x` but with hot dependency cache:
Command: `STACK_YAML=stack-9.4.yaml stack build --copy-bins --fast`
Before:
```
2760.74s user 862.67s system 1065% cpu 5:39.95 total
```
With this patch:
```
2789.40s user …
```
=> Remove configure lock

ChangeLog.md, package.yaml, src/Codec/Archive/Tar/Utf8.hs, src/Stack/SDist.hs, stack.cabal
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows 11. Replying on CI.
=> Fix #6372 Allow stack sdist to check packages with non-ASCII names

.stan.toml, doc/unpack_command.md, package.yaml, src/Stack/CLI.hs, src/Stack/Constants.hs, src/Stack/Options/UnpackParser.hs, src/Stack/Unpack.hs, stack.cabal
Also captures certain errors in the command line options parser.
Also updates the in-app help.
=> Re #6374 Refactor `stack unpack` command line options

ChangeLog.md, src/Stack/Setup.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows 11. Relying on CI for other OS.
=> Re #6377 Deprecate Stack support for Cabal < 2.2

ChangeLog.md, doc/yaml_configuration.md, src/Stack/Config.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Types/Config.hs, src/Stack/Types/ConfigMonoid.hs
=> Re #6379 Introduce `notify-if-arch-unknown` configuration option

doc/yaml_configuration.md
As described in the resolution to #5707, Cabal is no longer included in LTSs so this has no effect.
It would be nice to list *which* LTS dropped it -- see FIXME.
=> Remove mention of Cabal in drop-packages

.devcontainer/scripts/usr/local/bin/onCreateCommand.sh
- Cabal (the tool) ≥ 3.10 complies to the XDG Base Directory Specification
- i.e. use $HOME/.local/bin to store user-specific executable files
- Remove potentially appended $HOME/.local/bin from PATH
- Update PATH for both Zsh and Bash
---
=> Dev Containers: Update onCreateCommand

src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Haddock.hs, src/Stack/Build/Source.hs, src/Stack/BuildPlan.hs, src/Stack/Coverage.hs, src/Stack/DependencyGraph.hs, src/Stack/Ghci.hs, src/Stack/Package.hs, src/Stack/PackageFile.hs, src/Stack/Query.hs, src/Stack/SDist.hs, src/Stack/Types/Build.hs, src/Stack/Types/Build/ConstructPlan.hs, src/Stack/Types/Build/Exception.hs, src/Stack/Types/Component.hs, src/Stack/Types/ConfigureOpts.hs, src/Stack/Types/Package.hs, src/Stack/Upload.hs
=> Remove package prefix from Package field names

src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/Haddock.hs, src/Stack/Build/Source.hs, src/Stack/Config.hs, src/Stack/Config/Build.hs, src/Stack/Ghci.hs, src/Stack/SDist.hs, src/Stack/Types/BuildOpts.hs, src/Stack/Types/ConfigureOpts.hs, tests/unit/Stack/ConfigSpec.hs
=> Remove bopts prefix from BuildOpts field names

package.yaml, src/Stack/Config.hs, src/Stack/DefaultColorWhen.hs, src/Stack/Runners.hs, stack-ghc-9.8.1.yaml, stack-ghc-9.8.1.yaml.lock, stack.cabal, stack.yaml, stack.yaml.lock
=> Fix #6408 Depend on ansi-terminal >= 1.0.2; use hNowSupportsANSI

src/Stack/Build/Execute.hs, src/Stack/Build/ExecuteEnv.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Types/Build.hs, stack.cabal
Many things arre happening in the Execute Module, which requires a big split, like prior work, we'll have execute, executePackage, executeComponent
=> Minor refactoring

src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/ExecuteEnv.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Build/Haddock.hs, src/Stack/Build/Source.hs, src/Stack/Build/Target.hs, src/Stack/Coverage.hs, src/Stack/DependencyGraph.hs, src/Stack/Exec.hs, src/Stack/Ghci.hs, src/Stack/Hoogle.hs, src/Stack/Setup.hs, src/Stack/Types/BuildOpts.hs, src/Stack/Upgrade.hs
=> Remove boptsCLI prefix from BuildOptsCLI field names

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Types/Build.hs
=> Remove task prefix from Task field names, save taskType

src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Types/Build.hs
=> Remove plan prefix from Plan field names

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Build/Source.hs, src/Stack/Types/Curator.hs
=> Remove curator prefix from Curator field names

src/Stack/Config.hs, src/Stack/Runners.hs, src/Stack/Types/Runner.hs
The qualified import of `Stack.Types.GlobalOpts` in `Stack.Types.Runner` was to avoid problems with ambiguous record updates.
=> Remove runner prefix from Runner field names

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Source.hs, src/Stack/Build/Target.hs, src/Stack/BuildPlan.hs, src/Stack/Config.hs, src/Stack/DependencyGraph.hs, src/Stack/Ghci.hs, src/Stack/Hoogle.hs, src/Stack/IDE.hs, src/Stack/SDist.hs, src/Stack/Script.hs, src/Stack/SourceMap.hs, src/Stack/Types/SourceMap.hs
Makes use of import alias technique to avoid ambiguous record updates.
=> Remove dp/pp prefixes from DepPackage ProjectPackage field names

CONTRIBUTING.md
@theobat, this also documents what I've been doing to avoid the ambiguity problem on record update, when it arises (it has arisen only twice so far). It is a little 'hacky'.
The origin of the ambiguity avoidance is: https://chrisdone.com/posts/import-aliases-field-names/
=> Update CONTRIBUTING.md for Stack's use of 'record dot' syntax

.stan.toml, src/Stack/Build.hs, src/Stack/Build/ExecuteEnv.hs, src/Stack/Build/Source.hs, src/Stack/BuildPlan.hs, src/Stack/Config.hs, src/Stack/Options/ConfigParser.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Package.hs, src/Stack/PackageDump.hs, src/Stack/Runners.hs, src/Stack/SDist.hs, src/Stack/Setup.hs, src/Stack/Storage/User.hs, src/Stack/Types/GlobalOpts.hs, src/Stack/Types/GlobalOptsMonoid.hs, src/Stack/Types/ProjectAndConfigMonoid.hs, src/Stack/Types/Runner.hs
This refactoring renames the `termWidth` fields of `GlobalOpts` and `GlobalOptsMonoid` `termWidthOpt`, to distinguish it from the `termWidth` field of `Runner`, avoiding certain ambiguity in a different way.
It also makes greater use of `NamedFieldPuns` that is included in `GHC2021`. In so doing, it chooses the names of local variables to make the final record updates 'cleaner'.
=> Eliminate ambiguity; make use of GHC2021's NamedFieldPuns

src/GHC/Utils/GhcPkg/Main/Compat.hs, src/Stack/Build/Cache.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Source.hs, src/Stack/Config.hs, src/Stack/Config/Docker.hs, src/Stack/Config/Nix.hs, src/Stack/Ghci.hs, src/Stack/New.hs, src/Stack/Package.hs, src/Stack/SDist.hs, src/Stack/Setup.hs, src/Stack/Setup/Installed.hs, src/Stack/Storage/Project.hs, src/Stack/Types/BuildOptsMonoid.hs, src/Stack/Types/Casa.hs, src/Stack/Types/ConfigMonoid.hs, src/Stack/Types/Docker.hs, src/Stack/Types/ExtraDirs.hs, src/Stack/Types/GHCDownloadInfo.hs, src/Stack/Types/GhcOptions.hs, src/Stack/Types/Installed.hs, src/Stack/Types/Nix.hs, src/Stack/Types/Package.hs, src/Stack/Types/SetupInfo.hs, src/Stack/Types/TemplateName.hs, src/Stack/Types/Version.hs
ed/ExtraDirs, gdi/GHCDownloadInfo, un/GhcOptions, ili/InstalledLibraryInfo, un/ExeName, bio/BuildInfoOpts, un/MemoizedWith, fci/FileCacheHash, si/SetupInfo, rtp/RepoTemplatePath, get/IntersectingVersionRange.
Also remove redundant `$` in `pure $ Constructor { ... }`.
=> Remove various prefixes from field names of types

src/Control/Concurrent/Execute.hs, src/Options/Applicative/Builder/Extra.hs, src/Stack/Build/Execute.hs, src/Stack/Build/ExecuteEnv.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/BuildPlan.hs, src/Stack/Init.hs, src/Stack/Options/ConfigParser.hs
action/Action, ac/ActionContext, es/ExecuteState, pco/PathCompleterOpts, de/DepError.
=> Remove other prefixes from field names of types

.stan.toml, package.yaml, src/Stack/Coverage.hs, src/Stack/DependencyGraph.hs, src/Stack/Docker.hs, src/Stack/Eval.hs, src/Stack/Exec.hs, src/Stack/Ghci.hs, src/Stack/Lock.hs, src/Stack/Ls.hs, src/Stack/New.hs, src/Stack/Types/DotConfig.hs, stack.cabal, tests/unit/Stack/LockSpec.hs
Also moves `DotConfig` to its own module to avoid ambiguity.
hropts/HpcReportOpts, ii/Inspect, ic/ImageConfig, eval/EvalOpts, eo/ExecOpts, eo/ExecOptsExtra, eo/ExecOpts, ghci/GhciOpts, ghciPkg/GhciPkgInfo, ghciDesc/GhciPkgDesc, ll/LockedLocation, lck/Locked, sopt/SnapshotOpts, listDeps/ListDepsOpts, listDeps/ListDepsFormatOpts, copt/ListStyleOpts, snap/Snapshot, newOpts/NewOpts, tpl/TemplateDownloadSettings, dc/DotConfig.
=> Remove prefixes from field names of various types

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Config.hs, src/Stack/Init.hs, src/Stack/Types/Build/ConstructPlan.hs, src/Stack/Types/Project.hs, src/Stack/Types/ProjectAndConfigMonoid.hs
`project.dependencies` -> `project.extraDeps`.
`curator` consistently (replacing `mcurator`, `mcur`).
Makes greater use of `NamedFieldPuns`.
=> Rename certain fields and variables for consistency

src/Stack/Component.hs, src/Stack/ComponentFile.hs, src/Stack/Package.hs, src/Stack/Types/CompCollection.hs, src/Stack/Types/Component.hs
Also removes `sbi` prefix from `StackBuildInfo` field names.
=> Fix #6448 "hspec-iscover" -> "hspec-discover"

.stan.toml, ChangeLog.md, src/Stack/Build.hs, src/Stack/Build/ExecuteEnv.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/ComponentFile.hs, src/Stack/Package.hs, src/Stack/Setup.hs
=> Fix #6377 Drop support of Cabal < 2.2

src/Stack/Types/Component.hs
@mpilgrem While there is no urge to do so, I think this fix should be backported to stack 2.15, because it'll likely create wrong behaviors in ghci for benchmarks (and probably in hls then).
=> fix: wrong instance for qualified name of benchmarks

ChangeLog.md, doc/path_command.md, src/Stack/Options/PathParser.hs, src/Stack/Path.hs
=> Fix #6484 stack path avoids EnvConfig where possible

ChangeLog.md, src/Stack/Build.hs, src/Stack/Setup.hs
=> Re #6498 Better in-app information about using a downgraded Stack

src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Execute.hs, src/Stack/Build/ExecuteEnv.hs, src/Stack/Build/Haddock.hs, src/Stack/Build/Source.hs, src/Stack/Build/Target.hs, src/Stack/Clean.hs, src/Stack/Dot.hs, src/Stack/Ghci.hs, src/Stack/Init.hs, src/Stack/Ls.hs, src/Stack/Options/BuildMonoidParser.hs, src/Stack/SDist.hs, src/Stack/Types/ApplyGhcOptions.hs, src/Stack/Types/ApplyProgOptions.hs, src/Stack/Types/Build/ConstructPlan.hs, src/Stack/Types/Build/Exception.hs, src/Stack/Types/BuildOpts.hs, src/Stack/Types/EnvConfig.hs, src/Stack/Types/EnvSettings.hs, tests/integration/tests/cabal-sublibrary-dependency/Main.hs
Also seeks to distinguish where 'local packages' is intended to refer to project packages and local extra-deps, for example in the context of the contents of the mutable package database (the local package database).
=> Re #6492 Further prefer 'project packages' to 'local packages'

ChangeLog.md, src/Stack/Setup.hs, src/Stack/Types/CompilerBuild.hs, src/Stack/Types/DownloadInfo.hs
Also corrects some Haddock documentation
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows. Relying on CI.
=> Fix #1768 Remove tool archive file after installation

.stan.toml, ChangeLog.md, package.yaml, src/Stack/Build.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Build/Haddock.hs, src/Stack/BuildOpts.hs, src/Stack/Config/Build.hs, src/Stack/Options/BuildMonoidParser.hs, src/Stack/Types/BuildOpts.hs, src/Stack/Types/BuildOptsMonoid.hs, src/Stack/Types/InterfaceOpt.hs, stack.cabal, tests/unit/Stack/ConfigSpec.hs
Note: This is not yet guarded for Cabal >= 3.8.1.0 and so is marked as draft. EDIT: Now guarded, but still draft while I consider how the Haddocks are included in the final indexes.
=> Re #729 Add `--haddock-executables` flag

etc/scripts/release-linux-aarch64.hs
See the introductory in-code comment for further information
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on a Mac mini/M1 using an Alpine Linux 3.19.1/AArch64 VM via UTM to test the resulting executable file.
=> Re #6531 Create release-linux-aarch64.hs for use on macOS/AArch64

.github/workflows/integration-tests.yml, etc/scripts/release.hs, tests/integration/tests/4095-utf8-pure-nix/Main.hs
This pull request folds the idea of #6533 into `etc/scripts/release.hs` itself, and extends it.
Currently, the Linux/AArch64 job in `integration-tests.yml` makes use of:
~~~bash
/usr/local/bin/stack etc/scripts/release.hs build --alpine --build-args --docker-stack-exe=image
~~~
You can't use a Docker container on GitHub's macOS/M1-based `macos-14`, but the idea is that you could use on macOS/AArch64 locally:
~~~zsh
stack etc/scripts/release.hs build --alpine --stack-args --docker-stack-exe=image
~~~
It also seeks to do the same with `release.hs check`, so that you can use on macOS/AArch64 locally:
~~~zsh
stack etc/scripts/release.hs check --alpine --stack-args --docker-stack-exe=image
~~~
The pull request introduces `--stack-args`, as `--docker-stack-exe` is a global flag, not a `stack …
=> Re #6531 Allow cross-OS use of `release.hs`

.stan.toml, src/Stack/Build/ExecuteEnv.hs
=> Re #6267 Move removal of `*.hi` and `*.o` to after their creation

Setup.hs, SetupHooks.hs
=> Re #6542 Add Well-Typed's patch to the repository, so it is to hand

ChangeLog.md, src/Stack/Build/ConstructPlan.hs
=> Fix #6551 Use action `getLatestApplicableVersionAndRev` only when needed

ChangeLog.md, src/Stack/ConfigCmd.hs
Also updates content of warning.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally.
=> Fix #6554 Recognise `key:` not a single-line format

.stan.toml, src/Stack/Constants.hs
`dph-par` and `dph-seq` appear to be 'ancient history' and not applicable to GHC >= 8.4.
Improve code documentation.
=> Fix #6558 Spring clean wiredInPackages

ChangeLog.md, doc/build_command.md, doc/maintainers/stack_errors.md, src/Stack/Build/Source.hs, src/Stack/Config.hs, src/Stack/Ghci.hs, src/Stack/SourceMap.hs, src/Stack/Types/Build/Exception.hs
Previously, the Cabal flags specified at the command line were added and then an action checked the validity of the flags specified for specific packages (only) (in `checkFlagsUsedThrowing`). Now, the flags are 'checked' as they are added and `applyOptsFlag` yields a value of type `RIO env (Either UnusedFlags CommonPackage)`.
Moves logic of `getLocalFiles` from module `Stack.Build.Source` to `Stack.Ghci.loadGhciPkgDescs`, as that is the only place where it is now used in the original form.
Moves logic of `checkFlagsUsedThrowing` from module `Stack.SourceMap` to `Stack.Config.fillProjectWanted`, as that is the only place where it is now used in the original form.
To avoid `Set.toList . Set.fromList`, changes error data constructor to be `InvalidFlagSpecification [UnusedFlags]`.
Note: Fixes …
=> Fix #6570 Apply `--flag *:[-]<flag_name` only to relevant packages

doc/nix_integration.md
This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: NixOS/foundation#113
=> docs/nix_integration: point to new nixos wiki

ChangeLog.md, src/Stack/Coverage.hs, src/Stack/PackageDump.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Ubuntu (on WSL2).
=> Re #6574 Use ghc-pkg to retreive field value

.github/workflows/integration-tests.yml, ChangeLog.md, doc/GUIDE.md, doc/global_flags.md, doc/other_resources.md, src/Options/Applicative/Complicated.hs, src/Stack/Constants.hs
=> Fix #6581 Add `stack -h`

ChangeLog.md, doc/maintainers/stack_errors.md, package.yaml, src/Stack/Setup.hs, src/Stack/Types/Build/Exception.hs, src/Stack/Types/WantedCompilerSetter.hs, stack.cabal
=> Fix #6583 Error S-6362 acknowledges compiler set at command line

.gitignore, CONTRIBUTING.md, Makefile, doc/Makefile
I previewed the docs locally for #6603. I couldn't find how to do this in CONTRIBUTING.md so added a makefile recipes for previewing and building the docs.
=> Add docs preview and build

etc/scripts/get-stack.sh
I saw a todo while inspecting the shell script that I could handle, having done this for other installers before.
tested on `zsh` and `bash` by setting `PATH` to something short, removing current installation, and running the shell script. Did not test `fish` but used what I believe is the default there.
=> get-stack.sh: offer to extend path for user

.stan.toml, ChangeLog.md, doc/maintainers/stack_errors.md, src/Stack/Build.hs, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Clean.hs, src/Stack/Config.hs, src/Stack/ConfigCmd.hs, src/Stack/Constants/Config.hs, src/Stack/Ghci.hs, src/Stack/New.hs, src/Stack/Package.hs, src/Stack/Path.hs, src/Stack/Runners.hs, src/Stack/SDist.hs, src/Stack/Setup.hs, src/Stack/SetupCmd.hs, src/Stack/Types/Build/Exception.hs, src/Stack/Types/BuildConfig.hs, src/Stack/Types/Config.hs, src/Stack/Types/Config/Exception.hs, src/Stack/Types/EnvConfig.hs, src/Stack/Uninstall.hs, tests/unit/Stack/ConfigSpec.hs
Also refactors where:
* 'project' is used to refer to a file or directory that may not be within a project directory but within the Stack root; or
* `stackYaml` is used to refer to a configuration file that may be a global one as well as a project-level one.
=> Fix #6606 Distinguish global and project-level configuration files

tests/integration/IntegrationSpec.hs
Provides time indication for integration tests.
It's obviously not a very good benchmark, but it's still better than nothing for very big variations.
For posterity :
1191; 1237 - Ubuntu
980; 1018 - Macos latest
1578; 1515 - Windows latest
=> feat: provide time indication for integration tests

ChangeLog.md, doc/maintainers/stack_errors.md, doc/yaml_configuration.md, src/Stack/Build.hs, src/Stack/Config.hs, src/Stack/FileWatch.hs, src/Stack/Types/Config.hs, src/Stack/Types/Config/Exception.hs, src/Stack/Types/ConfigMonoid.hs
This is draft while testing on different operating systems.
=> Fix #5925 Add file-watch-hook for post-processing

ChangeLog.md, doc/commands/upgrade_command.md, src/Stack.hs, src/Stack/CLI.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested `stack upgrade` locally on Windows, including with a symbolic link.
=> Fix #6630 Also take exectutable file name into account, for '`stack`'

doc/commands/exec_command.md, doc/maintainers/stack_errors.md, src/Stack.hs, src/Stack/Build/Execute.hs, src/Stack/Docker.hs, src/Stack/Nix.hs, src/Stack/Options/Completion.hs, src/Stack/Options/GlobalParser.hs, src/Stack/Options/LsParser.hs, src/Stack/Setup.hs, src/Stack/Types/Config/Exception.hs, src/Stack/Types/GlobalOpts.hs, src/Stack/Types/Runner.hs, tests/unit/Stack/ConfigSpec.hs, tests/unit/Stack/NixSpec.hs
This assumes that `progName` and `mExecutablePath` (the code in module `Stack`) are immutable and can sensibly be added as fields to `GlobalOpts`.
So, the code in modules `Stack.Build.Execute`, `Stack.Docker`, `Stack.Nix` and `Stack.Setup` does not need to use `getExecutablePath` and the code in `Stack.Docker` does not to use `getProgName`.
`getExecutablePath :: IO FilePath` and `mExecutablePath :: Maybe (Path Abs File)`, so the former can yield `argv[0]` if the file path is unavailable when the latter yields `Nothing`. `Nothing` should not feature on Linux, macOS, Windows, FreeBSD, NetBSD and Solaris.
In respect of that:
* in `Stack.Build.Execute`, the usage is Windows;
* in `Stack.Docker`, the usage is Linux and macOS;
* in `Stack.Nix`, the usage must be Linux and macOS;
* in …
=> Re #6630 Add `progName`, `mExecutablePath` to `GlobalOpts`

.stan.toml, src/Stack/Docker.hs
The only logical change is that the repeated `not docker.detach` is avoided.
=> Re #6633 Refactor `Stack.Docker` vis-a-vis `keepStdinOpen`

.stan.toml, ChangeLog.md, src/Stack/Docker.hs
=> Fix #6633 If not detached, always use Docker -i flag

ChangeLog.md, src/Stack/Build/Execute.hs
=> Fix #6641 `--dry-run` respects `--no-run-tests`, `--no-run-benchmarks`

ChangeLog.md, doc/maintainers/stack_errors.md, src/Stack/Build/Execute.hs, src/Stack/Build/ExecutePackage.hs, src/Stack/Types/Build/Exception.hs, tests/integration/tests/3959-order-of-flags/Main.hs
See:
* #6643 
Puts notification (if enabled) in `Stack.Build.Execute.executePlan'`.
In `Stack.Build.Execute.toActions`:
* does not add action `singleTest` if `not runTests`; and
* does not add action `singleBench` if `not runBenchmarks`.
=> Fix #6643 Respect `--no-run-tests`, `--no-run-benchmarks` when listing actions

doc/commands/haddock_command.md
Found that the documentation has a mismatching header for the command name stack bench instead of stack haddock.
No tests are necessary.
(Not sure if creating a new fork was the right way to change the base branch)
=> fix(doc.haddock_command): mismatching header for command

src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Installed.hs, src/Stack/Build/Source.hs, src/Stack/SourceMap.hs, src/Stack/Types/DumpPackage.hs
=> Minor refactoring around DumpPackage

doc/configure/yaml/non-project.md
After a few minutes of perplexed early morning debugging, it seems I was led astray by a minor typo in the documentation.
=> ✏️ Correct minor documentation typo

ChangeLog.md, src/Stack/Config.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows 11 but also relying on CI.
=> Re #6670 Extend S-8432 for non-Latin1 in Stack 'programs' path

.stan.toml, ChangeLog.md, doc/commands/build_command.md, src/Stack/Build/ExecuteEnv.hs
See:
* #6678
Tested locally on Windows with:
* `gi-gtk-4.0.12@rev:0` (no Cabal dependency)
* `gi-gtk-4.0.12@rev:1` (Cabal dependency added)
=> Fix #6678 Add Cabal boot package to `setup-depends` deps, when needed

.github/workflows/integration-tests.yml
=> Fix #6531 Use GitHub-hosted Ubuntu/AArch64 runner

ChangeLog.md, src/Stack/SDist.hs
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally with `stack sdist`.
=> `stack sdist`\`upload` identify Cabal version used to check packages

src/Stack/ComponentFile.hs, src/Stack/PackageFile.hs
This was useful when working on #6703 and can be merged on its own.
=> Add more type signatures

etc/scripts/package.yaml, etc/scripts/release.hs, etc/scripts/stack.yaml
See:
* #6711
which manifests in Stack's script-based CI.
=> Re #6711 Add work-around to Stack's CI

ChangeLog.md, doc/commands/script_command.md, src/Stack/Script.hs
See:
* #6616
Relying on the CI for now.
=> Fix #6616 Use GHC's -package-id rather than -package

ChangeLog.md, doc/commands/script_command.md, doc/topics/scripts.md, package.yaml, src/Stack/Config.hs, src/Stack/Options/ScriptParser.hs, src/Stack/Script.hs, src/Stack/Types/ProjectConfig.hs, src/Stack/Types/StackYamlLoc.hs, stack.cabal, stack.yaml, stack.yaml.lock
See:
* #5305
Tested locally on Windows.
Currently depends on an unreleased version of `pantry-0.10.1`.
=> Fix #5305 Extend `stack script --extra-dep` to any immutable extra-dep

.github/workflows/integration-tests.yml, etc/scripts/release.hs, tests/integration/IntegrationSpec.hs
See:
* #6720
`integration-tests.yml` now installs `lld` on the GitHub hosted runner `ubuntu-latest`.
`release.hs check` executes `stack-integration-test` outside of any Alpine Linux Docker container.
`stack-integration-test` uses `lld` on Linux, and expects it to be on the PATH.
=> Fix #6720 Involve lld linker on Ubuntu

package.yaml, src/Stack/Build/Source.hs, src/Stack/Config.hs, src/Stack/Options/GhciParser.hs, src/Stack/Options/PackagesParser.hs, src/Stack/Options/ScriptParser.hs, stack.cabal
Moves `packagesParser` into its own module, and uses it in modules `Stack.Options.GhciParser` and `Stack.Options.ScriptParser`.
Creates `loadCommonPackage'` and uses it in `loadCommonPackage` and `loadLocalPackage`.
Also adds missing Haddock documentation.
=> Reduce code duplication

doc/maintainers/stack_errors.md, src/Stack/Ghci.hs
Also is more accurate about what was `MissingFileTarget` (now `FileTargetIsInvalidAbsFile`). The exception is not always thrown when a specified 'file' is 'missing': it is also thrown when what is specified is not an absolute path to a file and it is not thrown when what is specified is an absolute path.
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally on Windows and relying on CI.
=> Make `stack ghci`'s Stack errors prettier

CONTRIBUTING.md, cabal.config, stack.yaml, stack.yaml.lock
`tls-2.1.10` is released, but it requires `random >= 1.3`.
=> Build Stack against tls-2.1.8

src/Stack/Config.hs
Fix a typo: 'To avoid sucn problems' -> 'To avoid such problems'
=> Fix typo in warning for space in local programs path

doc/tutorial/index.md
The first "Stackage" link in the documentation pointed to hackage...
I tested the change by following the updated link in the Preview.
(The original
| Note: Fixes for the online documentation of the current Stack release
| (https://docs.haskellstack.org/en/stable/) should target the 'stable' branch,
| not the 'master' branch.
could usefully be expanded by mentioning:
`stable` is merged into `master` on release
(https://docs.haskellstack.org/en/stable/maintainers/releases/#pre-release-checks) and, in practice, more
frequently than that.
)
=> doc/tutorial/index.md: Fixed "Stackage" link.

ChangeLog.md, src/Stack/Types/BuildOptsCLI.hs
=> Fix #6775 `--PROG-option=<argument>` passes without added quotes

.stan.toml, src/Stack/Build/ConstructPlan.hs, src/Stack/Build/Installed.hs, src/Stack/BuildPlan.hs, src/Stack/Constants.hs, src/Stack/DependencyGraph.hs, src/Stack/Dot.hs, src/Stack/Ls.hs, src/Stack/New.hs, src/Stack/Types/Build/Exception.hs
=> Re #6749 Allow `wiredInPackages` to depend on `ActualCompiler`

.stan.toml, ChangeLog.md, doc/commands/new_command.md, doc/configure/yaml/project.md, src/Stack/Constants.hs
=> Fix #6749 `wiredInPackages` depends on `ActualCompiler`

ChangeLog.md, doc/commands/dot_command.md, src/Stack/Dot.hs
See:
* #6784
Please also shortly describe how you tested your change. Bonus points for added tests! Tested locally with toy packages.
=> Re #6784 Consistent depth, recognise wired-in packaged, bottom line nodes

.gitattributes, CONTRIBUTING.md, Setup.hs, package.yaml, src/Stack/Component.hs, src/Stack/ComponentFile.hs, src/Stack/Package.hs, src/Stack/PackageFile.hs, src/Stack/SDist.hs, src/Stack/Types/Component.hs, stack.cabal, stack.yaml, stack.yaml.lock
Using `Cabal-3.14.*` is one of the required changes for GHC 9.12.  I need this for a personal project right now.  The purpose of this PR is not to necessarily have it merged right away, but rather to avoid duplicated work when Stack upgrades to GHC 9.12.
@mpilgrem from what I understand, we don't want CPP to support multiple versions of Cabal, right?
Do we ever use a more recent version of Cabal than what ships with GHC?  If "no", then this PR has to wait until we upgrade to GHC 9.12.
=> Depend on `Cabal-3.14.*`

.devcontainer/conf/shell/var/tmp/snippets/rc.sh, .devcontainer/devcontainer.json
=> Dev Containers: Update HLS to v2.12.0.0
